import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 11
// ==========================================
const day11_set1 = [
  {
    word: 'publish',
    partOfSpeech: 'v.',
    meaningKo: '출판하다, 발표하다',
    ipa: '/ˈpʌb.lɪʃ/',
    definition: 'to produce a book or magazine for people to buy',
    sentence: 'The young author was thrilled to publish her first storybook.',
    wordPromptScene: 'A fresh printing press rolling out colorful illustrated storybooks.',
    sentPromptScene: 'A proud author holds up a newly printed book to publish her story.',
  },
  {
    word: 'literature',
    partOfSpeech: 'n.',
    meaningKo: '문학',
    ipa: '/ˈlɪt̬.ɚ.ə.tʃʊr/',
    definition: 'written works such as stories, poems, and plays of value',
    sentence: 'Classic children’s literature introduces young readers to magical worlds.',
    wordPromptScene: 'A stack of antique gilded books with a feather quill pen.',
    sentPromptScene: 'Students read classic English literature together in a sunlit library.',
  },
  {
    word: 'fiction',
    partOfSpeech: 'n.',
    meaningKo: '소설, 허구',
    ipa: '/ˈfɪk.ʃən/',
    definition: 'stories about imaginary characters and events, not real facts',
    sentence: 'He loves reading science fiction stories about friendly alien planets.',
    wordPromptScene: 'An open book with a miniature glowing magical castle rising from pages.',
    sentPromptScene: 'A boy reads an exciting space adventure fiction novel before bedtime.',
  },
  {
    word: 'author',
    partOfSpeech: 'n.',
    meaningKo: '작가, 저자',
    ipa: '/ˈɑː.θɚ/',
    definition: 'the person who wrote a book, poem, or article',
    sentence: 'The famous author signed copies of her new mystery novel.',
    wordPromptScene: 'A cozy wooden writing desk with an inkwell, paper, and spectacles.',
    sentPromptScene: 'A smiling author speaks to excited young readers at a book festival.',
  },
  {
    word: 'symbol',
    partOfSpeech: 'n.',
    meaningKo: '상징, 기호',
    ipa: '/ˈsɪm.bəl/',
    definition: 'a picture, sign, or object that represents an idea',
    sentence: 'The white dove is an international symbol of peace worldwide.',
    wordPromptScene: 'A glowing white dove flying above an olive branch crest.',
    sentPromptScene: 'A student draws a green recycling symbol on an environmental poster.',
  },
  {
    word: 'plot',
    partOfSpeech: 'n.',
    meaningKo: '줄거리, 플롯',
    ipa: '/plɑːt/',
    definition: 'the series of events that form the story of book',
    sentence: 'The mystery novel has an exciting plot with unexpected surprises.',
    wordPromptScene: 'A storyline graph showing rising action, climax, and resolution peaks.',
    sentPromptScene: 'A teacher explains the thrilling plot of a fairy tale to students.',
  },
  {
    word: 'collaborate',
    partOfSpeech: 'v.',
    meaningKo: '협력하다, 공동 작업하다',
    ipa: '/kəˈlæb.ə.reɪt/',
    definition: 'to work together with someone to achieve something',
    sentence: 'The two artists will collaborate on a giant school wall mural.',
    wordPromptScene: 'Two cartoon artists painting together on a large colorful canvas.',
    sentPromptScene: 'Classmates collaborate on building a working model volcano for science day.',
  },
  {
    word: 'statue',
    partOfSpeech: 'n.',
    meaningKo: '동상, 조각상',
    ipa: '/ˈstætʃ.uː/',
    definition: 'an object made from stone or metal to look like someone',
    sentence: 'A bronze statue of a hero stands in town square.',
    wordPromptScene: 'A majestic bronze statue of a roaring lion in a public park.',
    sentPromptScene: 'Tourists take photographs in front of a famous historical city statue.',
  },
  {
    word: 'state',
    partOfSpeech: 'n.',
    meaningKo: '상태, 국가, 주',
    ipa: '/steɪt/',
    definition: 'the physical condition that something or someone is in',
    sentence: 'The antique wooden clock was kept in a perfect working state.',
    wordPromptScene: 'A shiny vintage pocket watch in pristine gleaming condition.',
    sentPromptScene: 'A museum curator examines the fine state of an ancient artifact.',
  },
  {
    word: 'status',
    partOfSpeech: 'n.',
    meaningKo: '지위, 신분, 상태',
    ipa: '/ˈsteɪ.t̬əs/',
    definition: 'the official legal or social position of someone or something',
    sentence: 'You can check the delivery status of your package online.',
    wordPromptScene: 'A smartphone screen displaying a green verified package delivery status bar.',
    sentPromptScene: 'A student checks the updated status of his contest submission online.',
  },
];

const day11_set2 = [
  {
    word: 'fit',
    partOfSpeech: 'v.',
    meaningKo: '맞다, 적합하다',
    ipa: '/fɪt/',
    definition: 'to be the right size or shape for someone',
    sentence: 'These warm winter mittens fit his hands perfectly without slipping.',
    wordPromptScene: 'A colorful puzzle piece snapping perfectly into a matching puzzle hole.',
    sentPromptScene: 'A boy tries on new hiking boots that fit comfortably on feet.',
  },
  {
    word: 'movement',
    partOfSpeech: 'n.',
    meaningKo: '움직임, 동작',
    ipa: '/ˈmuːv.mənt/',
    definition: 'a change of position or going from one place to another',
    sentence: 'The graceful movement of the ballet dancer amazed the audience.',
    wordPromptScene: 'A spinning ballet dancer with elegant glowing motion ribbon trails.',
    sentPromptScene: 'A dancer practices a fluid arm movement in front of studio mirrors.',
  },
  {
    word: 'brilliant',
    partOfSpeech: 'adj.',
    meaningKo: '빛나는, 훌륭한',
    ipa: '/ˈbrɪl.jənt/',
    definition: 'extremely intelligent, skilled, or full of bright light',
    sentence: 'The young inventor had a brilliant idea for cleaning rivers.',
    wordPromptScene: 'A glittering faceted diamond radiating brilliant rainbow sparkles of light.',
    sentPromptScene: 'A student shares a brilliant solution that solves the class puzzle.',
  },
  {
    word: 'prior',
    partOfSpeech: 'adj.',
    meaningKo: '이전의, 사전의',
    ipa: '/ˈpraɪ.ɚ/',
    definition: 'existing or happening before something else in time',
    sentence: 'No prior experience is needed to join our fun art club.',
    wordPromptScene: 'A calendar showing highlighted checkmarks on previous dates.',
    sentPromptScene: 'A cooking instructor welcomes beginners with no prior baking experience.',
  },
  {
    word: 'outline',
    partOfSpeech: 'n.',
    meaningKo: '개요, 윤곽',
    ipa: '/ˈaʊt.laɪn/',
    definition: 'a general plan showing the main points of something',
    sentence: 'Write a brief outline before drafting your complete history essay.',
    wordPromptScene: 'A clear pencil sketch outline of a castle on white paper.',
    sentPromptScene: 'A student organizes chapter topics into a neat essay outline on desk.',
  },
  {
    word: 'sort',
    partOfSpeech: 'v.',
    meaningKo: '분류하다, 구분하다',
    ipa: '/sɔːrt/',
    definition: 'to arrange things into different groups according to type',
    sentence: 'Please help sort the colored markers into their proper boxes.',
    wordPromptScene: 'Sorting colorful buttons into three neat separate wooden bowls.',
    sentPromptScene: 'Children sort recyclable paper and plastic bottles into designated colored bins.',
  },
  {
    word: 'portrait',
    partOfSpeech: 'n.',
    meaningKo: '초상화',
    ipa: '/ˈpɔːr.trɪt/',
    definition: 'a painting, drawing, or photograph of a person’s face',
    sentence: 'The museum gallery displayed a painted portrait of the queen.',
    wordPromptScene: 'An ornate golden picture frame displaying an oil portrait of a cat.',
    sentPromptScene: 'An art student paints a detailed portrait of a friend on easel.',
  },
  {
    word: 'tale',
    partOfSpeech: 'n.',
    meaningKo: '이야기, 설화',
    ipa: '/teɪl/',
    definition: 'a story, especially one about imaginative or exciting events',
    sentence: 'Grandmother told a charming fairy tale about a friendly dragon.',
    wordPromptScene: 'A glowing fairytale book open beside a cozy nightstand lamp.',
    sentPromptScene: 'Children gather around to listen to an old folk tale by campfire.',
  },
  {
    word: 'add',
    partOfSpeech: 'v.',
    meaningKo: '더하다, 추가하다',
    ipa: '/æd/',
    definition: 'to put something together with something else to increase it',
    sentence: 'You can add fresh berries to make the cereal sweeter.',
    wordPromptScene: 'A cartoon hand dropping ripe blueberries into a bowl of yogurt.',
    sentPromptScene: 'A baker begins to add sweet chocolate chips to the cookie batter.',
  },
  {
    word: 'volume',
    partOfSpeech: 'n.',
    meaningKo: '음량, 권, 부피',
    ipa: '/ˈvɑːl.juːm/',
    definition: 'the level of sound produced by a speaker or TV',
    sentence: 'Please turn down the speaker volume so babies can sleep.',
    wordPromptScene: 'A round speaker volume knob with glowing green audio sound bars.',
    sentPromptScene: 'A student lowers the headphone volume while listening to audio stories.',
  },
];

const day11_set3 = [
  {
    word: 'wisdom',
    partOfSpeech: 'n.',
    meaningKo: '지혜, 슬기',
    ipa: '/ˈwɪz.dəm/',
    definition: 'the ability to use knowledge and experience to make good decisions',
    sentence: 'The village elder shared words of ancient wisdom with children.',
    wordPromptScene: 'A wise cartoon owl wearing spectacles perched on an open encyclopedia.',
    sentPromptScene: 'A grandfather shares his wisdom with smiling grandchildren by fireplace.',
  },
  {
    word: 'impressed',
    partOfSpeech: 'adj.',
    meaningKo: '감명받은, 깊은 인상을 받은',
    ipa: '/ɪmˈprest/',
    definition: 'feeling admiration and respect for someone or something',
    sentence: 'The science teacher was very impressed by his volcano model.',
    wordPromptScene: 'A gold award ribbon with sparkling stars of high praise.',
    sentPromptScene: 'Judges look visibly impressed while watching a student’s robot demonstration.',
  },
  {
    word: 'emphasize',
    partOfSpeech: 'v.',
    meaningKo: '강조하다, 역설하다',
    ipa: '/ˈem.fə.saɪz/',
    definition: 'to show that something is especially important or needs attention',
    sentence: 'Teachers always emphasize the importance of regular reading every day.',
    wordPromptScene: 'A bright yellow highlighter pen underlining important bold words on paper.',
    sentPromptScene: 'A teacher points to the board to emphasize key safety rules in class.',
  },
  {
    word: 'bold',
    partOfSpeech: 'adj.',
    meaningKo: '대담한, 굵은',
    ipa: '/boʊld/',
    definition: 'brave and not afraid of taking risks, or strong text',
    sentence: 'The brave knight made a bold move across the board.',
    wordPromptScene: 'A lion cartoon character standing proudly atop a sunlit rocky cliff.',
    sentPromptScene: 'A player makes a bold strategy choice during the chess match.',
  },
  {
    word: 'admire',
    partOfSpeech: 'v.',
    meaningKo: '존경하다, 감탄하다',
    ipa: '/ədˈmaɪr/',
    definition: 'to look at someone with great respect and approval',
    sentence: 'Many young athletes admire the Olympic champion for her dedication.',
    wordPromptScene: 'A small cartoon character gazing up in wonder at a towering hero statue.',
    sentPromptScene: 'Students admire the beautiful landscape paintings displayed in the art gallery.',
  },
  {
    word: 'vivid',
    partOfSpeech: 'adj.',
    meaningKo: '생생한, 선명한',
    ipa: '/ˈvɪv.ɪd/',
    definition: 'producing very clear and detailed pictures in your mind',
    sentence: 'The artist used vivid red and yellow colors for sunset.',
    wordPromptScene: 'A vibrant palette of glowing neon and rainbow paint splatters.',
    sentPromptScene: 'A colorful butterfly with vivid orange wings rests on a sunflower.',
  },
  {
    word: 'multiple',
    partOfSpeech: 'adj.',
    meaningKo: '다수의, 다양한',
    ipa: '/ˈmʌl.tə.pəl/',
    definition: 'involving or having many different parts, individuals, or elements',
    sentence: 'The library offers multiple choices of interesting mystery adventure books.',
    wordPromptScene: 'A row of five different colorful storybooks standing on a wooden shelf.',
    sentPromptScene: 'A student examines multiple science project display boards at the fair.',
  },
  {
    word: 'profound',
    partOfSpeech: 'adj.',
    meaningKo: '깊은, 심오한',
    ipa: '/prəˈfaʊnd/',
    definition: 'showing great knowledge or understanding of serious topics',
    sentence: 'The wise philosopher wrote a book of profound life lessons.',
    wordPromptScene: 'A deep blue ocean scene with mysterious glowing light from depths.',
    sentPromptScene: 'A speaker shares profound insights that inspire everyone in the hall.',
  },
  {
    word: 'terrible',
    partOfSpeech: 'adj.',
    meaningKo: '끔찍한, 형편없는',
    ipa: '/ˈter.ə.bəl/',
    definition: 'very unpleasant, serious, or of bad quality',
    sentence: 'The stormy wind created a terrible mess in the yard.',
    wordPromptScene: 'A funny cartoon rain cloud soaking an overturned toy wagon.',
    sentPromptScene: 'Children clean up fallen twigs after a terrible windy rain storm.',
  },
  {
    word: 'terrific',
    partOfSpeech: 'adj.',
    meaningKo: '아주 멋진, 훌륭한',
    ipa: '/təˈrɪf.ɪk/',
    definition: 'very good, wonderful, or of great quality',
    sentence: 'Our school concert was a terrific success with many songs.',
    wordPromptScene: 'Celebratory fireworks bursting in bright colors with gold stars.',
    sentPromptScene: 'An audience cheers enthusiastically after a terrific school band performance.',
  },
];

const day11_set4 = [
  {
    word: 'calculate',
    partOfSpeech: 'v.',
    meaningKo: '계산하다, 산출하다',
    ipa: '/ˈkæl.kjə.leɪt/',
    definition: 'to judge the number or amount using basic mathematics',
    sentence: 'She used a solar calculator to calculate the total price.',
    wordPromptScene: 'A colorful desktop calculator with large friendly buttons and digits.',
    sentPromptScene: 'A student uses a wooden abacus to calculate math problems quickly.',
  },
  {
    word: 'opportunity',
    partOfSpeech: 'n.',
    meaningKo: '기회',
    ipa: '/ˌɑː.pɚˈtuː.nə.t̬i/',
    definition: 'an occasion or situation making it possible to do something',
    sentence: 'Visiting the space museum was an exciting opportunity for learning.',
    wordPromptScene: 'A golden glowing doorway opening into a magical star-filled universe.',
    sentPromptScene: 'Students seize the opportunity to ask questions to a real astronaut.',
  },
  {
    word: 'poetry',
    partOfSpeech: 'n.',
    meaningKo: '시, 시가',
    ipa: '/ˈpoʊ.ə.tri/',
    definition: 'poems in general as a form of literature',
    sentence: 'She recited a gentle spring poetry verse during the assembly.',
    wordPromptScene: 'An open poetry scroll with handwritten verses and floral illustrations.',
    sentPromptScene: 'A student recites nature poetry with emotion in front of classmates.',
  },
  {
    word: 'recall',
    partOfSpeech: 'v.',
    meaningKo: '기억해 내다, 상기하다',
    ipa: '/rɪˈkɑːl/',
    definition: 'to bring the memory of a past event into mind',
    sentence: 'Can you recall the title of the book we read?',
    wordPromptScene: 'A glowing lightbulb appearing inside a thought cloud above a head.',
    sentPromptScene: 'A student pauses to recall the spelling of a difficult word.',
  },
  {
    word: 'inferior',
    partOfSpeech: 'adj.',
    meaningKo: '질이 떨어지는, 하위의',
    ipa: '/ɪnˈfɪr.i.ɚ/',
    definition: 'not good or not as good as someone or something',
    sentence: 'The cheap plastic toy was inferior to the wooden blocks.',
    wordPromptScene: 'Two toy cars compared, one sturdy wood and one thin plastic.',
    sentPromptScene: 'A shopper inspects materials to avoid buying an inferior fragile product.',
  },
  {
    word: 'spirit',
    partOfSpeech: 'n.',
    meaningKo: '정신, 영혼, 기운',
    ipa: '/ˈspɪr.ət/',
    definition: 'the enthusiastic and lively attitude of a person or group',
    sentence: 'The team played with great sportsmanship and energetic school spirit.',
    wordPromptScene: 'A soaring glowing phoenix bird shining with vibrant golden wings.',
    sentPromptScene: 'Cheerleaders wave colorful pom-poms with great school spirit at game.',
  },
  {
    word: 'fade',
    partOfSpeech: 'v.',
    meaningKo: '희미해지다, 사라지다',
    ipa: '/feɪd/',
    definition: 'to lose brightness, color, or sound gradually over time',
    sentence: 'The afternoon sunlight began to fade behind the western hills.',
    wordPromptScene: 'A warm orange sunset sky gradually transitioning into soft twilight purple.',
    sentPromptScene: 'Pastel sidewalk chalk drawings slowly fade under gentle raindrops.',
  },
  {
    word: 'generation',
    partOfSpeech: 'n.',
    meaningKo: '세대, 시대',
    ipa: '/ˌdʒen.əˈreɪ.ʃən/',
    definition: 'all the people of about the same age in society',
    sentence: 'This fairy tale has been passed down through every generation.',
    wordPromptScene: 'Three generations of a friendly family standing together smiling happily.',
    sentPromptScene: 'A grandmother shares traditional recipes with the younger family generation.',
  },
  {
    word: 'masterpiece',
    partOfSpeech: 'n.',
    meaningKo: '걸작, 명작',
    ipa: '/ˈmæs.tɚ.piːs/',
    definition: 'a work of art that is an extremely good achievement',
    sentence: 'The painted Mona Lisa is regarded as a worldwide masterpiece.',
    wordPromptScene: 'A framed magnificent oil painting illuminated on an art gallery wall.',
    sentPromptScene: 'An art teacher explains why a painting is hailed as a masterpiece.',
  },
  {
    word: 'figure',
    partOfSpeech: 'n.',
    meaningKo: '인물, 수치, 도형',
    ipa: '/ˈfɪɡ.jɚ/',
    definition: 'a person who is well known, or a geometric shape',
    sentence: 'He is an important historical figure in modern science discoveries.',
    wordPromptScene: 'A collection of colorful geometric shapes including cube, sphere, and pyramid.',
    sentPromptScene: 'A history book highlights a famous historical figure on the page.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 11, set: 1, wordsData: day11_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 11, set: 2, wordsData: day11_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 11, set: 3, wordsData: day11_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 11, set: 4, wordsData: day11_set4 });
  console.log('DAY 11 written successfully');
}

run();
