import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 08
// ==========================================
const day08_set1 = [
  {
    word: 'comment',
    partOfSpeech: 'n.',
    meaningKo: '의견, 논평',
    ipa: '/ˈkɑː.ment/',
    definition: 'something that you say or write expressing your opinion',
    sentence: 'The teacher wrote a encouraging positive comment on his paper.',
    wordPromptScene: 'A neat notebook page with a star sticker and a speech bubble.',
    sentPromptScene: 'A smiling teacher writes a friendly comment on a student’s drawing.',
  },
  {
    word: 'popular',
    partOfSpeech: 'adj.',
    meaningKo: '인기 있는, 대중적인',
    ipa: '/ˈpɑː.pjə.lɚ/',
    definition: 'liked, enjoyed, or supported by many people',
    sentence: 'Soccer is the most popular outdoor sport at our school.',
    wordPromptScene: 'A gold star badge surrounded by cheerful thumbs-up icons.',
    sentPromptScene: 'Many happy students gather to play the popular playground ball game.',
  },
  {
    word: 'develop',
    partOfSpeech: 'v.',
    meaningKo: '발달시키다, 개발하다',
    ipa: '/dɪˈvel.əp/',
    definition: 'to grow or change into something bigger or better',
    sentence: 'Daily reading habits help develop a rich English vocabulary naturally.',
    wordPromptScene: 'A small green acorn sprouting and growing into a mighty oak tree.',
    sentPromptScene: 'Children practice drawing cartoons to develop their artistic creativity.',
  },
  {
    word: 'moment',
    partOfSpeech: 'n.',
    meaningKo: '순간, 잠깐',
    ipa: '/ˈmoʊ.mənt/',
    definition: 'a very short period of time',
    sentence: 'Please wait one moment while I tie my running shoelaces.',
    wordPromptScene: 'A glowing hourglass with sparkling sand grains falling through the middle.',
    sentPromptScene: 'A runner pauses for a brief moment to adjust sports goggles.',
  },
  {
    word: 'public',
    partOfSpeech: 'adj.',
    meaningKo: '공공의, 대중의',
    ipa: '/ˈpʌb.lɪk/',
    definition: 'provided for the use of all people in a community',
    sentence: 'Our town has a quiet public library with great books.',
    wordPromptScene: 'A welcoming stone public library building with open double doors.',
    sentPromptScene: 'Citizens enjoy reading peacefully inside the bright public town library.',
  },
  {
    word: 'promise',
    partOfSpeech: 'n.',
    meaningKo: '약속',
    ipa: '/ˈprɑː.mɪs/',
    definition: 'a statement telling someone that you will certainly do something',
    sentence: 'He kept his promise to walk the family dog every afternoon.',
    wordPromptScene: 'Two friendly cartoon hands making a pinky promise with glowing sparkles.',
    sentPromptScene: 'A boy walks his joyful dog to keep his daily promise.',
  },
  {
    word: 'select',
    partOfSpeech: 'v.',
    meaningKo: '선택하다, 고르다',
    ipa: '/səˈlekt/',
    definition: 'to choose someone or something carefully from a group',
    sentence: 'You can select three colorful toppings for your frozen yogurt.',
    wordPromptScene: 'A glowing cursor arrow pointing at one bright strawberry from a bowl.',
    sentPromptScene: 'A girl uses tongs to select fresh strawberries at the fruit stand.',
  },
  {
    word: 'pleasure',
    partOfSpeech: 'n.',
    meaningKo: '기쁨, 즐거움',
    ipa: '/ˈpleʒ.ɚ/',
    definition: 'a feeling of happy satisfaction and enjoyment',
    sentence: 'It was a true pleasure to meet the friendly author today.',
    wordPromptScene: 'A bright smiling sunshine character surrounded by musical notes and butterflies.',
    sentPromptScene: 'Students smile with pleasure as an author reads a funny story.',
  },
  {
    word: 'involve',
    partOfSpeech: 'v.',
    meaningKo: '포함하다, 수반하다',
    ipa: '/ɪnˈvɑːlv/',
    definition: 'to include someone or something as a necessary part',
    sentence: 'Science fair projects usually involve doing experiments and recording data.',
    wordPromptScene: 'Several colorful puzzle pieces coming together into a round sphere.',
    sentPromptScene: 'Team members plan an experiment to involve every student in class.',
  },
  {
    word: 'evolve',
    partOfSpeech: 'v.',
    meaningKo: '진화하다, 발전하다',
    ipa: '/ɪˈvɑːlv/',
    definition: 'to develop gradually over time into more advanced forms',
    sentence: 'Modern smartphones continue to evolve with faster chips and cameras.',
    wordPromptScene: 'A progression diagram of simple gears evolving into a futuristic robot.',
    sentPromptScene: 'A teacher shows how ancient tools continue to evolve into computers.',
  },
];

const day08_set2 = [
  {
    word: 'range',
    partOfSpeech: 'n.',
    meaningKo: '범위, 다양성',
    ipa: '/reɪndʒ/',
    definition: 'a group or series of different things of the same type',
    sentence: 'The art store offers a wide range of colorful paints.',
    wordPromptScene: 'A painter’s color wheel displaying a wide range of rainbow tones.',
    sentPromptScene: 'A student explores a wide range of books in the school library.',
  },
  {
    word: 'stuff',
    partOfSpeech: 'n.',
    meaningKo: '물건, 물질',
    ipa: '/stʌf/',
    definition: 'things that people have, use, or talk about in general',
    sentence: 'He packed all his camping stuff into a large green backpack.',
    wordPromptScene: 'A neat collection of school supplies, pencils, rulers, and scissors.',
    sentPromptScene: 'A boy packs his art stuff into a neat wooden toolbox.',
  },
  {
    word: 'journal',
    partOfSpeech: 'n.',
    meaningKo: '일기, 저널',
    ipa: '/ˈdʒɝː.nəl/',
    definition: 'a book in which you write personal thoughts and events',
    sentence: 'She writes three sentences in her nature journal every evening.',
    wordPromptScene: 'A leather-bound notebook with an illustrated leaf pressed inside open pages.',
    sentPromptScene: 'A girl sketches birds in her nature journal while sitting outdoors.',
  },
  {
    word: 'describe',
    partOfSpeech: 'v.',
    meaningKo: '묘사하다, 설명하다',
    ipa: '/dɪˈskraɪb/',
    definition: 'to say what someone or something is like using words',
    sentence: 'Can you describe the missing cartoon cat to the detective?',
    wordPromptScene: 'A magnifying glass looking at a cute sketched cartoon cat drawing.',
    sentPromptScene: 'A child uses adjectives to describe a colorful butterfly to classmates.',
  },
  {
    word: 'otherwise',
    partOfSpeech: 'adv.',
    meaningKo: '그렇지 않으면',
    ipa: '/ˈʌð.ɚ.waɪz/',
    definition: 'if not or in a different situation',
    sentence: 'Put on your warm raincoat, otherwise you will get wet.',
    wordPromptScene: 'A yellow raincoat hanging ready on a hook near front door.',
    sentPromptScene: 'A girl puts on boots otherwise rain puddles will wet socks.',
  },
  {
    word: 'share',
    partOfSpeech: 'v.',
    meaningKo: '공유하다, 나누다',
    ipa: '/ʃer/',
    definition: 'to give a part of something to others to use',
    sentence: 'It is kind to share your coloring markers with friends.',
    wordPromptScene: 'Two friendly cartoon hands sharing a freshly baked chocolate chip cookie.',
    sentPromptScene: 'A smiling boy offers to share his coloring pencils with a classmate.',
  },
  {
    word: 'jealous',
    partOfSpeech: 'adj.',
    meaningKo: '질투하는, 시기하는',
    ipa: '/ˈdʒel.əs/',
    definition: 'feeling unhappy because someone has something that you want',
    sentence: 'The little kitten was jealous of the puppy’s new blanket.',
    wordPromptScene: 'A small cartoon kitten peering curiously at a puppy with a toy.',
    sentPromptScene: 'A kitten watches a puppy with a ball without feeling jealous.',
  },
  {
    word: 'translate',
    partOfSpeech: 'v.',
    meaningKo: '번역하다, 통역하다',
    ipa: '/trænsˈleɪt/',
    definition: 'to change words from one language into another language',
    sentence: 'The digital dictionary can translate English phrases into Korean instantly.',
    wordPromptScene: 'Two speech bubbles connected by double arrows showing English and Korean letters.',
    sentPromptScene: 'A student uses an app to translate a fairy tale into English.',
  },
  {
    word: 'nod',
    partOfSpeech: 'v.',
    meaningKo: '고개를 끄덕이다',
    ipa: '/nɑːd/',
    definition: 'to move your head down and up to show agreement',
    sentence: 'The polite student will nod his head to show understanding.',
    wordPromptScene: 'A friendly cartoon face moving head in a clear agreeing nod gesture.',
    sentPromptScene: 'Children nod in agreement as the teacher explains the game rules.',
  },
  {
    word: 'mean',
    partOfSpeech: 'v.',
    meaningKo: '의미하다, 뜻하다',
    ipa: '/miːn/',
    definition: 'to express or have a particular meaning or intention',
    sentence: 'Red traffic lights always mean that vehicles must stop safely.',
    wordPromptScene: 'A clear traffic light shining bright red at a street corner.',
    sentPromptScene: 'A teacher explains what ancient symbols mean on the history poster.',
  },
];

const day08_set3 = [
  {
    word: 'conclude',
    partOfSpeech: 'v.',
    meaningKo: '결론을 내리다, 끝나다',
    ipa: '/kənˈkluːd/',
    definition: 'to finish something or form an opinion after thinking',
    sentence: 'We can conclude our science presentation with a short video.',
    wordPromptScene: 'A presentation slide displaying The End with sparkling confetti ribbons.',
    sentPromptScene: 'Speakers bow politely as they conclude their project presentation on stage.',
  },
  {
    word: 'intend',
    partOfSpeech: 'v.',
    meaningKo: '~할 작정이다, 의도하다',
    ipa: '/ɪnˈtend/',
    definition: 'to have a plan or purpose in your mind',
    sentence: 'I intend to plant sunflowers in the sunny garden tomorrow.',
    wordPromptScene: 'A seed packet of yellow sunflowers placed next to a garden trowel.',
    sentPromptScene: 'A young gardener holds sunflower seeds as he will intend to plant.',
  },
  {
    word: 'worth',
    partOfSpeech: 'adj.',
    meaningKo: '~의 가치가 있는',
    ipa: '/wɝːθ/',
    definition: 'having a particular value in money, effort, or importance',
    sentence: 'The long hike was worth the effort for this view.',
    wordPromptScene: 'A golden award coin surrounded by shimmering sparkling light rays.',
    sentPromptScene: 'Hikers cheer as the gorgeous mountaintop view is worth every step.',
  },
  {
    word: 'outcome',
    partOfSpeech: 'n.',
    meaningKo: '결과, 성과',
    ipa: '/ˈaʊt.kʌm/',
    definition: 'the final result or effect of an action or event',
    sentence: 'Hard work and practice led to a positive tournament outcome.',
    wordPromptScene: 'A scoreboard displaying a happy winning score with celebratory stars.',
    sentPromptScene: 'Team members celebrate a successful project outcome with cheerful smiles.',
  },
  {
    word: 'honor',
    partOfSpeech: 'n.',
    meaningKo: '영예, 명예',
    ipa: '/ˈɑː.nɚ/',
    definition: 'great respect, praise, or a proud privilege received',
    sentence: 'It was a great honor to represent our school team.',
    wordPromptScene: 'A shiny gold medal on a ribbon resting on a velvet cushion.',
    sentPromptScene: 'A student receives a certificate of honor at the school assembly.',
  },
  {
    word: 'internal',
    partOfSpeech: 'adj.',
    meaningKo: '내부의, 안의',
    ipa: '/ɪnˈtɝː.nəl/',
    definition: 'inside a person, object, or organization',
    sentence: 'The robot has internal wires protected by a sturdy metal shell.',
    wordPromptScene: 'A cutaway diagram of a friendly robot showing glowing internal gears.',
    sentPromptScene: 'An engineer inspects the internal parts of a toy solar car.',
  },
  {
    word: 'verbal',
    partOfSpeech: 'adj.',
    meaningKo: '구두의, 말로 하는',
    ipa: '/ˈvɝː.bəl/',
    definition: 'spoken rather than written, using spoken words',
    sentence: 'The coach gave clear verbal instructions before the relay race.',
    wordPromptScene: 'A friendly megaphone with musical spoken sound wave symbols.',
    sentPromptScene: 'A coach gives verbal guidance to young runners on the track.',
  },
  {
    word: 'besides',
    partOfSpeech: 'prep.',
    meaningKo: '~ 외에도, 게다가',
    ipa: '/bɪˈsaɪdz/',
    definition: 'in addition to or also something else',
    sentence: 'Besides English, she can speak fluent Korean and French everyday.',
    wordPromptScene: 'A stack of three language books topped with international flag bookmarks.',
    sentPromptScene: 'A student practices speaking French besides English in language club.',
  },
  {
    word: 'cure',
    partOfSpeech: 'v.',
    meaningKo: '치료하다, 낫게 하다',
    ipa: '/kjʊr/',
    definition: 'to make an illness or sickness go away completely',
    sentence: 'Fresh rest and warm soup will help cure your cold.',
    wordPromptScene: 'A steaming bowl of vegetable soup beside a glass of water.',
    sentPromptScene: 'A caring parent brings warm tea to help cure a cold.',
  },
  {
    word: 'core',
    partOfSpeech: 'n.',
    meaningKo: '핵심, 중심부',
    ipa: '/kɔːr/',
    definition: 'the basic, central, or most important part of something',
    sentence: 'The molten metal core lies deep inside the planet Earth.',
    wordPromptScene: 'A cutaway globe of planet Earth showing the glowing golden core.',
    sentPromptScene: 'A science teacher shows a 3D model of Earth’s central core.',
  },
];

const day08_set4 = [
  {
    word: 'strike',
    partOfSpeech: 'v.',
    meaningKo: '치다, 때리다',
    ipa: '/straɪk/',
    definition: 'to hit something forcibly with a hand or tool',
    sentence: 'The player used the wooden bat to strike the baseball.',
    wordPromptScene: 'A baseball bat making solid contact with a baseball with starburst lines.',
    sentPromptScene: 'A young batter swings firmly to strike the incoming practice baseball.',
  },
  {
    word: 'channel',
    partOfSpeech: 'n.',
    meaningKo: '채널, 수로',
    ipa: '/ˈtʃæn.əl/',
    definition: 'a television station or a passage for water to flow',
    sentence: 'We tuned into the science documentary channel on the television.',
    wordPromptScene: 'A television screen displaying a colorful planet documentary program.',
    sentPromptScene: 'A family selects an educational nature channel on their living room television.',
  },
  {
    word: 'gratitude',
    partOfSpeech: 'n.',
    meaningKo: '감사, 고마움',
    ipa: '/ˈɡræt̬.ə.tuːd/',
    definition: 'the feeling of being thankful and wanting to express thanks',
    sentence: 'She expressed her sincere gratitude with a lovely thank-you note.',
    wordPromptScene: 'A bouquet of colorful blooming gratitude tulips tied with a ribbon.',
    sentPromptScene: 'A student smiles with gratitude while handing a card to teacher.',
  },
  {
    word: 'metaphor',
    partOfSpeech: 'n.',
    meaningKo: '은유, 비유',
    ipa: '/ˈmet̬.ə.fɔːr/',
    definition: 'a word or phrase describing something by comparing it directly',
    sentence: 'Saying her smile is sunshine is a very warm metaphor.',
    wordPromptScene: 'An open poetry book with a glowing smiling sun emerging from words.',
    sentPromptScene: 'An English teacher explains how authors use a metaphor in poetry.',
  },
  {
    word: 'interpret',
    partOfSpeech: 'v.',
    meaningKo: '해석하다, 이해하다',
    ipa: '/ɪnˈtɝː.prət/',
    definition: 'to explain or understand the meaning of something',
    sentence: 'The art teacher helped us interpret the abstract modern painting.',
    wordPromptScene: 'A magnifying glass focusing on abstract geometric art shapes on canvas.',
    sentPromptScene: 'Students discuss together to interpret the meaning of a colorful painting.',
  },
  {
    word: 'insult',
    partOfSpeech: 'v.',
    meaningKo: '모욕하다, 무례하게 굴다',
    ipa: '/ɪnˈsʌlt/',
    definition: 'to say or do something rude that offends someone',
    sentence: 'Polite sports players never insult their opponents during the game.',
    wordPromptScene: 'Two cartoon hands shaking warmly over a soccer ball on pitch.',
    sentPromptScene: 'Players show fair play and never insult competitors on the court.',
  },
  {
    word: 'weird',
    partOfSpeech: 'adj.',
    meaningKo: '기이한, 이상한',
    ipa: '/wɪrd/',
    definition: 'very strange, unusual, or unexpected',
    sentence: 'We saw a weird purple mushroom growing in the forest.',
    wordPromptScene: 'A whimsical cartoon purple polka-dot mushroom glowing softly in moss.',
    sentPromptScene: 'An explorer discovers a weird glowing mushroom along a jungle trail.',
  },
  {
    word: 'random',
    partOfSpeech: 'adj.',
    meaningKo: '무작위의, 임의의',
    ipa: '/ˈræn.dəm/',
    definition: 'chosen or done without any particular plan or pattern',
    sentence: 'The computer selected a random winner for the school raffle.',
    wordPromptScene: 'A pair of colorful rolling board game dice in mid-air.',
    sentPromptScene: 'A student draws a random lucky ticket from a spinning wheel.',
  },
  {
    word: 'remark',
    partOfSpeech: 'n.',
    meaningKo: '발언, 언급',
    ipa: '/rɪˈmɑːrk/',
    definition: 'something that you say or write expressing an opinion',
    sentence: 'His kind remark made everyone in the room feel welcome.',
    wordPromptScene: 'A gentle glowing speech bubble containing a cheerful smiley face icon.',
    sentPromptScene: 'A speaker shares a friendly remark that makes the audience smile.',
  },
  {
    word: 'sentence',
    partOfSpeech: 'n.',
    meaningKo: '문장',
    ipa: '/ˈsen.təns/',
    definition: 'a group of words that expresses a complete thought',
    sentence: 'Every complete English sentence begins with a capital letter always.',
    wordPromptScene: 'A neat line of text on lined paper ending with a clear period.',
    sentPromptScene: 'A student writes a complete sentence neatly on the green chalkboard.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 8, set: 1, wordsData: day08_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 8, set: 2, wordsData: day08_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 8, set: 3, wordsData: day08_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 8, set: 4, wordsData: day08_set4 });
  console.log('DAY 08 written successfully');
}

run();
