import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 25
// ==========================================
const day25_set1 = [
  {
    word: 'environment',
    partOfSpeech: 'n.',
    meaningKo: '환경, 자연환경',
    ipa: '/ɪnˈvaɪ.rən.mənt/',
    definition: 'the air, water, and land in which people and plants live',
    sentence: 'Planting green trees helps protect our clean living environment.',
    wordPromptScene: 'A glowing Earth globe resting safely in the center of lush green leaves.',
    sentPromptScene: 'Children plant sunflower seedlings to improve their local school environment.',
  },
  {
    word: 'release',
    partOfSpeech: 'v.',
    meaningKo: '방출하다, 놓아주다',
    ipa: '/rɪˈliːs/',
    definition: 'to allow something to move, act, or flow freely',
    sentence: 'Students cheered as they helped release a healed sparrow into sky.',
    wordPromptScene: 'Two cartoon hands gently releasing a white dove into a bright blue sky.',
    sentPromptScene: 'A wildlife volunteer opens a carrier to release a rehabilitated sea turtle.',
  },
  {
    word: 'disaster',
    partOfSpeech: 'n.',
    meaningKo: '재난, 재앙',
    ipa: '/dɪˈzæs.tɚ/',
    definition: 'a sudden event causing great damage or loss, like storm',
    sentence: 'Careful planning helped prevent a major flood disaster in the valley.',
    wordPromptScene: 'A sturdy stone barrier successfully holding back rushing river waters.',
    sentPromptScene: 'Volunteers organize supplies to assist neighbors after a stormy weather disaster.',
  },
  {
    word: 'destroy',
    partOfSpeech: 'v.',
    meaningKo: '파괴하다, 망가뜨리다',
    ipa: '/dɪˈstrɔɪ/',
    definition: 'to damage something so badly that it cannot be used',
    sentence: 'Huge ocean waves can destroy sandcastles on the beach quickly.',
    wordPromptScene: 'A gentle sea wave washing smoothly over a playful sandcastle.',
    sentPromptScene: 'A rolling bowling ball knocks down all ten wooden pins to destroy the set.',
  },
  {
    word: 'waste',
    partOfSpeech: 'n.',
    meaningKo: '쓰레기, 낭비',
    ipa: '/weɪst/',
    definition: 'unwanted or unusable materials, items, or substances',
    sentence: 'Recycling paper helps reduce classroom waste and saves forest trees.',
    wordPromptScene: 'A set of blue, green, and yellow labeled recycling bins in a park.',
    sentPromptScene: 'Students collect plastic waste along the riverbank to keep nature clean.',
  },
  {
    word: 'period',
    partOfSpeech: 'n.',
    meaningKo: '기간, 시대, 교시',
    ipa: '/ˈpɪr.i.əd/',
    definition: 'a length of time, especially one characterized by features',
    sentence: 'We enjoyed a thirty-minute quiet reading period in the morning.',
    wordPromptScene: 'A wooden desk hourglass with colorful sand grains marking a period.',
    sentPromptScene: 'A school bell rings signaling the start of the afternoon art period.',
  },
  {
    word: 'announce',
    partOfSpeech: 'v.',
    meaningKo: '발표하다, 알리다',
    ipa: '/əˈnaʊns/',
    definition: 'to make something known publicly and officially to people',
    sentence: 'The principal will announce the science fair winners this afternoon.',
    wordPromptScene: 'A bright microphone with golden musical notes and star sparkles around.',
    sentPromptScene: 'A teacher speaks into the loudspeaker to announce the sports day date.',
  },
  {
    word: 'occur',
    partOfSpeech: 'v.',
    meaningKo: '발생하다, 일어나다',
    ipa: '/əˈkɝː/',
    definition: 'to happen or take place, especially unexpectedly',
    sentence: 'Rainbows often occur when sunshine breaks through gentle rain showers.',
    wordPromptScene: 'A brilliant rainbow arching across a sky with sunbeams and light rain.',
    sentPromptScene: 'A science teacher explains why solar eclipses occur only at specific times.',
  },
  {
    word: 'quality',
    partOfSpeech: 'n.',
    meaningKo: '품질, 특성, 우수함',
    ipa: '/ˈkwɑː.lə.t̬i/',
    definition: 'how good or bad something is, degree of excellence',
    sentence: 'The handmade wooden toys were known for their exceptional high quality.',
    wordPromptScene: 'A shiny gold quality assurance seal badge with five stars.',
    sentPromptScene: 'An inspector checks wooden blocks to ensure the highest safety quality.',
  },
  {
    word: 'quantity',
    partOfSpeech: 'n.',
    meaningKo: '양, 수량',
    ipa: '/ˈkwɑːn.t̬ə.t̬i/',
    definition: 'the amount or number of a material or abstract thing',
    sentence: 'The bakery ordered a large quantity of fresh organic flour.',
    wordPromptScene: 'A stack of ten brown paper flour sacks neatly arranged on pallet.',
    sentPromptScene: 'A student measures a precise quantity of baking powder for cookies.',
  },
];

const day25_set2 = [
  {
    word: 'protect',
    partOfSpeech: 'v.',
    meaningKo: '보호하다, 지키다',
    ipa: '/prəˈtekt/',
    definition: 'to keep someone or something safe from injury or damage',
    sentence: 'Wearing a helmet will protect your head while riding bicycles.',
    wordPromptScene: 'A sturdy glowing green shield protecting a seedling plant.',
    sentPromptScene: 'A mother bear walks beside her cubs to protect them in woods.',
  },
  {
    word: 'loss',
    partOfSpeech: 'n.',
    meaningKo: '손실, 상실',
    ipa: '/lɑːs/',
    definition: 'the fact or process of losing something or someone',
    sentence: 'Planting new saplings prevents soil loss during heavy seasonal rains.',
    wordPromptScene: 'Deep green tree roots holding dark rich soil securely on a hillside.',
    sentPromptScene: 'A gardener plants thick clover to prevent topsoil loss on the slope.',
  },
  {
    word: 'generate',
    partOfSpeech: 'v.',
    meaningKo: '발생시키다, 만들어 내다',
    ipa: '/ˈdʒen.ə.reɪt/',
    definition: 'to produce or create energy, power, heat, or ideas',
    sentence: 'Spinning wind turbines generate clean electricity for all town residents.',
    wordPromptScene: 'A sleek white wind turbine spinning with glowing green energy sparks.',
    sentPromptScene: 'Students brainstorm together to generate creative ideas for the school festival.',
  },
  {
    word: 'amazed',
    partOfSpeech: 'adj.',
    meaningKo: '깜짝 놀란, 감탄한',
    ipa: '/əˈmeɪzd/',
    definition: 'extremely surprised, impressed, or filled with wonder',
    sentence: 'Children were amazed by the magician’s floating card trick today.',
    wordPromptScene: 'A cute cartoon character with wide eyes looking at a magical glowing floating star.',
    sentPromptScene: 'Students are amazed when the chemistry solution suddenly turns bright purple.',
  },
  {
    word: 'harm',
    partOfSpeech: 'v.',
    meaningKo: '해치다, 피해를 주다',
    ipa: '/hɑːrm/',
    definition: 'to hurt, damage, or have a bad effect on someone',
    sentence: 'Always handle gentle garden snails carefully so you do not harm them.',
    wordPromptScene: 'Two gentle cartoon hands cupping a tiny garden snail safely.',
    sentPromptScene: 'Children place a lost butterfly on a flower so no one will harm it.',
  },
  {
    word: 'intense',
    partOfSpeech: 'adj.',
    meaningKo: '강렬한, 극심한',
    ipa: '/ɪnˈtens/',
    definition: 'extreme in force, degree, or strength, very strong',
    sentence: 'The runner showed intense focus during the final hundred meters.',
    wordPromptScene: 'A beam of intense bright focused golden light shining on a crystal.',
    sentPromptScene: 'A chess player shows intense concentration while analyzing the board.',
  },
  {
    word: 'amount',
    partOfSpeech: 'n.',
    meaningKo: '양, 액수',
    ipa: '/əˈmaʊnt/',
    definition: 'a quantity of something such as time, money, or substance',
    sentence: 'Add a small amount of honey to sweeten the tea.',
    wordPromptScene: 'A clear measuring cup filled with golden honey to the exact line.',
    sentPromptScene: 'A baker measures the correct amount of milk for the pancake recipe.',
  },
  {
    word: 'marine',
    partOfSpeech: 'adj.',
    meaningKo: '해양의, 바다의',
    ipa: '/məˈriːn/',
    definition: 'relating to or found in the sea or ocean',
    sentence: 'Dolphins and sea turtles are wonderful marine creatures of ocean.',
    wordPromptScene: 'A sea turtle gliding peacefully over a vibrant colorful marine coral reef.',
    sentPromptScene: 'Students study marine biology by observing small fish in an aquarium.',
  },
  {
    word: 'permanent',
    partOfSpeech: 'adj.',
    meaningKo: '영구적인, 영속하는',
    ipa: '/ˈpɝː.mə.nənt/',
    definition: 'lasting or intended to last for a long time or forever',
    sentence: 'The museum opened a permanent exhibition of ancient dinosaur fossils.',
    wordPromptScene: 'A carved stone plaque mounted permanently on a sturdy granite monument.',
    sentPromptScene: 'An artist uses permanent waterproof ink to sketch the city landscape.',
  },
  {
    word: 'fine',
    partOfSpeech: 'adj.',
    meaningKo: '좋은, 고운, 미세한',
    ipa: '/faɪn/',
    definition: 'of high quality, or made of very small particles',
    sentence: 'The beach was covered in soft and fine white sand.',
    wordPromptScene: 'A stream of fine white sand pouring smoothly through a wooden hourglass.',
    sentPromptScene: 'A pastry chef sifts fine powdered sugar over a warm berry tart.',
  },
];

const day25_set3 = [
  {
    word: 'pesticide',
    partOfSpeech: 'n.',
    meaningKo: '살충제, 농약',
    ipa: '/ˈpes.tə.saɪd/',
    definition: 'a chemical substance used to kill harmful insects on crops',
    sentence: 'Organic farmers choose natural remedies instead of chemical pesticide sprays.',
    wordPromptScene: 'A friendly ladybug resting on an organic green tomato leaf.',
    sentPromptScene: 'A farmer explains why organic apples are grown without any chemical pesticide.',
  },
  {
    word: 'alternative',
    partOfSpeech: 'n.',
    meaningKo: '대안, 대체물',
    ipa: '/ɑːlˈtɝː.nə.t̬ɪv/',
    definition: 'one of two or more things that can be chosen',
    sentence: 'Riding a bicycle is a healthy green alternative to driving.',
    wordPromptScene: 'A road fork sign showing paths for Bicycles and Walking.',
    sentPromptScene: 'A student chooses a fresh fruit smoothie as an alternative to soda.',
  },
  {
    word: 'respect',
    partOfSpeech: 'n.',
    meaningKo: '존중, 존경',
    ipa: '/rɪˈspekt/',
    definition: 'admiration felt or shown for someone because of good qualities',
    sentence: 'Showing respect to teachers and classmates creates a happy classroom.',
    wordPromptScene: 'Two friendly cartoon figures bowing politely with warm smiles.',
    sentPromptScene: 'Students listen attentively, showing respect during a classmate’s presentation.',
  },
  {
    word: 'vast',
    partOfSpeech: 'adj.',
    meaningKo: '광대한, 거대한',
    ipa: '/væst/',
    definition: 'extremely large in area, size, or amount, immense',
    sentence: 'A vast blue ocean stretched endlessly toward the distant horizon.',
    wordPromptScene: 'A panoramic view of a vast calm ocean meeting a clear blue sky.',
    sentPromptScene: 'Hikers gaze out over the vast expanse of the green mountain valley.',
  },
  {
    word: 'refreshing',
    partOfSpeech: 'adj.',
    meaningKo: '상쾌한, 신선한',
    ipa: '/rɪˈfreʃ.ɪŋ/',
    definition: 'making you feel cool, less hot, or full of energy',
    sentence: 'A cool glass of lemonade was very refreshing after soccer.',
    wordPromptScene: 'A tall glass of iced sparkling water with fresh mint and lemon.',
    sentPromptScene: 'A runner enjoys a refreshing splash of cool water on a warm afternoon.',
  },
  {
    word: 'responsible',
    partOfSpeech: 'adj.',
    meaningKo: '책임감 있는, 책임이 있는',
    ipa: '/rɪˈspɑːn.sə.bəl/',
    definition: 'having the duty of taking care of something or someone',
    sentence: 'A responsible pet owner feeds and walks the dog daily.',
    wordPromptScene: 'A child happily filling a dog bowl with food beside a clean pet bed.',
    sentPromptScene: 'A responsible student turns off classroom lights to conserve electric energy.',
  },
  {
    word: 'confuse',
    partOfSpeech: 'v.',
    meaningKo: '혼란스럽게 하다, 혼동하다',
    ipa: '/kənˈfjuːz/',
    definition: 'to make someone feel uncertain or unable to understand clearly',
    sentence: 'Clear instructions help so we do not confuse the rules.',
    wordPromptScene: 'A cartoon character with a small funny spiral question mark above head.',
    sentPromptScene: 'A teacher explains the game steps clearly so they do not confuse players.',
  },
  {
    word: 'separate',
    partOfSpeech: 'v.',
    meaningKo: '분리하다, 나누다',
    ipa: '/ˈsep.ə.reɪt/',
    definition: 'to divide into different parts or keep things apart',
    sentence: 'Remember to separate plastic bottles from paper for proper recycling.',
    wordPromptScene: 'Two sorting trays dividing colorful glass marbles into red and blue.',
    sentPromptScene: 'Students separate recyclable paper, cans, and bottles into designated colored bins.',
  },
  {
    word: 'delicate',
    partOfSpeech: 'adj.',
    meaningKo: '섬세한, 연약한',
    ipa: '/ˈdel.ə.kət/',
    definition: 'easily broken or damaged, made with fine care and skill',
    sentence: 'The delicate glass vase was decorated with tiny painted blossoms.',
    wordPromptScene: 'A delicate crystal snowflake ornament catching rainbow sunbeams on a ribbon.',
    sentPromptScene: 'An artist holds a delicate porcelain teacup with careful gentle hands.',
  },
  {
    word: 'dedicate',
    partOfSpeech: 'v.',
    meaningKo: '바치다, 헌신하다',
    ipa: '/ˈded.ə.keɪt/',
    definition: 'to give your time and energy to a particular activity',
    sentence: 'She will dedicate her afternoon to volunteering at animal shelter.',
    wordPromptScene: 'A glowing golden heart badge inscribed with a ribbon of dedication.',
    sentPromptScene: 'Musicians dedicate extra rehearsal hours to prepare for the spring concert.',
  },
];

const day25_set4 = [
  {
    word: 'extinction',
    partOfSpeech: 'n.',
    meaningKo: '멸종, 소멸',
    ipa: '/ɪkˈstɪŋk.ʃən/',
    definition: 'the state or situation that results when a species dies out',
    sentence: 'Museum exhibits teach how ancient dinosaurs faced complete global extinction.',
    wordPromptScene: 'A fossilized skeleton of a Tyrannosaurus Rex illuminated in a museum hall.',
    sentPromptScene: 'Students learn about conservation efforts to save endangered rhinos from extinction.',
  },
  {
    word: 'superior',
    partOfSpeech: 'adj.',
    meaningKo: '우수한, 뛰어난',
    ipa: '/səˈpɪr.i.ɚ/',
    definition: 'better than average or better than other people or things',
    sentence: 'The sturdy wooden blocks had superior durability compared to plastic.',
    wordPromptScene: 'A golden trophy with a five-star seal denoting superior craft quality.',
    sentPromptScene: 'A master craftsman explains why hand-stitched leather has superior strength.',
  },
  {
    word: 'consequence',
    partOfSpeech: 'n.',
    meaningKo: '결과, 결말',
    ipa: '/ˈkɑːn.sə.kwəns/',
    definition: 'a result of a particular action or situation, outcome',
    sentence: 'A healthy strong body is a natural consequence of regular exercise.',
    wordPromptScene: 'A green sprout growing into a blooming flower as the consequence of care.',
    sentPromptScene: 'A teacher explains the positive consequence of studying consistently every evening.',
  },
  {
    word: 'fabric',
    partOfSpeech: 'n.',
    meaningKo: '직물, 천, 구조',
    ipa: '/ˈfæb.rɪk/',
    definition: 'cloth or material produced by weaving cotton, wool, or silk',
    sentence: 'She chose a soft floral cotton fabric to sew a dress.',
    wordPromptScene: 'Spools of colorful silk and cotton fabric neatly rolled on a wooden shelf.',
    sentPromptScene: 'A tailor measures lengths of soft blue fabric with a measuring tape.',
  },
  {
    word: 'interrupt',
    partOfSpeech: 'v.',
    meaningKo: '방해하다, 중단시키다',
    ipa: '/ˌɪn.t̬əˈrʌpt/',
    definition: 'to stop a person from speaking by saying something yourself',
    sentence: 'Wait for your turn and do not interrupt when someone talks.',
    wordPromptScene: 'Two friendly speech bubbles waiting politely in turn for dialogue.',
    sentPromptScene: 'Students raise hands politely and never interrupt while the teacher is speaking.',
  },
  {
    word: 'concrete',
    partOfSpeech: 'n.',
    meaningKo: '콘크리트, 구체적인',
    ipa: '/ˈkɑːn.kriːt/',
    definition: 'a hard building material made from cement, sand, and water',
    sentence: 'Workers poured smooth gray concrete to pave the new sidewalk.',
    wordPromptScene: 'A smooth new concrete garden pathway winding through green lawn grass.',
    sentPromptScene: 'Builders smooth wet concrete on a park foundation with a trowel.',
  },
  {
    word: 'acknowledge',
    partOfSpeech: 'v.',
    meaningKo: '인정하다, 감사를 표하다',
    ipa: '/əkˈnɑː.lɪdʒ/',
    definition: 'to accept, admit, or recognize the truth or existence of something',
    sentence: 'The principal will acknowledge all student volunteers during the assembly.',
    wordPromptScene: 'A certificate of appreciation with a golden ribbon seal of recognition.',
    sentPromptScene: 'A speaker smiles to acknowledge the hard work of all event helpers.',
  },
  {
    word: 'considerable',
    partOfSpeech: 'adj.',
    meaningKo: '상당한, 많은',
    ipa: '/kənˈsɪd.ɚ.ə.bəl/',
    definition: 'large or of noticeable importance, amount, or extent',
    sentence: 'Building the community wooden playground required a considerable team effort.',
    wordPromptScene: 'A large sturdy wooden treehouse built through collaborative teamwork.',
    sentPromptScene: 'A student makes considerable progress in math through steady daily study.',
  },
  {
    word: 'discard',
    partOfSpeech: 'v.',
    meaningKo: '버리다, 폐기하다',
    ipa: '/dɪˈskɑːrd/',
    definition: 'to throw something away that you no longer want or need',
    sentence: 'Please discard fruit peelings into the green compost bin properly.',
    wordPromptScene: 'A hand placing apple peelings into a clean green kitchen compost bin.',
    sentPromptScene: 'A student cleans his desk to discard scrap paper into recycling.',
  },
  {
    word: 'matter',
    partOfSpeech: 'n.',
    meaningKo: '문제, 물질, 중요하다',
    ipa: '/ˈmæt̬.ɚ/',
    definition: 'physical substance in the universe, or an issue for discussion',
    sentence: 'Solids, liquids, and gases are three common states of matter.',
    wordPromptScene: 'An illustration showing ice, water, and steam representing three states of matter.',
    sentPromptScene: 'A science teacher shows how heat transforms matter from ice to vapor.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 25, set: 1, wordsData: day25_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 25, set: 2, wordsData: day25_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 25, set: 3, wordsData: day25_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 25, set: 4, wordsData: day25_set4 });
  console.log('DAY 25 written successfully');
}

run();
