import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 04
// ==========================================
const day04_set1 = [
  {
    word: 'career',
    partOfSpeech: 'n.',
    meaningKo: '경력, 직업',
    ipa: '/kəˈrɪr/',
    definition: 'a job or profession that you do for a long time',
    sentence: 'She chose a rewarding career as a friendly elementary teacher.',
    wordPromptScene: 'A winding pathway climbing up a mountain toward a shining star.',
    sentPromptScene: 'A smiling teacher happily points to a chalkboard in her career.',
  },
  {
    word: 'skill',
    partOfSpeech: 'n.',
    meaningKo: '기술, 솜씨',
    ipa: '/skɪl/',
    definition: 'the ability to do something well through practice',
    sentence: 'Learning to code is a very useful modern computer skill.',
    wordPromptScene: 'A colorful glowing toolkit containing a wrench, paintbrush, and compass.',
    sentPromptScene: 'A young programmer practices typing code to improve digital skill.',
  },
  {
    word: 'task',
    partOfSpeech: 'n.',
    meaningKo: '과업, 일',
    ipa: '/tæsk/',
    definition: 'a piece of work to be done, especially something difficult',
    sentence: 'Cleaning his messy bedroom was his first morning task today.',
    wordPromptScene: 'A clipboard checklist with three green checkmarks and a pencil.',
    sentPromptScene: 'A responsible boy puts away toys to finish his daily task.',
  },
  {
    word: 'tend',
    partOfSpeech: 'v.',
    meaningKo: '~하는 경향이 있다, 돌보다',
    ipa: '/tend/',
    definition: 'to be likely to do something or care for something',
    sentence: 'Young children tend to fall asleep during long car rides.',
    wordPromptScene: 'A gentle gardener tending to young green tomato plants in garden.',
    sentPromptScene: 'A caring gardener waters blooming red roses with a watering can.',
  },
  {
    word: 'position',
    partOfSpeech: 'n.',
    meaningKo: '위치, 직책',
    ipa: '/pəˈzɪʃ.ən/',
    definition: 'the place where someone or something is or a job',
    sentence: 'He applied for the open position of student team captain.',
    wordPromptScene: 'A bright red map pin pointing precisely on a colorful world globe.',
    sentPromptScene: 'A proud soccer player takes a forward position on the green field.',
  },
  {
    word: 'hire',
    partOfSpeech: 'v.',
    meaningKo: '고용하다, 채용하다',
    ipa: '/haɪr/',
    definition: 'to give someone a job in return for pay',
    sentence: 'The bakery owner decided to hire an assistant for morning baking.',
    wordPromptScene: 'Two friendly business characters shaking hands warmly in agreement.',
    sentPromptScene: 'A cheerful baker welcomes a new apprentice after deciding to hire him.',
  },
  {
    word: 'quit',
    partOfSpeech: 'v.',
    meaningKo: '그만두다, 중단하다',
    ipa: '/kwɪt/',
    definition: 'to stop doing something or leave a job',
    sentence: 'She decided to quit eating sugary candy before going to bed.',
    wordPromptScene: 'A red octagon stop sign glowing gently with a friendly smile.',
    sentPromptScene: 'A determined runner drinks fresh water and refuses to quit early.',
  },
  {
    word: 'proud',
    partOfSpeech: 'adj.',
    meaningKo: '자랑스러운, 뿌듯한',
    ipa: '/praʊd/',
    definition: 'feeling pleased and satisfied about something you did',
    sentence: 'The parents were proud of their daughter’s science fair victory.',
    wordPromptScene: 'A smiling cartoon lion with a gold medal around its neck.',
    sentPromptScene: 'A smiling girl holds her handmade robot and feels very proud.',
  },
  {
    word: 'labor',
    partOfSpeech: 'n.',
    meaningKo: '노동, 근로',
    ipa: '/ˈleɪ.bɚ/',
    definition: 'hard physical or mental work',
    sentence: 'Building the stone wall required many hours of physical labor.',
    wordPromptScene: 'A pair of durable work gloves resting on a wooden wheelbarrow.',
    sentPromptScene: 'Friendly construction workers build a wooden playground through teamwork and labor.',
  },
  {
    word: 'label',
    partOfSpeech: 'n.',
    meaningKo: '라벨, 상표표',
    ipa: '/ˈleɪ.bəl/',
    definition: 'a piece of paper or cloth giving information about something',
    sentence: 'Check the price label on the shirt before buying it.',
    wordPromptScene: 'A neat luggage tag tag tied with a string to a suitcase.',
    sentPromptScene: 'A student writes his name clearly on a book label sticker.',
  },
];

const day04_set2 = [
  {
    word: 'familiar',
    partOfSpeech: 'adj.',
    meaningKo: '익숙한, 친숙한',
    ipa: '/fəˈmɪl.jɚ/',
    definition: 'easy to recognize because you have seen it before',
    sentence: 'The friendly puppy recognized the familiar sound of his owner.',
    wordPromptScene: 'A warm cozy fireplace in a familiar living room setting.',
    sentPromptScene: 'A lost kitten purrs when it hears a familiar sweet whistle.',
  },
  {
    word: 'spread',
    partOfSpeech: 'v.',
    meaningKo: '펼치다, 바르다',
    ipa: '/spred/',
    definition: 'to cover a surface or open something out flat',
    sentence: 'Let us spread the picnic blanket on the green grass.',
    wordPromptScene: 'A butter knife spreading sweet strawberry jam across golden toast.',
    sentPromptScene: 'Two friends spread a red checkered blanket on a sunny hill.',
  },
  {
    word: 'divide',
    partOfSpeech: 'v.',
    meaningKo: '나누다, 분할하다',
    ipa: '/dɪˈvaɪd/',
    definition: 'to separate something into two or more parts',
    sentence: 'We will divide the round pizza into eight equal slices.',
    wordPromptScene: 'A pizza cutter neatly slicing a cheesy round pizza in half.',
    sentPromptScene: 'A boy uses a knife to divide a fresh watermelon evenly.',
  },
  {
    word: 'retire',
    partOfSpeech: 'v.',
    meaningKo: '은퇴하다, 퇴직하다',
    ipa: '/rɪˈtaɪr/',
    definition: 'to stop working because you have reached a certain age',
    sentence: 'Grandfather plans to retire next year and enjoy peaceful gardening.',
    wordPromptScene: 'A cozy rocking chair beside a warm window with garden view.',
    sentPromptScene: 'An elderly smiling teacher receives flowers as colleagues help him retire.',
  },
  {
    word: 'vision',
    partOfSpeech: 'n.',
    meaningKo: '시력, 비전, 꿈',
    ipa: '/ˈvɪʒ.ən/',
    definition: 'the ability to see or an idea for the future',
    sentence: 'The young inventor had a bold vision for clean energy.',
    wordPromptScene: 'A pair of round glasses looking towards a glowing lightbulb.',
    sentPromptScene: 'An architect sketches a futuristic city sharing his grand vision.',
  },
  {
    word: 'obstacle',
    partOfSpeech: 'n.',
    meaningKo: '장애물',
    ipa: '/ˈɑːb.stə.kəl/',
    definition: 'something that makes it difficult for you to move forward',
    sentence: 'The brave horse jumped cleanly over every wooden obstacle today.',
    wordPromptScene: 'A wooden hurdle hurdle bar on an obstacle course track.',
    sentPromptScene: 'A trained dog leaps over a hurdle obstacle with high energy.',
  },
  {
    word: 'contrary',
    partOfSpeech: 'adj.',
    meaningKo: '반대의, 반대되는',
    ipa: '/ˈkɑːn.trer.i/',
    definition: 'completely different from something else',
    sentence: 'The bright sunny weather was contrary to the cold forecast.',
    wordPromptScene: 'Two opposing arrows pointing in completely opposite left and right directions.',
    sentPromptScene: 'Children play in the sunshine contrary to the morning weather report.',
  },
  {
    word: 'arrange',
    partOfSpeech: 'v.',
    meaningKo: '정리하다, 배열하다',
    ipa: '/əˈreɪndʒ/',
    definition: 'to put things into a neat and orderly plan',
    sentence: 'She helped arrange the colorful flowers inside a glass vase.',
    wordPromptScene: 'Neatly organized books arranged in rainbow color order on shelf.',
    sentPromptScene: 'A florist arranges yellow and pink roses neatly in a vase.',
  },
  {
    word: 'attempt',
    partOfSpeech: 'v.',
    meaningKo: '시도하다',
    ipa: '/əˈtempt/',
    definition: 'to try to do something difficult',
    sentence: 'The baby bird will attempt its very first flight today.',
    wordPromptScene: 'A cute little bird spreading wings on a sturdy tree branch.',
    sentPromptScene: 'A young gymnast prepares to attempt a difficult backflip on mat.',
  },
  {
    word: 'board',
    partOfSpeech: 'v.',
    meaningKo: '탑승하다, 타다',
    ipa: '/bɔːrd/',
    definition: 'to get on a bus, train, plane, or ship',
    sentence: 'Passengers line up to board the yellow school bus safely.',
    wordPromptScene: 'A boarding pass ticket beside an airplane stairway ramp.',
    sentPromptScene: 'Happy students line up to board the yellow school bus in morning.',
  },
];

const day04_set3 = [
  {
    word: 'presentation',
    partOfSpeech: 'n.',
    meaningKo: '발표, 설명',
    ipa: '/ˌprez.ənˈteɪ.ʃən/',
    definition: 'a talk giving information about a topic to an audience',
    sentence: 'He gave an interesting presentation about solar system planets today.',
    wordPromptScene: 'A projector screen displaying colorful pie charts and space graphics.',
    sentPromptScene: 'A confident student delivers a science presentation using slides in class.',
  },
  {
    word: 'accomplish',
    partOfSpeech: 'v.',
    meaningKo: '성취하다, 해내다',
    ipa: '/əˈkɑːm.plɪʃ/',
    definition: 'to succeed in finishing something or achieving an aim',
    sentence: 'Together our team can accomplish even the hardest school goals.',
    wordPromptScene: 'A checkered flag waving proudly at a mountain peak summit.',
    sentPromptScene: 'Team members high-five each other after they accomplish their group project.',
  },
  {
    word: 'convince',
    partOfSpeech: 'v.',
    meaningKo: '설득하다, 확신시키다',
    ipa: '/kənˈvɪns/',
    definition: 'to make someone believe that something is true',
    sentence: 'She used clear facts to convince her friends to recycle.',
    wordPromptScene: 'A cartoon lightbulb turning on above a smiling listener’s head.',
    sentPromptScene: 'A passionate speaker uses posters to convince students to plant trees.',
  },
  {
    word: 'audience',
    partOfSpeech: 'n.',
    meaningKo: '청중, 관객',
    ipa: '/ˈɑː.di.əns/',
    definition: 'the group of people gathered to see or hear something',
    sentence: 'The delighted audience clapped enthusiastically after the magic show ended.',
    wordPromptScene: 'Silhouettes of many clapping people watching a lit stage performance.',
    sentPromptScene: 'A cheerful audience watches a puppet performance in a bright hall.',
  },
  {
    word: 'wage',
    partOfSpeech: 'n.',
    meaningKo: '임금, 급여',
    ipa: '/weɪdʒ/',
    definition: 'money paid to a worker for hours worked',
    sentence: 'Workers receive a fair hourly wage for their dedicated labor.',
    wordPromptScene: 'A neat stack of coins and a weekly payroll envelope.',
    sentPromptScene: 'A young worker receives an envelope with a weekly fair wage.',
  },
  {
    word: 'previous',
    partOfSpeech: 'adj.',
    meaningKo: '이전의, 앞선',
    ipa: '/ˈpriː.vi.əs/',
    definition: 'happening or existing before something else in time',
    sentence: 'Review the previous lesson before starting the new chapter today.',
    wordPromptScene: 'A calendar page pointing backward with a rewind time arrow.',
    sentPromptScene: 'A student looks at notes from the previous math lesson at desk.',
  },
  {
    word: 'spend',
    partOfSpeech: 'v.',
    meaningKo: '쓰다, 보내다',
    ipa: '/spend/',
    definition: 'to give money as payment or use time doing something',
    sentence: 'They love to spend quiet weekend afternoons reading adventure books.',
    wordPromptScene: 'A piggy bank with shiny coins being placed inside gently.',
    sentPromptScene: 'Friends spend a pleasant afternoon painting pictures in a sunny park.',
  },
  {
    word: 'distinguish',
    partOfSpeech: 'v.',
    meaningKo: '구별하다, 구분하다',
    ipa: '/dɪˈstɪŋ.ɡwɪʃ/',
    definition: 'to recognize the difference between two people or things',
    sentence: 'Can you distinguish between these two similar bird species easily?',
    wordPromptScene: 'A magnifying glass comparing two colorful patterned butterfly wings.',
    sentPromptScene: 'A young birdwatcher looks closely to distinguish two types of sparrows.',
  },
  {
    word: 'former',
    partOfSpeech: 'adj.',
    meaningKo: '이전의, 전자의',
    ipa: '/ˈfɔːr.mɚ/',
    definition: 'happening or existing in an earlier time',
    sentence: 'The former school building was transformed into a community center.',
    wordPromptScene: 'An antique sepia photo placed beside a modern color photo.',
    sentPromptScene: 'A town mayor visits the former school building newly renovated into library.',
  },
  {
    word: 'formal',
    partOfSpeech: 'adj.',
    meaningKo: '격식 있는, 공식적인',
    ipa: '/ˈfɔːr.məl/',
    definition: 'suitable for official or serious events and situations',
    sentence: 'He wore a formal black suit for the music award.',
    wordPromptScene: 'A crisp bowtie and tuxedo suit jacket on a mannequin.',
    sentPromptScene: 'Students dress in neat formal attire for the annual school ceremony.',
  },
];

const day04_set4 = [
  {
    word: 'envious',
    partOfSpeech: 'adj.',
    meaningKo: '부러워하는, 질투하는',
    ipa: '/ˈen.vi.əs/',
    definition: 'wishing you had something that another person has',
    sentence: 'He was not envious when his best friend won first.',
    wordPromptScene: 'A cartoon cat looking wistfully at a puppy’s shiny new ball.',
    sentPromptScene: 'A boy smiles and claps instead of feeling envious of winner.',
  },
  {
    word: 'vice',
    partOfSpeech: 'n.',
    meaningKo: '부(副), 대리',
    ipa: '/vaɪs/',
    definition: 'acting as a deputy or next in rank to a leader',
    sentence: 'The vice captain helped lead the team onto the field.',
    wordPromptScene: 'A silver deputy badge beside a golden captain badge.',
    sentPromptScene: 'The vice captain organizes sports equipment for teammates before the match.',
  },
  {
    word: 'architect',
    partOfSpeech: 'n.',
    meaningKo: '건축가',
    ipa: '/ˈɑːr.kə.tekt/',
    definition: 'a person whose job is designing new buildings',
    sentence: 'The talented architect drew blueprints for a modern wooden library.',
    wordPromptScene: 'A blue blueprint roll, wooden ruler, and a drawing compass.',
    sentPromptScene: 'An architect looks at 3D building models on a design desk.',
  },
  {
    word: 'relevant',
    partOfSpeech: 'adj.',
    meaningKo: '관련 있는, 적절한',
    ipa: '/ˈrel.ə.vənt/',
    definition: 'connected with what is happening or being discussed',
    sentence: 'Please include only relevant facts in your history essay today.',
    wordPromptScene: 'Two interlocking puzzle pieces with matching colorful patterns.',
    sentPromptScene: 'A student selects relevant book chapters to research for a project.',
  },
  {
    word: 'enthusiasm',
    partOfSpeech: 'n.',
    meaningKo: '열정, 열의',
    ipa: '/ɪnˈθuː.zi.æz.əm/',
    definition: 'a strong feeling of excitement and interest in something',
    sentence: 'Students showed great enthusiasm for the science robot competition.',
    wordPromptScene: 'A burning bright flame shaped like a smiling energetic star.',
    sentPromptScene: 'Excited kids cheer with enthusiasm as their robot moves forward.',
  },
  {
    word: 'desirable',
    partOfSpeech: 'adj.',
    meaningKo: '바람직한, 탐나는',
    ipa: '/dɪˈzaɪr.ə.bəl/',
    definition: 'worth having, wanting, or wishing for very much',
    sentence: 'Good reading habits are a very desirable quality for students.',
    wordPromptScene: 'A glowing golden apple sitting on a pedestal in sunlight.',
    sentPromptScene: 'A peaceful sunny room provides a desirable place for quiet study.',
  },
  {
    word: 'dismiss',
    partOfSpeech: 'v.',
    meaningKo: '해산시키다, 묵살하다',
    ipa: '/dɪsˈmɪs/',
    definition: 'to allow someone to leave or send them away',
    sentence: 'The bell will ring to dismiss students from the classroom.',
    wordPromptScene: 'A school bell ringing with smiling students walking out the door.',
    sentPromptScene: 'A teacher smiles to dismiss the class as the afternoon bell rings.',
  },
  {
    word: 'competent',
    partOfSpeech: 'adj.',
    meaningKo: '유능한, 능숙한',
    ipa: '/ˈkɑːm.pə.t̬ənt/',
    definition: 'having the necessary ability or skill to do something well',
    sentence: 'She is a competent swimmer who won many junior medals.',
    wordPromptScene: 'A swimming trophy and goggles resting beside a pool lane.',
    sentPromptScene: 'A competent young swimmer glides smoothly across the swimming pool.',
  },
  {
    word: 'memorize',
    partOfSpeech: 'v.',
    meaningKo: '암기하다, 외우다',
    ipa: '/ˈmem.ə.raɪz/',
    definition: 'to learn something so that you can remember it perfectly',
    sentence: 'He tried to memorize ten new vocabulary words each evening.',
    wordPromptScene: 'A glowing brain icon surrounded by floating alphabet letter blocks.',
    sentPromptScene: 'A student uses flashcards to memorize English words at his desk.',
  },
  {
    word: 'fix',
    partOfSpeech: 'v.',
    meaningKo: '고치다, 수리하다',
    ipa: '/fɪks/',
    definition: 'to repair something that is broken or damaged',
    sentence: 'The handy mechanic helped fix the broken bicycle chain quickly.',
    wordPromptScene: 'A shiny wrench tightening a metal bolt on a gear wheel.',
    sentPromptScene: 'A girl uses a small wrench to fix her bicycle chain.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 4, set: 1, wordsData: day04_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 4, set: 2, wordsData: day04_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 4, set: 3, wordsData: day04_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 4, set: 4, wordsData: day04_set4 });
  console.log('DAY 04 written successfully');
}

run();
