import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 14
// ==========================================
const day14_set1 = [
  {
    word: 'ancient',
    partOfSpeech: 'adj.',
    meaningKo: '고대의, 아주 오래된',
    ipa: '/ˈeɪn.ʃənt/',
    definition: 'from a long time ago, having lasted for thousands of years',
    sentence: 'Archaeologists discovered an ancient stone pyramid in the desert.',
    wordPromptScene: 'A majestic ancient stone pyramid glowing in warm sunset desert sands.',
    sentPromptScene: 'Tourists marvel at an ancient stone temple ruin during a guided tour.',
  },
  {
    word: 'tradition',
    partOfSpeech: 'n.',
    meaningKo: '전통, 관습',
    ipa: '/trəˈdɪʃ.ən/',
    definition: 'a custom or belief that has existed for a long time',
    sentence: 'Baking honey cookies together is our family’s holiday winter tradition.',
    wordPromptScene: 'A steaming tray of traditional gingerbread cookies and rolling pin.',
    sentPromptScene: 'A family makes traditional clay pots together in a craft workshop.',
  },
  {
    word: 'origin',
    partOfSpeech: 'n.',
    meaningKo: '기원, 유래',
    ipa: '/ˈɔːr.ə.dʒɪn/',
    definition: 'the point or place where something begins or arises',
    sentence: 'The teacher explained the historical origin of the Olympic games.',
    wordPromptScene: 'A globe showing glowing migratory lines tracing back to a golden origin star.',
    sentPromptScene: 'A museum guide explains the cultural origin of ancient pottery symbols.',
  },
  {
    word: 'folk',
    partOfSpeech: 'adj.',
    meaningKo: '민속의, 전통적인',
    ipa: '/foʊk/',
    definition: 'originating among ordinary people of a region or culture',
    sentence: 'We enjoyed listening to lively traditional folk music at festival.',
    wordPromptScene: 'An acoustic banjo and wooden tambourine resting on rustic hay.',
    sentPromptScene: 'Musicians play cheerful folk songs on acoustic instruments in village square.',
  },
  {
    word: 'device',
    partOfSpeech: 'n.',
    meaningKo: '장치, 기기',
    ipa: '/dɪˈvaɪs/',
    definition: 'an object or machine invented for a particular purpose',
    sentence: 'A digital pedometer is a useful device for counting steps.',
    wordPromptScene: 'A sleek modern smart wristband showing glowing digital heart rate numbers.',
    sentPromptScene: 'A student uses a handheld weather measurement device in science class.',
  },
  {
    word: 'usual',
    partOfSpeech: 'adj.',
    meaningKo: '평상시의, 보통의',
    ipa: '/ˈjuː.ʒu.əl/',
    definition: 'normal, happening most of the time, or customary',
    sentence: 'He walked to school along his usual quiet morning route.',
    wordPromptScene: 'A familiar cheerful suburban sidewalk lined with sunny maple trees.',
    sentPromptScene: 'A boy sits at his usual sunny window desk in the classroom.',
  },
  {
    word: 'ritual',
    partOfSpeech: 'n.',
    meaningKo: '의식, 의례',
    ipa: '/ˈrɪtʃ.u.əl/',
    definition: 'a set of fixed actions performed regularly in a ceremony',
    sentence: 'Drinking morning warm tea is a relaxing daily quiet ritual.',
    wordPromptScene: 'A delicate porcelain teapot, tea cup, and small blooming jasmine flower.',
    sentPromptScene: 'A student practices a morning stretching ritual before starting homework.',
  },
  {
    word: 'entire',
    partOfSpeech: 'adj.',
    meaningKo: '전체의, 온전한',
    ipa: '/ɪnˈtaɪr/',
    definition: 'whole or complete, with nothing left out',
    sentence: 'The enthusiastic student read the entire thick chapter book overnight.',
    wordPromptScene: 'A whole round unsliced golden pumpkin on a wooden table.',
    sentPromptScene: 'A girl completes the entire jigsaw puzzle on the living room rug.',
  },
  {
    word: 'region',
    partOfSpeech: 'n.',
    meaningKo: '지역, 지방',
    ipa: '/ˈriː.dʒən/',
    definition: 'a particular area in a country or the world',
    sentence: 'This mountainous region is famous for sweet wild honeycombs.',
    wordPromptScene: 'A topographical 3D terrain map showing rolling green mountain peaks.',
    sentPromptScene: 'Explorers map out the forest trails across the scenic mountain region.',
  },
  {
    word: 'religion',
    partOfSpeech: 'n.',
    meaningKo: '종교',
    ipa: '/rɪˈlɪdʒ.ən/',
    definition: 'a particular system of faith and worship of a god',
    sentence: 'Students learn about world history and diverse religion traditions peacefully.',
    wordPromptScene: 'An open ancient book illuminated by gentle warm candlelight.',
    sentPromptScene: 'A teacher shows photos of historical temples representing world religion history.',
  },
];

const day14_set2 = [
  {
    word: 'record',
    partOfSpeech: 'n.',
    meaningKo: '기록, 최고 기록',
    ipa: '/ˈrek.ɚd/',
    definition: 'the best achievement so far in a sport or activity',
    sentence: 'The young runner set a new school record in sprinting.',
    wordPromptScene: 'A golden track stopwatch displaying record-breaking numbers and star sparkles.',
    sentPromptScene: 'A runner celebrates crossing the finish line to set a new record.',
  },
  {
    word: 'settle',
    partOfSpeech: 'v.',
    meaningKo: '정착하다, 해결하다',
    ipa: '/ˈset̬.əl/',
    definition: 'to go and live permanently in a new place',
    sentence: 'Pioneers traveled west to settle near the fresh mountain river.',
    wordPromptScene: 'A cozy log cabin being built near a clear flowing stream.',
    sentPromptScene: 'A family chooses a sunny green valley to settle and build farm.',
  },
  {
    word: 'occupation',
    partOfSpeech: 'n.',
    meaningKo: '직업, 점유',
    ipa: '/ˌɑː.kjəˈpeɪ.ʃən/',
    definition: 'a person’s job or principal activity for earning a living',
    sentence: 'Teaching children to read is a very fulfilling and noble occupation.',
    wordPromptScene: 'Icons of a stethoscope, chef hat, wrench, and artist brush.',
    sentPromptScene: 'Students dress up to represent their future dream occupation on career day.',
  },
  {
    word: 'mass',
    partOfSpeech: 'n.',
    meaningKo: '덩어리, 질량, 대량',
    ipa: '/mæs/',
    definition: 'a large amount of substance with no definite shape, or matter',
    sentence: 'A huge mass of fluffy white clouds gathered over mountains.',
    wordPromptScene: 'A giant fluffy white cumulonimbus cloud floating in bright blue sky.',
    sentPromptScene: 'A baker kneads a large mass of golden bread dough on counter.',
  },
  {
    word: 'tap',
    partOfSpeech: 'v.',
    meaningKo: '가볍게 두드리다, 톡톡 치다',
    ipa: '/tæp/',
    definition: 'to hit something gently with a light, quick blow',
    sentence: 'He will tap his foot to the cheerful rhythm of music.',
    wordPromptScene: 'A colorful wooden drumstick tapping a snare drum with musical sparks.',
    sentPromptScene: 'A student uses two pencils to tap a fun beat on desk.',
  },
  {
    word: 'grasp',
    partOfSpeech: 'v.',
    meaningKo: '꽉 잡다, 이해하다',
    ipa: '/ɡræsp/',
    definition: 'to take hold of something tightly with your hand, or understand',
    sentence: 'The baby monkey used both hands to grasp the tree branch.',
    wordPromptScene: 'A cute baby monkey holding tightly onto a leafy jungle vine.',
    sentPromptScene: 'A young gymnast reaches up to grasp the gymnastics bar firmly.',
  },
  {
    word: 'fame',
    partOfSpeech: 'n.',
    meaningKo: '명성, 유명세',
    ipa: '/feɪm/',
    definition: 'the state of being known or talked about by many',
    sentence: 'The talented young pianist achieved international fame for her concerts.',
    wordPromptScene: 'A golden star plaque embedded in a shining red marble floor.',
    sentPromptScene: 'A humble artist enjoys painting more than seeking worldwide fame and spotlight.',
  },
  {
    word: 'comfort',
    partOfSpeech: 'n.',
    meaningKo: '편안함, 위로',
    ipa: '/ˈkʌm.fɚt/',
    definition: 'a state of physical ease and freedom from pain or worry',
    sentence: 'A warm woolen blanket gave great comfort on the chilly evening.',
    wordPromptScene: 'A fluffy soft fleece blanket and plush velvet cushion on a rocking chair.',
    sentPromptScene: 'A cup of warm cocoa brings sweet comfort on a snowy afternoon.',
  },
  {
    word: 'hole',
    partOfSpeech: 'n.',
    meaningKo: '구멍, 틈',
    ipa: '/hoʊl/',
    definition: 'an empty space in an object or opening in the ground',
    sentence: 'The little rabbit quickly hopped into its cozy underground burrow hole.',
    wordPromptScene: 'A neat round burrow hole in a grassy mound with wildflowers around.',
    sentPromptScene: 'A curious squirrel peeks out from a round hole in an oak tree.',
  },
  {
    word: 'succeed',
    partOfSpeech: 'v.',
    meaningKo: '성공하다, 뒤를 잇다',
    ipa: '/səkˈsiːd/',
    definition: 'to achieve the desired aim or result you tried for',
    sentence: 'If you try your hardest, you will surely succeed in learning.',
    wordPromptScene: 'A cartoon character standing victoriously at the top of a colorful staircase.',
    sentPromptScene: 'A student smiles proudly as hard work helps him succeed on exams.',
  },
];

const day14_set3 = [
  {
    word: 'routine',
    partOfSpeech: 'n.',
    meaningKo: '일과, 루틴',
    ipa: '/ruːˈtiːn/',
    definition: 'a fixed, regular way of doing things in sequence',
    sentence: 'Brushing teeth before bed is a healthy daily bedtime routine.',
    wordPromptScene: 'A neat daily schedule chart with illustrated toothbrush, book, and bed icons.',
    sentPromptScene: 'A student follows a morning routine of stretching and packing school bag.',
  },
  {
    word: 'numerous',
    partOfSpeech: 'adj.',
    meaningKo: '수많은, 다수의',
    ipa: '/ˈnuː.mɚ.əs/',
    definition: 'existing in large numbers, very many',
    sentence: 'We could see numerous sparkling stars shining in the night sky.',
    wordPromptScene: 'A dark velvet sky filled with numerous glittering golden star constellations.',
    sentPromptScene: 'A beachcomber collects numerous colorful sea shells along the ocean shore.',
  },
  {
    word: 'legend',
    partOfSpeech: 'n.',
    meaningKo: '전설',
    ipa: '/ˈledʒ.ənd/',
    definition: 'a traditional story sometimes regarded as historical but not proven',
    sentence: 'The village storyteller shared an exciting ancient legend about dragons.',
    wordPromptScene: 'A majestic friendly emerald dragon perched on an ancient stone tower.',
    sentPromptScene: 'Children listen wide-eyed to a famous legend about a lost magical city.',
  },
  {
    word: 'military',
    partOfSpeech: 'adj.',
    meaningKo: '군사의, 군대의',
    ipa: '/ˈmɪl.ə.ter.i/',
    definition: 'relating to soldiers, the army, or defense forces',
    sentence: 'The parade featured a marching military brass band playing patriotic songs.',
    wordPromptScene: 'A row of shiny brass trumpets and drums decorated with parade ribbons.',
    sentPromptScene: 'A ceremonial military marching band performs in neat formation at the plaza.',
  },
  {
    word: 'weapon',
    partOfSpeech: 'n.',
    meaningKo: '무기',
    ipa: '/ˈwep.ən/',
    definition: 'an object used in defense or board game knight battles',
    sentence: 'The foam sword was a fun toy weapon for knights.',
    wordPromptScene: 'A foam toy knight sword resting beside a colorful plastic shield.',
    sentPromptScene: 'Costumed children play with a safe foam weapon in school drama.',
  },
  {
    word: 'celebrate',
    partOfSpeech: 'v.',
    meaningKo: '축하하다, 기념하다',
    ipa: '/ˈsel.ə.breɪt/',
    definition: 'to do something enjoyable for an important special occasion',
    sentence: 'The entire family gathered to celebrate grandmother’s eightieth happy birthday.',
    wordPromptScene: 'A delicious layered birthday cake with glowing candles and flying confetti.',
    sentPromptScene: 'Friends throw party hats in the air to celebrate their graduation day.',
  },
  {
    word: 'combat',
    partOfSpeech: 'n.',
    meaningKo: '전투, 대결',
    ipa: '/ˈkɑːm.bæt/',
    definition: 'a contest or competition between opposing players or teams',
    sentence: 'The chess game was an intense strategic combat between masters.',
    wordPromptScene: 'A wooden chessboard with carved kings and knights locked in strategic position.',
    sentPromptScene: 'Two players focus deeply during a strategic combat on the tournament chessboard.',
  },
  {
    word: 'historical',
    partOfSpeech: 'adj.',
    meaningKo: '역사적인, 역사의',
    ipa: '/hɪˈstɔːr.ɪ.kəl/',
    definition: 'connected with the study or recording of past events',
    sentence: 'We visited a preserved historical wooden schoolhouse built in 1890.',
    wordPromptScene: 'An antique wooden school desk with an ink pot and slate board.',
    sentPromptScene: 'Students examine historical documents displayed safely inside museum glass cases.',
  },
  {
    word: 'royal',
    partOfSpeech: 'adj.',
    meaningKo: '왕실의, 국왕의',
    ipa: '/ˈrɔɪ.əl/',
    definition: 'belonging or connected to a king, queen, or their family',
    sentence: 'The royal crown was made of solid gold and rubies.',
    wordPromptScene: 'A gleaming gold royal crown studded with rubies on a velvet pillow.',
    sentPromptScene: 'A costumed actor wears a royal purple cape in a school play.',
  },
  {
    word: 'loyal',
    partOfSpeech: 'adj.',
    meaningKo: '충실한, 충성스러운',
    ipa: '/ˈlɔɪ.əl/',
    definition: 'giving firm and constant support or friendship to someone',
    sentence: 'The loyal golden retriever stayed right beside its young master always.',
    wordPromptScene: 'A faithful cartoon dog sitting loyally beside a pair of boots.',
    sentPromptScene: 'A loyal dog walks side by side with its owner along the beach.',
  },
];

const day14_set4 = [
  {
    word: 'harvest',
    partOfSpeech: 'n.',
    meaningKo: '수확, 추수',
    ipa: '/ˈhɑːr.vəst/',
    definition: 'the time of year when crops are cut and collected',
    sentence: 'Farmers celebrated an abundant autumn harvest of golden sweet corn.',
    wordPromptScene: 'A wicker basket brimming with ripe yellow ears of corn and pumpkins.',
    sentPromptScene: 'Farmers gather ripe red apples into wooden crates during autumn harvest.',
  },
  {
    word: 'illustrate',
    partOfSpeech: 'v.',
    meaningKo: '설명하다, 삽화를 넣다',
    ipa: '/ˈɪl.ə.streɪt/',
    definition: 'to draw pictures for a book, or explain clearly',
    sentence: 'The talented artist will illustrate the new magical fairytale book.',
    wordPromptScene: 'An artist’s easel with colorful paint brushes sketching a fairytale castle.',
    sentPromptScene: 'A graphic artist uses digital pens to illustrate a children’s storybook.',
  },
  {
    word: 'dare',
    partOfSpeech: 'v.',
    meaningKo: '감히 ~하다, 용기가 있다',
    ipa: '/der/',
    definition: 'to be brave enough to do something difficult',
    sentence: 'Few birds dare to fly close to the sleeping lion.',
    wordPromptScene: 'A small brave cartoon sparrow perched on a rock looking ahead.',
    sentPromptScene: 'Young explorers dare to venture into the mysterious glowing crystal cave.',
  },
  {
    word: 'voyage',
    partOfSpeech: 'n.',
    meaningKo: '항해, 긴 여행',
    ipa: '/ˈvɔɪ.ɪdʒ/',
    definition: 'a long journey, especially by ship across the sea',
    sentence: 'The wooden sailing ship embarked on a brave ocean voyage.',
    wordPromptScene: 'A grand tall ship with white sails gliding over sparkling blue seas.',
    sentPromptScene: 'Sailors wave goodbye from the deck as their voyage begins at harbor.',
  },
  {
    word: 'conventional',
    partOfSpeech: 'adj.',
    meaningKo: '전통적인, 관습적인',
    ipa: '/kənˈven.ʃən.əl/',
    definition: 'traditional and ordinary, following what is customary and standard',
    sentence: 'He preferred conventional paper books over reading on digital screens.',
    wordPromptScene: 'A classic hardcover paper book with a stitched fabric ribbon bookmark.',
    sentPromptScene: 'An architect uses conventional wooden beams to build a cozy country barn.',
  },
  {
    word: 'contemporary',
    partOfSpeech: 'adj.',
    meaningKo: '현대의, 동시대의',
    ipa: '/kənˈtem.pə.rer.i/',
    definition: 'existing or happening in the modern present time period',
    sentence: 'The city art gallery features exciting contemporary sculptures and paintings.',
    wordPromptScene: 'A sleek modern glass building with abstract geometric metal sculptures outside.',
    sentPromptScene: 'Visitors discuss an eye-catching contemporary abstract painting in a modern museum.',
  },
  {
    word: 'revolution',
    partOfSpeech: 'n.',
    meaningKo: '혁명, 대변혁, 회전',
    ipa: '/ˌrev.əˈluː.ʃən/',
    definition: 'a major change in ideas, methods, or government systems',
    sentence: 'The invention of the internet caused a huge digital revolution.',
    wordPromptScene: 'A glowing futuristic globe surrounded by digital interconnected data nodes.',
    sentPromptScene: 'A science teacher explains how renewable wind energy creates a clean revolution.',
  },
  {
    word: 'cooperation',
    partOfSpeech: 'n.',
    meaningKo: '협력, 협동',
    ipa: '/koʊˌɑː.pəˈreɪ.ʃən/',
    definition: 'the act of working together with someone towards a goal',
    sentence: 'Success in team sports requires strong communication and friendly cooperation.',
    wordPromptScene: 'Several diverse cartoon hands interlocking together in a supportive circle.',
    sentPromptScene: 'Students show great cooperation while building a bridge from craft sticks.',
  },
  {
    word: 'conquer',
    partOfSpeech: 'v.',
    meaningKo: '정복하다, 극복하다',
    ipa: '/ˈkɑːŋ.kɚ/',
    definition: 'to overcome a difficulty or take control through skill',
    sentence: 'With practice, you can conquer your fear of public speaking.',
    wordPromptScene: 'A climber planting a victory flag on a high snowy mountain peak.',
    sentPromptScene: 'A proud student smiles after practicing hard to conquer math anxiety.',
  },
  {
    word: 'stable',
    partOfSpeech: 'adj.',
    meaningKo: '안정된, 마구간',
    ipa: '/ˈsteɪ.bəl/',
    definition: 'firmly fixed or not likely to change or fall',
    sentence: 'The wooden table had sturdy four legs and was stable.',
    wordPromptScene: 'A solid four-legged wooden stool standing firmly on level ground.',
    sentPromptScene: 'Hikers cross a solid stone bridge that remains sturdy and stable.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 14, set: 1, wordsData: day14_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 14, set: 2, wordsData: day14_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 14, set: 3, wordsData: day14_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 14, set: 4, wordsData: day14_set4 });
  console.log('DAY 14 written successfully');
}

run();
