import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 30
// ==========================================
const day30_set1 = [
  {
    word: 'magazine',
    partOfSpeech: 'n.',
    meaningKo: '잡지',
    ipa: '/ˌmæɡ.əˈziːn/',
    definition: 'a periodical publication containing articles, stories, and photographs',
    sentence: 'She enjoyed reading a colorful children’s science magazine every month.',
    wordPromptScene: 'A glossy magazine cover featuring a vibrant space galaxy illustration.',
    sentPromptScene: 'Children sit in library reading a colorful monthly wildlife magazine.',
  },
  {
    word: 'article',
    partOfSpeech: 'n.',
    meaningKo: '기사, 글, 품목',
    ipa: '/ˈɑːr.t̬ɪ.kəl/',
    definition: 'a piece of writing included with others in a newspaper/magazine',
    sentence: 'He wrote an interesting news article for the school newspaper.',
    wordPromptScene: 'A printed newspaper column with a clear headline and color illustration.',
    sentPromptScene: 'A young reporter types an article about school sports on laptop.',
  },
  {
    word: 'press',
    partOfSpeech: 'v.',
    meaningKo: '누르다, 언론',
    ipa: '/pres/',
    definition: 'to apply firm, steady weight or force against something',
    sentence: 'Please press the green button to start the elevator motor.',
    wordPromptScene: 'A cartoon finger pressing a glowing green circular elevator button.',
    sentPromptScene: 'A student uses a thumb to press the doorbell at friend’s house.',
  },
  {
    word: 'advertise',
    partOfSpeech: 'v.',
    meaningKo: '광고하다, 홍보하다',
    ipa: '/ˈæd.vɚ.taɪz/',
    definition: 'to describe or draw attention to a product to encourage sales',
    sentence: 'Students made colorful posters to advertise the school bake sale.',
    wordPromptScene: 'A bright colorful billboard poster showing sweet cupcakes and fruit pies.',
    sentPromptScene: 'Children hold illustrated signs to advertise their charity lemon drink stand.',
  },
  {
    word: 'recent',
    partOfSpeech: 'adj.',
    meaningKo: '최근의, 얼마 전의',
    ipa: '/ˈriː.sənt/',
    definition: 'having happened, begun, or been done not long ago',
    sentence: 'The library received a recent shipment of exciting adventure storybooks.',
    wordPromptScene: 'A freshly unpacked cardboard box filled with brand new glossy books.',
    sentPromptScene: 'A science teacher discusses recent discoveries in solar space exploration.',
  },
  {
    word: 'diverse',
    partOfSpeech: 'adj.',
    meaningKo: '다양한',
    ipa: '/daɪˈvɝːs/',
    definition: 'showing a great deal of variety, very different',
    sentence: 'The botanical conservatory features a diverse collection of tropical plants.',
    wordPromptScene: 'A vibrant garden bed filled with diverse flowers in rainbow colors.',
    sentPromptScene: 'Students showcase diverse traditional costumes from around the world on stage.',
  },
  {
    word: 'document',
    partOfSpeech: 'n.',
    meaningKo: '문서, 서류',
    ipa: '/ˈdɑː.kjə.mənt/',
    definition: 'a piece of written, printed, or electronic matter providing information',
    sentence: 'Save your completed homework document in the shared project folder.',
    wordPromptScene: 'A formal printed document page with a blue ribbon and seal.',
    sentPromptScene: 'A student saves a digital science document on the computer cloud.',
  },
  {
    word: 'expert',
    partOfSpeech: 'n.',
    meaningKo: '전문가',
    ipa: '/ˈek.spɝːt/',
    definition: 'a person who has a comprehensive knowledge or skill in area',
    sentence: 'The visiting astronomer was a leading expert on distant galaxies.',
    wordPromptScene: 'An astronomer wearing glasses pointing at a starry celestial star globe.',
    sentPromptScene: 'An expert mechanic demonstrates how bicycle gears function to curious students.',
  },
  {
    word: 'explore',
    partOfSpeech: 'v.',
    meaningKo: '탐험하다, 탐구하다',
    ipa: '/ɪkˈsplɔːr/',
    definition: 'to travel through an unfamiliar area to learn about it',
    sentence: 'Curious hikers love to explore winding nature trails in spring.',
    wordPromptScene: 'A backpack, brass compass, and trail map resting on forest rock.',
    sentPromptScene: 'Children use magnifying glasses to explore tidal pools along the coast.',
  },
  {
    word: 'explode',
    partOfSpeech: 'v.',
    meaningKo: '폭발하다, 터지다',
    ipa: '/ɪkˈsploʊd/',
    definition: 'to burst or shatter violently and noisily, like party popper',
    sentence: 'Party poppers will explode with colorful shiny paper confetti ribbons.',
    wordPromptScene: 'A celebratory party popper bursting with colorful sparkling paper confetti streamers.',
    sentPromptScene: 'Children laugh as party poppers explode with ribbons at birthday celebration.',
  },
];

const day30_set2 = [
  {
    word: 'handle',
    partOfSpeech: 'v.',
    meaningKo: '다루다, 처리하다, 손잡이',
    ipa: '/ˈhæn.dəl/',
    definition: 'to manage, deal with, or control a situation or object',
    sentence: 'Careful training helps young gymnasts handle difficult balance beam routines.',
    wordPromptScene: 'A shiny brass door handle shaped like a smooth curved lever.',
    sentPromptScene: 'A student learns to handle delicate glass microscope slides with care.',
  },
  {
    word: 'phrase',
    partOfSpeech: 'n.',
    meaningKo: '구, 어구, 구절',
    ipa: '/freɪz/',
    definition: 'a small group of words standing together as a conceptual unit',
    sentence: 'Please repeat the new vocabulary phrase aloud with good pronunciation.',
    wordPromptScene: 'A neat chalkboard displaying a highlighted three-word greeting phrase.',
    sentPromptScene: 'Students practice an everyday conversational phrase in foreign language class.',
  },
  {
    word: 'annoy',
    partOfSpeech: 'v.',
    meaningKo: '짜증나게 하다, 귀찮게 하다',
    ipa: '/əˈnɔɪ/',
    definition: 'to irritate or make someone slightly angry by repeated action',
    sentence: 'A buzzing fly around the room began to annoy readers.',
    wordPromptScene: 'A cartoon bee buzzing in small harmless loops near a windowpane.',
    sentPromptScene: 'A student closes the window so street traffic noise will not annoy.',
  },
  {
    word: 'obvious',
    partOfSpeech: 'adj.',
    meaningKo: '명백한, 분명한',
    ipa: '/ˈɑːb.vi.əs/',
    definition: 'easily perceived or understood, clear, self-evident, or apparent',
    sentence: 'It was obvious that the sunny weather brought everyone outdoors.',
    wordPromptScene: 'A giant bright glowing yellow arrow pointing clearly toward a gate.',
    sentPromptScene: 'The correct puzzle solution becomes obvious once you align the pieces.',
  },
  {
    word: 'mention',
    partOfSpeech: 'v.',
    meaningKo: '언급하다, 말하다',
    ipa: '/ˈmen.ʃən/',
    definition: 'to refer to something briefly without going into detail',
    sentence: 'Be sure to mention your sources in the science bibliography.',
    wordPromptScene: 'A neat citation checklist at the bottom of a book page.',
    sentPromptScene: 'A speaker will mention the names of all student project helpers.',
  },
  {
    word: 'entertain',
    partOfSpeech: 'v.',
    meaningKo: '즐겁게 하다, 대접하다',
    ipa: '/en.t̬ɚˈteɪn/',
    definition: 'to provide someone with amusement, enjoyment, or hospitality',
    sentence: 'The cheerful circus clown used colorful juggling balls to entertain children.',
    wordPromptScene: 'A friendly jester juggling three colorful glowing balls with star sparkles.',
    sentPromptScene: 'Musicians entertain park visitors with upbeat folk melodies on acoustic guitars.',
  },
  {
    word: 'detail',
    partOfSpeech: 'n.',
    meaningKo: '세부 사항, 디테일',
    ipa: '/ˈdiː.teɪl/',
    definition: 'an individual feature, fact, or item in a whole',
    sentence: 'The artist painted every fine leaf detail on the canvas.',
    wordPromptScene: 'A magnifying glass revealing delicate fine brushwork lines on a painting.',
    sentPromptScene: 'An architect reviews every architectural detail on the building blueprint plans.',
  },
  {
    word: 'conflict',
    partOfSpeech: 'n.',
    meaningKo: '갈등, 충돌',
    ipa: '/ˈkɑːn.flɪkt/',
    definition: 'a serious disagreement or argument between people or characters',
    sentence: 'Good communication helps resolve any friendly playground game conflict peacefully.',
    wordPromptScene: 'Two puzzle pieces that didn’t fit being gently replaced to fit.',
    sentPromptScene: 'A teacher guides two students to resolve their playground game conflict.',
  },
  {
    word: 'thus',
    partOfSpeech: 'adv.',
    meaningKo: '따라서, 그러므로',
    ipa: '/ðʌs/',
    definition: 'as a result or consequence of this, therefore, in manner',
    sentence: 'We practiced daily and thus achieved a great performance score.',
    wordPromptScene: 'A glowing equals mathematical sign connecting study blocks to a trophy.',
    sentPromptScene: 'A scientist connects two chemical tubes and thus completes the demonstration.',
  },
  {
    word: 'medium',
    partOfSpeech: 'n.',
    meaningKo: '매체, 매개물, 중간의',
    ipa: '/ˈmiː.di.əm/',
    definition: 'an agency or means of doing something, artistic material',
    sentence: 'Watercolor is a wonderful artistic medium for painting sunny landscapes.',
    wordPromptScene: 'An artist palette with fresh watercolor paint pans and wet brushes.',
    sentPromptScene: 'An art teacher introduces clay sculpture as a tactile creative medium.',
  },
];

const day30_set3 = [
  {
    word: 'depress',
    partOfSpeech: 'v.',
    meaningKo: '누르다, 우울하게 하다',
    ipa: '/dɪˈpres/',
    definition: 'to push or press down a lever or button physically',
    sentence: 'Gently depress the piano key to play a soft note.',
    wordPromptScene: 'A cartoon finger pressing down a shiny white acoustic piano key.',
    sentPromptScene: 'A musician uses fingers to depress brass trumpet valves during rehearsal.',
  },
  {
    word: 'demand',
    partOfSpeech: 'n.',
    meaningKo: '수요, 요구',
    ipa: '/dɪˈmænd/',
    definition: 'the desire of purchasers for a commodity or service',
    sentence: 'There was high community demand for fresh local organic apples.',
    wordPromptScene: 'A busy fruit stall with customers eagerly selecting crisp red apples.',
    sentPromptScene: 'The library orders extra book copies to meet high student demand.',
  },
  {
    word: 'identify',
    partOfSpeech: 'v.',
    meaningKo: '식별하다, 확인하다',
    ipa: '/aɪˈden.t̬ə.faɪ/',
    definition: 'to establish or indicate who or what someone or something is',
    sentence: 'Use a field guide to identify colorful birds in garden.',
    wordPromptScene: 'An open bird guidebook with an illustrated chart of backyard birds.',
    sentPromptScene: 'Students use a leaf key chart to identify oak and maple trees.',
  },
  {
    word: 'award',
    partOfSpeech: 'n.',
    meaningKo: '상, 수상품',
    ipa: '/əˈwɔːrd/',
    definition: 'a prize or other mark of recognition given in honor',
    sentence: 'She received a golden ribbon award for her science project.',
    wordPromptScene: 'A gleaming gold ribbon medal with a five-star champion seal design.',
    sentPromptScene: 'The principal presents an academic achievement award to a proud student.',
  },
  {
    word: 'regret',
    partOfSpeech: 'v.',
    meaningKo: '후회하다, 유감스러워하다',
    ipa: '/rɪˈɡret/',
    definition: 'to feel sad, repentant, or disappointed over an action',
    sentence: 'You will not regret spending your sunny afternoon reading outdoors.',
    wordPromptScene: 'A cozy hammock under a shade tree with an open storybook.',
    sentPromptScene: 'A student smiles knowing she will never regret joining the music choir.',
  },
  {
    word: 'regard',
    partOfSpeech: 'v.',
    meaningKo: '여기다, 간주하다, 배려',
    ipa: '/rɪˈɡɑːrd/',
    definition: 'to consider or think of in a specified way, respect',
    sentence: 'Teachers regard honesty as the most important character trait in school.',
    wordPromptScene: 'A shining gold star emblem symbolizing honor, respect, and trustworthy values.',
    sentPromptScene: 'Students regard their dedicated elderly science teacher with immense admiration and affection.',
  },
  {
    word: 'inquire',
    partOfSpeech: 'v.',
    meaningKo: '묻다, 문의하다',
    ipa: '/ɪnˈkwaɪr/',
    definition: 'to ask for information from someone in a polite way',
    sentence: 'Visitors can inquire about tour schedules at the information desk.',
    wordPromptScene: 'A friendly information desk with an illustrated Guide Map banner above.',
    sentPromptScene: 'A student steps up to the librarian to inquire about book renewals.',
  },
  {
    word: 'script',
    partOfSpeech: 'n.',
    meaningKo: '대본, 각본, 글씨체',
    ipa: '/skrɪpt/',
    definition: 'the written text of a play, film, or broadcast',
    sentence: 'Actors read their lines aloud from the theatrical play script.',
    wordPromptScene: 'A bound theater script with highlighted character lines and pencil notes.',
    sentPromptScene: 'Students practice dialogue lines from their historical drama play script in class.',
  },
  {
    word: 'decline',
    partOfSpeech: 'v.',
    meaningKo: '감소하다, 거절하다',
    ipa: '/dɪˈklaɪn/',
    definition: 'to become smaller, fewer, or politely refuse an invitation',
    sentence: 'Evening temperatures begin to decline as the golden sun sets.',
    wordPromptScene: 'A smooth downward curving line chart with soothing twilight cloud hues.',
    sentPromptScene: 'A polite guest says thank you but chooses to decline extra dessert.',
  },
  {
    word: 'declare',
    partOfSpeech: 'v.',
    meaningKo: '선언하다, 공표하다',
    ipa: '/dɪˈkler/',
    definition: 'to announce something clearly, firmly, and officially to all',
    sentence: 'The mayor will declare the annual spring flower festival officially open.',
    wordPromptScene: 'A golden horn trumpet with an official herald banner announcing festival.',
    sentPromptScene: 'A referee raises a hand to declare the fair match winner.',
  },
];

const day30_set4 = [
  {
    word: 'deceive',
    partOfSpeech: 'v.',
    meaningKo: '속이다, 기만하다',
    ipa: '/dɪˈsiːv/',
    definition: 'to cause someone to believe something that is not true',
    sentence: 'Optical illusions can easily deceive our eyes with playful perspective tricks.',
    wordPromptScene: 'A checkerboard optical illusion where straight lines appear playfully wavy.',
    sentPromptScene: 'A science teacher demonstrates how curved mirrors can deceive our visual perception.',
  },
  {
    word: 'external',
    partOfSpeech: 'adj.',
    meaningKo: '외부의, 밖의',
    ipa: '/ɪkˈstɝː.nəl/',
    definition: 'belonging to or forming the outer surface or structure',
    sentence: 'The turtle’s hard shell provides strong external protection from predators.',
    wordPromptScene: 'A patterned green turtle shell showing sturdy interlocking protective plates.',
    sentPromptScene: 'Engineers inspect the sturdy external brick walls of the historical school.',
  },
  {
    word: 'instantly',
    partOfSpeech: 'adv.',
    meaningKo: '즉시, 당장',
    ipa: '/ˈɪn.stənt.li/',
    definition: 'at once, immediately, without any delay in time',
    sentence: 'Flipping the wall switch will instantly illuminate the whole room.',
    wordPromptScene: 'A light switch clicked on causing a ceiling bulb to shine instantly.',
    sentPromptScene: 'Students recognize the familiar melody instantly and begin humming along happily.',
  },
  {
    word: 'norm',
    partOfSpeech: 'n.',
    meaningKo: '규범, 표준, 기준',
    ipa: '/nɔːrm/',
    definition: 'something that is usual, typical, or standard practice in society',
    sentence: 'Recycling paper and cans is a healthy community norm here.',
    wordPromptScene: 'A friendly community charter poster showing shared neighborhood recycling standards.',
    sentPromptScene: 'Raising hands before speaking is the polite standard norm in class.',
  },
  {
    word: 'analyze',
    partOfSpeech: 'v.',
    meaningKo: '분석하다, 분해하다',
    ipa: '/ˈæn.əl.aɪz/',
    definition: 'to examine methodically and in detail the constitution or structure',
    sentence: 'Students use charts to analyze daily rainfall patterns in science.',
    wordPromptScene: 'A digital tablet showing colorful analytical charts, graphs, and percentage data.',
    sentPromptScene: 'Young scientists analyze water samples under high-power microscopes in laboratory.',
  },
  {
    word: 'clarify',
    partOfSpeech: 'v.',
    meaningKo: '명확하게 하다, 분명히 하다',
    ipa: '/ˈkler.ə.faɪ/',
    definition: 'to make an idea or statement clear or easy to understand',
    sentence: 'The teacher used diagrams to clarify the complex math rule.',
    wordPromptScene: 'A blurry sketch transforming into a sharp crystal clear blueprint diagram.',
    sentPromptScene: 'A teacher answers questions patiently to clarify the science experiment steps.',
  },
  {
    word: 'defend',
    partOfSpeech: 'v.',
    meaningKo: '방어하다, 지키다',
    ipa: '/dɪˈfend/',
    definition: 'to protect from harm or danger, or guard a goal',
    sentence: 'The alert goalkeeper leaped across to defend the soccer goal.',
    wordPromptScene: 'A soccer goalkeeper wearing padded gloves blocking a speeding soccer ball.',
    sentPromptScene: 'A chess player moves her rook piece to defend the king.',
  },
  {
    word: 'reputation',
    partOfSpeech: 'n.',
    meaningKo: '명성, 평판',
    ipa: '/ˌrep.jəˈteɪ.ʃən/',
    definition: 'the beliefs or opinions that are generally held about someone',
    sentence: 'The bakery has a well-deserved reputation for delicious sourdough loaves.',
    wordPromptScene: 'A shiny five-star quality plaque displayed proudly in a shop window.',
    sentPromptScene: 'A skilled watchmaker earns a trusted reputation for precision repair work.',
  },
  {
    word: 'exclude',
    partOfSpeech: 'v.',
    meaningKo: '제외하다, 배제하다',
    ipa: '/ɪkˈskluːd/',
    definition: 'to deny someone or something access to place or group',
    sentence: 'Our inclusive playground games never exclude any student from joining.',
    wordPromptScene: 'A large circle of diverse smiling children welcoming a new friend.',
    sentPromptScene: 'Team captains make sure they never exclude anyone from playing kickball.',
  },
  {
    word: 'net',
    partOfSpeech: 'n.',
    meaningKo: '그물, 골대 망, 순수한',
    ipa: '/net/',
    definition: 'a piece of open-meshed material used for catching or goals',
    sentence: 'The soccer ball flew cleanly into the back of net.',
    wordPromptScene: 'A crisp white soccer goal net rippling as a ball lands inside.',
    sentPromptScene: 'Children use a soft butterfly net to gently catch and observe insects.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 30, set: 1, wordsData: day30_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 30, set: 2, wordsData: day30_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 30, set: 3, wordsData: day30_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 30, set: 4, wordsData: day30_set4 });
  console.log('DAY 30 written successfully');
}

run();
