import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 15
// ==========================================
const day15_set1 = [
  {
    word: 'university',
    partOfSpeech: 'n.',
    meaningKo: '대학교',
    ipa: '/ˌjuː.nəˈvɝː.sə.t̬i/',
    definition: 'a school of high-level education offering degree programs',
    sentence: 'The grand brick university library welcomed scholars from around world.',
    wordPromptScene: 'A historic brick university campus building with grand pillars and ivy.',
    sentPromptScene: 'Students walk across a green sunny lawn at the university campus.',
  },
  {
    word: 'education',
    partOfSpeech: 'n.',
    meaningKo: '교육',
    ipa: '/ˌedʒ.uˈkeɪ.ʃən/',
    definition: 'the process of teaching or learning in a school',
    sentence: 'A good elementary education builds a strong foundation for life.',
    wordPromptScene: 'A graduation mortarboard cap resting on a stack of textbooks.',
    sentPromptScene: 'A teacher guides eager children during a fun interactive science education lesson.',
  },
  {
    word: 'focus',
    partOfSpeech: 'v.',
    meaningKo: '집중하다, 초점을 맞추다',
    ipa: '/ˈfoʊ.kəs/',
    definition: 'to give all your attention to a particular subject',
    sentence: 'Please focus your attention on the board during math class.',
    wordPromptScene: 'A camera lens aperture focusing sharply on a glowing light point.',
    sentPromptScene: 'A student sits at his desk to focus completely on homework.',
  },
  {
    word: 'entry',
    partOfSpeech: 'n.',
    meaningKo: '입구, 입장, 참가작',
    ipa: '/ˈen.tri/',
    definition: 'the door, gate, or act of going into a place',
    sentence: 'The stone archway marked the grand main entry of park.',
    wordPromptScene: 'A decorative wrought iron garden gate opening into blooming rose paths.',
    sentPromptScene: 'Visitors walk through the welcoming main entry of the science museum.',
  },
  {
    word: 'medical',
    partOfSpeech: 'adj.',
    meaningKo: '의학의, 의료의',
    ipa: '/ˈmed.ɪ.kəl/',
    definition: 'related to the treatment of illness and health injuries',
    sentence: 'The friendly school nurse provided gentle medical care to students.',
    wordPromptScene: 'A modern stethoscope and a clean medical first-aid kit box.',
    sentPromptScene: 'A caring doctor uses a stethoscope for a routine medical checkup.',
  },
  {
    word: 'accept',
    partOfSpeech: 'v.',
    meaningKo: '받아들이다, 수락하다',
    ipa: '/əkˈsept/',
    definition: 'to agree to take something that is offered to you',
    sentence: 'She was delighted to accept the invitation to the party.',
    wordPromptScene: 'Two friendly hands accepting a glowing gift box with a bow.',
    sentPromptScene: 'A student smiles warmly to accept a certificate of merit on stage.',
  },
  {
    word: 'pioneer',
    partOfSpeech: 'n.',
    meaningKo: '개척자, 선구자',
    ipa: '/ˌpaɪ.əˈnɪr/',
    definition: 'a person who is one of the first to develop ideas',
    sentence: 'Marie Curie was a brave scientific pioneer in physics discoveries.',
    wordPromptScene: 'A glowing brass compass resting beside an explorer’s rolled world map.',
    sentPromptScene: 'A teacher shares stories of a space pioneer who explored the moon.',
  },
  {
    word: 'mathematics',
    partOfSpeech: 'n.',
    meaningKo: '수학',
    ipa: '/ˌmæθˈmæt̬.ɪks/',
    definition: 'the study of numbers, shapes, logic, and measurements',
    sentence: 'Solving geometry puzzles makes mathematics an exciting school subject daily.',
    wordPromptScene: 'A wooden ruler, protractor, compass, and colorful geometric shapes.',
    sentPromptScene: 'Students use rulers and blocks during an active mathematics workshop.',
  },
  {
    word: 'professor',
    partOfSpeech: 'n.',
    meaningKo: '교수',
    ipa: '/prəˈfes.ɚ/',
    definition: 'a teacher of the highest rank in a university',
    sentence: 'The astronomy professor explained the rings of Saturn to visitors.',
    wordPromptScene: 'A friendly professor wearing tweed jacket pointing at a chalkboard galaxy.',
    sentPromptScene: 'A university professor demonstrates chemistry experiments to visiting school children.',
  },
  {
    word: 'profession',
    partOfSpeech: 'n.',
    meaningKo: '전문직, 직업',
    ipa: '/prəˈfeʃ.ən/',
    definition: 'any type of work that needs special training or skill',
    sentence: 'Nursing is a caring profession dedicated to helping sick people.',
    wordPromptScene: 'A collage of tools representing architecture, medicine, law, and engineering.',
    sentPromptScene: 'An architect sketches building plans representing his chosen design profession.',
  },
];

const day15_set2 = [
  {
    word: 'theory',
    partOfSpeech: 'n.',
    meaningKo: '이론, 학설',
    ipa: '/ˈθɪr.i/',
    definition: 'a formal idea or set of ideas explaining something',
    sentence: 'Scientists tested their new theory with multiple laboratory experiments today.',
    wordPromptScene: 'A blackboard filled with neat chalk diagrams of light waves.',
    sentPromptScene: 'A young scientist explains her theory using a tabletop volcano model.',
  },
  {
    word: 'philosophy',
    partOfSpeech: 'n.',
    meaningKo: '철학',
    ipa: '/fɪˈlɑː.sə.fi/',
    definition: 'the study of the fundamental nature of knowledge and reality',
    sentence: 'Ancient Greek philosophy encourages people to seek truth and wisdom.',
    wordPromptScene: 'A classic marble bust statue surrounded by ancient leather scrolls.',
    sentPromptScene: 'Students sit in a circle discussing fairness in a philosophy club.',
  },
  {
    word: 'method',
    partOfSpeech: 'n.',
    meaningKo: '방법, 방식',
    ipa: '/ˈmeθ.əd/',
    definition: 'a particular way of doing something, especially a systematic one',
    sentence: 'Using flashcards is an effective study method for learning vocabulary.',
    wordPromptScene: 'A series of numbered flowchart steps leading to a glowing star.',
    sentPromptScene: 'A teacher demonstrates a simple step-by-step method for solving equations.',
  },
  {
    word: 'praise',
    partOfSpeech: 'v.',
    meaningKo: '칭찬하다, 찬양하다',
    ipa: '/preɪz/',
    definition: 'to express strong approval or admiration of someone or something',
    sentence: 'Parents and teachers praise students for their honest team efforts.',
    wordPromptScene: 'Two friendly cartoon hands giving a double enthusiastic thumbs up.',
    sentPromptScene: 'A coach claps warmly to praise players for good sportsmanship.',
  },
  {
    word: 'standard',
    partOfSpeech: 'n.',
    meaningKo: '기준, 표준',
    ipa: '/ˈstæn.dɚd/',
    definition: 'a level of quality or attainment that is considered acceptable',
    sentence: 'The clean laboratory maintains a very high standard of hygiene.',
    wordPromptScene: 'A golden standard meter ruler with precise engraved measurement tick marks.',
    sentPromptScene: 'Inspectors check equipment to ensure each item meets the safety standard.',
  },
  {
    word: 'character',
    partOfSpeech: 'n.',
    meaningKo: '등장인물, 성격, 글자',
    ipa: '/ˈker.ək.tɚ/',
    definition: 'a person in a story, book, play, or movie',
    sentence: 'The cheerful wizard was my favorite character in the fantasy tale.',
    wordPromptScene: 'A charming cartoon wizard character holding a glowing star-tipped wand.',
    sentPromptScene: 'An author sketches a new animal character for an illustrated storybook.',
  },
  {
    word: 'throw',
    partOfSpeech: 'v.',
    meaningKo: '던지다',
    ipa: '/θroʊ/',
    definition: 'to send something through the air by moving your arm',
    sentence: 'He learned how to throw the baseball straight and fast.',
    wordPromptScene: 'A white baseball flying through the air with dynamic motion trails.',
    sentPromptScene: 'A boy steps forward to throw a ball to his friend.',
  },
  {
    word: 'psychology',
    partOfSpeech: 'n.',
    meaningKo: '심리학',
    ipa: '/saɪˈkɑː.lə.dʒi/',
    definition: 'the scientific study of the human mind and its functions',
    sentence: 'Reading about child psychology helps teachers understand how kids learn.',
    wordPromptScene: 'A glowing silhouette of a human profile with a vibrant puzzle inside.',
    sentPromptScene: 'A professor gives a lecture on the fascinating history of psychology.',
  },
  {
    word: 'intention',
    partOfSpeech: 'n.',
    meaningKo: '의도, 목적',
    ipa: '/ɪnˈten.ʃən/',
    definition: 'something that you want and plan to do, an aim',
    sentence: 'It was never his intention to hurt anyone’s friendly feelings.',
    wordPromptScene: 'An archery bow aimed carefully at the bright center of a target.',
    sentPromptScene: 'A boy explains his kind intention when helping fix a broken toy.',
  },
  {
    word: 'apply',
    partOfSpeech: 'v.',
    meaningKo: '신청하다, 적용하다, 바르다',
    ipa: '/əˈplaɪ/',
    definition: 'to make a formal application for a job, club, or school',
    sentence: 'She decided to apply for the school robotics summer camp.',
    wordPromptScene: 'An official application form with a pen and a Submitted badge.',
    sentPromptScene: 'A student fills out a form to apply for the chess club.',
  },
];

const day15_set3 = [
  {
    word: 'tune',
    partOfSpeech: 'n.',
    meaningKo: '곡조, 멜로디',
    ipa: '/tuːn/',
    definition: 'a series of musical notes that produce a pleasing song',
    sentence: 'The cheerful whistling bird whistled a catchy morning musical tune.',
    wordPromptScene: 'A stream of colorful musical notes floating out from a flute.',
    sentPromptScene: 'A young flutist plays a lively folk tune for the class.',
  },
  {
    word: 'submit',
    partOfSpeech: 'v.',
    meaningKo: '제출하다',
    ipa: '/səbˈmɪt/',
    definition: 'to give a document to someone for their approval',
    sentence: 'Remember to submit your science fair report before noon today.',
    wordPromptScene: 'A neat paper report sliding smoothly into a teacher’s inbox tray.',
    sentPromptScene: 'A student walks to the desk to submit her completed homework.',
  },
  {
    word: 'logical',
    partOfSpeech: 'adj.',
    meaningKo: '논리적인, 타당한',
    ipa: '/ˈlɑː.dʒɪ.kəl/',
    definition: 'using sensible reason and clear thinking to solve problems',
    sentence: 'Follow a logical step-by-step method to solve the math puzzle.',
    wordPromptScene: 'Neatly interlocking colorful puzzle gears turning smoothly together.',
    sentPromptScene: 'A student presents a clear logical argument during the school debate.',
  },
  {
    word: 'blame',
    partOfSpeech: 'v.',
    meaningKo: '비난하다, 탓하다',
    ipa: '/bleɪm/',
    definition: 'to say or think that someone is responsible for something',
    sentence: 'Good teammates never blame others when a match is lost.',
    wordPromptScene: 'Two cartoon hands shaking over a fallen board game piece warmly.',
    sentPromptScene: 'Players encourage each other and do not blame teammates after defeat.',
  },
  {
    word: 'display',
    partOfSpeech: 'v.',
    meaningKo: '전시하다, 보여주다',
    ipa: '/dɪˈspleɪ/',
    definition: 'to put something in a prominent place for people to see',
    sentence: 'Art teachers will display student paintings in the main lobby.',
    wordPromptScene: 'An art gallery easel displaying a colorful landscape watercolor painting.',
    sentPromptScene: 'Students hang paintings on easels to display their creative work.',
  },
  {
    word: 'likewise',
    partOfSpeech: 'adv.',
    meaningKo: '마찬가지로, 똑같이',
    ipa: '/ˈlaɪk.waɪz/',
    definition: 'in the same way or also in similar manner',
    sentence: 'She was polite to others, and they treated her likewise.',
    wordPromptScene: 'Two identical smiling cartoon sunflowers facing each other in garden.',
    sentPromptScene: 'A student waves goodbye and a classmate smiles and responds likewise.',
  },
  {
    word: 'discipline',
    partOfSpeech: 'n.',
    meaningKo: '규율, 훈육, 절제',
    ipa: '/ˈdɪs.ə.plɪn/',
    definition: 'the practice of training people to obey rules or self-control',
    sentence: 'Learning martial arts teaches students patience, respect, and self discipline.',
    wordPromptScene: 'A pair of clean white karate belts tied neatly in a knot.',
    sentPromptScene: 'Martial arts students bow respectfully, showing strong focus and self discipline.',
  },
  {
    word: 'boost',
    partOfSpeech: 'v.',
    meaningKo: '증대시키다, 북돋우다',
    ipa: '/buːst/',
    definition: 'to improve or increase something, giving more energy',
    sentence: 'Eating a fresh ripe apple will boost your afternoon energy.',
    wordPromptScene: 'A green upward rocket booster arrow with sparkling power stars.',
    sentPromptScene: 'A warm healthy fruit snack helps boost energy for soccer practice.',
  },
  {
    word: 'shallow',
    partOfSpeech: 'adj.',
    meaningKo: '얕은',
    ipa: '/ˈʃæl.oʊ/',
    definition: 'having only a short distance from the top to bottom',
    sentence: 'Children played safely in the shallow water of the pool.',
    wordPromptScene: 'A clear shallow stream with smooth pebbles visible at the bottom.',
    sentPromptScene: 'Little kids splash happily in the shallow end of the swimming pool.',
  },
  {
    word: 'swallow',
    partOfSpeech: 'v.',
    meaningKo: '삼키다, 제비',
    ipa: '/ˈswɑː.loʊ/',
    definition: 'to cause food or drink to pass down the throat',
    sentence: 'Drink warm water to swallow the small vitamin tablet easily.',
    wordPromptScene: 'A glass of clear water beside a tiny chewable fruit vitamin.',
    sentPromptScene: 'A child takes a sip of water to swallow medicine smoothly.',
  },
];

const day15_set4 = [
  {
    word: 'bias',
    partOfSpeech: 'n.',
    meaningKo: '편향, 선입견',
    ipa: '/ˈbaɪ.əs/',
    definition: 'an unfair preference for or dislike of something',
    sentence: 'A fair sports judge makes decisions without any personal bias.',
    wordPromptScene: 'A balance scale tipped slightly to one side being corrected evenly.',
    sentPromptScene: 'A judge listens carefully to all competitors to avoid any bias.',
  },
  {
    word: 'string',
    partOfSpeech: 'n.',
    meaningKo: '줄, 끈, 현',
    ipa: '/strɪŋ/',
    definition: 'a thin piece of twisted fiber used for tying things',
    sentence: 'He used strong yellow string to fly his colorful kite.',
    wordPromptScene: 'A spool of sturdy bright twine with a kite soaring above.',
    sentPromptScene: 'A boy holds a reel of string to guide his kite.',
  },
  {
    word: 'examination',
    partOfSpeech: 'n.',
    meaningKo: '시험, 검사',
    ipa: '/ɪɡˌzæm.əˈneɪ.ʃən/',
    definition: 'a formal test of a person’s knowledge or physical checkup',
    sentence: 'The doctor performed a thorough health examination for the student.',
    wordPromptScene: 'A medical eye chart and a stethoscope resting on a clean desk.',
    sentPromptScene: 'A student concentrates calmly during a final math examination in class.',
  },
  {
    word: 'rational',
    partOfSpeech: 'adj.',
    meaningKo: '합리적인, 이성적인',
    ipa: '/ˈræʃ.ən.əl/',
    definition: 'based on reason and clear facts rather than emotions',
    sentence: 'Making a rational budget helps you save pocket money wisely.',
    wordPromptScene: 'A balanced ledger book with neat numerical columns and a calculator.',
    sentPromptScene: 'Students hold a calm rational discussion to solve the club budget.',
  },
  {
    word: 'laboratory',
    partOfSpeech: 'n.',
    meaningKo: '실험실, 연구소',
    ipa: '/ˈlæb.rə.tɔːr.i/',
    definition: 'a room equipped for scientific experiments and research studies',
    sentence: 'Students put on safety coats inside the school chemistry laboratory.',
    wordPromptScene: 'A modern science lab bench with beakers, test tubes, and a microscope.',
    sentPromptScene: 'Young scientists test liquid samples inside a well-lit chemistry laboratory.',
  },
  {
    word: 'authority',
    partOfSpeech: 'n.',
    meaningKo: '권위, 당국, 권한',
    ipa: '/əˈθɔːr.ə.t̬i/',
    definition: 'the power or right to give orders and make decisions',
    sentence: 'The park authority maintains clean trails and protects wild animals.',
    wordPromptScene: 'A shiny brass park ranger badge with an official forest emblem.',
    sentPromptScene: 'A park ranger speaks with authority to guide tourists along trails.',
  },
  {
    word: 'misunderstanding',
    partOfSpeech: 'n.',
    meaningKo: '오해',
    ipa: '/ˌmɪs.ʌn.dɚˈstæn.dɪŋ/',
    definition: 'a failure to understand something correctly between people',
    sentence: 'A calm conversation cleared up the small misunderstanding between friends.',
    wordPromptScene: 'Two speech bubbles untangling from each other with smiling emoji faces.',
    sentPromptScene: 'Two smiling friends talk openly to resolve a minor misunderstanding.',
  },
  {
    word: 'pursue',
    partOfSpeech: 'v.',
    meaningKo: '추구하다, 쫓다',
    ipa: '/pɚˈsuː/',
    definition: 'to follow a goal or course of action to achieve it',
    sentence: 'She decided to pursue her dream of becoming a veterinarian.',
    wordPromptScene: 'A pathway leading up a mountain toward a shining dream star.',
    sentPromptScene: 'A young student studies hard to pursue a career in science.',
  },
  {
    word: 'deprived',
    partOfSpeech: 'adj.',
    meaningKo: '혜택받지 못한, 가난한',
    ipa: '/dɪˈpraɪvd/',
    definition: 'not having the things necessary for a pleasant life',
    sentence: 'Volunteers collected warm winter blankets for deprived animal rescue shelters.',
    wordPromptScene: 'A donation box overflowing with warm blankets and canned pet food.',
    sentPromptScene: 'Students pack supply boxes for children in deprived rural school communities.',
  },
  {
    word: 'spell',
    partOfSpeech: 'v.',
    meaningKo: '철자를 쓰다, 마법 주문',
    ipa: '/spel/',
    definition: 'to write or name the letters that form a word',
    sentence: 'Can you spell the word butterfly for our classroom game?',
    wordPromptScene: 'Wooden alphabet toy letter blocks spelling out the word PLAY.',
    sentPromptScene: 'A student steps up to spell a difficult word in spelling bee.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 15, set: 1, wordsData: day15_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 15, set: 2, wordsData: day15_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 15, set: 3, wordsData: day15_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 15, set: 4, wordsData: day15_set4 });
  console.log('DAY 15 written successfully');
}

run();
