import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 21
// ==========================================
const day21_set1 = [
  {
    word: 'wild',
    partOfSpeech: 'adj.',
    meaningKo: '야생의, 자연 그대로의',
    ipa: '/waɪld/',
    definition: 'living or growing in natural conditions without human care',
    sentence: 'Beautiful wild purple daisies grew all along the forest trail.',
    wordPromptScene: 'A field of blooming colorful wild flowers in a sunny alpine meadow.',
    sentPromptScene: 'Children admire wild deer grazing peacefully along the forest edge.',
  },
  {
    word: 'species',
    partOfSpeech: 'n.',
    meaningKo: '종, 생물종',
    ipa: '/ˈspiː.ʃiːz/',
    definition: 'a set of animals or plants with similar characteristics',
    sentence: 'The rainforest is home to thousands of rare butterfly species.',
    wordPromptScene: 'A collection of four diverse colorful tropical butterflies on display.',
    sentPromptScene: 'A biologist studies a rare plant species in the botanical garden.',
  },
  {
    word: 'bark',
    partOfSpeech: 'v.',
    meaningKo: '짖다, 나무껍질',
    ipa: '/bɑːrk/',
    definition: 'to make the characteristic loud sound of a dog',
    sentence: 'The friendly puppy began to bark happily at the bouncing ball.',
    wordPromptScene: 'A cute golden puppy wagging its tail and giving a cheerful bark.',
    sentPromptScene: 'A watchdog lets out a brief bark to greet its returning owner.',
  },
  {
    word: 'nest',
    partOfSpeech: 'n.',
    meaningKo: '둥지, 보금자리',
    ipa: '/nest/',
    definition: 'a structure built by birds to hold their eggs',
    sentence: 'A blue robin built a cozy twig nest in tree.',
    wordPromptScene: 'A neat bird nest made of twigs holding three speckled blue eggs.',
    sentPromptScene: 'Children watch a mother bird feeding tiny chicks in the nest.',
  },
  {
    word: 'certain',
    partOfSpeech: 'adj.',
    meaningKo: '확실한, 특정한',
    ipa: '/ˈsɝː.tən/',
    definition: 'completely sure of something, or particular',
    sentence: 'She was certain that her answer on the quiz was correct.',
    wordPromptScene: 'A green test worksheet showing a double star and verified checkmark.',
    sentPromptScene: 'A student feels certain and raises his hand to answer the question.',
  },
  {
    word: 'greet',
    partOfSpeech: 'v.',
    meaningKo: '맞이하다, 인사하다',
    ipa: '/ɡriːt/',
    definition: 'to welcome someone with friendly words or gestures',
    sentence: 'The friendly librarian will greet every student with a warm smile.',
    wordPromptScene: 'A smiling cartoon character waving both hands in a welcoming gesture.',
    sentPromptScene: 'Teachers greet arriving students at the front entrance of the school.',
  },
  {
    word: 'seed',
    partOfSpeech: 'n.',
    meaningKo: '씨앗, 종자',
    ipa: '/siːd/',
    definition: 'a small hard part produced by a plant to grow new plants',
    sentence: 'A tiny sunflower seed sprouted into a tall golden blossom.',
    wordPromptScene: 'A small brown plant seed sprouting a tiny green root into soil.',
    sentPromptScene: 'A young gardener places a pumpkin seed into rich potting soil.',
  },
  {
    word: 'predator',
    partOfSpeech: 'n.',
    meaningKo: '포식자, 육식 동물',
    ipa: '/ˈpred.ə.t̬ɚ/',
    definition: 'an animal that hunts and eats other animals for food',
    sentence: 'The sharp-eyed hawk is a skilled predator of open grasslands.',
    wordPromptScene: 'A majestic hawk soaring with wings spread wide across clear blue sky.',
    sentPromptScene: 'A wildlife ranger explains how an eagle acts as a natural predator.',
  },
  {
    word: 'scene',
    partOfSpeech: 'n.',
    meaningKo: '장면, 현장, 풍경',
    ipa: '/siːn/',
    definition: 'the place where an action happens, or a view in nature',
    sentence: 'The sunset over the lake was a peaceful and picturesque scene.',
    wordPromptScene: 'A beautiful watercolor landscape showing a calm lake and setting sun.',
    sentPromptScene: 'An artist paints a dramatic mountain landscape scene on canvas outdoors.',
  },
  {
    word: 'scent',
    partOfSpeech: 'n.',
    meaningKo: '향기, 냄새',
    ipa: '/sent/',
    definition: 'a pleasant, natural smell, especially from flowers',
    sentence: 'The sweet scent of blooming jasmine filled the warm evening air.',
    wordPromptScene: 'A sprig of fragrant purple lavender with gentle swirling aroma sparkles.',
    sentPromptScene: 'A girl closes her eyes to enjoy the fresh floral scent of roses.',
  },
];

const day21_set2 = [
  {
    word: 'shape',
    partOfSpeech: 'n.',
    meaningKo: '모양, 형태',
    ipa: '/ʃeɪp/',
    definition: 'the particular physical form or outline of something',
    sentence: 'Fluffy white clouds formed the shape of a leaping bunny.',
    wordPromptScene: 'A set of colorful 3D geometric shapes including sphere, star, and pyramid.',
    sentPromptScene: 'A child points out a cloud in the shape of a dolphin.',
  },
  {
    word: 'fierce',
    partOfSpeech: 'adj.',
    meaningKo: '사나운, 맹렬한',
    ipa: '/fɪrs/',
    definition: 'having or showing a powerful and aggressive intensity in weather',
    sentence: 'The fierce winter blizzard piled deep snowdrifts against the cabin.',
    wordPromptScene: 'A cartoon blizzard wind gust swirling with playful icy blue snowflakes.',
    sentPromptScene: 'Hikers stay safe inside a warm lodge during a fierce storm.',
  },
  {
    word: 'ripe',
    partOfSpeech: 'adj.',
    meaningKo: '익은, 숙성한',
    ipa: '/raɪp/',
    definition: 'ready to be harvested and eaten, fully developed',
    sentence: 'We picked sweet and ripe red strawberries in the garden.',
    wordPromptScene: 'A basket filled with glowing ruby-red ripe strawberries with green stems.',
    sentPromptScene: 'A boy picks a ripe golden peach from a sunny fruit tree.',
  },
  {
    word: 'lay',
    partOfSpeech: 'v.',
    meaningKo: '알을 낳다, 놓다',
    ipa: '/leɪ/',
    definition: 'to produce an egg from the body, or place down',
    sentence: 'The mother hen will lay brown eggs in her straw nest.',
    wordPromptScene: 'A speckled hen sitting comfortably on golden straw in a wooden coop.',
    sentPromptScene: 'A child gathers fresh eggs that the hens lay each morning.',
  },
  {
    word: 'male',
    partOfSpeech: 'adj.',
    meaningKo: '수컷의, 남성의',
    ipa: '/meɪl/',
    definition: 'belonging to the sex that produces sperm, not female',
    sentence: 'The male peacock displayed its magnificent emerald and blue tail feathers.',
    wordPromptScene: 'A magnificent male peacock fanning out its vibrant iridescent tail feathers.',
    sentPromptScene: 'Visitors admire the colorful plumage of a male mandarin duck in pond.',
  },
  {
    word: 'foster',
    partOfSpeech: 'v.',
    meaningKo: '육성하다, 기르다',
    ipa: '/ˈfɑː.stɚ/',
    definition: 'to encourage the development of something, or care for young',
    sentence: 'Reading books helps foster creativity and deep imagination in children.',
    wordPromptScene: 'Two cartoon hands gently nurturing a small green sprout with sunshine.',
    sentPromptScene: 'Teachers design group activities to foster cooperation among all classmates.',
  },
  {
    word: 'surface',
    partOfSpeech: 'n.',
    meaningKo: '표면, 겉면',
    ipa: '/ˈsɝː.fɪs/',
    definition: 'the outer or top layer of something',
    sentence: 'Water drops rolled smoothly across the shiny leaf surface.',
    wordPromptScene: 'Crystal clear water droplets beading on a waxy green lotus leaf surface.',
    sentPromptScene: 'A skater glides smoothly across the polished ice surface of rink.',
  },
  {
    word: 'engage',
    partOfSpeech: 'v.',
    meaningKo: '참여하다, 사로잡다',
    ipa: '/ɪnˈɡeɪdʒ/',
    definition: 'to participate or become involved in an activity actively',
    sentence: 'Students love to engage in lively science discussions after experiments.',
    wordPromptScene: 'A group of diverse cartoon students raising hands and discussing ideas excitedly.',
    sentPromptScene: 'Children engage enthusiastically in a creative storytelling circle in class.',
  },
  {
    word: 'location',
    partOfSpeech: 'n.',
    meaningKo: '장소, 위치',
    ipa: '/loʊˈkeɪ.ʃən/',
    definition: 'a particular place or position where something is situated',
    sentence: 'The botanical garden is an ideal location for our nature walk.',
    wordPromptScene: 'A bright red map location pin marking a green park on map.',
    sentPromptScene: 'Hikers check their map to verify the exact location of campsite.',
  },
  {
    word: 'store',
    partOfSpeech: 'v.',
    meaningKo: '저장하다, 보관하다',
    ipa: '/stɔːr/',
    definition: 'to keep or put something away for future use',
    sentence: 'Squirrels collect and store crunchy acorns for the cold winter.',
    wordPromptScene: 'A cartoon squirrel placing acorns into a hollow tree trunk storage pantry.',
    sentPromptScene: 'A farmer stacks crates in a cool cellar to store apples.',
  },
];

const day21_set3 = [
  {
    word: 'attract',
    partOfSpeech: 'v.',
    meaningKo: '끌어당기다, 유인하다',
    ipa: '/əˈtrækt/',
    definition: 'to pull something toward itself by natural physical force',
    sentence: 'Bright sweet flowers attract buzzing honeybees and colorful butterflies.',
    wordPromptScene: 'A red horseshoe magnet pulling sparkling metal paperclips towards its poles.',
    sentPromptScene: 'Sunflowers in the garden attract colorful butterflies with their bright yellow petals.',
  },
  {
    word: 'poison',
    partOfSpeech: 'n.',
    meaningKo: '독, 독극물',
    ipa: '/ˈpɔɪ.zən/',
    definition: 'a substance that can cause illness if swallowed or absorbed',
    sentence: 'Some wild red berries contain natural poison to protect themselves.',
    wordPromptScene: 'A decorative cartoon potion flask labeled Danger with bright yellow warning.',
    sentPromptScene: 'A guide warns hikers that certain wild mushrooms contain dangerous natural poison.',
  },
  {
    word: 'weigh',
    partOfSpeech: 'v.',
    meaningKo: '무게를 달다, 무게가 나가다',
    ipa: '/weɪ/',
    definition: 'to measure how heavy someone or something is',
    sentence: 'The baker used a kitchen scale to weigh the flour.',
    wordPromptScene: 'A vintage metal balance scale with brass weights and a red apple.',
    sentPromptScene: 'A student uses a balance scale to weigh minerals in science.',
  },
  {
    word: 'automatic',
    partOfSpeech: 'adj.',
    meaningKo: '자동의',
    ipa: '/ˌɑː.t̬əˈmæt̬.ɪk/',
    definition: 'working by itself with little or no direct human control',
    sentence: 'The greenhouse has an automatic watering system for potted flowers.',
    wordPromptScene: 'A robotic garden sprinkler automatically spraying a fine mist over plants.',
    sentPromptScene: 'Automatic sliding glass doors open smoothly as shoppers enter the supermarket.',
  },
  {
    word: 'role',
    partOfSpeech: 'n.',
    meaningKo: '역할, 배역',
    ipa: '/roʊl/',
    definition: 'the position, purpose, or part played by someone or something',
    sentence: 'Every team member has an important role in our project.',
    wordPromptScene: 'A golden puzzle piece completing the center of a collaborative team puzzle.',
    sentPromptScene: 'A student plays the lead detective role in the school play.',
  },
  {
    word: 'exchange',
    partOfSpeech: 'v.',
    meaningKo: '교환하다, 주고받다',
    ipa: '/ɪksˈtʃeɪndʒ/',
    definition: 'to give something and receive something of equal value back',
    sentence: 'Students love to exchange colorful friendship cards during holiday celebrations.',
    wordPromptScene: 'Two cartoon hands exchanging wrapped gifts with golden sparkle trails.',
    sentPromptScene: 'Pen pals exchange handwritten letters and foreign stamps through the post.',
  },
  {
    word: 'contain',
    partOfSpeech: 'v.',
    meaningKo: '포함하다, 담고 있다',
    ipa: '/kənˈteɪn/',
    definition: 'to have something inside or include something as a part',
    sentence: 'These fresh oranges contain plenty of healthy natural vitamin C.',
    wordPromptScene: 'A clear glass jar filled to the brim with colorful marbles.',
    sentPromptScene: 'A lunchbox is packed to contain fruit, a sandwich, and juice.',
  },
  {
    word: 'trail',
    partOfSpeech: 'n.',
    meaningKo: '오솔길, 자국',
    ipa: '/treɪl/',
    definition: 'a path through the countryside, mountain, or forest',
    sentence: 'We followed a gentle wooden trail through the pine forest.',
    wordPromptScene: 'A winding dirt trail lined with green moss and tall pine trees.',
    sentPromptScene: 'Hikers walk single file along a scenic mountain nature trail.',
  },
  {
    word: 'trait',
    partOfSpeech: 'n.',
    meaningKo: '특성, 특색',
    ipa: '/treɪt/',
    definition: 'a particular characteristic or quality that someone has',
    sentence: 'Curiosity is a wonderful personality trait of young scientists.',
    wordPromptScene: 'A glowing lightbulb surrounded by icons of courage, kindness, and curiosity.',
    sentPromptScene: 'A biology teacher explains how eye color is an inherited genetic trait.',
  },
  {
    word: 'trial',
    partOfSpeech: 'n.',
    meaningKo: '시험, 시도, 재판',
    ipa: '/traɪəl/',
    definition: 'a test of the performance, qualities, or suitability of something',
    sentence: 'The engineers ran a successful speed trial for the car.',
    wordPromptScene: 'A miniature solar car racing down a marked laboratory test track.',
    sentPromptScene: 'Students record stopwatch times during the first trial of their model glider.',
  },
];

const day21_set4 = [
  {
    word: 'overcome',
    partOfSpeech: 'v.',
    meaningKo: '극복하다, 이겨내다',
    ipa: '/ˌoʊ.vɚˈkʌm/',
    definition: 'to successfully deal with and control a difficult problem',
    sentence: 'With daily practice, you can overcome your fear of heights.',
    wordPromptScene: 'A cartoon character standing victoriously at the top of a stone peak.',
    sentPromptScene: 'A young swimmer smiles after working hard to overcome fear of diving.',
  },
  {
    word: 'tiny',
    partOfSpeech: 'adj.',
    meaningKo: '아주 작은, 조그마한',
    ipa: '/ˈtaɪ.ni/',
    definition: 'extremely small in size, amount, or degree',
    sentence: 'A tiny green hummingbird hovered gently beside the red flower.',
    wordPromptScene: 'A miniature green hummingbird drinking nectar from a tiny floral blossom.',
    sentPromptScene: 'A student uses a magnifying glass to observe a tiny ant.',
  },
  {
    word: 'exceed',
    partOfSpeech: 'v.',
    meaningKo: '넘다, 초과하다',
    ipa: '/ɪkˈsiːd/',
    definition: 'to be greater than a number, amount, or allowed limit',
    sentence: 'Do not exceed the safe weight limit on the bridge.',
    wordPromptScene: 'A gauge needle staying safely within the green zone below limit mark.',
    sentPromptScene: 'Athletes train hard so their sprint performance will exceed expectations.',
  },
  {
    word: 'bury',
    partOfSpeech: 'v.',
    meaningKo: '묻다, 매장하다',
    ipa: '/ˈber.i/',
    definition: 'to put something into a hole in the ground and cover',
    sentence: 'Pirate legends say sailors would bury golden treasure on islands.',
    wordPromptScene: 'A wooden treasure chest half-buried in soft white island beach sand.',
    sentPromptScene: 'Children plant sunflower seeds and bury them gently with rich soil.',
  },
  {
    word: 'stem',
    partOfSpeech: 'n.',
    meaningKo: '줄기, 대',
    ipa: '/stem/',
    definition: 'the main long thin part of a plant supporting leaves',
    sentence: 'A strong green stem supports the heavy sunflower blossom upright.',
    wordPromptScene: 'A tall green plant stem with healthy green leaves reaching toward sunlight.',
    sentPromptScene: 'A student points to the sturdy stem of a potted rose.',
  },
  {
    word: 'diameter',
    partOfSpeech: 'n.',
    meaningKo: '지름, 직경',
    ipa: '/daɪˈæm.ə.t̬ɚ/',
    definition: 'a straight line passing from side to side through circle center',
    sentence: 'We measured the diameter of the giant tree trunk circle.',
    wordPromptScene: 'A wooden ruler measuring a circular tree ring cross-section across center.',
    sentPromptScene: 'Students use measuring tape to calculate the diameter of a large pumpkin.',
  },
  {
    word: 'fascinate',
    partOfSpeech: 'v.',
    meaningKo: '매료시키다, 마음을 사로잡다',
    ipa: '/ˈfæs.ən.eɪt/',
    definition: 'to attract and hold the interest and attention of someone completely',
    sentence: 'Stories of space exploration always fascinate curious young minds.',
    wordPromptScene: 'A glowing 3D hologram of swirling galaxies captivating two cartoon viewers.',
    sentPromptScene: 'Glowing deep-sea jellyfish fascinate visitors standing in front of aquarium tank.',
  },
  {
    word: 'furthermore',
    partOfSpeech: 'adv.',
    meaningKo: '더욱이, 게다가',
    ipa: '/ˈfɝː.ðɚ.mɔːr/',
    definition: 'in addition to what has been said, also',
    sentence: 'The park is clean and, furthermore, it has great trails.',
    wordPromptScene: 'A plus sign connecting a sunny park bench to blooming flowers.',
    sentPromptScene: 'A speaker explains that recycling saves energy and, furthermore, protects nature.',
  },
  {
    word: 'concentrate',
    partOfSpeech: 'v.',
    meaningKo: '집중하다, 전념하다',
    ipa: '/ˈkɑːn.sən.treɪt/',
    definition: 'to direct all your mental effort or attention toward something',
    sentence: 'Turn off noisy distractions so you can concentrate on your reading.',
    wordPromptScene: 'A glowing magnifying glass focusing warm light onto a single center point.',
    sentPromptScene: 'A student sits in a quiet corner to concentrate on homework.',
  },
  {
    word: 'general',
    partOfSpeech: 'adj.',
    meaningKo: '일반적인, 전반적인',
    ipa: '/ˈdʒen.ər.əl/',
    definition: 'affecting or concerning all or most people or things',
    sentence: 'The teacher gave a general overview of the science curriculum.',
    wordPromptScene: 'A high panoramic view of a sunny green valley showing overall landscape.',
    sentPromptScene: 'A tour guide gives a general introduction before leading visitors through museum.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 21, set: 1, wordsData: day21_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 21, set: 2, wordsData: day21_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 21, set: 3, wordsData: day21_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 21, set: 4, wordsData: day21_set4 });
  console.log('DAY 21 written successfully');
}

run();
