import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 13
// ==========================================
const day13_set1 = [
  {
    word: 'represent',
    partOfSpeech: 'v.',
    meaningKo: '대표하다, 나타내다',
    ipa: '/ˌrep.rɪˈzent/',
    definition: 'to speak or act on behalf of a group',
    sentence: 'The student council leader will represent our school at festival.',
    wordPromptScene: 'A student holding a school banner proudly in an auditorium.',
    sentPromptScene: 'A team captain steps up to represent fellow athletes on stage.',
  },
  {
    word: 'exhibit',
    partOfSpeech: 'n.',
    meaningKo: '전시, 전시품',
    ipa: '/ɪɡˈzɪb.ɪt/',
    definition: 'an object or collection of objects shown in a museum',
    sentence: 'We visited the fascinating dinosaur fossil exhibit at the museum.',
    wordPromptScene: 'A museum gallery display case showing ancient sparkling mineral rocks.',
    sentPromptScene: 'Students walk through an interactive science museum exhibit about sound.',
  },
  {
    word: 'minister',
    partOfSpeech: 'n.',
    meaningKo: '장관, 성직자',
    ipa: '/ˈmɪn.ə.stɚ/',
    definition: 'a member of government in charge of a department',
    sentence: 'The education minister visited the new school library opening today.',
    wordPromptScene: 'A distinguished government building with stately pillars and national flags.',
    sentPromptScene: 'The minister delivers an inspiring speech at the school ribbon ceremony.',
  },
  {
    word: 'vary',
    partOfSpeech: 'v.',
    meaningKo: '다양하다, 다르다',
    ipa: '/ˈver.i/',
    definition: 'to be different in size, amount, or character',
    sentence: 'The colors of autumn leaves vary from bright yellow to red.',
    wordPromptScene: 'A rainbow spectrum of maple leaves ranging from gold to crimson.',
    sentPromptScene: 'The sizes of sea shells vary widely along the sandy beach.',
  },
  {
    word: 'tribe',
    partOfSpeech: 'n.',
    meaningKo: '부족, 종족',
    ipa: '/traɪb/',
    definition: 'a group of people of the same race with common customs',
    sentence: 'The ancient mountain tribe celebrated the harvest with lively dances.',
    wordPromptScene: 'Traditional patterned woven banners and wooden drums around a fire.',
    sentPromptScene: 'Children learn about the rich history of a traditional mountain tribe.',
  },
  {
    word: 'community',
    partOfSpeech: 'n.',
    meaningKo: '지역사회, 공동체',
    ipa: '/kəˈmjuː.nə.t̬i/',
    definition: 'the people living in one particular area or sharing interests',
    sentence: 'Neighbors in our local community organized a peaceful park cleanup.',
    wordPromptScene: 'A colorful welcoming town center with green trees and small shops.',
    sentPromptScene: 'Volunteers from the local community plant flowers in the central square.',
  },
  {
    word: 'consider',
    partOfSpeech: 'v.',
    meaningKo: '고려하다, 숙고하다',
    ipa: '/kənˈsɪd.ɚ/',
    definition: 'to spend time thinking about something carefully before deciding',
    sentence: 'Take time to consider all your options before choosing.',
    wordPromptScene: 'A cartoon character resting chin on hand looking at two path signs.',
    sentPromptScene: 'A student takes a moment to consider which science topic to research.',
  },
  {
    word: 'concept',
    partOfSpeech: 'n.',
    meaningKo: '개념, 생각',
    ipa: '/ˈkɑːn.sept/',
    definition: 'a principle or idea that is developed in the mind',
    sentence: 'Gravity is a fundamental science concept explained by Isaac Newton.',
    wordPromptScene: 'A glowing lightbulb surrounded by orbiting atomic rings and stars.',
    sentPromptScene: 'A science teacher uses wooden models to explain the concept of orbits.',
  },
  {
    word: 'pray',
    partOfSpeech: 'v.',
    meaningKo: '기도하다, 간청하다',
    ipa: '/preɪ/',
    definition: 'to speak to God or express a sincere hope',
    sentence: 'Villagers gather at sunset to pray for a good harvest.',
    wordPromptScene: 'Two gentle cartoon hands folded peacefully in quiet reflection.',
    sentPromptScene: 'People bow their heads peacefully to pray inside a sunlit chapel.',
  },
  {
    word: 'prey',
    partOfSpeech: 'n.',
    meaningKo: '먹이, 사냥감',
    ipa: '/preɪ/',
    definition: 'an animal that is hunted and killed for food',
    sentence: 'The swift eagle spotted its prey from high in sky.',
    wordPromptScene: 'A soaring eagle circling high above green pine forest hills.',
    sentPromptScene: 'A cartoon owl scans the meadow grass to look for prey.',
  },
];

const day13_set2 = [
  {
    word: 'myth',
    partOfSpeech: 'n.',
    meaningKo: '신화, 근거 없는 믿음',
    ipa: '/mɪθ/',
    definition: 'an ancient story explaining natural events using gods or heroes',
    sentence: 'We read a fascinating Greek myth about the winged horse.',
    wordPromptScene: 'A glowing winged horse Pegasus flying among golden clouds.',
    sentPromptScene: 'A teacher reads an exciting Greek myth about ancient brave heroes.',
  },
  {
    word: 'attitude',
    partOfSpeech: 'n.',
    meaningKo: '태도, 자세',
    ipa: '/ˈæt̬.ə.tuːd/',
    definition: 'a feeling or opinion about something, or how you behave',
    sentence: 'A positive attitude helps you overcome difficult challenges in school.',
    wordPromptScene: 'A cheerful cartoon smiling face wearing a bright thumbs-up badge.',
    sentPromptScene: 'A runner shows a determined attitude before the long track race.',
  },
  {
    word: 'priest',
    partOfSpeech: 'n.',
    meaningKo: '사제, 성직자',
    ipa: '/priːst/',
    definition: 'a person who performs religious ceremonies in a church',
    sentence: 'The kind priest welcomed visitors to the quiet stone cathedral.',
    wordPromptScene: 'A gentle figure in traditional robes standing in a sunlit cathedral doorway.',
    sentPromptScene: 'Visitors listen respectfully as the priest explains the cathedral’s history.',
  },
  {
    word: 'approve',
    partOfSpeech: 'v.',
    meaningKo: '승인하다, 찬성하다',
    ipa: '/əˈpruːv/',
    definition: 'to officially accept or have a positive opinion of something',
    sentence: 'The principal will approve our plan for the school garden.',
    wordPromptScene: 'A document stamped with a bold green Approved seal badge.',
    sentPromptScene: 'Teachers smile and officially approve the students’ charity bake sale proposal.',
  },
  {
    word: 'carve',
    partOfSpeech: 'v.',
    meaningKo: '조각하다, 새기다',
    ipa: '/kɑːrv/',
    definition: 'to make an object by cutting away stone or wood',
    sentence: 'Artists use sharp wooden chisels to carve intricate decorative statues.',
    wordPromptScene: 'A wooden sculpture of an eagle being carved with sharp chisels.',
    sentPromptScene: 'A craftsman uses wooden tools to carve a small wooden duck.',
  },
  {
    word: 'primitive',
    partOfSpeech: 'adj.',
    meaningKo: '원시의, 초기의',
    ipa: '/ˈprɪm.ə.t̬ɪv/',
    definition: 'relating to human society at a very early stage',
    sentence: 'Early humans created primitive stone tools for daily survival tasks.',
    wordPromptScene: 'A display of ancient chipped flint arrowheads and stone axes.',
    sentPromptScene: 'Museum visitors examine primitive stone tools crafted by ancient early humans.',
  },
  {
    word: 'invade',
    partOfSpeech: 'v.',
    meaningKo: '침입하다, 몰려들다',
    ipa: '/ɪnˈveɪd/',
    definition: 'to enter a place in large numbers or by force',
    sentence: 'Hungry sea gulls invade the sandy picnic area for breadcrumbs.',
    wordPromptScene: 'A group of friendly cartoon seagulls gathering around a park bench.',
    sentPromptScene: 'Flocks of sparrows fly down to invade the garden bird feeder.',
  },
  {
    word: 'arise',
    partOfSpeech: 'v.',
    meaningKo: '발생하다, 생기다',
    ipa: '/əˈraɪz/',
    definition: 'to happen or start to exist unexpectedly',
    sentence: 'New unexpected questions may arise during the science experiment today.',
    wordPromptScene: 'A golden sun rising gently above morning mist on a lake.',
    sentPromptScene: 'The team meets calmly whenever unexpected challenges arise in their project.',
  },
  {
    word: 'register',
    partOfSpeech: 'v.',
    meaningKo: '등록하다, 기록하다',
    ipa: '/ˈredʒ.ə.stɚ/',
    definition: 'to record your name on an official list',
    sentence: 'Students must register online before joining the after-school art club.',
    wordPromptScene: 'A neat registration form with a pen and a Member Card.',
    sentPromptScene: 'A student fills out a paper slip to register for sports.',
  },
  {
    word: 'custom',
    partOfSpeech: 'n.',
    meaningKo: '관습, 풍습',
    ipa: '/ˈkʌs.təm/',
    definition: 'an accepted way of behaving or doing things in society',
    sentence: 'Bowing politely is a traditional respectful custom in many cultures.',
    wordPromptScene: 'Two friendly cartoon characters bowing respectfully with warm smiles.',
    sentPromptScene: 'A family observes a traditional holiday custom by sharing sweet rice cakes.',
  },
];

const day13_set3 = [
  {
    word: 'punish',
    partOfSpeech: 'v.',
    meaningKo: '처벌하다, 벌주다',
    ipa: '/ˈpʌn.ɪʃ/',
    definition: 'to make someone suffer for doing something wrong by rules',
    sentence: 'Board game rules will punish players who skip their turn.',
    wordPromptScene: 'A referee holding up a yellow card on a game board.',
    sentPromptScene: 'In the board game, rules punish a player by losing one turn.',
  },
  {
    word: 'tie',
    partOfSpeech: 'v.',
    meaningKo: '묶다, 동점을 이루다',
    ipa: '/taɪ/',
    definition: 'to fasten something with string or rope securely',
    sentence: 'Remember to tie your running shoelaces tightly before the race.',
    wordPromptScene: 'A pair of colorful sneakers with neatly tied shoelace bows.',
    sentPromptScene: 'A young runner bends down to tie shoelaces securely on track.',
  },
  {
    word: 'indicate',
    partOfSpeech: 'v.',
    meaningKo: '나타내다, 가리키다',
    ipa: '/ˈɪn.də.keɪt/',
    definition: 'to show, point, or make something clear',
    sentence: 'Flashing arrow signs indicate the correct exit direction along highway.',
    wordPromptScene: 'A bright green illuminated arrow sign pointing clearly to the right.',
    sentPromptScene: 'A museum guide uses a pointer to indicate landmarks on a map.',
  },
  {
    word: 'humor',
    partOfSpeech: 'n.',
    meaningKo: '유머, 해학',
    ipa: '/ˈhjuː.mɚ/',
    definition: 'the ability to find things funny or be amusing',
    sentence: 'The comedian’s gentle humor made the whole theater laugh happily.',
    wordPromptScene: 'Two smiling cartoon masks, comedy and drama, glowing with cheer.',
    sentPromptScene: 'A teacher tells a joke with witty humor that delights the class.',
  },
  {
    word: 'stack',
    partOfSpeech: 'n.',
    meaningKo: '더미, 쌓아 올린 것',
    ipa: '/stæk/',
    definition: 'a neat pile of things arranged one on top of another',
    sentence: 'He placed a heavy stack of storybooks onto the wooden table.',
    wordPromptScene: 'A neat vertical pile of ten colorful hardcover books on desk.',
    sentPromptScene: 'A student carefully carries a tall stack of library books.',
  },
  {
    word: 'odd',
    partOfSpeech: 'adj.',
    meaningKo: '이상한, 홀수의',
    ipa: '/ɑːd/',
    definition: 'strange or unusual, or not divisible by two',
    sentence: 'The old clock made an odd ticking sound at midnight.',
    wordPromptScene: 'A whimsical grandfather clock with colorful twisted spiral hands.',
    sentPromptScene: 'A detective investigates an odd glowing key found in garden soil.',
  },
  {
    word: 'persist',
    partOfSpeech: 'v.',
    meaningKo: '지속하다, 끈질기게 계속하다',
    ipa: '/pɚˈsɪst/',
    definition: 'to continue doing something firmly despite difficulties',
    sentence: 'If you persist with daily practice, you will surely succeed.',
    wordPromptScene: 'A tiny green plant growing determinedly through a crack in stone.',
    sentPromptScene: 'A dedicated student will persist until solving the tricky math riddle.',
  },
  {
    word: 'insight',
    partOfSpeech: 'n.',
    meaningKo: '통찰력, 이해',
    ipa: '/ˈɪn.saɪt/',
    definition: 'a clear, deep understanding of a complicated problem or situation',
    sentence: 'The documentary gave us valuable insight into deep ocean life.',
    wordPromptScene: 'A glowing lightbulb illuminating the inner workings of a complex gear mechanism.',
    sentPromptScene: 'A scientist shares deep insight into how honeybees communicate with dances.',
  },
  {
    word: 'novel',
    partOfSpeech: 'n.',
    meaningKo: '소설',
    ipa: '/ˈnɑː.vəl/',
    definition: 'a long printed story about imaginary characters and events',
    sentence: 'She read a thrilling fantasy novel about enchanted forest creatures.',
    wordPromptScene: 'A thick hardcover book with an illustrated dragon on the cover.',
    sentPromptScene: 'A girl reads an exciting adventure novel in a sunny hammock.',
  },
  {
    word: 'noble',
    partOfSpeech: 'adj.',
    meaningKo: '고결한, 귀족의',
    ipa: '/ˈnoʊ.bəl/',
    definition: 'having high moral qualities like courage, honesty, and honor',
    sentence: 'Saving the lost puppy was a truly noble and kind deed.',
    wordPromptScene: 'A proud white stallion with a golden mane standing on a crest.',
    sentPromptScene: 'A storybook tells the tale of a noble knight defending the village.',
  },
];

const day13_set4 = [
  {
    word: 'outstanding',
    partOfSpeech: 'adj.',
    meaningKo: '뛰어난, 두드러진',
    ipa: '/ˌaʊtˈstæn.dɪŋ/',
    definition: 'clearly very much better than what is usual or normal',
    sentence: 'She received an outstanding award for her brilliant science project.',
    wordPromptScene: 'A gold trophy cup standing on a high pedestal above silver stars.',
    sentPromptScene: 'A student receives an outstanding achievement certificate at the school assembly.',
  },
  {
    word: 'resist',
    partOfSpeech: 'v.',
    meaningKo: '저항하다, 참다',
    ipa: '/rɪˈzɪst/',
    definition: 'to stop yourself from having or doing something you want',
    sentence: 'It was hard to resist the smell of warm cookies.',
    wordPromptScene: 'A warm freshly baked chocolate chip cookie releasing delicious sweet aroma.',
    sentPromptScene: 'A boy tries to resist eating frosting before the cake is ready.',
  },
  {
    word: 'hesitate',
    partOfSpeech: 'v.',
    meaningKo: '망설이다, 주저하다',
    ipa: '/ˈhez.ə.teɪt/',
    definition: 'to pause before saying or doing something because of uncertainty',
    sentence: 'Do not hesitate to ask questions if you need help.',
    wordPromptScene: 'A cartoon character pausing at a diving board looking at water.',
    sentPromptScene: 'A student does not hesitate and raises his hand in class.',
  },
  {
    word: 'protest',
    partOfSpeech: 'v.',
    meaningKo: '항의하다, 이의를 제기하다',
    ipa: '/prəˈtest/',
    definition: 'to express strong disagreement or disapproval publicly',
    sentence: 'Students gathered to protest against cutting down the ancient park trees.',
    wordPromptScene: 'Peaceful colorful signboards reading Save Our Trees with leaf emblems.',
    sentPromptScene: 'Children hold signs to protest and protect a local green forest.',
  },
  {
    word: 'restore',
    partOfSpeech: 'v.',
    meaningKo: '복원하다, 회복시키다',
    ipa: '/rɪˈstɔːr/',
    definition: 'to return something to its original good condition',
    sentence: 'Craftsmen worked for months to restore the ancient wooden temple.',
    wordPromptScene: 'A delicate antique painting being carefully cleaned with fine artist brushes.',
    sentPromptScene: 'Volunteers plant native shrubs to restore the damaged wetland nature park.',
  },
  {
    word: 'associate',
    partOfSpeech: 'v.',
    meaningKo: '연관 짓다, 결부시키다',
    ipa: '/əˈsoʊ.si.eɪt/',
    definition: 'to connect someone or something in your mind with another',
    sentence: 'People often associate bright sunny yellow with joy and energy.',
    wordPromptScene: 'Two glowing interconnected puzzle rings labeled Sunshine and Happiness.',
    sentPromptScene: 'Students associate snowflakes and hot cocoa with cozy winter holidays.',
  },
  {
    word: 'heritage',
    partOfSpeech: 'n.',
    meaningKo: '유산, 전통',
    ipa: '/ˈher.ə.t̬ɪdʒ/',
    definition: 'features belonging to the culture of a society from the past',
    sentence: 'The ancient stone castle is a protected national cultural heritage.',
    wordPromptScene: 'A majestic ancient stone castle tower with historic heraldic banners.',
    sentPromptScene: 'Students visit a folk village to learn about traditional cultural heritage.',
  },
  {
    word: 'restriction',
    partOfSpeech: 'n.',
    meaningKo: '제한, 규제',
    ipa: '/rɪˈstrɪk.ʃən/',
    definition: 'an official limit on what you can do or have',
    sentence: 'There is a strict speed restriction in all school zones.',
    wordPromptScene: 'A road sign showing a clear speed limit number inside a red circle.',
    sentPromptScene: 'A sign shows the height restriction for riding the amusement park ride.',
  },
  {
    word: 'perceive',
    partOfSpeech: 'v.',
    meaningKo: '인지하다, 감지하다',
    ipa: '/pɚˈsiːv/',
    definition: 'to notice or become aware of something using your senses',
    sentence: 'Dogs can easily perceive high sounds that humans cannot hear.',
    wordPromptScene: 'A cute cartoon dog perking up its ears at sound wave ripples.',
    sentPromptScene: 'An artist helps students perceive delicate shade differences in watercolor paints.',
  },
  {
    word: 'scale',
    partOfSpeech: 'n.',
    meaningKo: '규모, 저울, 비늘',
    ipa: '/skeɪl/',
    definition: 'the size or level of something, or a weighing device',
    sentence: 'The scientist measured the mineral weight on a precise digital scale.',
    wordPromptScene: 'A modern digital balance scale with glowing numbers and a specimen.',
    sentPromptScene: 'A scientist places a rock on a digital scale in the lab.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 13, set: 1, wordsData: day13_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 13, set: 2, wordsData: day13_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 13, set: 3, wordsData: day13_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 13, set: 4, wordsData: day13_set4 });
  console.log('DAY 13 written successfully');
}

run();
