import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 20
// ==========================================
const day20_set1 = [
  {
    word: 'traffic',
    partOfSpeech: 'n.',
    meaningKo: '교통, 교통량',
    ipa: '/ˈtræf.ɪk/',
    definition: 'all the vehicles moving along roads, streets, or tracks',
    sentence: 'The crossing guard ensured safe pedestrian traffic near the school.',
    wordPromptScene: 'A cheerful cartoon crossing guard holding a bright red Stop sign.',
    sentPromptScene: 'Children cross the street safely as cars stop for traffic signal.',
  },
  {
    word: 'major',
    partOfSpeech: 'adj.',
    meaningKo: '주요한, 중대한',
    ipa: '/ˈmeɪ.dʒɚ/',
    definition: 'more important, bigger, or more serious than others',
    sentence: 'The highway is a major transportation route connecting two cities.',
    wordPromptScene: 'A grand multi-lane suspension bridge glowing in golden sunset light.',
    sentPromptScene: 'City planners review a map showing major bus lines in the region.',
  },
  {
    word: 'route',
    partOfSpeech: 'n.',
    meaningKo: '경로, 노선',
    ipa: '/ruːt/',
    definition: 'a particular way or path taken to get from place to place',
    sentence: 'Hikers followed a scenic mountain route marked with yellow flags.',
    wordPromptScene: 'A rolled-out topographic trail map with a highlighted dotted green path.',
    sentPromptScene: 'A scout leader points at the planned hiking route on paper.',
  },
  {
    word: 'rush',
    partOfSpeech: 'v.',
    meaningKo: '서두르다, 급히 가다',
    ipa: '/rʌʃ/',
    definition: 'to move or do something with great speed and urgency',
    sentence: 'Take your time and do not rush through your homework.',
    wordPromptScene: 'A classic cartoon stopwatch with wind speed lines showing fast pace.',
    sentPromptScene: 'Students walk calmly down the hallway so they do not rush dangerously.',
  },
  {
    word: 'vehicle',
    partOfSpeech: 'n.',
    meaningKo: '차량, 탈것',
    ipa: '/ˈviː.ə.kəl/',
    definition: 'a machine with wheels used for transporting people or goods',
    sentence: 'The electric delivery van is an eco-friendly vehicle in town.',
    wordPromptScene: 'A friendly bright yellow electric van plugged into a green charging station.',
    sentPromptScene: 'An engineer tests a solar-powered exploration vehicle on rough test terrain.',
  },
  {
    word: 'transport',
    partOfSpeech: 'v.',
    meaningKo: '수송하다, 나르다',
    ipa: '/trænˈspɔːrt/',
    definition: 'to carry people or goods from one place to another',
    sentence: 'Cargo trains transport fresh apples from orchards to city markets.',
    wordPromptScene: 'A modern streamlined freight train carrying colorful shipping containers.',
    sentPromptScene: 'Workers load wooden fruit crates onto trucks to transport them safely.',
  },
  {
    word: 'utilize',
    partOfSpeech: 'v.',
    meaningKo: '활용하다, 이용하다',
    ipa: '/ˈjuː.t̬əl.aɪz/',
    definition: 'to use something in an effective or practical way',
    sentence: 'Students utilize digital library tablets to research science project topics.',
    wordPromptScene: 'A toolkit containing a ruler, compass, wrench, and glowing lightbulb.',
    sentPromptScene: 'Young scientists utilize solar panels to power a small water pump.',
  },
  {
    word: 'remote',
    partOfSpeech: 'adj.',
    meaningKo: '외딴, 원격의',
    ipa: '/rɪˈmoʊt/',
    definition: 'far away in distance or time from where other people live',
    sentence: 'Astronomers built an observatory on a remote mountain summit away from lights.',
    wordPromptScene: 'A gleaming white astronomical dome sitting on a quiet starlit mountain peak.',
    sentPromptScene: 'Explorers reach a remote alpine meadow surrounded by snowy cliff peaks.',
  },
  {
    word: 'leap',
    partOfSpeech: 'v.',
    meaningKo: '도약하다, 껑충 뛰다',
    ipa: '/liːp/',
    definition: 'to make a large jump or jump high over something',
    sentence: 'The playful dolphin would leap high above the ocean waves.',
    wordPromptScene: 'A sleek cartoon dolphin leaping joyfully through sparkling ocean water.',
    sentPromptScene: 'A young gymnast prepares to leap across the padded practice mat.',
  },
  {
    word: 'leak',
    partOfSpeech: 'v.',
    meaningKo: '새다, 누출되다',
    ipa: '/liːk/',
    definition: 'to allow liquid or gas to escape through a hole or crack',
    sentence: 'The plumber tightened the pipe so water would not leak.',
    wordPromptScene: 'A shiny silver pipe with a small clear water drop forming at joint.',
    sentPromptScene: 'A plumber uses a wrench to fix a pipe that began to leak.',
  },
];

const day20_set2 = [
  {
    word: 'guess',
    partOfSpeech: 'v.',
    meaningKo: '추측하다, 맞히다',
    ipa: '/ɡes/',
    definition: 'to give an answer about something when you are not certain',
    sentence: 'Can you guess which mystery storybook is hidden inside box?',
    wordPromptScene: 'A wrapped gift box decorated with a question mark and star sparkles.',
    sentPromptScene: 'Students laugh and try to guess the secret riddle in classroom game.',
  },
  {
    word: 'temperature',
    partOfSpeech: 'n.',
    meaningKo: '온도, 기온',
    ipa: '/ˈtem.pɚ.ə.tʃɚ/',
    definition: 'the measured degree of heat or cold in an object or place',
    sentence: 'The outdoor garden thermometer showed a mild spring temperature of twenty.',
    wordPromptScene: 'A glass garden thermometer displaying twenty degrees under mild sunshine.',
    sentPromptScene: 'A weather student records the morning air temperature in her science journal.',
  },
  {
    word: 'passage',
    partOfSpeech: 'n.',
    meaningKo: '통로, 구절',
    ipa: '/ˈpæs.ɪdʒ/',
    definition: 'a narrow way or corridor allowing travel between places, or text',
    sentence: 'The students walked through a brightly lit stone castle passage.',
    wordPromptScene: 'A charming arched stone corridor illuminated with warm lanterns along walls.',
    sentPromptScene: 'A student reads an inspiring passage aloud from the historical novel.',
  },
  {
    word: 'flat',
    partOfSpeech: 'adj.',
    meaningKo: '평평한, 납작한',
    ipa: '/flæt/',
    definition: 'smooth and level, without any raised areas or hollows',
    sentence: 'We found a flat grassy meadow perfect for pitching our tent.',
    wordPromptScene: 'A smooth level wooden tabletop with a wooden carpenter’s level bubble centered.',
    sentPromptScene: 'Campers set up their tent on a flat grassy clearing in forest.',
  },
  {
    word: 'enormous',
    partOfSpeech: 'adj.',
    meaningKo: '거대한, 엄청난',
    ipa: '/əˈnɔːr.məs/',
    definition: 'extremely large in size, amount, or degree, gigantic',
    sentence: 'The blue whale is an enormous gentle mammal of ocean.',
    wordPromptScene: 'A majestic gentle blue whale gliding peacefully through sunlit ocean waters.',
    sentPromptScene: 'Children look up in awe at the enormous dinosaur skeleton in museum.',
  },
  {
    word: 'accurate',
    partOfSpeech: 'adj.',
    meaningKo: '정확한, 정밀한',
    ipa: '/ˈæk.jɚ.ət/',
    definition: 'correct, exact, and without any mistakes or errors',
    sentence: 'Digital atomic clocks provide an extremely accurate measurement of time.',
    wordPromptScene: 'An archery target showing an arrow striking the exact dead center bullseye.',
    sentPromptScene: 'A student uses a precise millimeter ruler for an accurate science diagram.',
  },
  {
    word: 'freeze',
    partOfSpeech: 'v.',
    meaningKo: '얼다, 얼리다',
    ipa: '/friːz/',
    definition: 'to turn into ice as a result of extreme cold',
    sentence: 'Water in the birdbath will freeze during cold winter nights.',
    wordPromptScene: 'Delicate ice crystal frost patterns forming across a cold glass windowpane.',
    sentPromptScene: 'A chef uses an ice cream maker to freeze fruit juice popsicles.',
  },
  {
    word: 'gear',
    partOfSpeech: 'n.',
    meaningKo: '장비, 기어, 톱니바퀴',
    ipa: '/ɡɪr/',
    definition: 'the equipment needed for a particular activity, or toothed wheel',
    sentence: 'Pack your safety helmet and protective knee pad gear today.',
    wordPromptScene: 'A collection of camping equipment, compass, flashlight, and backpack.',
    sentPromptScene: 'A cyclist checks the gear teeth on her sports bicycle before ride.',
  },
  {
    word: 'fuel',
    partOfSpeech: 'n.',
    meaningKo: '연료',
    ipa: '/ˈfjuː.əl/',
    definition: 'a substance that is burned or used to provide heat or power',
    sentence: 'The clean hydrogen fuel powers the eco-friendly city transit bus.',
    wordPromptScene: 'A modern green electric charging pump nozzle glowing with clean energy.',
    sentPromptScene: 'A worker fills an expedition vehicle with clean biofuel at station.',
  },
  {
    word: 'miss',
    partOfSpeech: 'v.',
    meaningKo: '놓치다, 빗나가다, 그리워하다',
    ipa: '/mɪs/',
    definition: 'to arrive too late to catch a bus or fail to hit',
    sentence: 'Leave home early so you do not miss the school bus.',
    wordPromptScene: 'A yellow school bus pulling up to a designated bus stop sign.',
    sentPromptScene: 'A student walks briskly so she does not miss the morning bell.',
  },
];

const day20_set3 = [
  {
    word: 'license',
    partOfSpeech: 'n.',
    meaningKo: '면허증, 자격증',
    ipa: '/ˈlaɪ.səns/',
    definition: 'an official document giving permission to do or own something',
    sentence: 'He was proud to earn his junior boat pilot license.',
    wordPromptScene: 'A laminated card with a photo and a shiny gold hologram seal.',
    sentPromptScene: 'A young sailor shows a junior sailing license proudly at the marina.',
  },
  {
    word: 'construction',
    partOfSpeech: 'n.',
    meaningKo: '건설, 공사',
    ipa: '/kənˈstrʌk.ʃən/',
    definition: 'the building of houses, bridges, roads, or other structures',
    sentence: 'Workers wore bright yellow hard hats at the bridge construction site.',
    wordPromptScene: 'A friendly yellow crane lifting a steel beam on a building site.',
    sentPromptScene: 'Students observe bridge construction from a safe viewing platform with guides.',
  },
  {
    word: 'wireless',
    partOfSpeech: 'adj.',
    meaningKo: '무선의',
    ipa: '/ˈwaɪr.ləs/',
    definition: 'using radio signals rather than wires to connect electronic devices',
    sentence: 'We connected our laptop to the school’s high-speed wireless network.',
    wordPromptScene: 'A modern sleek Wi-Fi router emitting glowing blue curved signal waves.',
    sentPromptScene: 'Students use wireless keyboards during an interactive coding class on tablets.',
  },
  {
    word: 'nevertheless',
    partOfSpeech: 'adv.',
    meaningKo: '그럼에도 불구하고',
    ipa: '/ˌnev.ɚ.ðəˈles/',
    definition: 'in spite of what has just been mentioned, still',
    sentence: 'It was raining, but nevertheless they enjoyed the forest hike.',
    wordPromptScene: 'Hikers smiling brightly under colorful umbrellas along a scenic trail.',
    sentPromptScene: 'Students carry on with enthusiasm, and nevertheless win the wet match.',
  },
  {
    word: 'barrier',
    partOfSpeech: 'n.',
    meaningKo: '장벽, 장애물',
    ipa: '/ˈber.i.ɚ/',
    definition: 'a fence or gate that prevents people or vehicles from passing',
    sentence: 'The safety barrier along the cliff keeps hikers on path.',
    wordPromptScene: 'A sturdy wooden railing barrier along a scenic mountain canyon overlook.',
    sentPromptScene: 'Hikers walk safely behind the wooden barrier at the scenic viewpoint.',
  },
  {
    word: 'lift',
    partOfSpeech: 'v.',
    meaningKo: '들어 올리다',
    ipa: '/lɪft/',
    definition: 'to move something from a lower to a higher position',
    sentence: 'The strong crane can lift heavy wooden crates with ease.',
    wordPromptScene: 'A hydraulic forklift lifting a wooden pallet of goods into air.',
    sentPromptScene: 'Two friends work together to lift a heavy storage box safely.',
  },
  {
    word: 'curved',
    partOfSpeech: 'adj.',
    meaningKo: '곡선의, 굽은',
    ipa: '/kɝːvd/',
    definition: 'having a smooth, rounded shape without straight angles',
    sentence: 'A rainbow forms a magnificent curved colorful arch across sky.',
    wordPromptScene: 'A vibrant rainbow arching smoothly across a bright blue cloud sky.',
    sentPromptScene: 'An architect draws a graceful curved wooden roof for the library.',
  },
  {
    word: 'eliminate',
    partOfSpeech: 'v.',
    meaningKo: '없애다, 제거하다',
    ipa: '/iˈlɪm.ə.neɪt/',
    definition: 'to remove or take away someone or something completely',
    sentence: 'Using reusable cloth bags helps eliminate plastic waste in town.',
    wordPromptScene: 'A canvas tote bag replacing plastic bags with green leaf checkmarks.',
    sentPromptScene: 'Students use reusable water bottles to eliminate single-use plastic waste.',
  },
  {
    word: 'commit',
    partOfSpeech: 'v.',
    meaningKo: '헌신하다, 전념하다',
    ipa: '/kəˈmɪt/',
    definition: 'to promise to give your time and energy to something',
    sentence: 'Athletes commit hours of daily practice to prepare for games.',
    wordPromptScene: 'A golden pledge scroll with a wax seal of steadfast promise.',
    sentPromptScene: 'Volunteers commit their Saturday morning to cleaning the local nature park.',
  },
  {
    word: 'commute',
    partOfSpeech: 'v.',
    meaningKo: '통근하다, 통학하다',
    ipa: '/kəˈmjuːt/',
    definition: 'to travel regularly between home and work or school',
    sentence: 'Many students commute to school by bicycle along green trails.',
    wordPromptScene: 'A bicycle parked neatly beside a city train station platform.',
    sentPromptScene: 'Commuters board the morning electric train to commute into the city.',
  },
];

const day20_set4 = [
  {
    word: 'drag',
    partOfSpeech: 'v.',
    meaningKo: '끌다, 끌고 가다',
    ipa: '/dræɡ/',
    definition: 'to pull something or someone along the ground with effort',
    sentence: 'The children helped drag the wooden sled up the snowy hill.',
    wordPromptScene: 'A classic red wooden sled resting at the bottom of snow hill.',
    sentPromptScene: 'Two laughing children drag a sled up the hill for another ride.',
  },
  {
    word: 'fasten',
    partOfSpeech: 'v.',
    meaningKo: '매다, 잠그다',
    ipa: '/ˈfæs.ən/',
    definition: 'to join or close together the two parts of something',
    sentence: 'Always fasten your bicycle helmet strap snugly under your chin.',
    wordPromptScene: 'A bicycle helmet buckle clicking together with a secure green star.',
    sentPromptScene: 'A passenger clicks the seatbelt buckle to fasten it before takeoff.',
  },
  {
    word: 'precise',
    partOfSpeech: 'adj.',
    meaningKo: '정확한, 정밀한',
    ipa: '/prəˈsaɪs/',
    definition: 'exact, clear, and accurate in every minute detail',
    sentence: 'The watchmaker used tiny tools to make precise gear adjustments.',
    wordPromptScene: 'A watchmaker’s magnifying loupe and miniature tweezers over a watch gear.',
    sentPromptScene: 'A student uses a precise metal compass to draw exact circles.',
  },
  {
    word: 'vital',
    partOfSpeech: 'adj.',
    meaningKo: '필수적인, 극히 중요한',
    ipa: '/ˈvaɪ.t̬əl/',
    definition: 'necessary for the success, continued existence, or life of something',
    sentence: 'Fresh water is a vital resource for all plants and animals.',
    wordPromptScene: 'A crystal drop of clean water surrounded by vibrant green leaves.',
    sentPromptScene: 'A doctor explains why regular hydration is vital for growing children.',
  },
  {
    word: 'component',
    partOfSpeech: 'n.',
    meaningKo: '구성 요소, 부품',
    ipa: '/kəmˈpoʊ.nənt/',
    definition: 'one of the parts that make up a whole machine',
    sentence: 'A strong battery is a key electrical component of electric cars.',
    wordPromptScene: 'A green circuit board with glowing colorful microchips and capacitors.',
    sentPromptScene: 'Young engineers assemble each small electronic component of a toy robot.',
  },
  {
    word: 'seldom',
    partOfSpeech: 'adv.',
    meaningKo: '좀처럼 ~않는, 드물게',
    ipa: '/ˈsel.dəm/',
    definition: 'almost never, rarely happening or appearing',
    sentence: 'It seldom snows in this sunny southern coastal resort town.',
    wordPromptScene: 'A tropical beach with palm trees under warm bright sunny skies.',
    sentPromptScene: 'The shy mountain owl is seldom seen during daylight hours.',
  },
  {
    word: 'enhance',
    partOfSpeech: 'v.',
    meaningKo: '향상시키다, 높이다',
    ipa: '/ɪnˈhæns/',
    definition: 'to improve the quality, amount, or strength of something',
    sentence: 'Adding fresh strawberries will enhance the sweet flavor of yogurt.',
    wordPromptScene: 'A bowl of creamy yogurt topped with fresh glowing ruby strawberries.',
    sentPromptScene: 'Colorful illustrations enhance the storytelling experience for young readers.',
  },
  {
    word: 'sink',
    partOfSpeech: 'v.',
    meaningKo: '가라앉다, 싱크대',
    ipa: '/sɪŋk/',
    definition: 'to go down below the surface of water or liquid',
    sentence: 'A heavy metal pebble will sink quickly to the pond bottom.',
    wordPromptScene: 'A smooth stone dropping through clear water creating gentle ripples.',
    sentPromptScene: 'Children test which objects float and which objects sink in water.',
  },
  {
    word: 'destination',
    partOfSpeech: 'n.',
    meaningKo: '목적지, 행선지',
    ipa: '/ˌdes.təˈneɪ.ʃən/',
    definition: 'the place where someone or something is going or being sent',
    sentence: 'The mountain lake was our final destination on the weekend hike.',
    wordPromptScene: 'A picturesque wooden cabin at the end of a winding forest trail.',
    sentPromptScene: 'Travelers arrive happily at their holiday destination after a train ride.',
  },
  {
    word: 'station',
    partOfSpeech: 'n.',
    meaningKo: '역, 정거장',
    ipa: '/ˈsteɪ.ʃən/',
    definition: 'a building where trains or buses stop for passengers',
    sentence: 'We waited on the clean platform of the central railway station.',
    wordPromptScene: 'A charming brick railway station with a clock tower and platform benches.',
    sentPromptScene: 'Passengers wave goodbye as the train pulls away from the station.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 20, set: 1, wordsData: day20_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 20, set: 2, wordsData: day20_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 20, set: 3, wordsData: day20_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 20, set: 4, wordsData: day20_set4 });
  console.log('DAY 20 written successfully');
}

run();
