import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 02
// ==========================================
const day02_set1 = [
  {
    word: 'active',
    partOfSpeech: 'adj.',
    meaningKo: '활동적인, 적극적인',
    ipa: '/ˈæk.tɪv/',
    definition: 'doing things that require physical movement or energy',
    sentence: 'The active puppy chased the rolling yellow ball outside.',
    wordPromptScene: 'An energetic cartoon puppy jumping happily over a colorful hurdle.',
    sentPromptScene: 'A playful puppy dashes across green grass after a bouncing ball.',
  },
  {
    word: 'excellent',
    partOfSpeech: 'adj.',
    meaningKo: '훌륭한, 뛰어난',
    ipa: '/ˈek.səl.ənt/',
    definition: 'extremely good or of very high quality',
    sentence: 'She received an excellent score on her science project.',
    wordPromptScene: 'A shiny gold medal with three sparkling stars beside it.',
    sentPromptScene: 'A happy student holds up an excellent science test score card.',
  },
  {
    word: 'lecture',
    partOfSpeech: 'n.',
    meaningKo: '강의, 강연',
    ipa: '/ˈlek.tʃər/',
    definition: 'a talk given to teach people about a subject',
    sentence: 'Students listened carefully to the science lecture about planets.',
    wordPromptScene: 'A wooden podium with a microphone and a chalkboard behind it.',
    sentPromptScene: 'A teacher gives an exciting lecture about planets to students.',
  },
  {
    word: 'academic',
    partOfSpeech: 'adj.',
    meaningKo: '학업의, 학문의',
    ipa: '/ˌæk.əˈdem.ɪk/',
    definition: 'relating to schools, colleges, and studying',
    sentence: 'The library supports students with various academic goals every year.',
    wordPromptScene: 'A graduation cap resting on top of a stack of textbooks.',
    sentPromptScene: 'Students study hard in a bright library for academic success.',
  },
  {
    word: 'encourage',
    partOfSpeech: 'v.',
    meaningKo: '격려하다, 용기를 북돋우다',
    ipa: '/ɪnˈkɝː.ɪdʒ/',
    definition: 'to give someone hope, confidence, or support',
    sentence: 'Teachers always encourage students to try their very best.',
    wordPromptScene: 'Two friendly cartoon hands giving a warm thumbs up together.',
    sentPromptScene: 'A smiling teacher cheers to encourage a young runner at school.',
  },
  {
    word: 'debate',
    partOfSpeech: 'n.',
    meaningKo: '토론, 논쟁',
    ipa: '/dɪˈbeɪt/',
    definition: 'a formal discussion on a particular topic',
    sentence: 'The two teams held a lively debate about technology.',
    wordPromptScene: 'Two microphones facing each other on debate tables with note cards.',
    sentPromptScene: 'Two student speakers present ideas during a lively classroom debate.',
  },
  {
    word: 'president',
    partOfSpeech: 'n.',
    meaningKo: '회장, 대통령',
    ipa: '/ˈprez.ɪ.dənt/',
    definition: 'the leader of a country, club, or organization',
    sentence: 'The student club president announced the spring festival date.',
    wordPromptScene: 'A friendly student leader standing with a speech scroll in hand.',
    sentPromptScene: 'A cheerful club president speaks at a podium to fellow students.',
  },
  {
    word: 'assignment',
    partOfSpeech: 'n.',
    meaningKo: '과제, 숙제',
    ipa: '/əˈsaɪn.mənt/',
    definition: 'a piece of work given to someone to do',
    sentence: 'He finished his math assignment before watching the game.',
    wordPromptScene: 'A neat worksheet with a checklist and a colorful pencil.',
    sentPromptScene: 'A boy completes a drawing assignment at his study desk.',
  },
  {
    word: 'principal',
    partOfSpeech: 'n.',
    meaningKo: '교장',
    ipa: '/ˈprɪn.sə.pəl/',
    definition: 'the person in charge of a school',
    sentence: 'The school principal greeted everyone at the main entrance.',
    wordPromptScene: 'A kind school principal waving near the front gates of school.',
    sentPromptScene: 'The principal smiles and welcomes students arriving on school bus.',
  },
  {
    word: 'principle',
    partOfSpeech: 'n.',
    meaningKo: '원칙, 원리',
    ipa: '/ˈprɪn.sə.pəl/',
    definition: 'a basic truth, rule, or belief that guides you',
    sentence: 'Honesty is the most important principle in our classroom.',
    wordPromptScene: 'A glowing stone pillar inscribed with a compass and balance scale.',
    sentPromptScene: 'Children sign a poster showing the golden principle of kindness.',
  },
];

const day02_set2 = [
  {
    word: 'graduate',
    partOfSpeech: 'v.',
    meaningKo: '졸업하다',
    ipa: '/ˈɡrædʒ.u.eɪt/',
    definition: 'to complete school, college, or university studies successfully',
    sentence: 'My older sister will graduate from middle school soon.',
    wordPromptScene: 'A diploma scroll tied with a red ribbon beside a graduation cap.',
    sentPromptScene: 'A happy student waves to graduate with honors on stage.',
  },
  {
    word: 'sense',
    partOfSpeech: 'n.',
    meaningKo: '감각, 느낌',
    ipa: '/sens/',
    definition: 'an ability to see, hear, smell, taste, or touch',
    sentence: 'Dogs have a sharp sense of smell for tracking.',
    wordPromptScene: 'Five friendly icons representing sight, hearing, smell, taste, and touch.',
    sentPromptScene: 'A puppy uses its keen sense of smell to find hidden treats.',
  },
  {
    word: 'real',
    partOfSpeech: 'adj.',
    meaningKo: '진짜의, 실제의',
    ipa: '/ˈriː.əl/',
    definition: 'actually existing or not fake',
    sentence: 'The museum display showed a real dinosaur fossil tooth.',
    wordPromptScene: 'A sparkling genuine diamond alongside a magnifying glass.',
    sentPromptScene: 'A curious visitor examines a real ancient dinosaur fossil in museum.',
  },
  {
    word: 'annual',
    partOfSpeech: 'adj.',
    meaningKo: '매년의, 연례의',
    ipa: '/ˈæn.ju.əl/',
    definition: 'happening once every year',
    sentence: 'The town celebrated its annual flower parade in May.',
    wordPromptScene: 'A wall calendar flipped to a highlighted date marked with a wreath.',
    sentPromptScene: 'Townspeople gather in costume for the annual spring flower parade.',
  },
  {
    word: 'collect',
    partOfSpeech: 'v.',
    meaningKo: '모으다, 수집하다',
    ipa: '/kəˈlekt/',
    definition: 'to bring things together from different places',
    sentence: 'Children love to collect shiny seashells on the sandy beach.',
    wordPromptScene: 'A wooden treasure box filling with colorful postage stamps and coins.',
    sentPromptScene: 'A smiling boy bends down to collect pretty shells on shore.',
  },
  {
    word: 'deadline',
    partOfSpeech: 'n.',
    meaningKo: '마감 기한',
    ipa: '/ˈded.laɪn/',
    definition: 'a time or day by which something must be finished',
    sentence: 'We must submit our science project before the deadline.',
    wordPromptScene: 'A wall clock with an alarm bell beside an urgent calendar checklist.',
    sentPromptScene: 'A student hurries to finish a project before the deadline.',
  },
  {
    word: 'confident',
    partOfSpeech: 'adj.',
    meaningKo: '자신감 있는, 확신하는',
    ipa: '/ˈkɑːn.fə.dənt/',
    definition: 'sure of your own ability to succeed',
    sentence: 'The young speaker felt confident on the big stage.',
    wordPromptScene: 'A proud little superhero standing tall with hands on hips.',
    sentPromptScene: 'A confident girl smiles brightly while speaking into a microphone.',
  },
  {
    word: 'include',
    partOfSpeech: 'v.',
    meaningKo: '포함하다',
    ipa: '/ɪnˈkluːd/',
    definition: 'to make someone or something part of a group',
    sentence: 'Does the lunch box include fresh fruit and milk?',
    wordPromptScene: 'A picnic basket open to show sandwiches, fruit, and drinks.',
    sentPromptScene: 'A cafeteria worker packs a tray to include soup and salad.',
  },
  {
    word: 'shout',
    partOfSpeech: 'v.',
    meaningKo: '소리치다, 외치다',
    ipa: '/ʃaʊt/',
    definition: 'to say something very loudly',
    sentence: 'Fans began to shout loudly when their team scored.',
    wordPromptScene: 'A classic megaphone with sound waves radiating outwards.',
    sentPromptScene: 'Excited cheerleaders shout encouragement from the stadium bleachers.',
  },
  {
    word: 'subject',
    partOfSpeech: 'n.',
    meaningKo: '과목, 주제',
    ipa: '/ˈsʌb.dʒɪkt/',
    definition: 'an area of knowledge studied in a school',
    sentence: 'Science is my favorite subject in school this year.',
    wordPromptScene: 'Icons of an atom, musical note, paint palette, and math ruler.',
    sentPromptScene: 'A student points happily at science as the best subject.',
  },
];

const day02_set3 = [
  {
    word: 'participate',
    partOfSpeech: 'v.',
    meaningKo: '참여하다, 참가하다',
    ipa: '/pɑːrˈtɪs.ə.peɪt/',
    definition: 'to take part in an activity or event',
    sentence: 'All students can participate in the annual sports day.',
    wordPromptScene: 'A raised friendly hand volunteer icon glowing brightly with energy.',
    sentPromptScene: 'Children line up to participate in a fun relay race.',
  },
  {
    word: 'auditorium',
    partOfSpeech: 'n.',
    meaningKo: '강당, 대강의실',
    ipa: '/ˌɑː.dəˈtɔːr.i.əm/',
    definition: 'a large room or building where an audience sits',
    sentence: 'The audience filled the large auditorium for the concert.',
    wordPromptScene: 'A grand hall with red velvet seats facing a brightly lit stage.',
    sentPromptScene: 'Crowds fill the school auditorium to watch a music show.',
  },
  {
    word: 'inform',
    partOfSpeech: 'v.',
    meaningKo: '알리다, 통지하다',
    ipa: '/ɪnˈfɔːrm/',
    definition: 'to tell someone about particular facts or information',
    sentence: 'The captain will inform passengers about the flight delay.',
    wordPromptScene: 'A loudspeaker broadcasting glowing note symbols and notice icons.',
    sentPromptScene: 'A pilot uses the radio system to inform waiting travelers.',
  },
  {
    word: 'duty',
    partOfSpeech: 'n.',
    meaningKo: '의무, 직무',
    ipa: '/ˈduː.t̬i/',
    definition: 'something that you have to do because it is right',
    sentence: 'It is the safety officer’s duty to help people.',
    wordPromptScene: 'A shining badge and a neat checklist on a clipboard.',
    sentPromptScene: 'A crossing guard performs his morning duty near the crosswalk.',
  },
  {
    word: 'evaluate',
    partOfSpeech: 'v.',
    meaningKo: '평가하다',
    ipa: '/ɪˈvæl.ju.eɪt/',
    definition: 'to judge the quality, importance, or value of something',
    sentence: 'Judges will evaluate each painting in the art contest.',
    wordPromptScene: 'A magnifying glass examining a report card with five stars.',
    sentPromptScene: 'Art judges look closely to evaluate paintings at a gallery.',
  },
  {
    word: 'minimum',
    partOfSpeech: 'n.',
    meaningKo: '최소한, 최소',
    ipa: '/ˈmɪn.ə.məm/',
    definition: 'the smallest amount or number allowed or possible',
    sentence: 'You need a minimum of four players for this board game.',
    wordPromptScene: 'A gauge needle pointing to the lowest green indicator line.',
    sentPromptScene: 'A sign shows the minimum height required to ride roller coasters.',
  },
  {
    word: 'introduction',
    partOfSpeech: 'n.',
    meaningKo: '소개, 도입',
    ipa: '/ˌɪn.trəˈdʌk.ʃən/',
    definition: 'the act of telling people someone’s name or presenting something',
    sentence: 'The speaker began with a brief introduction of himself.',
    wordPromptScene: 'A name tag sticker with a smiling face and waving hand.',
    sentPromptScene: 'A new classmate gives a friendly introduction in front of class.',
  },
  {
    word: 'photograph',
    partOfSpeech: 'n.',
    meaningKo: '사진',
    ipa: '/ˈfoʊ.t̬ə.ɡræf/',
    definition: 'a picture made using a camera',
    sentence: 'We framed a beautiful photograph of our mountain camping trip.',
    wordPromptScene: 'A framed color photo showing a scenic mountain sunset and trees.',
    sentPromptScene: 'A family places a photograph inside a wooden wall frame.',
  },
  {
    word: 'council',
    partOfSpeech: 'n.',
    meaningKo: '의회, 위원회',
    ipa: '/ˈkaʊn.səl/',
    definition: 'a group of people elected or chosen to make decisions',
    sentence: 'The student council planned a fun game for everyone.',
    wordPromptScene: 'A round wooden conference table with empty microphones and notebooks.',
    sentPromptScene: 'Members of the council gather in a room to vote.',
  },
  {
    word: 'conceal',
    partOfSpeech: 'v.',
    meaningKo: '숨기다, 감추다',
    ipa: '/kənˈsiːl/',
    definition: 'to hide something so it cannot be seen',
    sentence: 'Thick green bushes conceal the entrance to the secret garden.',
    wordPromptScene: 'A wooden treasure chest tucked behind leafy jungle vines.',
    sentPromptScene: 'Dense ivy leaves conceal an old stone doorway along the wall.',
  },
];

const day02_set4 = [
  {
    word: 'session',
    partOfSpeech: 'n.',
    meaningKo: '시간, 기간, 회기',
    ipa: '/ˈseʃ.ən/',
    definition: 'a period of time spent doing a particular activity',
    sentence: 'We had a thirty-minute practice session after school today.',
    wordPromptScene: 'A digital stopwatch showing running time beside a sports ball.',
    sentPromptScene: 'Swimmers finish a morning training session at the local pool.',
  },
  {
    word: 'strict',
    partOfSpeech: 'adj.',
    meaningKo: '엄격한, 엄한',
    ipa: '/strɪkt/',
    definition: 'expecting people to obey rules completely',
    sentence: 'The coach has strict rules about arriving on time.',
    wordPromptScene: 'A clean clipboard listing numbered rules with green checkmarks.',
    sentPromptScene: 'A whistle-holding coach enforces strict safety rules on the track.',
  },
  {
    word: 'twist',
    partOfSpeech: 'v.',
    meaningKo: '비틀다, 구부리다',
    ipa: '/twɪst/',
    definition: 'to turn something around or change its shape',
    sentence: 'You can twist the bottle cap to open the drink.',
    wordPromptScene: 'Two colorful wires twisting around each other into a spiral.',
    sentPromptScene: 'A girl uses both hands to twist open a juice bottle.',
  },
  {
    word: 'spill',
    partOfSpeech: 'v.',
    meaningKo: '엎지르다, 흘리다',
    ipa: '/spɪl/',
    definition: 'to flow or fall over the edge of a container',
    sentence: 'Be careful not to spill warm tea on the tablecloth.',
    wordPromptScene: 'A fallen mug splashing drops of liquid onto a wooden surface.',
    sentPromptScene: 'A careful child carries a glass slowly not to spill water.',
  },
  {
    word: 'union',
    partOfSpeech: 'n.',
    meaningKo: '결합, 연합',
    ipa: '/ˈjuː.njən/',
    definition: 'an act of joining two or more things together',
    sentence: 'The strong union of two clubs made the project successful.',
    wordPromptScene: 'Two interlocking golden puzzle rings glowing with bright synergy.',
    sentPromptScene: 'Club members celebrate the union of their two volunteer teams.',
  },
  {
    word: 'maximum',
    partOfSpeech: 'n.',
    meaningKo: '최대, 최고한도',
    ipa: '/ˈmæk.sə.məm/',
    definition: 'the largest amount or number that is possible',
    sentence: 'The elevator can carry a maximum of eight people safely.',
    wordPromptScene: 'A speedometer gauge needle reaching the highest red number mark.',
    sentPromptScene: 'An elevator sign displays the maximum capacity of passengers clearly.',
  },
  {
    word: 'semester',
    partOfSpeech: 'n.',
    meaningKo: '학기',
    ipa: '/səˈmes.tər/',
    definition: 'one of the two periods into which a school year is divided',
    sentence: 'Our fall semester begins on the first Monday of September.',
    wordPromptScene: 'A school calendar dividing the year into two colorful term blocks.',
    sentPromptScene: 'Happy students enter the school gate on the first day of semester.',
  },
  {
    word: 'ceiling',
    partOfSpeech: 'n.',
    meaningKo: '천장',
    ipa: '/ˈsiː.lɪŋ/',
    definition: 'the inside top surface of a room',
    sentence: 'Glowing star stickers shone brightly on the high bedroom ceiling.',
    wordPromptScene: 'A modern room ceiling decorated with warm circular recessed lights.',
    sentPromptScene: 'A child looks up at glowing star stickers on the ceiling.',
  },
  {
    word: 'stationery',
    partOfSpeech: 'n.',
    meaningKo: '문구류, 문방구',
    ipa: '/ˈsteɪ.ʃə.ner.i/',
    definition: 'materials like paper, pens, and envelopes for writing',
    sentence: 'She bought colorful stationery for writing letters to her friends.',
    wordPromptScene: 'An assortment of pastel envelopes, fountain pens, and paper pads.',
    sentPromptScene: 'A girl picks out cute stationery items in a cozy shop.',
  },
  {
    word: 'term',
    partOfSpeech: 'n.',
    meaningKo: '용어, 기간',
    ipa: '/tɝːm/',
    definition: 'a word or expression with a specific meaning',
    sentence: 'The teacher explained an important scientific term during class.',
    wordPromptScene: 'A glossary book page with highlighted bold words and definitions.',
    sentPromptScene: 'A teacher writes a new vocabulary term on the chalkboard.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 2, set: 1, wordsData: day02_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 2, set: 2, wordsData: day02_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 2, set: 3, wordsData: day02_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 2, set: 4, wordsData: day02_set4 });
  console.log('DAY 02 written successfully');
}

run();
