import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 17
// ==========================================
const day17_set1 = [
  {
    word: 'biology',
    partOfSpeech: 'n.',
    meaningKo: '생물학',
    ipa: '/baɪˈɑː.lə.dʒi/',
    definition: 'the scientific study of living things and life processes',
    sentence: 'In our biology class, we studied how green leaves photosynthesize.',
    wordPromptScene: 'A high-powered microscope examining a glowing plant leaf cell structure.',
    sentPromptScene: 'Students examine botanical specimens during an engaging biology class.',
  },
  {
    word: 'gene',
    partOfSpeech: 'n.',
    meaningKo: '유전자',
    ipa: '/dʒiːn/',
    definition: 'a unit of heredity passed from parents to children',
    sentence: 'The plant inherited a special gene that resists cold winter.',
    wordPromptScene: 'A glowing colorful 3D DNA double-helix spiral model.',
    sentPromptScene: 'A scientist points at a digital screen showing a plant gene structure.',
  },
  {
    word: 'factor',
    partOfSpeech: 'n.',
    meaningKo: '요인, 요소',
    ipa: '/ˈfæk.tɚ/',
    definition: 'one of several things that cause or influence a situation',
    sentence: 'Sunlight is an essential factor for healthy flower blooming.',
    wordPromptScene: 'Three interlocking puzzle pieces labeled Sun, Water, and Soil.',
    sentPromptScene: 'A gardener explains how warm temperature is a key growth factor.',
  },
  {
    word: 'trace',
    partOfSpeech: 'v.',
    meaningKo: '추적하다, 베끼다',
    ipa: '/treɪs/',
    definition: 'to follow the path or track of someone or something',
    sentence: 'Young scientists can trace the migration route of sea turtles.',
    wordPromptScene: 'A magnifying glass following little animal paw footprints in sand.',
    sentPromptScene: 'A student uses tracing paper to trace a detailed animal drawing.',
  },
  {
    word: 'require',
    partOfSpeech: 'v.',
    meaningKo: '필요로 하다, 요구하다',
    ipa: '/rɪˈkwaɪr/',
    definition: 'to need something or make something necessary',
    sentence: 'All students require safety goggles for the chemistry laboratory experiment.',
    wordPromptScene: 'A checklist showing safety goggles and lab coat with green checkmarks.',
    sentPromptScene: 'A science teacher explains what materials we require for the project.',
  },
  {
    word: 'structure',
    partOfSpeech: 'n.',
    meaningKo: '구조, 구조물',
    ipa: '/ˈstrʌk.tʃɚ/',
    definition: 'the way in which parts are connected together in something',
    sentence: 'The honeycomb has a perfect hexagonal geometric structure built by bees.',
    wordPromptScene: 'A close-up 3D view of a golden honeycomb with hexagonal cells.',
    sentPromptScene: 'An architect displays a wooden bridge model showing its sturdy structure.',
  },
  {
    word: 'research',
    partOfSpeech: 'n.',
    meaningKo: '연구, 조사',
    ipa: '/ˈriː.sɝːtʃ/',
    definition: 'detailed study of a subject to discover new facts',
    sentence: 'Her marine research helped protect endangered sea turtle nesting beaches.',
    wordPromptScene: 'An open field notebook with scientific sketches, charts, and a microscope.',
    sentPromptScene: 'Students conduct research on renewable energy in the school computer lab.',
  },
  {
    word: 'intelligent',
    partOfSpeech: 'adj.',
    meaningKo: '지능적인, 똑똑한',
    ipa: '/ɪnˈtel.ə.dʒənt/',
    definition: 'able to learn, understand, and think easily and well',
    sentence: 'Dolphins are highly intelligent animals capable of solving complex problems.',
    wordPromptScene: 'A cute cartoon dolphin leaping gracefully through a starry hoop.',
    sentPromptScene: 'A smart robot assists students with solving difficult intelligent logic puzzles.',
  },
  {
    word: 'sign',
    partOfSpeech: 'n.',
    meaningKo: '표지판, 징후, 신호',
    ipa: '/saɪn/',
    definition: 'a board or gesture giving information, warning, or instructions',
    sentence: 'The wooden trail sign showed the way to the campsite.',
    wordPromptScene: 'A wooden directional arrow signpost in a sunny green forest clearing.',
    sentPromptScene: 'Hikers look at a colorful sign pointing to the waterfall trail.',
  },
  {
    word: 'sigh',
    partOfSpeech: 'n.',
    meaningKo: '한숨, 탄식',
    ipa: '/saɪ/',
    definition: 'a slow, deep breath out expressing relief, tiredness, or sadness',
    sentence: 'She gave a gentle sigh of relief after finishing exams.',
    wordPromptScene: 'A cute cartoon character breathing out a tiny cloud of relief.',
    sentPromptScene: 'A student sits down with a peaceful sigh of relief after completing tasks.',
  },
];

const day17_set2 = [
  {
    word: 'insect',
    partOfSpeech: 'n.',
    meaningKo: '곤충',
    ipa: '/ˈɪn.sekt/',
    definition: 'a small creature with six legs and three body parts',
    sentence: 'A colorful ladybug is a helpful garden insect for plants.',
    wordPromptScene: 'A cute red ladybug with black spots resting on a green leaf.',
    sentPromptScene: 'Children use a magnifying glass to observe a harmless garden insect.',
  },
  {
    word: 'circumstance',
    partOfSpeech: 'n.',
    meaningKo: '상황, 환경',
    ipa: '/ˈsɝː.kəm.stæns/',
    definition: 'a condition or fact connected with an event or action',
    sentence: 'Under any circumstance, always wear your seatbelt while riding cars.',
    wordPromptScene: 'A car seatbelt clicking securely into a glowing green buckle mechanism.',
    sentPromptScene: 'A teacher explains safety rules that apply in every emergency circumstance.',
  },
  {
    word: 'normal',
    partOfSpeech: 'adj.',
    meaningKo: '정상적인, 평범한',
    ipa: '/ˈnɔːr.məl/',
    definition: 'ordinary or usual, the same as what happens typically',
    sentence: 'His body temperature was completely normal after resting all night.',
    wordPromptScene: 'A digital clinical thermometer showing a healthy normal green temperature reading.',
    sentPromptScene: 'A doctor confirms that the student’s heartbeat is steady and normal.',
  },
  {
    word: 'threat',
    partOfSpeech: 'n.',
    meaningKo: '위협, 협박',
    ipa: '/θret/',
    definition: 'a possibility that something very bad or dangerous may happen',
    sentence: 'Strong forest winds posed a serious threat to the campfire.',
    wordPromptScene: 'A sturdy stone wall protecting a cozy green tent from wind.',
    sentPromptScene: 'Campers put out the fire so it poses no threat to trees.',
  },
  {
    word: 'improve',
    partOfSpeech: 'v.',
    meaningKo: '개선하다, 향상시키다',
    ipa: '/ɪmˈpruːv/',
    definition: 'to get better or make something better than before',
    sentence: 'Daily reading practice will improve your English vocabulary skills rapidly.',
    wordPromptScene: 'A rising green trend graph with five sparkling gold stars.',
    sentPromptScene: 'A student practices cursive handwriting every day to improve neatness.',
  },
  {
    word: 'repeat',
    partOfSpeech: 'v.',
    meaningKo: '반복하다, 따라 하다',
    ipa: '/rɪˈpiːt/',
    definition: 'to say or do something again more than once',
    sentence: 'Please repeat the new vocabulary words aloud after the teacher.',
    wordPromptScene: 'Two green looping arrows forming a continuous repeating infinity circle.',
    sentPromptScene: 'Students listen and repeat the French phrases with great enthusiasm.',
  },
  {
    word: 'resemble',
    partOfSpeech: 'v.',
    meaningKo: '닮다, 비슷하다',
    ipa: '/rɪˈzem.bəl/',
    definition: 'to look like or be similar to another person',
    sentence: 'The baby bear cub does strongly resemble its loving mother.',
    wordPromptScene: 'A mother brown bear and her cute playful cub sitting together.',
    sentPromptScene: 'Children notice how fluffy clouds resemble galloping white horses in sky.',
  },
  {
    word: 'protein',
    partOfSpeech: 'n.',
    meaningKo: '단백질',
    ipa: '/ˈproʊ.tiːn/',
    definition: 'an organic substance found in foods that builds body muscles',
    sentence: 'Eggs, beans, and tofu provide healthy protein for active children.',
    wordPromptScene: 'A bowl containing hard-boiled eggs, fresh edamame beans, and tofu.',
    sentPromptScene: 'A nutritionist shows a colorful chart of healthy daily protein sources.',
  },
  {
    word: 'hatch',
    partOfSpeech: 'v.',
    meaningKo: '부화하다',
    ipa: '/hætʃ/',
    definition: 'to break out of an egg to be born',
    sentence: 'Three cute yellow ducklings began to hatch from warm eggs.',
    wordPromptScene: 'A speckled bird egg cracking open with a tiny yellow chick peeking out.',
    sentPromptScene: 'Children watch in wonder as baby chicks hatch in an incubator.',
  },
  {
    word: 'direct',
    partOfSpeech: 'adj.',
    meaningKo: '직접적인, 직행의',
    ipa: '/dɪˈrekt/',
    definition: 'going straight from one place to another with no stops',
    sentence: 'We took a direct train to the seaside holiday resort.',
    wordPromptScene: 'A straight yellow train track cutting cleanly through rolling green hills.',
    sentPromptScene: 'Passengers board a direct bus heading straight to the city airport.',
  },
];

const day17_set3 = [
  {
    word: 'individual',
    partOfSpeech: 'n.',
    meaningKo: '개인, 개체',
    ipa: '/ˌɪn.dəˈvɪdʒ.u.əl/',
    definition: 'a single person, animal, or thing considered separately',
    sentence: 'Each individual student in our class has unique creative talents.',
    wordPromptScene: 'A single glowing golden origami bird standing out among blue birds.',
    sentPromptScene: 'A teacher gives personalized helpful feedback to each individual student.',
  },
  {
    word: 'silent',
    partOfSpeech: 'adj.',
    meaningKo: '조용한, 침묵하는',
    ipa: '/ˈsaɪ.lənt/',
    definition: 'without any sound, completely quiet and not speaking',
    sentence: 'The forest was peaceful and completely silent under falling snow.',
    wordPromptScene: 'A serene snowy pine forest at twilight in absolute quiet.',
    sentPromptScene: 'Students keep silent in the reading room to focus on study.',
  },
  {
    word: 'fiber',
    partOfSpeech: 'n.',
    meaningKo: '섬유, 섬유질',
    ipa: '/ˈfaɪ.bɚ/',
    definition: 'substance in plant foods that helps digestion, or thin threads',
    sentence: 'Eating oats and apples provides essential dietary fiber for health.',
    wordPromptScene: 'A bowl of rolled oats, crunchy red apples, and flax seeds.',
    sentPromptScene: 'A health teacher explains why dietary fiber is great for digestion.',
  },
  {
    word: 'ancestor',
    partOfSpeech: 'n.',
    meaningKo: '조상, 선조',
    ipa: '/ˈæn.ses.tɚ/',
    definition: 'a person related to you who lived a long time ago',
    sentence: 'His ancient ancestor lived in a stone castle centuries ago.',
    wordPromptScene: 'An ornate family tree tapestry with heraldic crests and portraits.',
    sentPromptScene: 'A grandfather tells family history stories about an ancient brave ancestor.',
  },
  {
    word: 'yawn',
    partOfSpeech: 'v.',
    meaningKo: '하품하다',
    ipa: '/jɑːn/',
    definition: 'to open your mouth wide and breathe deeply when tired',
    sentence: 'The sleepy kitten began to yawn before taking an afternoon nap.',
    wordPromptScene: 'A cute fluffy cartoon kitten yawning widely on a soft pillow.',
    sentPromptScene: 'A tired puppy stretches its legs and begins to yawn cutely.',
  },
  {
    word: 'pregnant',
    partOfSpeech: 'adj.',
    meaningKo: '임신한, 새끼를 밴',
    ipa: '/ˈpreɡ.nənt/',
    definition: 'having an unborn baby or offspring developing inside the body',
    sentence: 'The pregnant mother cat rested comfortably in her warm cozy box.',
    wordPromptScene: 'A mother cat resting gently in a padded wicker bed with blankets.',
    sentPromptScene: 'A veterinarian checks a pregnant golden retriever with caring hands in clinic.',
  },
  {
    word: 'stimulate',
    partOfSpeech: 'v.',
    meaningKo: '자극하다, 촉진하다',
    ipa: '/ˈstɪm.jə.leɪt/',
    definition: 'to encourage something to grow, develop, or become active',
    sentence: 'Playing chess puzzles can stimulate brain activity and logical thinking.',
    wordPromptScene: 'A glowing cartoon brain surrounded by sparkling lightning bolts and gears.',
    sentPromptScene: 'Creative building blocks stimulate imagination and fine motor skills in children.',
  },
  {
    word: 'slightly',
    partOfSpeech: 'adv.',
    meaningKo: '약간, 조금',
    ipa: '/ˈslaɪt.li/',
    definition: 'a little bit or to a small degree',
    sentence: 'She smiled slightly when she recognized her friend in crowd.',
    wordPromptScene: 'A balance scale tilted ever so slightly to the right side.',
    sentPromptScene: 'A student adjusts the microscope dial slightly to focus the slide.',
  },
  {
    word: 'bleed',
    partOfSpeech: 'v.',
    meaningKo: '피가 나다',
    ipa: '/bliːd/',
    definition: 'to lose blood from the body through a cut',
    sentence: 'A small colorful bandage prevented the scratch to bleed further.',
    wordPromptScene: 'A cute cartoon bandage strip with smiley faces and stars.',
    sentPromptScene: 'A caring school nurse places a bandage so papercut will not bleed.',
  },
  {
    word: 'breed',
    partOfSpeech: 'n.',
    meaningKo: '품종, 종류',
    ipa: '/briːd/',
    definition: 'a particular type of animal developed by human selection',
    sentence: 'The golden retriever is a very friendly and gentle dog breed.',
    wordPromptScene: 'A happy golden retriever puppy sitting proudly in a meadow.',
    sentPromptScene: 'A dog trainer introduces a friendly sheepdog breed to festival visitors.',
  },
];

const day17_set4 = [
  {
    word: 'crawl',
    partOfSpeech: 'v.',
    meaningKo: '기어가다',
    ipa: '/krɑːl/',
    definition: 'to move along on hands and knees or slowly on the ground',
    sentence: 'The cute baby turtle started to crawl toward the ocean.',
    wordPromptScene: 'A baby sea turtle crawling across wet sand toward foamy waves.',
    sentPromptScene: 'A toddler giggles as she begins to crawl across soft playroom rugs.',
  },
  {
    word: 'sensation',
    partOfSpeech: 'n.',
    meaningKo: '감각, 느낌, 돌풍',
    ipa: '/senˈseɪ.ʃən/',
    definition: 'a physical feeling resulting from something that happens to body',
    sentence: 'Walking barefoot on soft green grass was a wonderful refreshing sensation.',
    wordPromptScene: 'Bare cartoon feet touching cool green clover lawn with dew sparkles.',
    sentPromptScene: 'A child laughs at the tickling sensation of gentle warm raindrops.',
  },
  {
    word: 'sequence',
    partOfSpeech: 'n.',
    meaningKo: '순서, 연속',
    ipa: '/ˈsiː.kwəns/',
    definition: 'a series of related things or events that follow an order',
    sentence: 'Arrange the story pictures in the correct chronological sequence today.',
    wordPromptScene: 'Numbered colorful puzzle blocks arranged in sequence one, two, three.',
    sentPromptScene: 'A student places comic story panels in correct narrative sequence on table.',
  },
  {
    word: 'blink',
    partOfSpeech: 'v.',
    meaningKo: '눈을 깜빡이다',
    ipa: '/blɪŋk/',
    definition: 'to open and close your eyes quickly once or repeatedly',
    sentence: 'The bright morning sunshine caused the sleepy owl to blink.',
    wordPromptScene: 'A cute cartoon owl blinking its big round eyes in sunlight.',
    sentPromptScene: 'A student steps outdoors and starts to blink against bright morning sunshine.',
  },
  {
    word: 'interfere',
    partOfSpeech: 'v.',
    meaningKo: '간섭하다, 방해하다',
    ipa: '/ˌɪn.t̬ɚˈfɪr/',
    definition: 'to get involved in a situation where you are not wanted',
    sentence: 'Loud background music can interfere with students trying to study.',
    wordPromptScene: 'Two radio wave signals overlapping with colorful static sound patterns.',
    sentPromptScene: 'A student closes the window so street noise will not interfere with reading.',
  },
  {
    word: 'identical',
    partOfSpeech: 'adj.',
    meaningKo: '동일한, 똑같은',
    ipa: '/aɪˈden.t̬ə.kəl/',
    definition: 'exactly the same in every detail, not different',
    sentence: 'The twin sisters wore identical blue sweaters to school today.',
    wordPromptScene: 'Two identical cartoon teddy bears sitting side by side on shelf.',
    sentPromptScene: 'Two identical crystal snowflakes are displayed under a microscope.',
  },
  {
    word: 'empathy',
    partOfSpeech: 'n.',
    meaningKo: '공감, 감정이입',
    ipa: '/ˈem.pə.θi/',
    definition: 'the ability to understand and share the feelings of another',
    sentence: 'Showing empathy helps build deep trust and kindness among friends.',
    wordPromptScene: 'Two glowing hearts connected by a warm rainbow bridge of light.',
    sentPromptScene: 'A student listens with empathy and comforts a friend who feels sad.',
  },
  {
    word: 'dramatic',
    partOfSpeech: 'adj.',
    meaningKo: '극적인, 인상적인',
    ipa: '/drəˈmæt̬.ɪk/',
    definition: 'very sudden, exciting, or noticeable in effect',
    sentence: 'The sunset created a dramatic display of crimson and purple clouds.',
    wordPromptScene: 'A sky filled with vibrant crimson, gold, and deep purple sunset hues.',
    sentPromptScene: 'The actor made a dramatic entrance onto the theater stage.',
  },
  {
    word: 'explicit',
    partOfSpeech: 'adj.',
    meaningKo: '명백한, 솔직한',
    ipa: '/ɪkˈsplɪs.ɪt/',
    definition: 'clear and exact, leaving no doubt about what is meant',
    sentence: 'The teacher gave explicit instructions for assembling the model spaceship.',
    wordPromptScene: 'A clear illustrated diagram with numbered step-by-step assembly arrows.',
    sentPromptScene: 'Students follow explicit safety rules before starting the chemistry laboratory.',
  },
  {
    word: 'tissue',
    partOfSpeech: 'n.',
    meaningKo: '조직, 화장지',
    ipa: '/ˈtɪʃ.uː/',
    definition: 'a group of connected cells in an animal or plant',
    sentence: 'Scientists examined muscle tissue under the high-power electronic microscope.',
    wordPromptScene: 'A box of soft white facial tissues with a gentle tissue popping out.',
    sentPromptScene: 'A student uses a clean tissue to wipe away watercolor paint spills.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 17, set: 1, wordsData: day17_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 17, set: 2, wordsData: day17_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 17, set: 3, wordsData: day17_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 17, set: 4, wordsData: day17_set4 });
  console.log('DAY 17 written successfully');
}

run();
