import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 19
// ==========================================
const day19_set1 = [
  {
    word: 'modern',
    partOfSpeech: 'adj.',
    meaningKo: '현대의, 현대적인',
    ipa: '/ˈmɑː.dɚn/',
    definition: 'relating to the present time and not to the past',
    sentence: 'The new school building has a modern science computer lab.',
    wordPromptScene: 'A sleek modern architecture library with floor-to-ceiling glass windows and solar panels.',
    sentPromptScene: 'Students work on modern tablet computers in a bright classroom.',
  },
  {
    word: 'mobile',
    partOfSpeech: 'adj.',
    meaningKo: '이동 가능한, 모바일의',
    ipa: '/ˈmoʊ.bəl/',
    definition: 'able to move or be moved easily and quickly',
    sentence: 'The city operates a mobile library bus to visit small villages.',
    wordPromptScene: 'A cheerful colorful library bus parked beside a village playground.',
    sentPromptScene: 'Children select books from the shelves inside a mobile library van.',
  },
  {
    word: 'function',
    partOfSpeech: 'n.',
    meaningKo: '기능, 작용',
    ipa: '/ˈfʌŋk.ʃən/',
    definition: 'the special purpose or activity for which a thing exists',
    sentence: 'The main function of a bicycle helmet is to protect head.',
    wordPromptScene: 'A cutaway diagram showing the safety padding function of a sports helmet.',
    sentPromptScene: 'A science teacher explains the important pumping function of heart.',
  },
  {
    word: 'machine',
    partOfSpeech: 'n.',
    meaningKo: '기계',
    ipa: '/məˈʃiːn/',
    definition: 'a piece of equipment with moving parts doing work',
    sentence: 'The robotic machine sorted plastic bottles into proper recycling bins.',
    wordPromptScene: 'A friendly blue robotic machine sorting colorful building blocks on a conveyor.',
    sentPromptScene: 'An engineer demonstrates a robotic machine to visiting school students.',
  },
  {
    word: 'repair',
    partOfSpeech: 'v.',
    meaningKo: '수리하다, 고치다',
    ipa: '/rɪˈper/',
    definition: 'to fix something that is broken, damaged, or not working',
    sentence: 'The mechanic used a wrench to repair the toy bicycle chain.',
    wordPromptScene: 'A shiny metal wrench tightening a gear on a bicycle wheel.',
    sentPromptScene: 'A student uses tools to repair a broken wooden toy cart.',
  },
  {
    word: 'efficient',
    partOfSpeech: 'adj.',
    meaningKo: '효율적인, 유능한',
    ipa: '/ɪˈfɪʃ.ənt/',
    definition: 'working well and not wasting time, energy, or money',
    sentence: 'Solar panels provide a clean and very efficient source of energy.',
    wordPromptScene: 'A gleaming solar panel absorbing bright golden sun rays efficiently.',
    sentPromptScene: 'An efficient robot vacuums the living room rug quickly and quietly.',
  },
  {
    word: 'install',
    partOfSpeech: 'v.',
    meaningKo: '설치하다, 장착하다',
    ipa: '/ɪnˈstɑːl/',
    definition: 'to put equipment or software in place ready for use',
    sentence: 'The technician helped install a new interactive whiteboard in our classroom.',
    wordPromptScene: 'A technician mounting a large digital smart screen on a clean wall.',
    sentPromptScene: 'A teacher turns on the new projector after technicians install it.',
  },
  {
    word: 'innovation',
    partOfSpeech: 'n.',
    meaningKo: '혁신, 획기적인 것',
    ipa: '/ˌɪn.əˈveɪ.ʃən/',
    definition: 'a new idea, method, or invention that brings positive change',
    sentence: 'Electric cars are an exciting green innovation for cleaner city air.',
    wordPromptScene: 'A glowing futuristic lightbulb sprouting green leaves and tech circuits.',
    sentPromptScene: 'Students showcase their clean water filtration innovation at the science fair.',
  },
  {
    word: 'trust',
    partOfSpeech: 'n.',
    meaningKo: '신뢰, 믿음',
    ipa: '/trʌst/',
    definition: 'the belief that someone is good, honest, and reliable',
    sentence: 'Honesty is the foundation of strong friendship and mutual trust.',
    wordPromptScene: 'Two friendly cartoon hands interlocking in a firm handshake of trust.',
    sentPromptScene: 'Teammates share a bond of trust as they pass the soccer ball.',
  },
  {
    word: 'truth',
    partOfSpeech: 'n.',
    meaningKo: '진실, 사실',
    ipa: '/truːθ/',
    definition: 'the real facts about a situation, not lies or fiction',
    sentence: 'It is always best to tell the truth with courage.',
    wordPromptScene: 'A glowing golden key opening a chest labeled Truth.',
    sentPromptScene: 'A brave child speaks the truth honestly to the school principal.',
  },
];

const day19_set2 = [
  {
    word: 'imagine',
    partOfSpeech: 'v.',
    meaningKo: '상상하다, 마음에 그리다',
    ipa: '/ɪˈmædʒ.ɪn/',
    definition: 'to form a mental picture or idea of something in your mind',
    sentence: 'Close your eyes and imagine flying across the starry blue sky.',
    wordPromptScene: 'A child floating on a fluffy cloud holding a magical glowing star.',
    sentPromptScene: 'Children close their eyes to imagine fantastic fairytale worlds during storytelling.',
  },
  {
    word: 'artificial',
    partOfSpeech: 'adj.',
    meaningKo: '인공의, 인조의',
    ipa: '/ˌɑːr.t̬əˈfɪʃ.əl/',
    definition: 'made by humans and not occurring naturally, imitation',
    sentence: 'The soccer field was covered with soft green artificial grass turf.',
    wordPromptScene: 'A vibrant artificial silk flower in a crystal glass vase.',
    sentPromptScene: 'Players practice kicks on the bright green artificial turf soccer field.',
  },
  {
    word: 'adjust',
    partOfSpeech: 'v.',
    meaningKo: '조정하다, 맞추다',
    ipa: '/əˈdʒʌst/',
    definition: 'to change something slightly to make it fit or work better',
    sentence: 'You can adjust the bicycle seat height to fit your legs.',
    wordPromptScene: 'A hand adjusting a bicycle seat quick-release clamp on frame.',
    sentPromptScene: 'A student uses a knob to adjust the microscope focus wheel.',
  },
  {
    word: 'ideal',
    partOfSpeech: 'adj.',
    meaningKo: '이상적인, 완벽한',
    ipa: '/aɪˈdiː.əl/',
    definition: 'perfect, or the best possible for a particular purpose',
    sentence: 'A warm sunny breeze made it an ideal day for sailing.',
    wordPromptScene: 'A picturesque sunny beach with calm turquoise waters and blue skies.',
    sentPromptScene: 'A peaceful park bench under a leafy oak provides an ideal reading spot.',
  },
  {
    word: 'gather',
    partOfSpeech: 'v.',
    meaningKo: '모으다, 모이다',
    ipa: '/ˈɡæð.ɚ/',
    definition: 'to come together in a group or collect things',
    sentence: 'Students gather in the school auditorium for the morning awards assembly.',
    wordPromptScene: 'A wicker basket full of freshly gathered golden chestnuts and pinecones.',
    sentPromptScene: 'Children gather around the library rug to hear an exciting story.',
  },
  {
    word: 'mechanic',
    partOfSpeech: 'n.',
    meaningKo: '정비사, 수리공',
    ipa: '/məˈkæn.ɪk/',
    definition: 'someone whose job is repairing machines and vehicle engines',
    sentence: 'The friendly mechanic inspected the brakes and tightened the bicycle chain.',
    wordPromptScene: 'A smiling cartoon mechanic holding a wrench beside a friendly car.',
    sentPromptScene: 'A mechanic explains how bicycle gears work to a curious young rider.',
  },
  {
    word: 'portable',
    partOfSpeech: 'adj.',
    meaningKo: '휴대용의, 들고 다닐 수 있는',
    ipa: '/ˈpɔːr.t̬ə.bəl/',
    definition: 'light and easy to carry or move from place to place',
    sentence: 'He brought a portable camp stove for our weekend forest trip.',
    wordPromptScene: 'A compact folding camping stool and miniature portable camp lantern.',
    sentPromptScene: 'Hikers boil water on a small portable gas stove at campsite.',
  },
  {
    word: 'remove',
    partOfSpeech: 'v.',
    meaningKo: '제거하다, 치우다',
    ipa: '/rɪˈmuːv/',
    definition: 'to take something away from a place or take off clothes',
    sentence: 'Please remove your wet boots before entering the clean living room.',
    wordPromptScene: 'A pair of muddy boots sitting neatly on a porch boot rack.',
    sentPromptScene: 'A boy pauses to remove his shoes before stepping onto the rug.',
  },
  {
    word: 'master',
    partOfSpeech: 'v.',
    meaningKo: '숙달하다, 통달하다',
    ipa: '/ˈmæs.tɚ/',
    definition: 'to learn how to do something extremely well through practice',
    sentence: 'With daily dedication, she was able to master the difficult cello piece.',
    wordPromptScene: 'A martial arts black belt tied neatly on a smooth wooden rack.',
    sentPromptScene: 'A student practices hard to master complex multiplication tables in math.',
  },
  {
    word: 'screen',
    partOfSpeech: 'n.',
    meaningKo: '화면, 스크린',
    ipa: '/skriːn/',
    definition: 'the flat glass surface on a computer or television showing images',
    sentence: 'The tablet screen displayed a colorful interactive map of world.',
    wordPromptScene: 'A tablet screen showing a vibrant illustrated 3D globe map.',
    sentPromptScene: 'Students touch the interactive display screen to solve an astronomy quiz.',
  },
];

const day19_set3 = [
  {
    word: 'widespread',
    partOfSpeech: 'adj.',
    meaningKo: '널리 퍼진, 광범위한',
    ipa: '/ˌwaɪdˈspred/',
    definition: 'existing or happening in many places among many people',
    sentence: 'The new recycling initiative received widespread support across our town.',
    wordPromptScene: 'A world map with glowing interconnected green recycling arrows worldwide.',
    sentPromptScene: 'Citizens show widespread enthusiasm for planting community flower gardens.',
  },
  {
    word: 'edge',
    partOfSpeech: 'n.',
    meaningKo: '가장자리, 모서리',
    ipa: '/edʒ/',
    definition: 'the outer point, boundary, or sharp border of something',
    sentence: 'Colorful wildflowers bloomed along the edge of the forest trail.',
    wordPromptScene: 'A smooth wooden table with a bevel rounded edge in sunlight.',
    sentPromptScene: 'Hikers walk safely along the wide grassy edge of the meadow.',
  },
  {
    word: 'remind',
    partOfSpeech: 'v.',
    meaningKo: '상기시키다, 일깨우다',
    ipa: '/rɪˈmaɪnd/',
    definition: 'to make someone remember something they must do',
    sentence: 'Post-it notes remind him to pack his library books every morning.',
    wordPromptScene: 'A bright yellow sticky note with a smiling star checklist on desk.',
    sentPromptScene: 'A digital calendar chime helps remind a student of piano practice.',
  },
  {
    word: 'acquire',
    partOfSpeech: 'v.',
    meaningKo: '습득하다, 획득하다',
    ipa: '/əˈkwaɪr/',
    definition: 'to gain something by your own ability or effort over time',
    sentence: 'Practice helps young students acquire great reading fluency and speed.',
    wordPromptScene: 'A glowing book surrounded by sparkling golden knowledge stars.',
    sentPromptScene: 'Through art classes, children acquire new watercolor painting skills with joy.',
  },
  {
    word: 'interact',
    partOfSpeech: 'v.',
    meaningKo: '상호작용하다, 소통하다',
    ipa: '/ˌɪn.t̬ɚˈækt/',
    definition: 'to communicate with or react to each other in an activity',
    sentence: 'Friendly dolphins love to interact with humans through playful clicks.',
    wordPromptScene: 'Two cute cartoon robots high-fiving with glowing blue digital signals.',
    sentPromptScene: 'Children interact happily with friendly farm animals at the petting zoo.',
  },
  {
    word: 'scatter',
    partOfSpeech: 'v.',
    meaningKo: '흩뿌리다, 흩어지다',
    ipa: '/ˈskæt̬.ɚ/',
    definition: 'to throw or drop things in different directions loosely',
    sentence: 'A gentle breeze helped scatter golden autumn leaves across the lawn.',
    wordPromptScene: 'Swirling colorful autumn leaves scattering across a sunny garden lawn.',
    sentPromptScene: 'A gardener tosses handfuls of wildflower seeds to scatter them evenly.',
  },
  {
    word: 'virtual',
    partOfSpeech: 'adj.',
    meaningKo: '가상의, 사실상의',
    ipa: '/ˈvɝː.tʃu.əl/',
    definition: 'created by computer technology and appearing to exist online',
    sentence: 'Students took an exciting virtual field trip to the deep ocean.',
    wordPromptScene: 'A modern VR headset displaying a colorful 3D coral reef scene.',
    sentPromptScene: 'Children wear lightweight headsets to explore a virtual solar system space museum.',
  },
  {
    word: 'convert',
    partOfSpeech: 'v.',
    meaningKo: '전환하다, 변환하다',
    ipa: '/kənˈvɝːt/',
    definition: 'to change the form, character, or function of something',
    sentence: 'Solar panels convert bright sunlight into clean usable electric energy.',
    wordPromptScene: 'A diagram showing sunbeams being converted into sparkling green electric power.',
    sentPromptScene: 'An engineer explains how wind turbines convert breeze into electricity.',
  },
  {
    word: 'ease',
    partOfSpeech: 'n.',
    meaningKo: '쉬움, 편안함',
    ipa: '/iːz/',
    definition: 'the state of experiencing no difficulty, effort, or pain',
    sentence: 'The experienced gymnast completed the difficult balance routine with ease.',
    wordPromptScene: 'A feather floating gracefully and effortlessly down onto a velvet pillow.',
    sentPromptScene: 'A skilled pianist plays a rapid musical scale with complete ease.',
  },
  {
    word: 'erase',
    partOfSpeech: 'v.',
    meaningKo: '지우다, 없애다',
    ipa: '/ɪˈreɪs/',
    definition: 'to remove writing or marks from paper or a board',
    sentence: 'Use a soft felt eraser to erase the chalk marks.',
    wordPromptScene: 'A pink pencil eraser cleanly wiping away a pencil graphite line.',
    sentPromptScene: 'A student uses a chalkboard felt eraser to erase math equations.',
  },
];

const day19_set4 = [
  {
    word: 'navigate',
    partOfSpeech: 'v.',
    meaningKo: '길을 찾다, 항해하다',
    ipa: '/ˈnæv.ə.ɡeɪt/',
    definition: 'to direct the course of a ship, vehicle, or path',
    sentence: 'Sailors use a brass compass to navigate safely across open seas.',
    wordPromptScene: 'A gleaming brass nautical compass resting on a parchment sea chart.',
    sentPromptScene: 'Hikers check a digital map on their phone to navigate the trail.',
  },
  {
    word: 'reproduce',
    partOfSpeech: 'v.',
    meaningKo: '복제하다, 번식하다',
    ipa: '/ˌriː.prəˈduːs/',
    definition: 'to produce a copy of something, or produce offspring',
    sentence: 'The modern color scanner can reproduce fine art prints with clarity.',
    wordPromptScene: 'A high-definition color scanner producing an exact duplicate of a painting.',
    sentPromptScene: 'An art student uses a printer to reproduce her original watercolor sketches.',
  },
  {
    word: 'differ',
    partOfSpeech: 'v.',
    meaningKo: '다르다, 의견이 맞지 않다',
    ipa: '/ˈdɪf.ɚ/',
    definition: 'to be not like something else in one or more ways',
    sentence: 'Butterfly wing patterns differ greatly between each colorful tropical species.',
    wordPromptScene: 'Two distinct tropical butterflies showing different vibrant geometric wing patterns.',
    sentPromptScene: 'Students observe how bird beaks differ to match their specific food.',
  },
  {
    word: 'instruction',
    partOfSpeech: 'n.',
    meaningKo: '설명, 지시, 교육',
    ipa: '/ɪnˈstrʌk.ʃən/',
    definition: 'detailed information telling you how to do or use something',
    sentence: 'Follow every clear safety instruction before beginning the laboratory experiment.',
    wordPromptScene: 'An illustrated instruction booklet showing clear step-by-step assembly diagrams.',
    sentPromptScene: 'A swimming coach gives clear instruction to students before water practice.',
  },
  {
    word: 'significant',
    partOfSpeech: 'adj.',
    meaningKo: '중요한, 상당한',
    ipa: '/sɪɡˈnɪf.ə.kənt/',
    definition: 'important, noticeable, or having a major effect on things',
    sentence: 'The discovery of penicillin was a significant breakthrough in modern medicine.',
    wordPromptScene: 'A gold star shining brilliantly atop a milestone stone marker.',
    sentPromptScene: 'Scientists celebrate a significant discovery in clean solar energy technology.',
  },
  {
    word: 'satellite',
    partOfSpeech: 'n.',
    meaningKo: '위성, 인공위성',
    ipa: '/ˈsæt̬.əl.aɪt/',
    definition: 'an artificial body placed in orbit around the earth or moon',
    sentence: 'A weather satellite sends accurate cloud pictures from space to Earth.',
    wordPromptScene: 'A solar-powered space satellite orbiting peacefully above blue planet Earth.',
    sentPromptScene: 'An astronomer explains how a communication satellite orbits high in space.',
  },
  {
    word: 'demonstrate',
    partOfSpeech: 'v.',
    meaningKo: '시연하다, 입증하다',
    ipa: '/ˈdem.ən.streɪt/',
    definition: 'to show clearly how something works or is done',
    sentence: 'The chef will demonstrate how to knead fresh pizza dough.',
    wordPromptScene: 'A smiling baker expertly rolling pizza dough on a floury board.',
    sentPromptScene: 'A science teacher uses a prism to demonstrate how light splits colors.',
  },
  {
    word: 'emerge',
    partOfSpeech: 'v.',
    meaningKo: '나타나다, 부상하다',
    ipa: '/ɪˈmɝːdʒ/',
    definition: 'to come out into view from a hidden or dark place',
    sentence: 'A colorful butterfly began to emerge from its green silk cocoon.',
    wordPromptScene: 'A vibrant monarch butterfly emerging gracefully from a green chrysalis.',
    sentPromptScene: 'The morning sun starts to emerge above mist-covered mountain pine ridges.',
  },
  {
    word: 'trigger',
    partOfSpeech: 'v.',
    meaningKo: '촉발하다, 유발하다',
    ipa: '/ˈtrɪɡ.ɚ/',
    definition: 'to cause an event, process, or reaction to start happening',
    sentence: 'Pushing the red button will trigger the celebratory confetti explosion.',
    wordPromptScene: 'A line of colorful dominoes where tipping one triggers the whole chain.',
    sentPromptScene: 'A smiling scientist flips a switch to trigger the robotic demo.',
  },
  {
    word: 'current',
    partOfSpeech: 'adj.',
    meaningKo: '현재의, 흐름',
    ipa: '/ˈkɝː.ənt/',
    definition: 'happening or existing now, or a flow of electricity/water',
    sentence: 'Our current science project focuses on protecting endangered coral reefs.',
    wordPromptScene: 'A daily newspaper displaying Today’s News beside a glowing digital tablet.',
    sentPromptScene: 'Students discuss their current science assignment in small library groups.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 19, set: 1, wordsData: day19_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 19, set: 2, wordsData: day19_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 19, set: 3, wordsData: day19_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 19, set: 4, wordsData: day19_set4 });
  console.log('DAY 19 written successfully');
}

run();
