import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 10
// ==========================================
const day10_set1 = [
  {
    word: 'welfare',
    partOfSpeech: 'n.',
    meaningKo: '복지, 안녕',
    ipa: '/ˈwel.fer/',
    definition: 'the health, happiness, and fortunes of a person or group',
    sentence: 'The community center works hard for the welfare of all residents.',
    wordPromptScene: 'A sunny community garden with smiling families watering green plants.',
    sentPromptScene: 'Volunteers build wooden benches for the welfare of park visitors.',
  },
  {
    word: 'victim',
    partOfSpeech: 'n.',
    meaningKo: '피해자, 희생자',
    ipa: '/ˈvɪk.tɪm/',
    definition: 'a person harmed, injured, or who suffered a trick in game',
    sentence: 'He was the funny victim of his sister’s April Fools joke.',
    wordPromptScene: 'A friendly cartoon whoopee cushion with cheerful colorful prank confetti.',
    sentPromptScene: 'A laughing boy realizes he is the friendly victim of a magic trick.',
  },
  {
    word: 'population',
    partOfSpeech: 'n.',
    meaningKo: '인구, 개체 수',
    ipa: '/ˌpɑː.pjəˈleɪ.ʃən/',
    definition: 'all the people living in a particular area or country',
    sentence: 'The city has a growing population of over one million residents.',
    wordPromptScene: 'A miniature bustling cartoon city with tiny colorful cars and houses.',
    sentPromptScene: 'Scientists study the healthy fish population swimming in the coral reef.',
  },
  {
    word: 'neighbor',
    partOfSpeech: 'n.',
    meaningKo: '이웃',
    ipa: '/ˈneɪ.bɚ/',
    definition: 'someone who lives next door or near your home',
    sentence: 'Our kind neighbor brought us a basket of freshly picked peaches.',
    wordPromptScene: 'Two cozy suburban houses separated by a low white picket fence.',
    sentPromptScene: 'A smiling neighbor waves across the garden fence with fresh fruit.',
  },
  {
    word: 'ignore',
    partOfSpeech: 'v.',
    meaningKo: '무시하다, 신경 쓰지 않다',
    ipa: '/ɪɡˈnɔːr/',
    definition: 'to pay no attention to someone or something',
    sentence: 'Try to ignore the noisy traffic and focus on your reading.',
    wordPromptScene: 'A cartoon cat sleeping peacefully wearing noise-canceling headphones.',
    sentPromptScene: 'A focused student learns to ignore outside distractions while studying.',
  },
  {
    word: 'donate',
    partOfSpeech: 'v.',
    meaningKo: '기부하다, 기증하다',
    ipa: '/ˈdoʊ.neɪt/',
    definition: 'to give money, food, or clothes to help people in need',
    sentence: 'Students love to donate old warm clothes to the winter shelter.',
    wordPromptScene: 'A wooden donation box with a heart slot receiving folded winter jackets.',
    sentPromptScene: 'Children carry boxes of toys to donate to the community center.',
  },
  {
    word: 'serious',
    partOfSpeech: 'adj.',
    meaningKo: '진지한, 심각한',
    ipa: '/ˈsɪr.i.əs/',
    definition: 'thinking carefully and not joking or making fun',
    sentence: 'The doctor gave serious attention to every patient in the clinic.',
    wordPromptScene: 'A cartoon owl wearing small spectacles and reading a thick ledger book.',
    sentPromptScene: 'A student has a serious look while concentrating on an important chess move.',
  },
  {
    word: 'fund',
    partOfSpeech: 'n.',
    meaningKo: '기금, 자금',
    ipa: '/fʌnd/',
    definition: 'an amount of money saved or collected for a particular purpose',
    sentence: 'Our bake sale created a fund to buy new soccer balls.',
    wordPromptScene: 'A clear glass savings jar labeled School Sports filled with coins.',
    sentPromptScene: 'Students count coins collected for the park playground renewal fund.',
  },
  {
    word: 'personal',
    partOfSpeech: 'adj.',
    meaningKo: '개인의, 사적인',
    ipa: '/ˈpɝː.sən.əl/',
    definition: 'belonging to or connected with one particular person only',
    sentence: 'She wrote her secret recipe in a small personal notebook today.',
    wordPromptScene: 'A locked colorful diary with a tiny golden heart padlock.',
    sentPromptScene: 'A student keeps personal sketches inside a private zippered art folder.',
  },
  {
    word: 'personnel',
    partOfSpeech: 'n.',
    meaningKo: '직원들, 인원',
    ipa: '/ˌpɝː.sənˈel/',
    definition: 'the people who work for an organization or business',
    sentence: 'Medical personnel arrived quickly at the park to help the runner.',
    wordPromptScene: 'A team of diverse friendly doctors and nurses wearing neat scrubs.',
    sentPromptScene: 'Airport security personnel assist travelers at the boarding gate counter.',
  },
];

const day10_set2 = [
  {
    word: 'half',
    partOfSpeech: 'n.',
    meaningKo: '절반, 반',
    ipa: '/hæf/',
    definition: 'one of two equal parts that together make a whole',
    sentence: 'He gave half of his fresh sandwich to his hungry friend.',
    wordPromptScene: 'A juicy orange sliced neatly into two identical half pieces.',
    sentPromptScene: 'A boy cuts an apple in half to share with his sister.',
  },
  {
    word: 'concern',
    partOfSpeech: 'n.',
    meaningKo: '걱정, 염려, 관심사',
    ipa: '/kənˈsɝːn/',
    definition: 'a feeling of worry about something or a matter of interest',
    sentence: 'Clean drinking water is a major concern for all island residents.',
    wordPromptScene: 'A glowing shield protecting a pure crystal drop of clean water.',
    sentPromptScene: 'Neighbors discuss their shared concern about traffic safety near the school.',
  },
  {
    word: 'rescue',
    partOfSpeech: 'v.',
    meaningKo: '구조하다, 구출하다',
    ipa: '/ˈres.kjuː/',
    definition: 'to save someone from a dangerous or unpleasant situation',
    sentence: 'Firefighters climbed the tall ladder to rescue a stranded kitten safely.',
    wordPromptScene: 'A bright red life preserver ring floating on calm ocean water.',
    sentPromptScene: 'A friendly firefighter climbs up a ladder to rescue a kitten.',
  },
  {
    word: 'critic',
    partOfSpeech: 'n.',
    meaningKo: '비평가, 평론가',
    ipa: '/ˈkrɪt.ɪk/',
    definition: 'a person whose job is giving opinions about books, movies, or food',
    sentence: 'The food critic praised the bakery for its delicious warm croissants.',
    wordPromptScene: 'A magnifying glass examining a five-star rated restaurant dish on table.',
    sentPromptScene: 'A book critic writes a positive review in a literary magazine.',
  },
  {
    word: 'charity',
    partOfSpeech: 'n.',
    meaningKo: '자선 단체, 자선',
    ipa: '/ˈtʃer.ə.t̬i/',
    definition: 'an organization giving money, food, or help to people in need',
    sentence: 'Our school donated winter blankets to a local animal charity today.',
    wordPromptScene: 'Two cartoon hands lifting a glowing golden heart with wings.',
    sentPromptScene: 'Students organize a car wash to raise money for a children’s charity.',
  },
  {
    word: 'rage',
    partOfSpeech: 'n.',
    meaningKo: '격노, 맹렬함',
    ipa: '/reɪdʒ/',
    definition: 'extreme anger or intense wild energy in nature',
    sentence: 'The wild storm blew with tremendous rage against the coastal cliffs.',
    wordPromptScene: 'A cartoon storm cloud blowing wind with funny puffed-out red cheeks.',
    sentPromptScene: 'Ocean waves crash against rocks during the rage of a winter gale.',
  },
  {
    word: 'afford',
    partOfSpeech: 'v.',
    meaningKo: '~할 여유가 있다',
    ipa: '/əˈfɔːrd/',
    definition: 'to have enough money or time to buy or do something',
    sentence: 'He saved his pocket money to afford a new bicycle helmet.',
    wordPromptScene: 'A piggy bank filled with coins beside a shiny new bicycle.',
    sentPromptScene: 'A boy counts his saved coins to afford a new skateboard.',
  },
  {
    word: 'unite',
    partOfSpeech: 'v.',
    meaningKo: '결합하다, 단결하다',
    ipa: '/juːˈnaɪt/',
    definition: 'to join together as a group to achieve a common goal',
    sentence: 'Citizens unite to clean up the neighborhood park every single spring.',
    wordPromptScene: 'Multiple hands of different colors holding together firmly in center.',
    sentPromptScene: 'Neighbors unite to plant a blooming flower garden along the roadside.',
  },
  {
    word: 'orphan',
    partOfSpeech: 'n.',
    meaningKo: '고아, 어미 잃은 동물',
    ipa: '/ˈɔːr.fən/',
    definition: 'a child or young animal whose parents have died',
    sentence: 'The wildlife rescue center looked after the sweet orphan bear cub.',
    wordPromptScene: 'A baby deer resting safely inside a warm cozy straw barn.',
    sentPromptScene: 'A veterinarian bottle-feeds an orphan puppy at the wildlife rescue center.',
  },
  {
    word: 'bear',
    partOfSpeech: 'v.',
    meaningKo: '견디다, 참다, 낳다',
    ipa: '/ber/',
    definition: 'to accept, tolerate, or endure something unpleasant',
    sentence: 'The brave little sled dog can bear freezing arctic temperatures easily.',
    wordPromptScene: 'A sturdy cartoon husky dog wearing a warm knitted winter scarf.',
    sentPromptScene: 'Hikers wear thick thermal coats to bear the chilly mountain wind.',
  },
];

const day10_set3 = [
  {
    word: 'abandon',
    partOfSpeech: 'v.',
    meaningKo: '버리다, 떠나다',
    ipa: '/əˈbæn.dən/',
    definition: 'to leave a place, thing, or person forever',
    sentence: 'Sailors had to abandon the sinking toy raft in the pond.',
    wordPromptScene: 'An ancient moss-covered wooden rowboat resting peacefully on a grassy lakeside.',
    sentPromptScene: 'Explorers discover an old wooden cabin that travelers had to abandon.',
  },
  {
    word: 'crash',
    partOfSpeech: 'v.',
    meaningKo: '충돌하다, 부딪히다',
    ipa: '/kræʃ/',
    definition: 'to hit something violently, making a loud noise',
    sentence: 'Huge ocean waves crash against the rocky sea cliffs all night.',
    wordPromptScene: 'Two colorful toy bumper cars bumping gently together with foam stars.',
    sentPromptScene: 'Foamy white ocean waves crash dramatically against huge dark coastal boulders.',
  },
  {
    word: 'promote',
    partOfSpeech: 'v.',
    meaningKo: '홍보하다, 증진하다',
    ipa: '/prəˈmoʊt/',
    definition: 'to encourage people to like, buy, or use something',
    sentence: 'Posters around the school promote healthy eating and drinking clean water.',
    wordPromptScene: 'A colorful banner reading Healthy Habits surrounded by fresh green fruits.',
    sentPromptScene: 'Students hang illustrated posters to promote recycling throughout the school hallway.',
  },
  {
    word: 'decade',
    partOfSpeech: 'n.',
    meaningKo: '10년, 10년간',
    ipa: '/ˈdek.eɪd/',
    definition: 'a period of ten consecutive years',
    sentence: 'The old oak tree grew thirty feet taller in just one decade.',
    wordPromptScene: 'A calendar showing ten consecutive year dates marked with golden laurels.',
    sentPromptScene: 'A grandfather shows photos of the town from the previous decade.',
  },
  {
    word: 'establish',
    partOfSpeech: 'v.',
    meaningKo: '설립하다, 확립하다',
    ipa: '/ɪˈstæb.lɪʃ/',
    definition: 'to start an organization, school, or system that will continue',
    sentence: 'The town decided to establish a new science center for children.',
    wordPromptScene: 'A foundation stone being laid for a modern community library building.',
    sentPromptScene: 'Town leaders cut a ribbon to establish a new public botanical garden.',
  },
  {
    word: 'burden',
    partOfSpeech: 'n.',
    meaningKo: '짐, 부담',
    ipa: '/ˈbɝː.dən/',
    definition: 'something heavy that is carried or a difficult duty',
    sentence: 'Sharing the heavy backpack helped lighten the burden for the hiker.',
    wordPromptScene: 'A cheerful cartoon donkey carrying two balanced colorful saddle baskets.',
    sentPromptScene: 'Two friends carry a heavy trunk together to ease the burden.',
  },
  {
    word: 'assist',
    partOfSpeech: 'v.',
    meaningKo: '돕다, 거들다',
    ipa: '/əˈsɪst/',
    definition: 'to help someone to do something or achieve a result',
    sentence: 'Older students assist younger kids with tying their ice skate laces.',
    wordPromptScene: 'Two cartoon hands helping a little character climb up a small step.',
    sentPromptScene: 'A kind volunteer reaches out to assist an elderly person crossing street.',
  },
  {
    word: 'resolve',
    partOfSpeech: 'v.',
    meaningKo: '해결하다, 결심하다',
    ipa: '/rɪˈzɑːlv/',
    definition: 'to find an acceptable solution to a problem or argument',
    sentence: 'The two friends talked calmly to resolve their small disagreement quickly.',
    wordPromptScene: 'A tangled string being smoothed into a neat, straight glowing line.',
    sentPromptScene: 'Classmates sit at a peace table to resolve their playground dispute.',
  },
  {
    word: 'detect',
    partOfSpeech: 'v.',
    meaningKo: '감지하다, 발견하다',
    ipa: '/dɪˈtekt/',
    definition: 'to discover or notice something, especially something difficult to see',
    sentence: 'The rescue dog can detect faint scents from very far away.',
    wordPromptScene: 'A metal detector with glowing detection signal rings over soft sandy ground.',
    sentPromptScene: 'A trained search dog sniffs the ground to detect hidden treats.',
  },
  {
    word: 'defeat',
    partOfSpeech: 'v.',
    meaningKo: '패배시키다, 이기다',
    ipa: '/dɪˈfiːt/',
    definition: 'to win a victory over someone in a game or fight',
    sentence: 'Our chess champion managed to defeat the grandmaster in ten moves.',
    wordPromptScene: 'A gold chess king standing victorious next to a fallen wooden piece.',
    sentPromptScene: 'A board game player moves a piece to defeat opponent in game.',
  },
];

const day10_set4 = [
  {
    word: 'capture',
    partOfSpeech: 'v.',
    meaningKo: '포착하다, 사로잡다',
    ipa: '/ˈkæp.tʃɚ/',
    definition: 'to take someone prisoner or catch something successfully in camera',
    sentence: 'The photographer was able to capture the flying eagle on camera.',
    wordPromptScene: 'A camera viewfinder framing a soaring golden eagle in mid flight.',
    sentPromptScene: 'A photographer clicks the shutter to capture a magnificent waterfall scene.',
  },
  {
    word: 'perspective',
    partOfSpeech: 'n.',
    meaningKo: '관점, 시각, 원근법',
    ipa: '/pɚˈspek.tɪv/',
    definition: 'a particular way of viewing or considering things and events',
    sentence: 'Viewing the world from a mountaintop gives a whole new perspective.',
    wordPromptScene: 'A perspective drawing grid leading towards a single glowing vanishing point.',
    sentPromptScene: 'A student looks at Earth globe models to gain a global perspective.',
  },
  {
    word: 'desperate',
    partOfSpeech: 'adj.',
    meaningKo: '필사적인, 절망적인',
    ipa: '/ˈdes.pɚ.ət/',
    definition: 'feeling a strong need or willing to do anything to succeed',
    sentence: 'The thirsty desert traveler was desperate for a cool sip of water.',
    wordPromptScene: 'A green oasis with a freshwater pond surrounded by desert sand dunes.',
    sentPromptScene: 'A runner makes a desperate final sprint toward the soccer ball.',
  },
  {
    word: 'apparent',
    partOfSpeech: 'adj.',
    meaningKo: '명백한, 분명한',
    ipa: '/əˈper.ənt/',
    definition: 'easy to see, recognize, or understand clearly',
    sentence: 'It was apparent that the sunny day was perfect for sailing.',
    wordPromptScene: 'A magnifying glass revealing crystal clear footprints on a sunny sandy path.',
    sentPromptScene: 'The joy on the child’s face made his happiness completely apparent.',
  },
  {
    word: 'contradict',
    partOfSpeech: 'v.',
    meaningKo: '모순되다, 반박하다',
    ipa: '/ˌkɑːn.trəˈdɪkt/',
    definition: 'to say the opposite of what someone else has said',
    sentence: 'The witness statements contradict each other about the color of car.',
    wordPromptScene: 'Two arrows pointing in direct opposite directions with question marks.',
    sentPromptScene: 'New scientific facts contradict old myths about weather formation in books.',
  },
  {
    word: 'aggressive',
    partOfSpeech: 'adj.',
    meaningKo: '공격적인, 적극적인',
    ipa: '/əˈɡres.ɪv/',
    definition: 'behaving in an angry, forceful, or very energetic way',
    sentence: 'The coach praised the soccer team for their aggressive offensive plays.',
    wordPromptScene: 'A cartoon ram with sturdy curled horns standing determined on a hill.',
    sentPromptScene: 'A soccer forward makes an aggressive sprint to score a goal.',
  },
  {
    word: 'companion',
    partOfSpeech: 'n.',
    meaningKo: '동반자, 동행',
    ipa: '/kəmˈpæn.jən/',
    definition: 'a person or animal with whom you spend a lot of time',
    sentence: 'The loyal golden retriever was his favorite travel companion on hikes.',
    wordPromptScene: 'A friendly cartoon dog and hiker walking side by side on trail.',
    sentPromptScene: 'A boy walks along the meadow with his loyal dog companion.',
  },
  {
    word: 'compromise',
    partOfSpeech: 'n.',
    meaningKo: '타협, 절충',
    ipa: '/ˈkɑːm.prə.maɪz/',
    definition: 'an agreement in which both sides reduce their demands slightly',
    sentence: 'The two siblings reached a fair compromise over sharing the bicycle.',
    wordPromptScene: 'Two puzzle pieces clicking together with a glowing handshake symbol above.',
    sentPromptScene: 'Children shake hands after reaching a compromise on which game to play.',
  },
  {
    word: 'commitment',
    partOfSpeech: 'n.',
    meaningKo: '헌신, 전념, 약속',
    ipa: '/kəˈmɪt.mənt/',
    definition: 'a willingness to give your time and energy to a job',
    sentence: 'Playing for the school orchestra requires serious daily practice commitment.',
    wordPromptScene: 'A musical note surrounded by a golden ribbon and star of dedication.',
    sentPromptScene: 'A violinist shows dedication and commitment during long orchestra practice sessions.',
  },
  {
    word: 'stock',
    partOfSpeech: 'n.',
    meaningKo: '재고, 주식',
    ipa: '/stɑːk/',
    definition: 'a supply of goods kept on hand for sale or use',
    sentence: 'The toy store has a large stock of teddy bears today.',
    wordPromptScene: 'Warehouse shelves filled with neatly labeled wooden crates and cardboard boxes.',
    sentPromptScene: 'A shopkeeper checks the stock of art supplies on wooden shelves.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 10, set: 1, wordsData: day10_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 10, set: 2, wordsData: day10_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 10, set: 3, wordsData: day10_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 10, set: 4, wordsData: day10_set4 });
  console.log('DAY 10 written successfully');
}

run();
