import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 07
// ==========================================
const day07_set1 = [
  {
    word: 'similar',
    partOfSpeech: 'adj.',
    meaningKo: '비슷한, 유사한',
    ipa: '/ˈsɪm.ə.lɚ/',
    definition: 'looking or being almost the same as something else',
    sentence: 'The twin kittens have very similar white paws and fur.',
    wordPromptScene: 'Two cute cartoon kittens sitting side by side with identical markings.',
    sentPromptScene: 'Two friends compare their similar drawings of a space rocket.',
  },
  {
    word: 'situation',
    partOfSpeech: 'n.',
    meaningKo: '상황, 처지',
    ipa: '/ˌsɪtʃ.uˈeɪ.ʃən/',
    definition: 'the set of things happening at a particular time',
    sentence: 'The calm captain handled the tricky weather situation with skill.',
    wordPromptScene: 'A lighthouse shining light across foggy waters guiding a small boat.',
    sentPromptScene: 'The scout leader calmly explains the situation to the group.',
  },
  {
    word: 'related',
    partOfSpeech: 'adj.',
    meaningKo: '관련된, 친척의',
    ipa: '/rɪˈleɪ.t̬ɪd/',
    definition: 'connected by a reason or belonging to same family',
    sentence: 'Lions and tigers are closely related large wild cat species.',
    wordPromptScene: 'A family tree diagram with colorful connecting branches and leaves.',
    sentPromptScene: 'A biology teacher explains how dogs and wolves are related animals.',
  },
  {
    word: 'suppose',
    partOfSpeech: 'v.',
    meaningKo: '생각하다, 가정하다',
    ipa: '/səˈpoʊz/',
    definition: 'to think that something is likely to be true',
    sentence: 'I suppose we should leave early to catch the train.',
    wordPromptScene: 'A cartoon character tapping chin with a thoughtful expression.',
    sentPromptScene: 'A boy checks the clock and begins to suppose it is time.',
  },
  {
    word: 'social',
    partOfSpeech: 'adj.',
    meaningKo: '사회의, 사교적인',
    ipa: '/ˈsoʊ.ʃəl/',
    definition: 'relating to society or enjoying being with other people',
    sentence: 'Dolphins are very social animals that love swimming in pods.',
    wordPromptScene: 'A group of diverse cartoon characters chatting happily together.',
    sentPromptScene: 'Friendly dolphins swim together in a joyful social ocean group.',
  },
  {
    word: 'unique',
    partOfSpeech: 'adj.',
    meaningKo: '독특한, 유일한',
    ipa: '/juːˈniːk/',
    definition: 'being the only one of its kind or unusual',
    sentence: 'Every tiny crystal snowflake has a completely unique geometric pattern.',
    wordPromptScene: 'A single glowing purple crystal surrounded by ordinary grey stones.',
    sentPromptScene: 'A child examines a unique snowflake through a clear magnifying glass.',
  },
  {
    word: 'prefer',
    partOfSpeech: 'v.',
    meaningKo: '더 좋아하다, 선호하다',
    ipa: '/prɪˈfɝː/',
    definition: 'to like one person or thing more than another',
    sentence: 'Many students prefer warm hot chocolate over cold fruit punch.',
    wordPromptScene: 'A cartoon hand choosing a red apple over a green one.',
    sentPromptScene: 'A girl smiles as she will prefer reading books outdoors.',
  },
  {
    word: 'remain',
    partOfSpeech: 'v.',
    meaningKo: '남아 있다, 머무르다',
    ipa: '/rɪˈmeɪn/',
    definition: 'to stay in the same place or condition',
    sentence: 'Please remain seated until the school bus comes to stop.',
    wordPromptScene: 'A loyal cartoon dog sitting obediently beside a park bench.',
    sentPromptScene: 'Passengers remain in their seats until the yellow bus stops completely.',
  },
  {
    word: 'distract',
    partOfSpeech: 'v.',
    meaningKo: '집중을 방해하다',
    ipa: '/dɪˈstrækt/',
    definition: 'to take someone’s attention away from what they do',
    sentence: 'Loud smartphone notifications can distract students during homework study time.',
    wordPromptScene: 'A buzzing cartoon fly hovering near a student trying to study.',
    sentPromptScene: 'A fluttering butterfly does not distract the focused young painter.',
  },
  {
    word: 'district',
    partOfSpeech: 'n.',
    meaningKo: '구역, 지역',
    ipa: '/ˈdɪs.trɪkt/',
    definition: 'an area of a town or country with particular characteristics',
    sentence: 'They visited the historic shopping district with brick cobblestone streets.',
    wordPromptScene: 'A colorful city map highlighting a specific neighborhood area block.',
    sentPromptScene: 'Tourists walk along the historic arts district looking at sculptures.',
  },
];

const day07_set2 = [
  {
    word: 'apologize',
    partOfSpeech: 'v.',
    meaningKo: '사과하다',
    ipa: '/əˈpɑː.lə.dʒaɪz/',
    definition: 'to say sorry for doing something wrong or hurtful',
    sentence: 'It is always polite to apologize when you bump someone.',
    wordPromptScene: 'A handwritten card saying Sorry with a tiny yellow daisy.',
    sentPromptScene: 'A polite student stops to apologize after dropping a classmate’s pencil.',
  },
  {
    word: 'refer',
    partOfSpeech: 'v.',
    meaningKo: '참조하다, 언급하다',
    ipa: '/rɪˈfɝː/',
    definition: 'to look at a book or person for information',
    sentence: 'You can refer to the glossary for difficult science words.',
    wordPromptScene: 'An open encyclopedia with a glowing index finger pointing to words.',
    sentPromptScene: 'A student looks at a chart to refer to correct dates.',
  },
  {
    word: 'colleague',
    partOfSpeech: 'n.',
    meaningKo: '동료',
    ipa: '/ˈkɑː.liːɡ/',
    definition: 'one of a group of people who work together',
    sentence: 'She discussed the lesson plan with her helpful teaching colleague.',
    wordPromptScene: 'Two professional cartoon characters working side by side at desks.',
    sentPromptScene: 'A teacher reviews a science project with an experienced school colleague.',
  },
  {
    word: 'rely',
    partOfSpeech: 'v.',
    meaningKo: '의지하다, 믿다',
    ipa: '/rɪˈlaɪ/',
    definition: 'to need or depend on someone or something',
    sentence: 'Baby birds rely on their parents for daily food supplies.',
    wordPromptScene: 'A sturdy walking cane supporting a friendly cartoon hiker.',
    sentPromptScene: 'Team members rely on each other to win the relay race.',
  },
  {
    word: 'mistake',
    partOfSpeech: 'n.',
    meaningKo: '실수, 잘못',
    ipa: '/mɪˈsteɪk/',
    definition: 'an action, decision, or judgment that produces incorrect results',
    sentence: 'He used an eraser to fix a small spelling mistake.',
    wordPromptScene: 'A pink rubber eraser cleanly wiping away a pencil smudge.',
    sentPromptScene: 'A student uses an eraser to correct a math mistake carefully.',
  },
  {
    word: 'request',
    partOfSpeech: 'n.',
    meaningKo: '요청, 신청',
    ipa: '/rɪˈkwest/',
    definition: 'an act of politely asking for something',
    sentence: 'The librarian approved his request for a new astronomy book.',
    wordPromptScene: 'A neat request form with a polite green stamped seal.',
    sentPromptScene: 'A student submits a book request slip at the library counter.',
  },
  {
    word: 'assume',
    partOfSpeech: 'v.',
    meaningKo: '추정하다, 생각하다',
    ipa: '/əˈsuːm/',
    definition: 'to accept something as true without having proof',
    sentence: 'Do not assume a test is easy without studying hard.',
    wordPromptScene: 'A cartoon detective looking at footprints with a magnifying glass.',
    sentPromptScene: 'A student checks facts so she does not assume false answers.',
  },
  {
    word: 'refuse',
    partOfSpeech: 'v.',
    meaningKo: '거절하다',
    ipa: '/rɪˈfjuːz/',
    definition: 'to state firmly that you will not do or accept',
    sentence: 'The strict guard had to refuse entry without a pass.',
    wordPromptScene: 'A friendly cartoon palm making a gentle polite stop gesture.',
    sentPromptScene: 'A student will refuse junk food and choose fresh green apples.',
  },
  {
    word: 'reply',
    partOfSpeech: 'v.',
    meaningKo: '대답하다, 답장하다',
    ipa: '/rɪˈplaɪ/',
    definition: 'to answer someone by words or writing back',
    sentence: 'She sat down to reply to her friend’s birthday invitation.',
    wordPromptScene: 'A paper airplane letter carrying a heart flying across blue sky.',
    sentPromptScene: 'A happy girl writes on stationery to reply to pen pal.',
  },
  {
    word: 'degree',
    partOfSpeech: 'n.',
    meaningKo: '도(단위), 정도, 학위',
    ipa: '/dɪˈɡriː/',
    definition: 'a unit for measuring temperature or angles',
    sentence: 'The thermometer showed twenty degree Celsius on a warm morning.',
    wordPromptScene: 'A glass outdoor thermometer displaying temperature marks and degree symbols.',
    sentPromptScene: 'A student reads the outdoor temperature degree on a garden thermometer.',
  },
];

const day07_set3 = [
  {
    word: 'capacity',
    partOfSpeech: 'n.',
    meaningKo: '수용력, 용량',
    ipa: '/kəˈpæs.ə.t̬i/',
    definition: 'the total amount that can be contained inside something',
    sentence: 'The stadium was filled to its maximum seating capacity today.',
    wordPromptScene: 'A clear measuring cup filled with water to the top mark.',
    sentPromptScene: 'Fans fill a basketball hall to full capacity for final game.',
  },
  {
    word: 'passion',
    partOfSpeech: 'n.',
    meaningKo: '열정',
    ipa: '/ˈpæʃ.ən/',
    definition: 'a very powerful feeling of excitement and love for something',
    sentence: 'She plays the grand piano with true artistry and passion.',
    wordPromptScene: 'A glowing heart surrounded by musical notes and bright sparkles.',
    sentPromptScene: 'A young pianist plays a classical song with visible passion.',
  },
  {
    word: 'surround',
    partOfSpeech: 'v.',
    meaningKo: '둘러싸다, 에워싸다',
    ipa: '/səˈraʊnd/',
    definition: 'to be on all sides of someone or something',
    sentence: 'Tall green pine trees surround the quiet mountain lake completely.',
    wordPromptScene: 'A small blue lake encircled neatly by a ring of pines.',
    sentPromptScene: 'Friendly children surround the camp storyteller around the crackling campfire.',
  },
  {
    word: 'indeed',
    partOfSpeech: 'adv.',
    meaningKo: '정말로, 참으로',
    ipa: '/ɪnˈdiːd/',
    definition: 'used to emphasize a statement or confirm the truth',
    sentence: 'The mountain view was indeed as breathtaking as people described.',
    wordPromptScene: 'A golden seal stamp with a double exclamation mark of confirmation.',
    sentPromptScene: 'Hikers agree that the waterfall is indeed magnificent from the bridge.',
  },
  {
    word: 'imitate',
    partOfSpeech: 'v.',
    meaningKo: '모방하다, 흉내 내다',
    ipa: '/ˈɪm.ə.teɪt/',
    definition: 'to copy someone’s speech or behavior closely',
    sentence: 'The clever parrot learned how to imitate human greeting sounds.',
    wordPromptScene: 'A colorful cartoon parrot speaking into a tiny toy microphone.',
    sentPromptScene: 'A green parrot tries to imitate a boy whistling a tune.',
  },
  {
    word: 'bond',
    partOfSpeech: 'n.',
    meaningKo: '유대, 결속',
    ipa: '/bɑːnd/',
    definition: 'a close connection joining two or more people together',
    sentence: 'Playing sports together created a strong friendship bond among teammates.',
    wordPromptScene: 'Two interlocking golden chain links shining with warm friendly light.',
    sentPromptScene: 'Teammates hug and celebrate their strong bond after the soccer match.',
  },
  {
    word: 'obtain',
    partOfSpeech: 'v.',
    meaningKo: '얻다, 획득하다',
    ipa: '/əbˈteɪn/',
    definition: 'to get something by making an effort or buying',
    sentence: 'You must obtain a library card before borrowing story books.',
    wordPromptScene: 'A shiny new membership card with a golden star seal.',
    sentPromptScene: 'A student smiles proudly after he can obtain his first library card.',
  },
  {
    word: 'precious',
    partOfSpeech: 'adj.',
    meaningKo: '귀중한, 소중한',
    ipa: '/ˈpreʃ.əs/',
    definition: 'of great value because of being rare, expensive, or loved',
    sentence: 'She keeps a precious family photo album on her shelf.',
    wordPromptScene: 'A glittering sapphire gem resting safely inside a velvet box.',
    sentPromptScene: 'A grandmother shows a precious old scrapbook to her smiling grandchildren.',
  },
  {
    word: 'contribute',
    partOfSpeech: 'v.',
    meaningKo: '기여하다, 기부하다',
    ipa: '/kənˈtrɪb.juːt/',
    definition: 'to give something to help achieve or provide something',
    sentence: 'Each student will contribute one book to the class library.',
    wordPromptScene: 'A donation box where colorful puzzle pieces are being placed.',
    sentPromptScene: 'Children contribute colorful storybooks to a classroom reading shelf.',
  },
  {
    word: 'distribute',
    partOfSpeech: 'v.',
    meaningKo: '나누어 주다, 배포하다',
    ipa: '/dɪˈstrɪb.juːt/',
    definition: 'to give something out to several people or places',
    sentence: 'The class monitor will distribute new worksheets to every desk.',
    wordPromptScene: 'A cartoon hand handing out colorful papers to three friendly hands.',
    sentPromptScene: 'A student walks down the aisle to distribute worksheets in class.',
  },
];

const day07_set4 = [
  {
    word: 'reject',
    partOfSpeech: 'v.',
    meaningKo: '거부하다, 거절하다',
    ipa: '/rɪˈdʒekt/',
    definition: 'to refuse to accept, use, or believe something',
    sentence: 'The honest captain chose to reject any unfair shortcut offer.',
    wordPromptScene: 'A red X mark gently turning away an untidy proposal document.',
    sentPromptScene: 'A team captain decides to reject an unfair rule during debate.',
  },
  {
    word: 'gaze',
    partOfSpeech: 'v.',
    meaningKo: '바라보다, 응시하다',
    ipa: '/ɡeɪz/',
    definition: 'to look at something for a long time in admiration',
    sentence: 'Children love to gaze at the starry night sky outdoors.',
    wordPromptScene: 'A brass telescope pointed toward a crescent moon and glowing stars.',
    sentPromptScene: 'Two friends gaze at a shooting star crossing the clear night sky.',
  },
  {
    word: 'cherish',
    partOfSpeech: 'v.',
    meaningKo: '소중히 여기다, 아끼다',
    ipa: '/ˈtʃer.ɪʃ/',
    definition: 'to love and protect someone or something very much',
    sentence: 'I will cherish the handmade friendship bracelet for many years.',
    wordPromptScene: 'Two hands cradling a glowing origami crane with gentle care.',
    sentPromptScene: 'A girl smiles as she will cherish a gift from her grandmother.',
  },
  {
    word: 'hospitality',
    partOfSpeech: 'n.',
    meaningKo: '환대, 친절',
    ipa: '/ˌhɑː.spɪˈtæl.ə.t̬i/',
    definition: 'the friendly and generous treatment of guests and visitors',
    sentence: 'The kind innkeeper offered warm hospitality and homemade apple pie.',
    wordPromptScene: 'A welcoming tray with warm tea cups and freshly baked cookies.',
    sentPromptScene: 'A smiling host shows warm hospitality to guests entering the cozy cabin.',
  },
  {
    word: 'uncover',
    partOfSpeech: 'v.',
    meaningKo: '발견하다, 덮개를 벗기다',
    ipa: '/ʌnˈkʌv.ɚ/',
    definition: 'to discover something hidden or remove a cover from it',
    sentence: 'Archaeologists hope to uncover ancient stone pottery beneath the sand.',
    wordPromptScene: 'A small brush brushing sand away from a buried golden artifact.',
    sentPromptScene: 'Scientists use brushes to uncover an ancient clay jar in desert.',
  },
  {
    word: 'casual',
    partOfSpeech: 'adj.',
    meaningKo: '격식 없는, 평상시의',
    ipa: '/ˈkæʒ.u.əl/',
    definition: 'comfortable and suitable for everyday use rather than formal',
    sentence: 'He wore casual jeans and a cotton T-shirt to the picnic.',
    wordPromptScene: 'A comfortable blue denim jacket and a plain white cotton shirt.',
    sentPromptScene: 'Students wear casual sneakers and hoodies for a relaxed school field trip.',
  },
  {
    word: 'mutual',
    partOfSpeech: 'adj.',
    meaningKo: '상호 간의, 서로의',
    ipa: '/ˈmjuː.tʃu.əl/',
    definition: 'shared between two or more people equally',
    sentence: 'Good teamwork relies on mutual trust and respect among members.',
    wordPromptScene: 'Two circular arrows forming an infinite loop of glowing cooperation.',
    sentPromptScene: 'Two teammates shake hands with mutual respect after a good game.',
  },
  {
    word: 'farewell',
    partOfSpeech: 'n.',
    meaningKo: '작별, 작별 인사',
    ipa: '/ˌferˈwel/',
    definition: 'an occasion when someone says goodbye',
    sentence: 'The class organized a sweet farewell party for their teacher.',
    wordPromptScene: 'A colorful goodbye banner with waving hands and flying balloons.',
    sentPromptScene: 'Students wave hands during a joyful farewell gathering at semester end.',
  },
  {
    word: 'owe',
    partOfSpeech: 'v.',
    meaningKo: '빚지다, 신세지다',
    ipa: '/oʊ/',
    definition: 'to need to pay someone money or be grateful to them',
    sentence: 'I owe my friend a big thank-you for helping me.',
    wordPromptScene: 'A handwritten Thank You note tied with a cheerful red ribbon.',
    sentPromptScene: 'A boy hands a thank-you drawing to a friend he will owe.',
  },
  {
    word: 'treat',
    partOfSpeech: 'v.',
    meaningKo: '대하다, 대접하다, 치료하다',
    ipa: '/triːt/',
    definition: 'to behave towards someone in a particular way',
    sentence: 'Always treat your classmates with kindness and a warm smile.',
    wordPromptScene: 'A friendly cartoon person offering an umbrella to a companion in rain.',
    sentPromptScene: 'Older students treat younger buddies with kindness on the school playground.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 7, set: 1, wordsData: day07_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 7, set: 2, wordsData: day07_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 7, set: 3, wordsData: day07_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 7, set: 4, wordsData: day07_set4 });
  console.log('DAY 07 written successfully');
}

run();
