import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 24
// ==========================================
const day24_set1 = [
  {
    word: 'resource',
    partOfSpeech: 'n.',
    meaningKo: '자원, 재원',
    ipa: '/ˈriː.sɔːrs/',
    definition: 'a useful supply of material, money, or support for people',
    sentence: 'Fresh river water is a precious natural resource for our town.',
    wordPromptScene: 'A sparkling blue mountain waterfall surrounded by lush green pine forests.',
    sentPromptScene: 'A teacher explains why clean solar energy is a sustainable energy resource.',
  },
  {
    word: 'fossil',
    partOfSpeech: 'n.',
    meaningKo: '화석',
    ipa: '/ˈfɑː.səl/',
    definition: 'the preserved remains or impression of an ancient living thing in rock',
    sentence: 'The museum displayed an ancient ammonite fossil found inside limestone.',
    wordPromptScene: 'A spiral ammonite fossil embedded in a smooth grey limestone slab.',
    sentPromptScene: 'Young students use brushes to uncover a fossil in museum discovery sand.',
  },
  {
    word: 'supply',
    partOfSpeech: 'n.',
    meaningKo: '공급, 보급품',
    ipa: '/səˈplaɪ/',
    definition: 'an amount of something that is available for use',
    sentence: 'Hikers packed an ample supply of fresh water and crunchy trail snacks.',
    wordPromptScene: 'A neatly organized collection of camping canteens and energy bars.',
    sentPromptScene: 'Volunteers organize a supply of warm blankets for community shelters.',
  },
  {
    word: 'common',
    partOfSpeech: 'adj.',
    meaningKo: '흔한, 공통의',
    ipa: '/ˈkɑː.mən/',
    definition: 'occurring, found, or done often, shared by people',
    sentence: 'Dandelions are a common yellow wildflower found in spring meadows.',
    wordPromptScene: 'A sunny grassy lawn sprinkled with bright blooming yellow dandelions.',
    sentPromptScene: 'Two friends discover they share a common hobby of collecting stamps.',
  },
  {
    word: 'explanation',
    partOfSpeech: 'n.',
    meaningKo: '설명, 해명',
    ipa: '/ˌek.spləˈneɪ.ʃən/',
    definition: 'a statement that makes something clear or easy to understand',
    sentence: 'The science teacher gave a clear explanation of how rainbows form.',
    wordPromptScene: 'An illustrated diagram showing how a prism splits sunlight into rainbow colors.',
    sentPromptScene: 'A student gives an engaging explanation of his volcano science project.',
  },
  {
    word: 'nuclear',
    partOfSpeech: 'adj.',
    meaningKo: '원자력의, 핵의',
    ipa: '/ˈnuː.kliː.ɚ/',
    definition: 'relating to the nucleus of an atom or atomic energy',
    sentence: 'Scientists study clean nuclear energy to generate electric power safely.',
    wordPromptScene: 'A futuristic clean energy power plant model with glowing blue atomic symbols.',
    sentPromptScene: 'An engineer explains how atomic reactions produce energy in a science lab.',
  },
  {
    word: 'material',
    partOfSpeech: 'n.',
    meaningKo: '물질, 재료, 직물',
    ipa: '/məˈtɪr.i.əl/',
    definition: 'matter from which a thing is or can be made',
    sentence: 'Wood is a natural building material used for crafting cozy furniture.',
    wordPromptScene: 'Smooth wooden planks, spools of cotton fabric, and glass bricks.',
    sentPromptScene: 'An architect selects sustainable material samples for building a green school.',
  },
  {
    word: 'essential',
    partOfSpeech: 'adj.',
    meaningKo: '필수적인, 극히 중요한',
    ipa: '/ɪˈsen.ʃəl/',
    definition: 'completely necessary or extremely important in a situation',
    sentence: 'Drinking plenty of clean water is essential for good health.',
    wordPromptScene: 'A sparkling glass of clear fresh water with sunbeams shining through.',
    sentPromptScene: 'A coach explains why warm-up stretching is essential before running.',
  },
  {
    word: 'metal',
    partOfSpeech: 'n.',
    meaningKo: '금속, 쇠',
    ipa: '/ˈmet̬.əl/',
    definition: 'a solid material that is typically hard, shiny, and conducts heat',
    sentence: 'The shiny bicycle frame was crafted from strong lightweight metal.',
    wordPromptScene: 'A shiny silver metal wrench resting on a polished steel plate.',
    sentPromptScene: 'A blacksmith demonstrates shaping heated metal into a garden gate hinge.',
  },
  {
    word: 'mental',
    partOfSpeech: 'adj.',
    meaningKo: '정신의, 마음의',
    ipa: '/ˈmen.təl/',
    definition: 'relating to the mind or involving the process of thinking',
    sentence: 'Solving daily crossword puzzles provides great mental exercise for everyone.',
    wordPromptScene: 'A glowing cartoon silhouette head with colorful interconnected puzzle gears.',
    sentPromptScene: 'A chess player demonstrates sharp mental focus during a tournament match.',
  },
];

const day24_set2 = [
  {
    word: 'solve',
    partOfSpeech: 'v.',
    meaningKo: '해결하다, 풀다',
    ipa: '/sɑːlv/',
    definition: 'to find an answer to a problem or explanation for riddle',
    sentence: 'Together our group can solve even the trickiest classroom riddles.',
    wordPromptScene: 'A solved Rubik’s cube glowing with all colorful matching sides aligned.',
    sentPromptScene: 'Students work together happily to solve a difficult math equation on board.',
  },
  {
    word: 'survive',
    partOfSpeech: 'v.',
    meaningKo: '살아남다, 생존하다',
    ipa: '/sɚˈvaɪv/',
    definition: 'to continue to live or exist, especially after difficult conditions',
    sentence: 'Desert plants have thick waxy stems to survive dry summer heat.',
    wordPromptScene: 'A blooming green succulent plant thriving in warm desert sand.',
    sentPromptScene: 'A biologist explains how arctic foxes survive freezing winter blizzards.',
  },
  {
    word: 'source',
    partOfSpeech: 'n.',
    meaningKo: '근원, 출처, 원천',
    ipa: '/sɔːrs/',
    definition: 'a place, person, or thing from which something originates',
    sentence: 'The bubbling mountain spring was the pure source of the river.',
    wordPromptScene: 'A crystal clear freshwater spring bubbling up among mossy forest stones.',
    sentPromptScene: 'Students cite a reliable book source for their historical research essay.',
  },
  {
    word: 'produce',
    partOfSpeech: 'v.',
    meaningKo: '생산하다, 만들다',
    ipa: '/prəˈduːs/',
    definition: 'to make or create something through a physical or natural process',
    sentence: 'Sunny green solar panels produce clean electricity for our school.',
    wordPromptScene: 'A modern rooftop solar panel array generating clean energy beams.',
    sentPromptScene: 'Honeybees work together inside the hive to produce sweet golden honey.',
  },
  {
    word: 'electronic',
    partOfSpeech: 'adj.',
    meaningKo: '전자의, 전자기기의',
    ipa: '/ˌel.ekˈtrɑː.nɪk/',
    definition: 'operating by means of a computer or microchip circuit device',
    sentence: 'Students used an electronic digital tablet to sketch colorful animations.',
    wordPromptScene: 'A sleek modern tablet computer displaying a glowing digital artwork stylus.',
    sentPromptScene: 'A young programmer codes an electronic game on his laptop.',
  },
  {
    word: 'coal',
    partOfSpeech: 'n.',
    meaningKo: '석탄',
    ipa: '/koʊl/',
    definition: 'a hard black rock that can be burned to produce energy',
    sentence: 'Antique steam locomotives were powered by burning dark black coal.',
    wordPromptScene: 'A chunk of shiny black coal resting on a wooden railway sleeper.',
    sentPromptScene: 'A museum guide shows how ancient steam engines used coal for fuel.',
  },
  {
    word: 'benefit',
    partOfSpeech: 'n.',
    meaningKo: '이점, 혜택',
    ipa: '/ˈben.ə.fɪt/',
    definition: 'a helpful or good effect, or something intended to help',
    sentence: 'Regular aerobic exercise provides a lasting health benefit for your heart.',
    wordPromptScene: 'A bright green shield with a glowing heart and five health stars.',
    sentPromptScene: 'A doctor explains the wonderful benefit of getting enough sleep every night.',
  },
  {
    word: 'vacuum',
    partOfSpeech: 'n.',
    meaningKo: '진공, 진공청소기',
    ipa: '/ˈvæk.juːm/',
    definition: 'a completely empty space containing no air or gas, or cleaner',
    sentence: 'Outer space is a vast near vacuum where sound cannot travel.',
    wordPromptScene: 'A modern robotic disc vacuum cleaner sweeping a sunny living room rug.',
    sentPromptScene: 'A science teacher demonstrates how sound requires air and cannot travel in vacuum.',
  },
  {
    word: 'treasure',
    partOfSpeech: 'n.',
    meaningKo: '보물, 소중한 것',
    ipa: '/ˈtreʒ.ɚ/',
    definition: 'a collection of precious things such as gold, silver, or jewels',
    sentence: 'The story told of a hidden golden treasure on island.',
    wordPromptScene: 'An open wooden pirate chest filled with sparkling gold coins and gems.',
    sentPromptScene: 'Children discover a painted rock treasure during a park scavenger hunt.',
  },
  {
    word: 'address',
    partOfSpeech: 'v.',
    meaningKo: '다루다, 연설하다',
    ipa: '/əˈdres/',
    definition: 'to speak to people or give attention to a problem',
    sentence: 'The student council president will address the whole assembly today.',
    wordPromptScene: 'A polished wooden podium with a microphone and a school crest.',
    sentPromptScene: 'A teacher speaks warmly to address student concerns about upcoming exams.',
  },
];

const day24_set3 = [
  {
    word: 'shortage',
    partOfSpeech: 'n.',
    meaningKo: '부족, 결핍',
    ipa: '/ˈʃɔːr.t̬ɪdʒ/',
    definition: 'a state where there is not enough of something that is needed',
    sentence: 'Conserving water helps prevent a water shortage during hot dry summer.',
    wordPromptScene: 'A rain barrel collecting clear rainwater from a roof gutter spout.',
    sentPromptScene: 'A town mayor encourages water conservation to avoid any summer water shortage.',
  },
  {
    word: 'renewable',
    partOfSpeech: 'adj.',
    meaningKo: '재생 가능한',
    ipa: '/rɪˈnuː.ə.bəl/',
    definition: 'capable of being replaced naturally and continuously, not depleting',
    sentence: 'Wind and solar power are important forms of clean renewable energy.',
    wordPromptScene: 'A modern white wind turbine spinning gently against a blue sky.',
    sentPromptScene: 'Students build working miniature wind turbines to study clean renewable power.',
  },
  {
    word: 'potential',
    partOfSpeech: 'n.',
    meaningKo: '잠재력, 가능성',
    ipa: '/poʊˈten.ʃəl/',
    definition: 'someone’s or something’s ability to develop, achieve, or succeed',
    sentence: 'Every young student has the potential to become a great scientist.',
    wordPromptScene: 'A tiny green seed glowing with magical potential as it sprouts.',
    sentPromptScene: 'A teacher encourages a young artist to develop her creative potential.',
  },
  {
    word: 'native',
    partOfSpeech: 'adj.',
    meaningKo: '토착의, 원산의',
    ipa: '/ˈneɪ.t̬ɪv/',
    definition: 'growing naturally in a particular region, not brought from elsewhere',
    sentence: 'Planting native wildflowers helps local honeybees and butterflies thrive happily.',
    wordPromptScene: 'A garden filled with colorful blooming native purple coneflowers.',
    sentPromptScene: 'Volunteers plant native shrubs to restore the local park ecosystem.',
  },
  {
    word: 'grain',
    partOfSpeech: 'n.',
    meaningKo: '곡물, 알갱이',
    ipa: '/ɡreɪn/',
    definition: 'seeds from plants such as wheat, rice, or oats used for food',
    sentence: 'Farmers harvested golden ears of wheat grain in late autumn.',
    wordPromptScene: 'A bundle of golden wheat stalks tied with a rustic hemp twine.',
    sentPromptScene: 'A baker measures whole wheat grain flour on a digital kitchen scale.',
  },
  {
    word: 'extreme',
    partOfSpeech: 'adj.',
    meaningKo: '극심한, 극도의',
    ipa: '/ɪkˈstriːm/',
    definition: 'very large in amount or degree, far from normal or moderate',
    sentence: 'Polar bears are adapted to survive the extreme freezing polar cold.',
    wordPromptScene: 'A majestic polar bear walking across crisp white arctic sea ice.',
    sentPromptScene: 'Explorers test insulated sleeping bags designed for extreme mountain winter weather.',
  },
  {
    word: 'typical',
    partOfSpeech: 'adj.',
    meaningKo: '전형적인, 대표적인',
    ipa: '/ˈtɪp.ɪ.kəl/',
    definition: 'showing the characteristics of a particular group, normal, expected',
    sentence: 'A typical school day includes science, reading, math, and outdoor sports.',
    wordPromptScene: 'A neat student desk with notebooks, pencils, an apple, and books.',
    sentPromptScene: 'A student follows a typical morning routine of breakfast and reading.',
  },
  {
    word: 'contact',
    partOfSpeech: 'n.',
    meaningKo: '접촉, 연락',
    ipa: '/ˈkɑːn.tækt/',
    definition: 'communication with someone, or the state of physical touching',
    sentence: 'Keep in touch and maintain regular contact with your pen pal.',
    wordPromptScene: 'Two friendly cartoon smartphone screens connected by glowing blue chat bubbles.',
    sentPromptScene: 'A student keeps in contact with an overseas friend through email letters.',
  },
  {
    word: 'content',
    partOfSpeech: 'n.',
    meaningKo: '내용, 내용물',
    ipa: '/ˈkɑːn.tent/',
    definition: 'the ideas or information contained in a piece of writing',
    sentence: 'The interesting digital content of the lesson inspired young students.',
    wordPromptScene: 'An open book page displaying a neat Table of Contents chapter list.',
    sentPromptScene: 'A teacher reviews the educational content of a new history textbook.',
  },
  {
    word: 'context',
    partOfSpeech: 'n.',
    meaningKo: '문맥, 맥락',
    ipa: '/ˈkɑːn.tekst/',
    definition: 'the words surrounding a text that help explain its meaning',
    sentence: 'Use surrounding context clues to guess the meaning of new words.',
    wordPromptScene: 'A magnifying glass highlighting a vocabulary word within a paragraph of text.',
    sentPromptScene: 'A reading teacher shows how sentence context helps understand unfamiliar words.',
  },
];

const day24_set4 = [
  {
    word: 'aspect',
    partOfSpeech: 'n.',
    meaningKo: '측면, 양상',
    ipa: '/ˈæs.pekt/',
    definition: 'one particular part or feature of a situation, problem, or idea',
    sentence: 'Teamwork is an important aspect of playing soccer and winning games.',
    wordPromptScene: 'A 3D prism reflecting different colorful spectrum sides of an idea.',
    sentPromptScene: 'Students discuss every aspect of their science project before presenting.',
  },
  {
    word: 'float',
    partOfSpeech: 'v.',
    meaningKo: '뜨다, 떠다니다',
    ipa: '/floʊt/',
    definition: 'to stay on the surface of a liquid and not sink',
    sentence: 'A yellow rubber duck will float happily in the bath water.',
    wordPromptScene: 'A cheerful yellow rubber duck bobbing gently on clear blue bathwater.',
    sentPromptScene: 'Children test different wooden toys to see which ones float on pond.',
  },
  {
    word: 'ingredient',
    partOfSpeech: 'n.',
    meaningKo: '재료, 성분',
    ipa: '/ɪnˈɡriː.di.ənt/',
    definition: 'one of the foods or substances that make up a dish',
    sentence: 'Fresh sweet strawberries are the key ingredient in this fruit pie.',
    wordPromptScene: 'A kitchen counter with fresh eggs, flour, berries, and vanilla extract.',
    sentPromptScene: 'A young baker measures each ingredient carefully into a ceramic mixing bowl.',
  },
  {
    word: 'ban',
    partOfSpeech: 'v.',
    meaningKo: '금지하다',
    ipa: '/bæn/',
    definition: 'to officially forbid something from being done or used',
    sentence: 'Park rules will ban single-use plastic bottles to protect local wildlife.',
    wordPromptScene: 'A sign showing a plastic bottle inside a red circle with a slash.',
    sentPromptScene: 'Town leaders vote to ban plastic bags in supermarkets to protect oceans.',
  },
  {
    word: 'witness',
    partOfSpeech: 'v.',
    meaningKo: '목격하다, 보다',
    ipa: '/ˈwɪt.nəs/',
    definition: 'to see something happen, especially an accident, event, or change',
    sentence: 'Early morning hikers were lucky to witness a magnificent golden sunrise.',
    wordPromptScene: 'Two hikers on a summit looking in wonder at a glowing sunrise.',
    sentPromptScene: 'Students witness a rare solar eclipse safely through special protective dark glasses.',
  },
  {
    word: 'solar',
    partOfSpeech: 'adj.',
    meaningKo: '태양의, 태양열의',
    ipa: '/ˈsoʊ.lɚ/',
    definition: 'relating to or determined by the sun, or using sun energy',
    sentence: 'Our rooftop solar panels absorb bright sunshine to power the school.',
    wordPromptScene: 'A gleaming blue solar panel with a smiling cartoon sun above it.',
    sentPromptScene: 'A young inventor displays a working model of a solar race car.',
  },
  {
    word: 'starve',
    partOfSpeech: 'v.',
    meaningKo: '굶주리다, 몹시 배고프다',
    ipa: '/stɑːrv/',
    definition: 'to suffer or become very hungry from lack of food',
    sentence: 'The playful puppy looked as if he would starve before lunchtime.',
    wordPromptScene: 'A cute cartoon dog sitting beside an empty bowl looking eagerly.',
    sentPromptScene: 'A bird feeder provides seeds so wild birds do not starve in winter.',
  },
  {
    word: 'attribute',
    partOfSpeech: 'v.',
    meaningKo: '~의 탓으로 돌리다, 기인하다',
    ipa: '/əˈtrɪb.juːt/',
    definition: 'to say or think that something is the result of something',
    sentence: 'Athletes attribute their winning success to hard work and team cooperation.',
    wordPromptScene: 'A gold trophy connected by glowing golden light beams to team members.',
    sentPromptScene: 'A student is proud to attribute her high score to daily practice.',
  },
  {
    word: 'appliance',
    partOfSpeech: 'n.',
    meaningKo: '가전제품, 기기',
    ipa: '/əˈplaɪ.əns/',
    definition: 'a machine or device used in the home for daily tasks',
    sentence: 'The modern energy-efficient refrigerator is a useful household kitchen appliance.',
    wordPromptScene: 'A sleek stainless steel refrigerator with an Energy Star green rating logo.',
    sentPromptScene: 'A family shops for an energy-saving appliance for their new kitchen.',
  },
  {
    word: 'plant',
    partOfSpeech: 'v.',
    meaningKo: '심다, 식물',
    ipa: '/plænt/',
    definition: 'to put a seed, bulb, or plant into soil to grow',
    sentence: 'Students will plant sunflower seedlings in the sunny school garden today.',
    wordPromptScene: 'A green plant seedling being placed gently into rich dark garden soil.',
    sentPromptScene: 'Children use small trowels to plant blooming flowers in the park bed.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 24, set: 1, wordsData: day24_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 24, set: 2, wordsData: day24_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 24, set: 3, wordsData: day24_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 24, set: 4, wordsData: day24_set4 });
  console.log('DAY 24 written successfully');
}

run();
