import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 26
// ==========================================
const day26_set1 = [
  {
    word: 'legal',
    partOfSpeech: 'adj.',
    meaningKo: '법률의, 합법적인',
    ipa: '/ˈliː.ɡəl/',
    definition: 'connected with the law, or allowed by the law',
    sentence: 'Wearing a bicycle helmet is a legal safety requirement in town.',
    wordPromptScene: 'A golden balance scale of justice and an official law book on desk.',
    sentPromptScene: 'A police officer explains legal traffic crossing rules to school children.',
  },
  {
    word: 'obey',
    partOfSpeech: 'v.',
    meaningKo: '복종하다, 따르다',
    ipa: '/oʊˈbeɪ/',
    definition: 'to act according to rules, orders, or instructions',
    sentence: 'Drivers must always obey red traffic lights at road crossings.',
    wordPromptScene: 'A friendly cartoon dog sitting obediently at a stop line.',
    sentPromptScene: 'Students obey the pool safety rules and walk slowly along the edge.',
  },
  {
    word: 'arrest',
    partOfSpeech: 'v.',
    meaningKo: '체포하다, 저지하다',
    ipa: '/əˈrest/',
    definition: 'to take someone into police custody according to the law',
    sentence: 'The cartoon detective arrived to arrest the mischievous thief in game.',
    wordPromptScene: 'A friendly cartoon police badge with a shining silver star.',
    sentPromptScene: 'A board game player moves a detective piece to arrest the villain.',
  },
  {
    word: 'report',
    partOfSpeech: 'n.',
    meaningKo: '보고서, 보도',
    ipa: '/rɪˈpɔːrt/',
    definition: 'a spoken or written description of an event or situation',
    sentence: 'She wrote an informative book report about endangered animal species.',
    wordPromptScene: 'A neat written report document with a colorful title page and ribbon.',
    sentPromptScene: 'A student presents her science lab report to the class enthusiastically.',
  },
  {
    word: 'innocent',
    partOfSpeech: 'adj.',
    meaningKo: '결백한, 순진한',
    ipa: '/ˈɪn.ə.sənt/',
    definition: 'not guilty of a crime, or having done no wrong',
    sentence: 'The playful puppy looked completely innocent with wide round eyes.',
    wordPromptScene: 'A cute fluffy white kitten smiling peacefully with a halo of light.',
    sentPromptScene: 'A detective clears the case when evidence proves the suspect is innocent.',
  },
  {
    word: 'caution',
    partOfSpeech: 'n.',
    meaningKo: '주의, 경고',
    ipa: '/ˈkɑː.ʃən/',
    definition: 'great care taken to avoid danger, accidents, or mistakes',
    sentence: 'Hikers crossed the slippery wooden footbridge with great mindful caution.',
    wordPromptScene: 'A bright yellow triangle caution road sign with a black exclamation mark.',
    sentPromptScene: 'A trail guide signals caution as hikers navigate a rocky slope.',
  },
  {
    word: 'charge',
    partOfSpeech: 'v.',
    meaningKo: '요금을 청구하다, 충전하다',
    ipa: '/tʃɑːrdʒ/',
    definition: 'to ask for money as a price, or supply electric power',
    sentence: 'Remember to charge your tablet battery before the science class starts.',
    wordPromptScene: 'A smartphone battery icon glowing full green with a charging lightning bolt.',
    sentPromptScene: 'A student plugs in a cable to charge the robotic model battery.',
  },
  {
    word: 'violate',
    partOfSpeech: 'v.',
    meaningKo: '위반하다, 어기다',
    ipa: '/ˈvaɪ.ə.leɪt/',
    definition: 'to break or act against a rule, agreement, or law',
    sentence: 'Do not violate library quiet rules by talking loudly inside.',
    wordPromptScene: 'A signboard showing a crossed-out red speaker in quiet study zone.',
    sentPromptScene: 'A referee whistles when players violate the offside rule on pitch.',
  },
  {
    word: 'law',
    partOfSpeech: 'n.',
    meaningKo: '법, 법률',
    ipa: '/lɑː/',
    definition: 'the system of rules that a country requires people to obey',
    sentence: 'Respecting traffic law keeps pedestrians and cyclists safe on streets.',
    wordPromptScene: 'An ornate leather-bound volume of law resting on a wooden podium.',
    sentPromptScene: 'A teacher explains how local community law protects clean public parks.',
  },
  {
    word: 'raw',
    partOfSpeech: 'adj.',
    meaningKo: '날것의, 가공되지 않은',
    ipa: '/rɑː/',
    definition: 'not cooked, in a natural and untreated physical state',
    sentence: 'Rabbits love to munch on crunchy raw orange carrots daily.',
    wordPromptScene: 'A wooden cutting board with crisp whole raw carrots and lettuce.',
    sentPromptScene: 'A chef washes fresh raw vegetables thoroughly before making garden salad.',
  },
];

const day26_set2 = [
  {
    word: 'search',
    partOfSpeech: 'v.',
    meaningKo: '찾다, 수색하다',
    ipa: '/sɝːtʃ/',
    definition: 'to look carefully in order to find something or someone',
    sentence: 'Children love to search for hidden colorful eggs during Easter.',
    wordPromptScene: 'A magnifying glass focusing on a shiny golden star in green grass.',
    sentPromptScene: 'Young detectives search the garden for clues during a treasure game.',
  },
  {
    word: 'raise',
    partOfSpeech: 'v.',
    meaningKo: '올리다, 기르다',
    ipa: '/reɪz/',
    definition: 'to lift something to a higher position, or rear animals',
    sentence: 'Please raise your hand politely if you have a question.',
    wordPromptScene: 'A friendly cartoon student raising one hand politely with a smile.',
    sentPromptScene: 'Students raise their hands enthusiastically to answer the teacher’s question.',
  },
  {
    word: 'aim',
    partOfSpeech: 'n.',
    meaningKo: '목표, 조준',
    ipa: '/eɪm/',
    definition: 'a goal or purpose that you hope to achieve',
    sentence: 'His primary aim this semester is to read twenty books.',
    wordPromptScene: 'An archery bow aiming an arrow directly at the red center target.',
    sentPromptScene: 'A student writes down her academic aim on a goal-setting chart.',
  },
  {
    word: 'criminal',
    partOfSpeech: 'n.',
    meaningKo: '범죄자, 범인',
    ipa: '/ˈkrɪm.ə.nəl/',
    definition: 'a person who has committed a crime in law or story',
    sentence: 'The clever detective captured the notorious jewel thief criminal in story.',
    wordPromptScene: 'A magnifying glass looking at a footprint in a mystery cartoon story.',
    sentPromptScene: 'A board game player catches the sneaky criminal piece on the board.',
  },
  {
    word: 'suspect',
    partOfSpeech: 'n.',
    meaningKo: '용의자',
    ipa: '/ˈsʌs.pekt/',
    definition: 'a person believed to have committed a crime in mystery',
    sentence: 'The cartoon detective questioned each colorful suspect in the mansion.',
    wordPromptScene: 'A detective trench coat, fedora hat, and magnifying glass on desk.',
    sentPromptScene: 'Young detectives interview a suspect character in the school mystery play.',
  },
  {
    word: 'neutral',
    partOfSpeech: 'adj.',
    meaningKo: '중립적인, 중성의',
    ipa: '/ˈnuː.trəl/',
    definition: 'not supporting or helping either side in a dispute or game',
    sentence: 'The referee remained completely neutral during the intense soccer match.',
    wordPromptScene: 'A balanced level scale with equal weights on both sides.',
    sentPromptScene: 'A mediator maintains a calm neutral attitude to resolve a dispute.',
  },
  {
    word: 'accuse',
    partOfSpeech: 'v.',
    meaningKo: '비난하다, 고발하다',
    ipa: '/əˈkjuːz/',
    definition: 'to say that someone has done something wrong or illegal',
    sentence: 'Do not accuse others without having clear proof or evidence.',
    wordPromptScene: 'A cartoon detective carefully examining verified proof notes on clipboard.',
    sentPromptScene: 'A student looks for facts before anyone can accuse a classmate.',
  },
  {
    word: 'firm',
    partOfSpeech: 'adj.',
    meaningKo: '단단한, 확고한',
    ipa: '/fɝːm/',
    definition: 'not soft, solid and hard, or unchanging in decision',
    sentence: 'He gave a firm handshake when greeting the new coach.',
    wordPromptScene: 'A solid stone foundation block standing firmly on the level ground.',
    sentPromptScene: 'Two team leaders exchange a firm friendly handshake before the game.',
  },
  {
    word: 'aid',
    partOfSpeech: 'n.',
    meaningKo: '도움, 원조',
    ipa: '/eɪd/',
    definition: 'help or support given to someone who needs it',
    sentence: 'The rescue team provided emergency aid to the stranded hikers.',
    wordPromptScene: 'A white first-aid kit box with a bright red medical cross.',
    sentPromptScene: 'Volunteers pack food parcels to provide aid to the community shelter.',
  },
  {
    word: 'interest',
    partOfSpeech: 'n.',
    meaningKo: '관심, 흥미, 이자',
    ipa: '/ˈɪn.trɪst/',
    definition: 'the feeling of wanting to give your attention to something',
    sentence: 'She developed a deep interest in astronomy after visiting planetarium.',
    wordPromptScene: 'A brass telescope surrounded by glowing star charts and galaxy globes.',
    sentPromptScene: 'Students show great interest while observing living cells through microscopes.',
  },
];

const day26_set3 = [
  {
    word: 'complex',
    partOfSpeech: 'adj.',
    meaningKo: '복잡한',
    ipa: '/kɑːmˈpleks/',
    definition: 'having many different parts and not easy to understand',
    sentence: 'The wooden clock mechanism had a very complex internal gear design.',
    wordPromptScene: 'An intricate network of interconnected glowing brass mechanical gears.',
    sentPromptScene: 'A student solves a complex maze puzzle using a logical step method.',
  },
  {
    word: 'organize',
    partOfSpeech: 'v.',
    meaningKo: '정리하다, 조직하다',
    ipa: '/ˈɔːr.ɡən.aɪz/',
    definition: 'to arrange things into a structured or neat order',
    sentence: 'Please help organize the library books in neat alphabetical order.',
    wordPromptScene: 'Neatly organized colorful folders arranged in rainbow order in a tray.',
    sentPromptScene: 'Students work together to organize sports equipment in the school gym.',
  },
  {
    word: 'plenty',
    partOfSpeech: 'n.',
    meaningKo: '풍부함, 많음',
    ipa: '/ˈplen.t̬i/',
    definition: 'a large or sufficient amount or quantity of something',
    sentence: 'There was plenty of fresh fruit for everyone at breakfast.',
    wordPromptScene: 'An overflowing cornucopia basket with sweet apples, grapes, and oranges.',
    sentPromptScene: 'Hikers pack plenty of snacks and water bottles for the day trip.',
  },
  {
    word: 'phenomenon',
    partOfSpeech: 'n.',
    meaningKo: '현상',
    ipa: '/fəˈnɑː.mə.nɑːn/',
    definition: 'a fact or situation that is observed to exist naturally',
    sentence: 'The Northern Lights are a breathtaking natural light phenomenon in winter.',
    wordPromptScene: 'Vibrant green and magenta aurora borealis waves dancing in arctic night.',
    sentPromptScene: 'A science teacher explains how a solar eclipse is a celestial phenomenon.',
  },
  {
    word: 'mount',
    partOfSpeech: 'v.',
    meaningKo: '올라타다, 설치하다',
    ipa: '/maʊnt/',
    definition: 'to get up on something, or fix something in position',
    sentence: 'He learned how to mount his new bicycle with balance.',
    wordPromptScene: 'A sturdy wall bracket mounted securely with a shiny display frame.',
    sentPromptScene: 'A cyclist adjusts her helmet before stepping up to mount the bike.',
  },
  {
    word: 'found',
    partOfSpeech: 'v.',
    meaningKo: '설립하다, 세우다',
    ipa: '/faʊnd/',
    definition: 'to bring something into existence, start an organization or school',
    sentence: 'Town citizens decided to found a public animal shelter this year.',
    wordPromptScene: 'A ceremonial foundation cornerstone inscribed with the founding year.',
    sentPromptScene: 'Leaders gather to found a new science research academy for students.',
  },
  {
    word: 'prove',
    partOfSpeech: 'v.',
    meaningKo: '증명하다, 입증하다',
    ipa: '/pruːv/',
    definition: 'to show that something is true by giving facts or proof',
    sentence: 'The laboratory experiment will prove that warm air rises above cool.',
    wordPromptScene: 'A magnifying glass highlighting a glowing verified checkmark on equations.',
    sentPromptScene: 'A student uses clear logic and math steps to prove the theorem.',
  },
  {
    word: 'forbid',
    partOfSpeech: 'v.',
    meaningKo: '금지하다',
    ipa: '/fɚˈbɪd/',
    definition: 'to order someone not to do something officially',
    sentence: 'School safety rules forbid running along the slippery swimming pool edge.',
    wordPromptScene: 'A circular sign showing a red slash across a running figure.',
    sentPromptScene: 'Park signs forbid campfires during dry summer seasons to protect trees.',
  },
  {
    word: 'contrast',
    partOfSpeech: 'n.',
    meaningKo: '대조, 차이',
    ipa: '/ˈkɑːn.træst/',
    definition: 'an obvious difference between two or more things',
    sentence: 'The bright red rose provided a beautiful contrast against white snow.',
    wordPromptScene: 'A stark circular icon split down the center into black and white.',
    sentPromptScene: 'An art student compares the color contrast between light and dark paints.',
  },
  {
    word: 'contract',
    partOfSpeech: 'n.',
    meaningKo: '계약, 계약서',
    ipa: '/ˈkɑːn.trækt/',
    definition: 'a legal document stating an agreement between two or more people',
    sentence: 'The builder signed an official contract to construct the wooden bridge.',
    wordPromptScene: 'An official parchment contract with a red wax seal and fountain pen.',
    sentPromptScene: 'A club leader signs a group contract agreeing to fair play rules.',
  },
];

const day26_set4 = [
  {
    word: 'stamp',
    partOfSpeech: 'n.',
    meaningKo: '우표, 도장',
    ipa: '/stæmp/',
    definition: 'a small piece of paper stuck to an envelope for postage',
    sentence: 'She placed a colorful postage stamp on the birthday postcard.',
    wordPromptScene: 'A colorful vintage postage stamp featuring a flying hummingbird illustration.',
    sentPromptScene: 'A student sticks a stamp onto an envelope before mailing the letter.',
  },
  {
    word: 'secure',
    partOfSpeech: 'adj.',
    meaningKo: '안전한, 튼튼한',
    ipa: '/səˈkjʊr/',
    definition: 'safe from danger, firmly fastened, and not likely to fail',
    sentence: 'Make sure the bicycle lock is secure before leaving the rack.',
    wordPromptScene: 'A sturdy golden padlock locked securely around a bicycle chain.',
    sentPromptScene: 'A hiker checks that tent ropes are secure against strong mountain winds.',
  },
  {
    word: 'conference',
    partOfSpeech: 'n.',
    meaningKo: '회의, 학회',
    ipa: '/ˈkɑːn.fɚ.əns/',
    definition: 'a formal meeting for discussion or consultation among professionals',
    sentence: 'Scientists attended an international climate conference to discuss clean energy.',
    wordPromptScene: 'A modern auditorium stage with a large presentation screen and microphones.',
    sentPromptScene: 'Teachers gather in the hall for an educational technology conference workshop.',
  },
  {
    word: 'urge',
    partOfSpeech: 'v.',
    meaningKo: '촉구하다, 권고하다',
    ipa: '/ɝːdʒ/',
    definition: 'to strongly advise or encourage someone to do something',
    sentence: 'Doctors urge everyone to drink plenty of clean fresh water.',
    wordPromptScene: 'A friendly cartoon character pointing encouragingly at a healthy water glass.',
    sentPromptScene: 'Teachers urge students to wear safety helmets when riding skateboards outdoors.',
  },
  {
    word: 'confront',
    partOfSpeech: 'v.',
    meaningKo: '맞서다, 직면하다',
    ipa: '/kənˈfrʌnt/',
    definition: 'to face, meet, or deal with a difficult situation bravely',
    sentence: 'The brave knight was ready to confront any obstacle ahead.',
    wordPromptScene: 'A cartoon knight with a silver shield standing determinedly on path.',
    sentPromptScene: 'A student decides to confront his math anxiety by practicing daily.',
  },
  {
    word: 'persuade',
    partOfSpeech: 'v.',
    meaningKo: '설득하다',
    ipa: '/pɚˈsweɪd/',
    definition: 'to make someone agree to do something by giving reasons',
    sentence: 'She was able to persuade her friend to join the club.',
    wordPromptScene: 'A cartoon lightbulb idea connecting two smiling characters with a bridge.',
    sentPromptScene: 'A student uses clear arguments to persuade classmates to recycle plastic.',
  },
  {
    word: 'scan',
    partOfSpeech: 'v.',
    meaningKo: '훑어보다, 스캔하다',
    ipa: '/skæn/',
    definition: 'to look through something quickly, or use an electronic scanner',
    sentence: 'The librarian will scan the barcode on the borrowed book.',
    wordPromptScene: 'A digital laser barcode scanner reading a code with red light beam.',
    sentPromptScene: 'A student uses a handheld scanner to scan book barcodes in library.',
  },
  {
    word: 'prohibit',
    partOfSpeech: 'v.',
    meaningKo: '금지하다',
    ipa: '/prəˈhɪb.ɪt/',
    definition: 'to officially forbid something by law or rule',
    sentence: 'Park rules prohibit feeding wild ducks to keep water clean.',
    wordPromptScene: 'A wooden sign showing a crossed-out bread icon beside a pond.',
    sentPromptScene: 'A sign shows that pool regulations prohibit running along the tiled edge.',
  },
  {
    word: 'moreover',
    partOfSpeech: 'adv.',
    meaningKo: '게다가, 더욱이',
    ipa: '/mɔːrˈoʊ.vɚ/',
    definition: 'in addition to what has been said, besides',
    sentence: 'Cycling is fun and, moreover, it keeps our body healthy.',
    wordPromptScene: 'A plus symbol connecting a bicycle to a shining gold heart.',
    sentPromptScene: 'A student explains that gardening is relaxing and, moreover, produces vegetables.',
  },
  {
    word: 'determine',
    partOfSpeech: 'v.',
    meaningKo: '결정하다, 알아내다',
    ipa: '/dɪˈtɝː.mɪn/',
    definition: 'to decide something officially, or discover the facts about something',
    sentence: 'Scientists conducted tests to determine the age of the ancient fossil.',
    wordPromptScene: 'A scientist examining a rock sample under a microscope with digital meters.',
    sentPromptScene: 'Judges review performance scores to determine the science fair winner.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 26, set: 1, wordsData: day26_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 26, set: 2, wordsData: day26_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 26, set: 3, wordsData: day26_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 26, set: 4, wordsData: day26_set4 });
  console.log('DAY 26 written successfully');
}

run();
