import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 27
// ==========================================
const day27_set1 = [
  {
    word: 'politics',
    partOfSpeech: 'n.',
    meaningKo: '정치, 정치학',
    ipa: '/ˈpɑː.lə.tɪks/',
    definition: 'the activities associated with the governance of a country or area',
    sentence: 'Students learned about local community government in their politics class.',
    wordPromptScene: 'A classic town hall building with white columns and a fluttering flag.',
    sentPromptScene: 'Students hold a model city council debate in politics class.',
  },
  {
    word: 'facility',
    partOfSpeech: 'n.',
    meaningKo: '시설, 기관',
    ipa: '/fəˈsɪl.ə.t̬i/',
    definition: 'a place, amenity, or piece of equipment provided for a purpose',
    sentence: 'The modern sports facility has a heated indoor swimming pool.',
    wordPromptScene: 'A modern community sports center building with basketball courts and pool.',
    sentPromptScene: 'Athletes train on running tracks inside the new sports facility.',
  },
  {
    word: 'vote',
    partOfSpeech: 'v.',
    meaningKo: '투표하다',
    ipa: '/voʊt/',
    definition: 'to express a choice in an election or opinion poll',
    sentence: 'Classmates will vote to choose our new student council president.',
    wordPromptScene: 'A cartoon hand placing a paper ballot into a wooden ballot box.',
    sentPromptScene: 'Students drop paper ballots into a box to vote for class leaders.',
  },
  {
    word: 'candidate',
    partOfSpeech: 'n.',
    meaningKo: '후보자, 지원자',
    ipa: '/ˈkæn.dɪ.deɪt/',
    definition: 'a person who is competing to get a job or elected position',
    sentence: 'Each presidential candidate presented creative ideas for improving the school.',
    wordPromptScene: 'A colorful campaign poster on a corkboard with stars and ribbons.',
    sentPromptScene: 'A student candidate speaks passionately about school recycling during the assembly.',
  },
  {
    word: 'civil',
    partOfSpeech: 'adj.',
    meaningKo: '시민의, 민간의, 정중한',
    ipa: '/ˈsɪv.əl/',
    definition: 'relating to ordinary citizens and their concerns, polite',
    sentence: 'Every citizen has important civil rights and civic responsibilities today.',
    wordPromptScene: 'A community gathering of diverse happy citizens holding hands in park.',
    sentPromptScene: 'Students discuss historical civil rights leaders who helped society become fair.',
  },
  {
    word: 'limit',
    partOfSpeech: 'n.',
    meaningKo: '한계, 한도, 제한',
    ipa: '/ˈlɪm.ɪt/',
    definition: 'the greatest amount, number, or level of something allowed',
    sentence: 'The speed limit on our quiet neighborhood street is thirty kilometers.',
    wordPromptScene: 'A circular road sign displaying a clean 30 speed limit number.',
    sentPromptScene: 'A teacher explains the thirty-minute time limit for the math quiz.',
  },
  {
    word: 'conservative',
    partOfSpeech: 'adj.',
    meaningKo: '보수적인, 조심스러운',
    ipa: '/kənˈsɝː.və.t̬ɪv/',
    definition: 'preferring traditional values and cautious about changes',
    sentence: 'The architect chose a classic conservative design for the town library.',
    wordPromptScene: 'A traditional brick library with classic wooden shutter windows.',
    sentPromptScene: 'Planners make a conservative budget estimate to avoid any financial shortfall.',
  },
  {
    word: 'belong',
    partOfSpeech: 'v.',
    meaningKo: '속하다, 제자리에 있다',
    ipa: '/bɪˈlɑːŋ/',
    definition: 'to be the property of, or be in the right place',
    sentence: 'These colorful picture storybooks belong on the lower library shelf.',
    wordPromptScene: 'A library book slotting neatly into its assigned spot on shelf.',
    sentPromptScene: 'Students return art supplies where they belong in the supply cupboard.',
  },
  {
    word: 'official',
    partOfSpeech: 'adj.',
    meaningKo: '공식적인, 공인의',
    ipa: '/əˈfɪʃ.əl/',
    definition: 'agreed to or confirmed by the government or an authority',
    sentence: 'The school principal signed the official certificate with golden seal.',
    wordPromptScene: 'A parchment diploma stamped with a shiny gold official embossed emblem.',
    sentPromptScene: 'Officials announce the official opening of the new community nature park.',
  },
  {
    word: 'officer',
    partOfSpeech: 'n.',
    meaningKo: '경찰관, 장교, 임원',
    ipa: '/ˈɑː.fɪ.sɚ/',
    definition: 'a person who holds a position of authority in organization/police',
    sentence: 'The friendly police officer helped children cross the busy avenue safely.',
    wordPromptScene: 'A smiling cartoon police officer waving warmly at a pedestrian crosswalk.',
    sentPromptScene: 'A safety officer visits the classroom to demonstrate bicycle helmet safety.',
  },
];

const day27_set2 = [
  {
    word: 'result',
    partOfSpeech: 'n.',
    meaningKo: '결과, 성과',
    ipa: '/rɪˈzʌlt/',
    definition: 'something that happens or exists because of something else',
    sentence: 'Hard daily practice led to a wonderful winning match result.',
    wordPromptScene: 'A scoreboard displaying a high score with sparkling gold celebration confetti.',
    sentPromptScene: 'Students celebrate the positive test result after weeks of study.',
  },
  {
    word: 'survey',
    partOfSpeech: 'n.',
    meaningKo: '설문 조사, 측량',
    ipa: '/ˈsɝː.veɪ/',
    definition: 'an investigation of the opinions or experience of people',
    sentence: 'Students conducted a classroom survey about their favorite school lunches.',
    wordPromptScene: 'A survey clipboard with checkboxes and a colorful bar chart pie.',
    sentPromptScene: 'A student tallies responses from a school reading habit survey.',
  },
  {
    word: 'notice',
    partOfSpeech: 'n.',
    meaningKo: '안내문, 공지, 통지',
    ipa: '/ˈnoʊ.t̬ɪs/',
    definition: 'information or a warning given about something that is happening',
    sentence: 'The teacher pinned an important field trip notice on board.',
    wordPromptScene: 'A colorful paper notice pinned with a red thumbtack on corkboard.',
    sentPromptScene: 'Students read the library schedule notice posted on the classroom door.',
  },
  {
    word: 'guard',
    partOfSpeech: 'v.',
    meaningKo: '지키다, 보호하다, 경비원',
    ipa: '/ɡɑːrd/',
    definition: 'to protect a place or person from harm or danger',
    sentence: 'The loyal dog will guard the cozy farmhouse all night.',
    wordPromptScene: 'A friendly cartoon sheepdog resting watchfully by a wooden gate.',
    sentPromptScene: 'Park rangers guard the wildlife sanctuary to protect nesting water birds.',
  },
  {
    word: 'profit',
    partOfSpeech: 'n.',
    meaningKo: '이익, 수익',
    ipa: '/ˈprɑː.fɪt/',
    definition: 'money that is earned in business after paying the costs',
    sentence: 'Students donated all the lemonade stand profit to animal shelters.',
    wordPromptScene: 'A piggy bank with shiny golden coins and an upward-trending green arrow.',
    sentPromptScene: 'Young entrepreneurs count the profit from their school charity bake sale.',
  },
  {
    word: 'deny',
    partOfSpeech: 'v.',
    meaningKo: '부인하다, 거부하다',
    ipa: '/dɪˈnaɪ/',
    definition: 'to say that something is not true, or refuse permission',
    sentence: 'No one can deny that sunset over ocean is breathtaking.',
    wordPromptScene: 'A glowing golden sunset over tranquil waters with soft violet clouds.',
    sentPromptScene: 'Historians examine clear evidence that no one can reasonably deny.',
  },
  {
    word: 'opinion',
    partOfSpeech: 'n.',
    meaningKo: '의견, 견해',
    ipa: '/əˈpɪn.jən/',
    definition: 'a thought or belief about something or someone',
    sentence: 'Everyone had a chance to share an opinion in discussion.',
    wordPromptScene: 'Two colorful speech bubbles exchanging creative ideas with star sparkles.',
    sentPromptScene: 'Students raise hands politely to express their opinion about the novel.',
  },
  {
    word: 'rural',
    partOfSpeech: 'adj.',
    meaningKo: '시골의, 전원의',
    ipa: '/ˈrʊr.əl/',
    definition: 'relating to the countryside rather than the town or city',
    sentence: 'We enjoyed a peaceful summer vacation in a quiet rural village.',
    wordPromptScene: 'A picturesque countryside scene with a red barn, windmill, and green pastures.',
    sentPromptScene: 'A school bus drives along a quiet rural road past dairy farms.',
  },
  {
    word: 'urban',
    partOfSpeech: 'adj.',
    meaningKo: '도시의, 도회지의',
    ipa: '/ˈɝː.bən/',
    definition: 'relating to, or characteristic of a town or city',
    sentence: 'The urban community park had flower gardens and modern bicycle lanes.',
    wordPromptScene: 'A modern eco-friendly city skyline with green rooftop gardens and trams.',
    sentPromptScene: 'Students explore an urban museum located in the heart of downtown.',
  },
  {
    word: 'issue',
    partOfSpeech: 'n.',
    meaningKo: '문제, 쟁점, 발행호',
    ipa: '/ˈɪʃ.uː/',
    definition: 'an important topic or problem for debate or discussion',
    sentence: 'Plastic waste reduction is an urgent environmental issue for everyone.',
    wordPromptScene: 'A round Earth surrounded by a green recycling loop arrow icon.',
    sentPromptScene: 'The student council meets to address the issue of cafeteria recycling.',
  },
];

const day27_set3 = [
  {
    word: 'simplify',
    partOfSpeech: 'v.',
    meaningKo: '단순화하다, 간소화하다',
    ipa: '/ˈsɪm.plə.faɪ/',
    definition: 'to make something easier to do or understand clearly',
    sentence: 'The teacher used diagrams to simplify complex fractions in math.',
    wordPromptScene: 'A tangled colorful line untangling smoothly into a clean straight arrow.',
    sentPromptScene: 'A math teacher uses colorful blocks to simplify a difficult algebra concept.',
  },
  {
    word: 'committee',
    partOfSpeech: 'n.',
    meaningKo: '위원회',
    ipa: '/kəˈmɪt̬.i/',
    definition: 'a group of people chosen to make decisions or plans',
    sentence: 'The student festival committee planned exciting carnival games for everyone.',
    wordPromptScene: 'A group of diverse students sitting around a table with project charts.',
    sentPromptScene: 'Members of the garden committee plant seasonal flowers around the school courtyard.',
  },
  {
    word: 'accompany',
    partOfSpeech: 'v.',
    meaningKo: '동행하다, 반주하다',
    ipa: '/əˈkʌm.pə.ni/',
    definition: 'to go with someone as a companion, or play music with',
    sentence: 'A parent will accompany younger children on the field trip.',
    wordPromptScene: 'An adult holding hands warmly with a young child on trail.',
    sentPromptScene: 'A pianist will accompany the school choir during the holiday concert.',
  },
  {
    word: 'proportion',
    partOfSpeech: 'n.',
    meaningKo: '비율, 균형',
    ipa: '/prəˈpɔːr.ʃən/',
    definition: 'a part or share in relation to a whole amount',
    sentence: 'A large proportion of the school garden is planted with sunflowers.',
    wordPromptScene: 'A 3D pie chart with three colorful equal pie slice wedges.',
    sentPromptScene: 'Students draw a pie chart showing the proportion of rainy days.',
  },
  {
    word: 'household',
    partOfSpeech: 'n.',
    meaningKo: '가정, 가구',
    ipa: '/ˈhaʊs.hoʊld/',
    definition: 'a family or group of people who live together under roof',
    sentence: 'Every household on our street joined the neighborhood tree-planting project.',
    wordPromptScene: 'A charming cartoon cottage with glowing windows and a blooming garden.',
    sentPromptScene: 'Neighbors distribute recycling bins to every household in the village.',
  },
  {
    word: 'absence',
    partOfSpeech: 'n.',
    meaningKo: '결석, 부재',
    ipa: '/ˈæb.səns/',
    definition: 'the state of being away from a place where expected',
    sentence: 'His absence from soccer practice was excused due to doctor visit.',
    wordPromptScene: 'A teacher roll-call notebook with neat green and yellow attendance markers.',
    sentPromptScene: 'A classmate shares homework notes with a friend after his brief absence.',
  },
  {
    word: 'primary',
    partOfSpeech: 'adj.',
    meaningKo: '주요한, 최초의, 초등의',
    ipa: '/ˈpraɪ.mer.i/',
    definition: 'more important than anything else, main, or earliest stage',
    sentence: 'Our primary goal this week is to complete the science poster.',
    wordPromptScene: 'Three primary paint colors red, yellow, and blue on artist palette.',
    sentPromptScene: 'The primary objective of the recycling project is reducing plastic waste.',
  },
  {
    word: 'spot',
    partOfSpeech: 'n.',
    meaningKo: '장소, 점, 발견하다',
    ipa: '/spɑːt/',
    definition: 'a particular place, or a small round mark of color',
    sentence: 'We found a sunny grassy spot for our afternoon picnic.',
    wordPromptScene: 'A cute cartoon dalmatian puppy covered in playful black polka spots.',
    sentPromptScene: 'Children choose a comfortable shady spot under the oak tree for reading.',
  },
  {
    word: 'bother',
    partOfSpeech: 'v.',
    meaningKo: '귀찮게 하다, 신경 쓰이다',
    ipa: '/ˈbɑː.ðɚ/',
    definition: 'to annoy or worry someone by interrupting their quiet activity',
    sentence: 'Please walk softly in library so you do not bother readers.',
    wordPromptScene: 'A cartoon kitten sleeping peacefully with soft floating zzz sleep icons.',
    sentPromptScene: 'A student wears headphones so background music will not bother his study partner.',
  },
  {
    word: 'border',
    partOfSpeech: 'n.',
    meaningKo: '국경, 경계, 가장자리',
    ipa: '/ˈbɔːr.dɚ/',
    definition: 'a line separating two countries or areas, or decorative edge',
    sentence: 'A low wooden fence marked the border around the vegetable garden.',
    wordPromptScene: 'A decorative border of blooming pansy flowers around a garden bed.',
    sentPromptScene: 'Hikers view the scenic natural border where river meets the mountain forest.',
  },
];

const day27_set4 = [
  {
    word: 'available',
    partOfSpeech: 'adj.',
    meaningKo: '이용 가능한, 시간이 있는',
    ipa: '/əˈveɪ.lə.bəl/',
    definition: 'ready to be used or obtained, not occupied or busy',
    sentence: 'Fresh cold water is always available at the park drinking fountain.',
    wordPromptScene: 'A shiny silver outdoor drinking fountain with a clear jet of water.',
    sentPromptScene: 'The librarian confirms that copies of the novel are available to borrow.',
  },
  {
    word: 'harbor',
    partOfSpeech: 'n.',
    meaningKo: '항구, 피난처',
    ipa: '/ˈhɑːr.bɚ/',
    definition: 'a protected area of water next to land where boats moor',
    sentence: 'Sailboats bobbed gently on the calm blue water in harbor.',
    wordPromptScene: 'A picturesque coastal harbor with colorful sailboats moored beside wooden docks.',
    sentPromptScene: 'Tourists watch fishing boats return to the safe harbor at sunset.',
  },
  {
    word: 'garage',
    partOfSpeech: 'n.',
    meaningKo: '차고, 정비소',
    ipa: '/ɡəˈrɑːʒ/',
    definition: 'a building or indoor space where a vehicle is kept',
    sentence: 'He parked his bicycle safely inside the tidy clean garage.',
    wordPromptScene: 'A clean organized garage with tools neatly hung and a bicycle rack.',
    sentPromptScene: 'A father and daughter fix a toy cart inside the home garage.',
  },
  {
    word: 'notion',
    partOfSpeech: 'n.',
    meaningKo: '개념, 생각',
    ipa: '/ˈnoʊ.ʃən/',
    definition: 'a belief or idea about something, an understanding',
    sentence: 'She had a creative notion for our upcoming school puppet show.',
    wordPromptScene: 'A glowing yellow lightbulb emerging gently from an open illustrated book.',
    sentPromptScene: 'Students discuss the notion of building a community rooftop greenhouse together.',
  },
  {
    word: 'suburb',
    partOfSpeech: 'n.',
    meaningKo: '교외, 근교',
    ipa: '/ˈsʌb.ɝːb/',
    definition: 'an area on the edge of a city where people live',
    sentence: 'Our quiet tree-lined suburb has friendly neighbors and wide bicycle paths.',
    wordPromptScene: 'A charming residential neighborhood with neat houses, green lawns, and trees.',
    sentPromptScene: 'A family takes a weekend bike ride along the quiet suburb sidewalks.',
  },
  {
    word: 'resident',
    partOfSpeech: 'n.',
    meaningKo: '주민, 거주자',
    ipa: '/ˈrez.ə.dənt/',
    definition: 'a person who lives in a particular place or area',
    sentence: 'Every local resident was invited to the summer block party celebration.',
    wordPromptScene: 'A cartoon mailbox with a friendly welcome sign on a picket fence.',
    sentPromptScene: 'A long-time resident gives directions to visitors at the community market.',
  },
  {
    word: 'investigate',
    partOfSpeech: 'v.',
    meaningKo: '조사하다, 수사하다',
    ipa: '/ɪnˈves.tə.ɡeɪt/',
    definition: 'to examine a problem or mystery carefully to discover truth',
    sentence: 'Young scientists investigate why water drops form beads on lotus leaves.',
    wordPromptScene: 'A detective magnifying glass examining tiny sparkling water droplets on leaf.',
    sentPromptScene: 'Students use science kits to investigate soil minerals in the garden.',
  },
  {
    word: 'reinforce',
    partOfSpeech: 'v.',
    meaningKo: '강화하다, 보강하다',
    ipa: '/ˌriː.ɪnˈfɔːrs/',
    definition: 'to make something stronger or more effective with extra support',
    sentence: 'Workers used steel beams to reinforce the wooden bridge structure securely.',
    wordPromptScene: 'Steel support brackets reinforcing the wooden joints of a bridge model.',
    sentPromptScene: 'Daily vocabulary review games reinforce new words learned in English class.',
  },
  {
    word: 'govern',
    partOfSpeech: 'v.',
    meaningKo: '통치하다, 지배하다',
    ipa: '/ˈɡʌv.ɚn/',
    definition: 'to control and direct the public affairs of a city/state',
    sentence: 'Elected student council leaders govern classroom activities with fairness and care.',
    wordPromptScene: 'A golden gavel resting on a polished wooden desk in council chamber.',
    sentPromptScene: 'Students elect representatives who will govern their school student council.',
  },
  {
    word: 'rate',
    partOfSpeech: 'n.',
    meaningKo: '비율, 속도, 평가하다',
    ipa: '/reɪt/',
    definition: 'the speed at which something happens over a period of time',
    sentence: 'The seedling grew at an impressive rate during sunny warm spring.',
    wordPromptScene: 'A growth chart showing a green plant sprout climbing rapidly beside ruler.',
    sentPromptScene: 'A runner checks her heart rate on a sports smartwatch during exercise.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 27, set: 1, wordsData: day27_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 27, set: 2, wordsData: day27_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 27, set: 3, wordsData: day27_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 27, set: 4, wordsData: day27_set4 });
  console.log('DAY 27 written successfully');
}

run();
