import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 05
// ==========================================
const day05_set1 = [
  {
    word: 'muscle',
    partOfSpeech: 'n.',
    meaningKo: '근육',
    ipa: '/ˈmʌs.əl/',
    definition: 'one of the tissues in the body that produces movement',
    sentence: 'Daily jumping exercise helps build strong leg muscle strength naturally.',
    wordPromptScene: 'A flexed arm showing a healthy toned bicep muscle icon.',
    sentPromptScene: 'A young gymnast stretches on a mat to build leg muscle.',
  },
  {
    word: 'regular',
    partOfSpeech: 'adj.',
    meaningKo: '규칙적인, 정기적인',
    ipa: '/ˈreɡ.jə.lɚ/',
    definition: 'happening repeatedly with equal time between events',
    sentence: 'He keeps a regular sleep schedule to stay healthy everyday.',
    wordPromptScene: 'A wall clock with evenly spaced golden chime bells chiming.',
    sentPromptScene: 'A student follows a neat daily timetable for regular study habits.',
  },
  {
    word: 'stretch',
    partOfSpeech: 'v.',
    meaningKo: '늘이다, 스트레칭하다',
    ipa: '/stretʃ/',
    definition: 'to make your body or limbs straight and reach out',
    sentence: 'Remember to stretch your arms before playing basketball today.',
    wordPromptScene: 'An elastic colorful rubber band stretching between two cartoon hands.',
    sentPromptScene: 'A smiling runner reaches up to stretch arms on track.',
  },
  {
    word: 'reduce',
    partOfSpeech: 'v.',
    meaningKo: '줄이다, 낮추다',
    ipa: '/rɪˈduːs/',
    definition: 'to make something smaller in size or amount',
    sentence: 'Drinking warm water can reduce your throat discomfort quickly.',
    wordPromptScene: 'A downward-pointing blue trend arrow showing a gentle reduction.',
    sentPromptScene: 'A chef turns down the stove burner to reduce soup heat.',
  },
  {
    word: 'opponent',
    partOfSpeech: 'n.',
    meaningKo: '상대, 적수',
    ipa: '/əˈpoʊ.nənt/',
    definition: 'a person who plays against you in a game',
    sentence: 'He shook hands with his friendly chess opponent after game.',
    wordPromptScene: 'Two chess pieces, a white knight and black knight, facing each other.',
    sentPromptScene: 'Two young chess players shake hands respectfully across the wooden board.',
  },
  {
    word: 'recommend',
    partOfSpeech: 'v.',
    meaningKo: '추천하다, 권하다',
    ipa: '/ˌrek.əˈmend/',
    definition: 'to suggest that someone or something is good or useful',
    sentence: 'Doctors recommend eating fresh green vegetables and fruits daily.',
    wordPromptScene: 'A five-star rating badge with a thumbs-up award ribbon.',
    sentPromptScene: 'A smiling nutritionist points to a bowl of fruit to recommend vitamins.',
  },
  {
    word: 'warn',
    partOfSpeech: 'v.',
    meaningKo: '경고하다, 주의를 주다',
    ipa: '/wɔːrn/',
    definition: 'to tell someone about possible danger or difficulty',
    sentence: 'Bright yellow signs warn hikers about the slippery forest trail.',
    wordPromptScene: 'A yellow triangle warning sign with a clear exclamation mark.',
    sentPromptScene: 'A trail guide holds up a sign to warn hikers about rain.',
  },
  {
    word: 'cause',
    partOfSpeech: 'v.',
    meaningKo: '원인이 되다, 야기하다',
    ipa: '/kɑːz/',
    definition: 'to make something happen, especially something bad',
    sentence: 'Loud sudden noises can cause the shy puppy to hide.',
    wordPromptScene: 'A falling line of colorful domino tiles triggering the next block.',
    sentPromptScene: 'Heavy dark rain clouds cause puddles to form along the sidewalk.',
  },
  {
    word: 'lose',
    partOfSpeech: 'v.',
    meaningKo: '잃다, 패하다',
    ipa: '/luːz/',
    definition: 'to no longer have something or fail to win a game',
    sentence: 'Be careful not to lose your house key while jogging.',
    wordPromptScene: 'A golden house key slipping safely into a secure pocket pouch.',
    sentPromptScene: 'A boy zips his pocket tightly so he does not lose keys.',
  },
  {
    word: 'loose',
    partOfSpeech: 'adj.',
    meaningKo: '헐거운, 느슨한',
    ipa: '/luːs/',
    definition: 'not fitting tightly or not firmly attached',
    sentence: 'He wore a comfortable loose cotton shirt during the hike.',
    wordPromptScene: 'A loose belt with extra room around a cartoon waist.',
    sentPromptScene: 'A hiker wears a loose light jacket on a sunny walking path.',
  },
];

const day05_set2 = [
  {
    word: 'rather',
    partOfSpeech: 'adv.',
    meaningKo: '오히려, 다소',
    ipa: '/ˈræð.ɚ/',
    definition: 'more accurately or to some degree',
    sentence: 'She would rather read a mystery book than watch TV.',
    wordPromptScene: 'A choice fork in a pathway with two colorful road signs.',
    sentPromptScene: 'A student chooses to read an illustrated book rather than play video.',
  },
  {
    word: 'straight',
    partOfSpeech: 'adj.',
    meaningKo: '똑바른, 곧은',
    ipa: '/streɪt/',
    definition: 'continuing in one direction without bending or turning',
    sentence: 'Draw a straight line across the paper with a ruler.',
    wordPromptScene: 'A bright wooden ruler aligned with a crisp straight red line.',
    sentPromptScene: 'A student uses a blue plastic ruler to draw a straight line.',
  },
  {
    word: 'meanwhile',
    partOfSpeech: 'adv.',
    meaningKo: '그동안에, 한편',
    ipa: '/ˈmiːn.waɪl/',
    definition: 'in the period of time between two events',
    sentence: 'The soup simmered, and meanwhile she chopped fresh green lettuce.',
    wordPromptScene: 'A split-screen illustration showing baking in oven and washing dishes simultaneously.',
    sentPromptScene: 'While bread bakes in the oven, meanwhile a cook washes dishes.',
  },
  {
    word: 'continuous',
    partOfSpeech: 'adj.',
    meaningKo: '연속적인, 끊임없는',
    ipa: '/kənˈtɪn.ju.əs/',
    definition: 'going on without stopping or having any breaks',
    sentence: 'The garden fountain produces a peaceful continuous sound of water.',
    wordPromptScene: 'An unbroken glowing loop circle flowing continuously with sparkles.',
    sentPromptScene: 'Water flows in a continuous gentle stream from a stone garden fountain.',
  },
  {
    word: 'ordinary',
    partOfSpeech: 'adj.',
    meaningKo: '평범한, 보통의',
    ipa: '/ˈɔːr.dən.er.i/',
    definition: 'not special, different, or unusual in any way',
    sentence: 'It looked like an ordinary brown pebble until it sparkled.',
    wordPromptScene: 'A simple plain white ceramic coffee mug sitting on a saucer.',
    sentPromptScene: 'A child finds a hidden glittering crystal inside an ordinary grey stone.',
  },
  {
    word: 'relationship',
    partOfSpeech: 'n.',
    meaningKo: '관계',
    ipa: '/rɪˈleɪ.ʃən.ʃɪp/',
    definition: 'the way in which two people or things are connected',
    sentence: 'The two classmates built a strong friendly relationship this year.',
    wordPromptScene: 'Two friendly cartoon hands shaking with a heart floating above them.',
    sentPromptScene: 'Two smiling friends walk together, sharing a close friendly relationship.',
  },
  {
    word: 'throat',
    partOfSpeech: 'n.',
    meaningKo: '목구멍, 목',
    ipa: '/θroʊt/',
    definition: 'the front of the neck or passage inside for swallowing',
    sentence: 'A spoonful of sweet honey soothed his dry sore throat.',
    wordPromptScene: 'A cozy warm scarf wrapped gently around a neck icon.',
    sentPromptScene: 'A girl drinks warm herbal tea with honey for her throat.',
  },
  {
    word: 'encounter',
    partOfSpeech: 'v.',
    meaningKo: '마주치다, 우연히 만나다',
    ipa: '/ɪnˈkaʊn.t̬ɚ/',
    definition: 'to meet someone or experience something unexpectedly',
    sentence: 'Hikers may encounter curious deer while walking along this trail.',
    wordPromptScene: 'Two friendly cartoon animals waving to each other on a path.',
    sentPromptScene: 'Two hikers pause happily to encounter a spotted fawn in forest.',
  },
  {
    word: 'disturb',
    partOfSpeech: 'v.',
    meaningKo: '방해하다, 어지럽히다',
    ipa: '/dɪˈstɝːb/',
    definition: 'to interrupt what someone is doing or make them worry',
    sentence: 'Please walk quietly so you do not disturb sleeping babies.',
    wordPromptScene: 'A Do Not Disturb door hanger sign hanging on a wooden door knob.',
    sentPromptScene: 'A girl tiptoes softly past a bedroom door not to disturb anyone.',
  },
  {
    word: 'lead',
    partOfSpeech: 'v.',
    meaningKo: '이끌다, 안내하다',
    ipa: '/liːd/',
    definition: 'to guide someone to a place by going in front',
    sentence: 'The experienced scout will lead the group through the woods.',
    wordPromptScene: 'A glowing brass lantern lighting the path ahead for travelers.',
    sentPromptScene: 'A scout holds a map to lead companions along a forest trail.',
  },
];

const day05_set3 = [
  {
    word: 'capable',
    partOfSpeech: 'adj.',
    meaningKo: '능력 있는, ~할 수 있는',
    ipa: '/ˈkeɪ.pə.bəl/',
    definition: 'having the ability, power, or qualities to do something',
    sentence: 'The smart robot is capable of solving complex math puzzles.',
    wordPromptScene: 'A cartoon robot successfully assembling a puzzle with many mechanical arms.',
    sentPromptScene: 'A capable young student solves a difficult riddle on classroom board.',
  },
  {
    word: 'proper',
    partOfSpeech: 'adj.',
    meaningKo: '적절한, 올바른',
    ipa: '/ˈprɑː.pɚ/',
    definition: 'correct, suitable, or right for a particular purpose',
    sentence: 'Always wear proper safety gear when riding your fast skateboard.',
    wordPromptScene: 'A sturdy helmet and elbow pads arranged neatly for skateboarding.',
    sentPromptScene: 'A boy wears a proper safety helmet before riding his bicycle.',
  },
  {
    word: 'frequent',
    partOfSpeech: 'adj.',
    meaningKo: '자주 일어나는, 빈번한',
    ipa: '/ˈfriː.kwənt/',
    definition: 'happening often or at short intervals',
    sentence: 'Taking frequent water breaks is essential during hot summer soccer.',
    wordPromptScene: 'A calendar with repeating star markers on almost every weekday.',
    sentPromptScene: 'Soccer players take frequent sips of water during practice break.',
  },
  {
    word: 'symptom',
    partOfSpeech: 'n.',
    meaningKo: '증상, 징후',
    ipa: '/ˈsɪmp.təm/',
    definition: 'a physical feeling showing that you have an illness',
    sentence: 'A slight cough was the only noticeable symptom he experienced.',
    wordPromptScene: 'A digital thermometer showing a mild reading with a caring heart icon.',
    sentPromptScene: 'A caring school nurse checks a mild fever symptom on student.',
  },
  {
    word: 'monitor',
    partOfSpeech: 'v.',
    meaningKo: '관찰하다, 감시하다',
    ipa: '/ˈmɑː.nə.t̬ɚ/',
    definition: 'to watch and check a situation carefully over time',
    sentence: 'Scientists monitor weather patterns using modern satellite radar equipment daily.',
    wordPromptScene: 'A digital display screen showing steady heartbeat pulses and data waves.',
    sentPromptScene: 'A weather scientist looks at computer screens to monitor wind speeds.',
  },
  {
    word: 'consume',
    partOfSpeech: 'v.',
    meaningKo: '소비하다, 섭취하다',
    ipa: '/kənˈsuːm/',
    definition: 'to eat, drink, or use up something completely',
    sentence: 'Athletes consume plenty of fresh water during long practice sessions.',
    wordPromptScene: 'A basket of fresh crunchy apples, oranges, and a water bottle.',
    sentPromptScene: 'A thirsty runner drinks cold water to consume healthy fluids after running.',
  },
  {
    word: 'struggle',
    partOfSpeech: 'v.',
    meaningKo: '애쓰다, 고군분투하다',
    ipa: '/ˈstrʌɡ.əl/',
    definition: 'to try very hard to do something difficult',
    sentence: 'The young climber did not struggle on the practice wall.',
    wordPromptScene: 'A climber reaching firmly for the next colorful handhold on rock wall.',
    sentPromptScene: 'A determined student works hard so he does not struggle with math.',
  },
  {
    word: 'strengthen',
    partOfSpeech: 'v.',
    meaningKo: '강화하다, 튼튼하게 하다',
    ipa: '/ˈstreŋ.θən/',
    definition: 'to make someone or something stronger or more effective',
    sentence: 'Daily swimming exercises help strengthen your back and shoulder muscles.',
    wordPromptScene: 'A cartoon dumbbell surrounded by sparkling power stars.',
    sentPromptScene: 'Swimmers practice kicking in the pool to strengthen their leg muscles.',
  },
  {
    word: 'slide',
    partOfSpeech: 'v.',
    meaningKo: '미끄러지다',
    ipa: '/slaɪd/',
    definition: 'to move smoothly along a shiny or wet surface',
    sentence: 'Children love to slide across the smooth frozen ice rink.',
    wordPromptScene: 'A bright yellow playground slide with a ladder in park.',
    sentPromptScene: 'Happy penguins slide smoothly on their bellies across icy snow slopes.',
  },
  {
    word: 'slice',
    partOfSpeech: 'v.',
    meaningKo: '얇게 썰다, 자르다',
    ipa: '/slaɪs/',
    definition: 'to cut something into thin, flat pieces',
    sentence: 'Please help slice the red tomatoes for the garden salad.',
    wordPromptScene: 'A wooden cutting board with neat circular slices of fresh lemon.',
    sentPromptScene: 'A smiling chef uses a safe knife to slice fresh bread.',
  },
];

const day05_set4 = [
  {
    word: 'sufficient',
    partOfSpeech: 'adj.',
    meaningKo: '충분한',
    ipa: '/səˈfɪʃ.ənt/',
    definition: 'enough for a particular purpose or need',
    sentence: 'Make sure you get sufficient sleep before the big exam.',
    wordPromptScene: 'A glass full of milk right up to the brim line.',
    sentPromptScene: 'A backpacker packs sufficient snacks and water bottles for day hike.',
  },
  {
    word: 'fulfill',
    partOfSpeech: 'v.',
    meaningKo: '이행하다, 성취하다',
    ipa: '/fʊlˈfɪl/',
    definition: 'to do or achieve what was promised or expected',
    sentence: 'The hard-working student was able to fulfill all her promises.',
    wordPromptScene: 'A completed task checklist with golden checkmarks and star stamps.',
    sentPromptScene: 'A happy student finishes all chores to fulfill his daily family duty.',
  },
  {
    word: 'suggest',
    partOfSpeech: 'v.',
    meaningKo: '제안하다, 추천하다',
    ipa: '/səˈdʒest/',
    definition: 'to mention an idea or plan for consideration',
    sentence: 'Can you suggest a good adventure book for our club?',
    wordPromptScene: 'A glowing lightbulb thought bubble appearing above a smiling face.',
    sentPromptScene: 'A librarian points at book covers to suggest a fantasy novel.',
  },
  {
    word: 'fatigue',
    partOfSpeech: 'n.',
    meaningKo: '피로, 피곤',
    ipa: '/fəˈtiːɡ/',
    definition: 'extreme tiredness resulting from mental or physical work',
    sentence: 'A short afternoon nap helped relieve his mild body fatigue.',
    wordPromptScene: 'A cozy sleeping eye mask and a fluffy white pillow.',
    sentPromptScene: 'A tired hiker sits under a tree to recover from fatigue.',
  },
  {
    word: 'intake',
    partOfSpeech: 'n.',
    meaningKo: '섭취, 섭취량',
    ipa: '/ˈɪn.teɪk/',
    definition: 'the amount of food, drink, or air taken in',
    sentence: 'Drinking eight glasses of water provides healthy daily fluid intake.',
    wordPromptScene: 'A tall water bottle with measurement lines showing daily hydration goals.',
    sentPromptScene: 'A student drinks from a measured bottle to track water intake.',
  },
  {
    word: 'pace',
    partOfSpeech: 'n.',
    meaningKo: '속도, 보폭',
    ipa: '/peɪs/',
    definition: 'the speed at which someone walks, runs, or moves',
    sentence: 'The runner kept a steady pace throughout the long race.',
    wordPromptScene: 'A digital running watch showing pace per mile and distance.',
    sentPromptScene: 'A marathon runner maintains a steady pace along the park road.',
  },
  {
    word: 'disorder',
    partOfSpeech: 'n.',
    meaningKo: '무질서, 혼란',
    ipa: '/dɪˈsɔːr.dɚ/',
    definition: 'a state of untidiness or lack of organization',
    sentence: 'She organized the messy playroom and cleared away the disorder.',
    wordPromptScene: 'A messy desk with scattered papers being sorted into neat trays.',
    sentPromptScene: 'Children work together to clean their toy room and stop disorder.',
  },
  {
    word: 'flexible',
    partOfSpeech: 'adj.',
    meaningKo: '유연한, 융통성 있는',
    ipa: '/ˈflek.sə.bəl/',
    definition: 'able to bend easily without breaking',
    sentence: 'The gymnast is very flexible and can do high splits.',
    wordPromptScene: 'A colorful bendy ruler bending smoothly into a semicircle arch.',
    sentPromptScene: 'A flexible gymnast performs an impressive backbend on a soft mat.',
  },
  {
    word: 'supplement',
    partOfSpeech: 'n.',
    meaningKo: '보충제, 보충',
    ipa: '/ˈsʌp.lə.mənt/',
    definition: 'something added to complete something or make it better',
    sentence: 'He took a vitamin supplement with breakfast every single morning.',
    wordPromptScene: 'A bottle of chewable fruit vitamin gummies with an orange label.',
    sentPromptScene: 'A boy takes a fruit-flavored vitamin supplement with a glass of juice.',
  },
  {
    word: 'physical',
    partOfSpeech: 'adj.',
    meaningKo: '신체의, 물리적인',
    ipa: '/ˈfɪz.ɪ.kəl/',
    definition: 'relating to the body rather than the mind',
    sentence: 'Regular physical exercise keeps your heart and body strong forever.',
    wordPromptScene: 'A pair of bright running sneakers and a jump rope.',
    sentPromptScene: 'Students enjoy physical activities like jumping rope on the playground.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 5, set: 1, wordsData: day05_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 5, set: 2, wordsData: day05_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 5, set: 3, wordsData: day05_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 5, set: 4, wordsData: day05_set4 });
  console.log('DAY 05 written successfully');
}

run();
