import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 18
// ==========================================
const day18_set1 = [
  {
    word: 'stomach',
    partOfSpeech: 'n.',
    meaningKo: '위, 배',
    ipa: '/ˈstʌm.ək/',
    definition: 'the organ in your body where food goes and begins digesting',
    sentence: 'Warm vegetable soup felt very soothing on his empty upset stomach.',
    wordPromptScene: 'A cheerful cartoon bear holding a warm steaming bowl of soup.',
    sentPromptScene: 'A boy drinks warm ginger tea to soothe an upset stomach.',
  },
  {
    word: 'pill',
    partOfSpeech: 'n.',
    meaningKo: '알약',
    ipa: '/pɪl/',
    definition: 'a small round piece of medicine that you swallow with water',
    sentence: 'Drink a glass of water to swallow the daily vitamin pill.',
    wordPromptScene: 'A bottle of chewable fruit vitamin pills with a glass of water.',
    sentPromptScene: 'A student takes a fruit-flavored chewable vitamin pill at breakfast.',
  },
  {
    word: 'thumb',
    partOfSpeech: 'n.',
    meaningKo: '엄지손가락',
    ipa: '/θʌm/',
    definition: 'the short, thick first finger on the side of hand',
    sentence: 'The friendly coach raised a cheerful thumb to praise the team.',
    wordPromptScene: 'A cartoon hand giving a bright glowing thumbs-up sign of praise.',
    sentPromptScene: 'A runner gives a thumbs-up thumb gesture as he crosses the finish.',
  },
  {
    word: 'wound',
    partOfSpeech: 'n.',
    meaningKo: '상처, 부상',
    ipa: '/wuːnd/',
    definition: 'an injury to the body, especially a cut in skin',
    sentence: 'The caring school nurse placed a clean bandage on the small wound.',
    wordPromptScene: 'A colorful illustrated box of sterile cartoon band-aids with star designs.',
    sentPromptScene: 'A nurse gently cleans a knee scrape to protect the wound safely.',
  },
  {
    word: 'therapy',
    partOfSpeech: 'n.',
    meaningKo: '치료, 요법',
    ipa: '/ˈθer.ə.pi/',
    definition: 'a treatment designed to help heal an illness or injury',
    sentence: 'Gentle swimming exercises served as physical therapy for his knee recovery.',
    wordPromptScene: 'A physical therapy exercise ball and colorful resistance stretch bands.',
    sentPromptScene: 'A trainer helps an athlete perform gentle stretching exercises in therapy.',
  },
  {
    word: 'surgery',
    partOfSpeech: 'n.',
    meaningKo: '수술',
    ipa: '/ˈsɝː.dʒɚ.i/',
    definition: 'medical treatment in which a doctor cuts open the body',
    sentence: 'The kind veterinary doctor performed surgery to fix the puppy’s leg.',
    wordPromptScene: 'A clean bright modern animal clinic with gentle veterinary equipment.',
    sentPromptScene: 'A veterinarian checks a recovering puppy after a successful clinic surgery.',
  },
  {
    word: 'physician',
    partOfSpeech: 'n.',
    meaningKo: '의사, 내과의사',
    ipa: '/fɪˈzɪʃ.ən/',
    definition: 'a medical doctor, especially one who specializes in medicine',
    sentence: 'The kind family physician checked his height and listened to heartbeat.',
    wordPromptScene: 'A friendly smiling doctor wearing a white coat and holding a stethoscope.',
    sentPromptScene: 'A physician uses a stethoscope to check a healthy child’s breathing.',
  },
  {
    word: 'positive',
    partOfSpeech: 'adj.',
    meaningKo: '긍정적인, 확신하는',
    ipa: '/ˈpɑː.zə.t̬ɪv/',
    definition: 'hopeful and confident, thinking of the good qualities in situations',
    sentence: 'Keeping a positive mindset helps you solve difficult math puzzles easily.',
    wordPromptScene: 'A beaming cartoon sunshine character with a bright smiling thumbs up.',
    sentPromptScene: 'A student maintains a positive cheerful attitude while studying for exams.',
  },
  {
    word: 'grab',
    partOfSpeech: 'v.',
    meaningKo: '붙잡다, 움켜쥐다',
    ipa: '/ɡræb/',
    definition: 'to take hold of something suddenly with your hand roughly',
    sentence: 'Remember to grab your warm coat before going out into snow.',
    wordPromptScene: 'A colorful winter coat hanging on a hook ready to take.',
    sentPromptScene: 'A boy reaches out to grab his umbrella as raindrops begin falling.',
  },
  {
    word: 'grip',
    partOfSpeech: 'n.',
    meaningKo: '꽉 쥠, 손잡이',
    ipa: '/ɡrɪp/',
    definition: 'a firm, tight hold on something with your hand',
    sentence: 'The young gymnast maintained a firm grip on the parallel bars.',
    wordPromptScene: 'A rubber-textured tennis racket handle showing a comfortable non-slip grip.',
    sentPromptScene: 'A gymnast keeps a secure grip on the bar during swings.',
  },
];

const day18_set2 = [
  {
    word: 'prevent',
    partOfSpeech: 'v.',
    meaningKo: '예방하다, 막다',
    ipa: '/prɪˈvent/',
    definition: 'to stop something from happening or someone from doing something',
    sentence: 'Washing hands regularly with soap helps prevent the spread of colds.',
    wordPromptScene: 'A glowing shield protecting a bar of foamy soap and clean water.',
    sentPromptScene: 'Children wash hands with bubbly soap to prevent illness in school.',
  },
  {
    word: 'suffer',
    partOfSpeech: 'v.',
    meaningKo: '고통받다, 겪다',
    ipa: '/ˈsʌf.ɚ/',
    definition: 'to experience physical pain, illness, or unpleasant feelings',
    sentence: 'Drink warm honey tea so you do not suffer from sore throat.',
    wordPromptScene: 'A cozy warm cup of herbal tea with honey and lemon.',
    sentPromptScene: 'A student rests under a soft blanket so she does not suffer from fever.',
  },
  {
    word: 'ruin',
    partOfSpeech: 'v.',
    meaningKo: '망치다, 파괴하다',
    ipa: '/ˈruː.ɪn/',
    definition: 'to spoil or destroy something completely or severely',
    sentence: 'Do not let a sudden rainy shower ruin your picnic mood.',
    wordPromptScene: 'A pop-up canopy tent protecting a colorful picnic table from rain.',
    sentPromptScene: 'Friends move their picnic indoors so rain will not ruin their party.',
  },
  {
    word: 'organ',
    partOfSpeech: 'n.',
    meaningKo: '장기, 기관, 오르간',
    ipa: '/ˈɔːr.ɡən/',
    definition: 'a part of the body that has a particular purpose',
    sentence: 'The human heart is an amazing organ that pumps fresh blood.',
    wordPromptScene: 'An educational cartoon model of a friendly smiling heart with pulse waves.',
    sentPromptScene: 'A science teacher shows a 3D model explaining how every organ functions.',
  },
  {
    word: 'instead',
    partOfSpeech: 'adv.',
    meaningKo: '대신에',
    ipa: '/ɪnˈsted/',
    definition: 'in place of someone or something else as a substitute',
    sentence: 'She chose a crunchy fresh apple instead of sweet sugary candy.',
    wordPromptScene: 'A fresh red apple chosen beside a wrapped piece of candy.',
    sentPromptScene: 'A student drinks pure water instead of soda during soccer practice.',
  },
  {
    word: 'ankle',
    partOfSpeech: 'n.',
    meaningKo: '발목',
    ipa: '/ˈæŋ.kəl/',
    definition: 'the joint connecting your foot with your lower leg',
    sentence: 'He wore high-top athletic shoes to protect his ankle during basketball.',
    wordPromptScene: 'A high-top sports sneaker supporting an ankle with cushioned padding.',
    sentPromptScene: 'A runner ties laces securely to give good support to ankle.',
  },
  {
    word: 'nutrition',
    partOfSpeech: 'n.',
    meaningKo: '영양, 영양분',
    ipa: '/nuːˈtrɪʃ.ən/',
    definition: 'the substances you take in through food that promote health',
    sentence: 'Fresh vegetables and colorful fruits provide essential daily vitamins and nutrition.',
    wordPromptScene: 'A bowl overflowing with broccoli, carrots, berries, and whole grains.',
    sentPromptScene: 'A chef plans a balanced school lunch menu rich in good nutrition.',
  },
  {
    word: 'decrease',
    partOfSpeech: 'v.',
    meaningKo: '줄이다, 감소하다',
    ipa: '/dɪˈkriːs/',
    definition: 'to become less, or make something become smaller or lower',
    sentence: 'Regular aerobic exercise helps decrease stress and promotes peaceful good sleep.',
    wordPromptScene: 'A downward-sloping blue trend arrow with gentle calming clouds.',
    sentPromptScene: 'Deep breathing exercises help decrease nervousness before giving a school presentation.',
  },
  {
    word: 'trouble',
    partOfSpeech: 'n.',
    meaningKo: '곤란, 문제, 수고',
    ipa: '/ˈtrʌb.əl/',
    definition: 'problems, difficulties, or a situation causing worry',
    sentence: 'Good friends always help each other when someone is in trouble.',
    wordPromptScene: 'A life ring buoy thrown to a small toy boat in water.',
    sentPromptScene: 'A student helps a classmate who has trouble carrying heavy books.',
  },
  {
    word: 'seal',
    partOfSpeech: 'n.',
    meaningKo: '물개, 봉인, 직인',
    ipa: '/siːl/',
    definition: 'a sea animal with flippers, or an official wax stamp',
    sentence: 'A playful spotted seal clapped its flippers on the rocky shore.',
    wordPromptScene: 'A cute cartoon seal resting happily on a coastal rock.',
    sentPromptScene: 'Children watch a playful seal swim gracefully at the coastal sanctuary.',
  },
];

const day18_set3 = [
  {
    word: 'track',
    partOfSpeech: 'n.',
    meaningKo: '경주로, 자국, 트랙',
    ipa: '/træk/',
    definition: 'a prepared path for running races, or footprint trail marks',
    sentence: 'Athletes ran around the red circular running track at stadium.',
    wordPromptScene: 'A polished all-weather red running track with white numbered lane lines.',
    sentPromptScene: 'Runners warm up by jogging lightly along the red school track.',
  },
  {
    word: 'perhaps',
    partOfSpeech: 'adv.',
    meaningKo: '아마도, 어쩌면',
    ipa: '/pɚˈhæps/',
    definition: 'used to say that something is possible or may happen',
    sentence: 'Perhaps we can visit the science museum on sunny Saturday morning.',
    wordPromptScene: 'A cartoon character resting chin in hand looking at a map thoughtfully.',
    sentPromptScene: 'A family looks at the sky and wonders if perhaps rain will stop.',
  },
  {
    word: 'bump',
    partOfSpeech: 'v.',
    meaningKo: '부딪히다, 찧다',
    ipa: '/bʌmp/',
    definition: 'to hit something with a light blow accidentally',
    sentence: 'Walk carefully in the dark so you do not bump into furniture.',
    wordPromptScene: 'Two soft colorful bumper cars gently touching with star sparkles.',
    sentPromptScene: 'A careful student walks with eyes open not to bump into desks.',
  },
  {
    word: 'alert',
    partOfSpeech: 'adj.',
    meaningKo: '기민한, 방심하지 않는',
    ipa: '/əˈlɝːt/',
    definition: 'quick to see, understand, and act in a particular situation',
    sentence: 'The guard dog remained alert and listened to every rustling leaf.',
    wordPromptScene: 'A cartoon German Shepherd with ears perked up listening attentively.',
    sentPromptScene: 'A soccer goalkeeper stays alert watching the ball on the field.',
  },
  {
    word: 'slip',
    partOfSpeech: 'v.',
    meaningKo: '미끄러지다, 살짝 들어가다',
    ipa: '/slɪp/',
    definition: 'to slide accidentally on a wet or smooth surface',
    sentence: 'Walk slowly on the icy sidewalk so you do not slip.',
    wordPromptScene: 'A bright yellow Caution Wet Floor cone sign on shiny floor.',
    sentPromptScene: 'A hiker wears rugged rubber boots so he does not slip on rocks.',
  },
  {
    word: 'modest',
    partOfSpeech: 'adj.',
    meaningKo: '겸손한, 알맞은',
    ipa: '/ˈmɑː.dɪst/',
    definition: 'not talking proudly about your own abilities or possessions',
    sentence: 'The talented chess champion gave a modest smile after winning.',
    wordPromptScene: 'A small sweet blooming violet flower growing quietly beside stone.',
    sentPromptScene: 'A modest student thanks teammates rather than bragging about his high score.',
  },
  {
    word: 'disabled',
    partOfSpeech: 'adj.',
    meaningKo: '장애가 있는',
    ipa: '/dɪˈseɪ.bəld/',
    definition: 'having an illness or condition that makes some activities difficult',
    sentence: 'The modern school has wide ramps to assist disabled wheelchair students.',
    wordPromptScene: 'A smooth blue wheelchair access ramp with a sturdy silver handrail.',
    sentPromptScene: 'Students walk beside a disabled classmate guiding him safely along the path.',
  },
  {
    word: 'rapid',
    partOfSpeech: 'adj.',
    meaningKo: '빠른, 신속한',
    ipa: '/ˈræp.ɪd/',
    definition: 'happening in a short time or at a great speed',
    sentence: 'The cheetah made a rapid dash across the sunny savanna grass.',
    wordPromptScene: 'A sleek cartoon cheetah running with dynamic motion speed blur lines.',
    sentPromptScene: 'A train moves at rapid speed along modern magnetic levitation tracks.',
  },
  {
    word: 'spin',
    partOfSpeech: 'v.',
    meaningKo: '회전하다, 돌리다',
    ipa: '/spɪn/',
    definition: 'to turn around and around quickly in a circular motion',
    sentence: 'Children love to spin the colorful spinning top on wooden floor.',
    wordPromptScene: 'A traditional wooden spinning top spinning smoothly with blurred color bands.',
    sentPromptScene: 'A figure skater begins to spin gracefully on the smooth ice.',
  },
  {
    word: 'spine',
    partOfSpeech: 'n.',
    meaningKo: '척추, 등뼈, 책등',
    ipa: '/spaɪn/',
    definition: 'the line of bones down the center of the back',
    sentence: 'Sitting with good posture keeps your backbone spine healthy and straight.',
    wordPromptScene: 'An educational anatomical model of a healthy human spinal column.',
    sentPromptScene: 'A doctor shows a diagram explaining how a straight spine supports posture.',
  },
];

const day18_set4 = [
  {
    word: 'rare',
    partOfSpeech: 'adj.',
    meaningKo: '희귀한, 드문',
    ipa: '/rer/',
    definition: 'not common, very unusual, or not seen very often',
    sentence: 'Finding a four-leaf clover in the meadow is a rare delight.',
    wordPromptScene: 'A sparkling green four-leaf clover growing among ordinary clovers.',
    sentPromptScene: 'A botanist photographs a rare wild orchid blooming on a mountain cliff.',
  },
  {
    word: 'beat',
    partOfSpeech: 'v.',
    meaningKo: '이기다, 치다, 두드리다',
    ipa: '/biːt/',
    definition: 'to defeat an opponent in a game or hit rhythmically',
    sentence: 'Our soccer team managed to beat the champions in final minutes.',
    wordPromptScene: 'A pair of drumsticks beating a marching drum with rhythmic sound waves.',
    sentPromptScene: 'Teammates celebrate with high-fives when they beat the top team fairly.',
  },
  {
    word: 'indifferent',
    partOfSpeech: 'adj.',
    meaningKo: '무관심한, 냉담한',
    ipa: '/ɪnˈdɪf.ɚ.ənt/',
    definition: 'not caring about or interested in someone or something',
    sentence: 'The lazy cat remained indifferent to the ticking sound of clock.',
    wordPromptScene: 'A sleepy cartoon cat lounging on a windowsill ignoring a mouse toy.',
    sentPromptScene: 'A puppy plays with a ball while an older dog stays indifferent.',
  },
  {
    word: 'sew',
    partOfSpeech: 'v.',
    meaningKo: '바느질하다, 꿰매다',
    ipa: '/soʊ/',
    definition: 'to join or repair pieces of cloth by using needle and thread',
    sentence: 'Grandmother will sew a colorful patch onto his torn jeans pocket.',
    wordPromptScene: 'A shiny silver needle with red thread stitched through blue denim.',
    sentPromptScene: 'A tailor uses needle and thread to sew a button on coat.',
  },
  {
    word: 'antibiotic',
    partOfSpeech: 'n.',
    meaningKo: '항생제',
    ipa: '/ˌæn.t̬i.baɪˈɑː.t̬ɪk/',
    definition: 'a medicine that destroys harmful bacteria in the body',
    sentence: 'The doctor prescribed a mild liquid antibiotic for the ear infection.',
    wordPromptScene: 'A bottle of liquid medicine with a measuring spoon and clean cup.',
    sentPromptScene: 'A caring parent measures a dose of antibiotic syrup for a child.',
  },
  {
    word: 'chronic',
    partOfSpeech: 'adj.',
    meaningKo: '만성적인, 장기간의',
    ipa: '/ˈkrɑː.nɪk/',
    definition: 'continuing for a long time or constantly recurring over time',
    sentence: 'Regular gentle stretching helped reduce his chronic lower back stiffness.',
    wordPromptScene: 'A wall calendar marked with weekly gentle yoga exercise reminder stars.',
    sentPromptScene: 'A doctor recommends daily warm baths to ease chronic joint stiffness.',
  },
  {
    word: 'sight',
    partOfSpeech: 'n.',
    meaningKo: '시력, 광경, 시야',
    ipa: '/saɪt/',
    definition: 'the ability to see, or something that is seen',
    sentence: 'The sunrise over the snowy peaks was a truly breathtaking sight.',
    wordPromptScene: 'A pair of stylish round spectacles resting beside a nature guidebook.',
    sentPromptScene: 'Tourists gaze in awe at the magnificent sight of a mountain waterfall.',
  },
  {
    word: 'fatal',
    partOfSpeech: 'adj.',
    meaningKo: '치명적인, 결정적인',
    ipa: '/ˈfeɪ.t̬əl/',
    definition: 'causing defeat or ruin in a game, or resulting in disaster',
    sentence: 'A small chess blunder proved to be a fatal mistake in game.',
    wordPromptScene: 'A video game screen showing a Game Over shield with restart button.',
    sentPromptScene: 'A chess master avoids making a fatal move on the tournament board.',
  },
  {
    word: 'tremble',
    partOfSpeech: 'v.',
    meaningKo: '떨다, 떨리다',
    ipa: '/ˈtrem.bəl/',
    definition: 'to shake slightly because of cold, fear, or excitement',
    sentence: 'The little kitten began to tremble slightly in the cold wind.',
    wordPromptScene: 'A cartoon kitten wrapped in a warm knitted wool blanket.',
    sentPromptScene: 'A gentle puppy stops to tremble when wrapped in a cozy towel.',
  },
  {
    word: 'patient',
    partOfSpeech: 'n.',
    meaningKo: '환자',
    ipa: '/ˈpeɪ.ʃənt/',
    definition: 'a person who is receiving medical care from a doctor',
    sentence: 'The kind nurse checked the temperature of every patient in hospital.',
    wordPromptScene: 'A cozy clinic room with a comfortable bed and flower vase.',
    sentPromptScene: 'A friendly doctor talks warmly to a young patient in the clinic.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 18, set: 1, wordsData: day18_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 18, set: 2, wordsData: day18_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 18, set: 3, wordsData: day18_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 18, set: 4, wordsData: day18_set4 });
  console.log('DAY 18 written successfully');
}

run();
