import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 23
// ==========================================
const day23_set1 = [
  {
    word: 'climate',
    partOfSpeech: 'n.',
    meaningKo: '기후',
    ipa: '/ˈklaɪ.mət/',
    definition: 'the general weather conditions of a region over long periods',
    sentence: 'The Mediterranean region enjoys a warm and sunny summer climate.',
    wordPromptScene: 'A globe showing warm sunny climate zones and tropical palm trees.',
    sentPromptScene: 'Students study climate maps showing average seasonal temperatures and rainfall.',
  },
  {
    word: 'landscape',
    partOfSpeech: 'n.',
    meaningKo: '풍경, 경관',
    ipa: '/ˈlænd.skeɪp/',
    definition: 'a large area of countryside, especially in terms of its appearance',
    sentence: 'The artist painted a magnificent landscape of rolling green hills.',
    wordPromptScene: 'A picturesque landscape painting with rolling green hills, river, and mountains.',
    sentPromptScene: 'Hikers admire the breathtaking landscape view from the mountain lookout.',
  },
  {
    word: 'storm',
    partOfSpeech: 'n.',
    meaningKo: '폭풍, 폭풍우',
    ipa: '/stɔːrm/',
    definition: 'an extreme weather condition with very strong winds, rain, or snow',
    sentence: 'The sudden summer storm passed quickly, leaving a bright rainbow.',
    wordPromptScene: 'A dramatic cartoon rain cloud with lightning flashes and raindrops.',
    sentPromptScene: 'Children watch the rain storm from a cozy warm window seat.',
  },
  {
    word: 'average',
    partOfSpeech: 'adj.',
    meaningKo: '평균의, 보통의',
    ipa: '/ˈæv.ər.ɪdʒ/',
    definition: 'standard, typical, or calculated by adding and dividing quantities',
    sentence: 'The average daytime temperature in spring is around eighteen degrees.',
    wordPromptScene: 'A bar chart showing average monthly temperature lines across the year.',
    sentPromptScene: 'Students calculate the average test score for their math class project.',
  },
  {
    word: 'drown',
    partOfSpeech: 'v.',
    meaningKo: '물에 잠기다, 익사하다',
    ipa: '/draʊn/',
    definition: 'to submerge completely in liquid or die underwater',
    sentence: 'Do not drown tender garden flowers with too much water.',
    wordPromptScene: 'A small potted plant with balanced gentle water droplets around roots.',
    sentPromptScene: 'A gardener waters carefully so he will not drown delicate seedlings.',
  },
  {
    word: 'happen',
    partOfSpeech: 'v.',
    meaningKo: '일어나다, 발생하다',
    ipa: '/ˈhæp.ən/',
    definition: 'to take place or occur, especially without being planned',
    sentence: 'Unexpected magical surprises happen in this charming fairy tale book.',
    wordPromptScene: 'A magician’s top hat with sparkling stars and a bunny appearing.',
    sentPromptScene: 'Students watch an exciting chemistry color change happen before their eyes.',
  },
  {
    word: 'rough',
    partOfSpeech: 'adj.',
    meaningKo: '거친, 험한',
    ipa: '/rʌf/',
    definition: 'not smooth, having an uneven or bumpy surface texture',
    sentence: 'The ancient pine tree had very thick and rough bark.',
    wordPromptScene: 'A piece of textured rough sandpaper resting beside smooth polished wood.',
    sentPromptScene: 'Hikers wear sturdy rubber-soled boots to walk along the rough path.',
  },
  {
    word: 'geography',
    partOfSpeech: 'n.',
    meaningKo: '지리학, 지리',
    ipa: '/dʒiˈɑː.ɡrə.fi/',
    definition: 'the study of the physical features of the earth and atmosphere',
    sentence: 'In geography class, we learned the names of seven world continents.',
    wordPromptScene: 'A colorful vintage globe, world atlas book, and brass magnifying glass.',
    sentPromptScene: 'Students point out major rivers on a large classroom geography wall map.',
  },
  {
    word: 'effect',
    partOfSpeech: 'n.',
    meaningKo: '영향, 효과, 결과',
    ipa: '/əˈfekt/',
    definition: 'a change that is a result or consequence of an action',
    sentence: 'Drinking warm water had an immediate soothing effect on his throat.',
    wordPromptScene: 'A water droplet hitting a calm pool creating perfect glowing ripples.',
    sentPromptScene: 'A science teacher explains the positive effect of sunlight on green plants.',
  },
  {
    word: 'affect',
    partOfSpeech: 'v.',
    meaningKo: '영향을 미치다',
    ipa: '/əˈfekt/',
    definition: 'to have an influence on someone or something, cause a change',
    sentence: 'Seasonal weather changes strongly affect how animals migrate south in winter.',
    wordPromptScene: 'Sunlight and rain clouds influencing the growth of a young sprout.',
    sentPromptScene: 'Students study how temperature changes affect the speed of chemical reactions.',
  },
];

const day23_set2 = [
  {
    word: 'valley',
    partOfSpeech: 'n.',
    meaningKo: '계곡, 골짜기',
    ipa: '/ˈvæl.i/',
    definition: 'a low area of land between hills or mountains, often with river',
    sentence: 'A crystal clear river flowed gently through the green mountain valley.',
    wordPromptScene: 'A lush green valley flanked by towering mountains with a winding river.',
    sentPromptScene: 'Hikers look down into the breathtaking valley dotted with cozy farmhouses.',
  },
  {
    word: 'influence',
    partOfSpeech: 'n.',
    meaningKo: '영향, 영향력',
    ipa: '/ˈɪn.flu.əns/',
    definition: 'the power to have an effect on people or things',
    sentence: 'Music has a very positive and calming influence on young learners.',
    wordPromptScene: 'Gentle musical notes radiating outward and turning into blooming flower buds.',
    sentPromptScene: 'A great teacher has a lasting positive influence on all her students.',
  },
  {
    word: 'damage',
    partOfSpeech: 'n.',
    meaningKo: '손상, 피해',
    ipa: '/ˈdæm.ɪdʒ/',
    definition: 'physical harm caused to something that impairs its value or function',
    sentence: 'The strong storm caused minor leaf damage to the garden bushes.',
    wordPromptScene: 'A sturdy wooden birdhouse with a slightly loose roof shingle repaired.',
    sentPromptScene: 'Volunteers clean up fallen tree branches to repair small storm damage.',
  },
  {
    word: 'lack',
    partOfSpeech: 'n.',
    meaningKo: '부족, 결핍',
    ipa: '/læk/',
    definition: 'the state of being without or not having enough of something',
    sentence: 'A lack of rain made the garden soil dry and dusty.',
    wordPromptScene: 'A watering can gently watering dry soil to restore healthy moisture.',
    sentPromptScene: 'A gardener adds compost so plants will not suffer from lack of nutrients.',
  },
  {
    word: 'predict',
    partOfSpeech: 'v.',
    meaningKo: '예측하다, 예언하다',
    ipa: '/prɪˈdɪkt/',
    definition: 'to say what will happen in the future based on facts',
    sentence: 'Modern satellites help meteorologists predict tomorrow’s weather with great accuracy.',
    wordPromptScene: 'A glowing digital weather forecast screen showing sunny sun and rain icons.',
    sentPromptScene: 'A young weather presenter uses radar maps to predict sunny weekend weather.',
  },
  {
    word: 'aware',
    partOfSpeech: 'adj.',
    meaningKo: '알고 있는, 의식하는',
    ipa: '/əˈwer/',
    definition: 'knowing that something exists or having knowledge of a situation',
    sentence: 'Hikers should be aware of changing weather conditions on mountains.',
    wordPromptScene: 'A cartoon scout pointing attentively at a trail weather warning sign.',
    sentPromptScene: 'Students become aware of energy conservation by turning off classroom lights.',
  },
  {
    word: 'correct',
    partOfSpeech: 'adj.',
    meaningKo: '정확한, 올바른',
    ipa: '/kəˈrekt/',
    definition: 'accurate, without any mistakes, or conforming to truth',
    sentence: 'She was proud to give the correct answer in math.',
    wordPromptScene: 'A green checkmark badge next to an A-plus grade stamp.',
    sentPromptScene: 'A teacher puts a golden star next to the correct spelling test word.',
  },
  {
    word: 'earthquake',
    partOfSpeech: 'n.',
    meaningKo: '지진',
    ipa: '/ˈɝːθ.kweɪk/',
    definition: 'a sudden violent shaking of the ground caused by movements in crust',
    sentence: 'Students practiced safe duck and cover drills during the earthquake drill.',
    wordPromptScene: 'A seismograph recording machine with a needle drawing needle wave vibrations.',
    sentPromptScene: 'Children take shelter under sturdy desks during a school earthquake safety drill.',
  },
  {
    word: 'due',
    partOfSpeech: 'adj.',
    meaningKo: '~하기로 되어 있는, 만기의',
    ipa: '/duː/',
    definition: 'expected or planned to happen at a certain time',
    sentence: 'Our completed science research project is due this Friday morning.',
    wordPromptScene: 'A calendar page with an urgent red circled date and checklist.',
    sentPromptScene: 'A student completes her book report because it is due tomorrow.',
  },
  {
    word: 'level',
    partOfSpeech: 'n.',
    meaningKo: '수준, 높이, 수위',
    ipa: '/ˈlev.əl/',
    definition: 'the height, amount, or standard of something measured',
    sentence: 'Rainfall raised the water level in the reservoir safely.',
    wordPromptScene: 'A clear measuring beaker showing blue water resting at the top line.',
    sentPromptScene: 'A park ranger monitors the steady water level of the nature pond.',
  },
];

const day23_set3 = [
  {
    word: 'shift',
    partOfSpeech: 'v.',
    meaningKo: '이동하다, 바꾸다, 변화',
    ipa: '/ʃɪft/',
    definition: 'to move or change from one position or direction to another',
    sentence: 'Winds began to shift from the north to the south.',
    wordPromptScene: 'A weather vane rooster spinning gently to point in a new direction.',
    sentPromptScene: 'Sailors adjust the white sails as winds shift across the bay.',
  },
  {
    word: 'narrow',
    partOfSpeech: 'adj.',
    meaningKo: '좁은, 좁아지다',
    ipa: '/ˈner.oʊ/',
    definition: 'measuring only a small distance from one side to other',
    sentence: 'The hikers carefully crossed the narrow wooden bridge over stream.',
    wordPromptScene: 'A charming narrow stone footbridge crossing a bubbling forest brook.',
    sentPromptScene: 'A group of backpackers walks along a narrow scenic mountain ledge trail.',
  },
  {
    word: 'drought',
    partOfSpeech: 'n.',
    meaningKo: '가뭄',
    ipa: '/draʊt/',
    definition: 'a long period of time when there is little or no rain',
    sentence: 'Farmers built water reservoirs to protect crops during summer drought.',
    wordPromptScene: 'A dry cracked soil patch being revitalized with fresh irrigation sprinkler droplets.',
    sentPromptScene: 'A farmer waters crops using saved rainwater during a dry summer drought.',
  },
  {
    word: 'boundary',
    partOfSpeech: 'n.',
    meaningKo: '경계, 한계',
    ipa: '/ˈbaʊn.dɚ.i/',
    definition: 'an edge or line marking the limits of an area',
    sentence: 'A low wooden fence marked the boundary of the nature reserve.',
    wordPromptScene: 'A rustic split-rail wooden fence running along a blooming wildflower meadow.',
    sentPromptScene: 'A park map highlights the boundary of the protected bird sanctuary reserve.',
  },
  {
    word: 'alarming',
    partOfSpeech: 'adj.',
    meaningKo: '걱정스러운, 놀라운',
    ipa: '/əˈlɑːr.mɪŋ/',
    definition: 'causing worry, fear, or serious concern about a situation',
    sentence: 'The rapid drop in evening temperature was an alarming weather sign.',
    wordPromptScene: 'A thermometer showing a sudden steep temperature drop with snowflake icons.',
    sentPromptScene: 'Campers pack up gear after hearing an alarming weather storm alert on radio.',
  },
  {
    word: 'harsh',
    partOfSpeech: 'adj.',
    meaningKo: '가혹한, 거친',
    ipa: '/hɑːrʃ/',
    definition: 'unpleasant, severe, or difficult to live in for creatures',
    sentence: 'Penguins have thick feathers to survive the harsh arctic winter.',
    wordPromptScene: 'A group of emperor penguins huddled together warmly against snowy wind.',
    sentPromptScene: 'Explorers wear heavy thermal gear to withstand the harsh polar climate.',
  },
  {
    word: 'cease',
    partOfSpeech: 'v.',
    meaningKo: '중단되다, 멈추다',
    ipa: '/siːs/',
    definition: 'to stop happening or to stop doing something completely',
    sentence: 'The pouring rain began to cease as blue sky appeared.',
    wordPromptScene: 'Rain clouds parting to reveal a brilliant warm yellow sunshine beam.',
    sentPromptScene: 'Children run outdoors as raindrops cease and sunshine fills the playground.',
  },
  {
    word: 'estimate',
    partOfSpeech: 'v.',
    meaningKo: '추정하다, 어림잡다',
    ipa: '/ˈes.tə.meɪt/',
    definition: 'to guess or calculate the cost, size, or amount roughly',
    sentence: 'We can estimate that the hike will take about two hours.',
    wordPromptScene: 'A notepad with rough distance calculations, a ruler, and a pencil.',
    sentPromptScene: 'Students use math skills to estimate the number of marbles in jar.',
  },
  {
    word: 'plane',
    partOfSpeech: 'n.',
    meaningKo: '비행기, 평면',
    ipa: '/pleɪn/',
    definition: 'a vehicle with wings that flies through the air',
    sentence: 'The silver passenger plane soared gracefully above the white clouds.',
    wordPromptScene: 'A sleek white passenger airplane cruising through fluffy sunlit clouds.',
    sentPromptScene: 'Children wave at a passenger plane flying high in the blue sky.',
  },
  {
    word: 'plain',
    partOfSpeech: 'n.',
    meaningKo: '평원, 평지',
    ipa: '/pleɪn/',
    definition: 'a large area of flat land with few or no trees',
    sentence: 'Herds of wild bison grazed across the vast grassy plain.',
    wordPromptScene: 'A vast golden grassy prairie plain stretching under an open blue sky.',
    sentPromptScene: 'Tourists take pictures of wildflowers growing across the wide open plain.',
  },
];

const day23_set4 = [
  {
    word: 'forecast',
    partOfSpeech: 'n.',
    meaningKo: '예보, 예측',
    ipa: '/ˈfɔːr.kæst/',
    definition: 'a statement of what the weather will be like in future',
    sentence: 'The morning weather forecast predicted sunny skies all weekend long.',
    wordPromptScene: 'A TV weather graphic showing bright sunshine and warm temperature numbers.',
    sentPromptScene: 'A family checks the weekend forecast before planning a beach camping trip.',
  },
  {
    word: 'incident',
    partOfSpeech: 'n.',
    meaningKo: '사건, 일어난 일',
    ipa: '/ˈɪn.sə.dənt/',
    definition: 'an event that is either unpleasant or unusual in occurrence',
    sentence: 'The park ranger recorded the small trail lost compass incident.',
    wordPromptScene: 'A park ranger clipboard with a checklist and a friendly star badge.',
    sentPromptScene: 'A guide calmly resolves a minor incident involving a dropped hiking map.',
  },
  {
    word: 'continent',
    partOfSpeech: 'n.',
    meaningKo: '대륙',
    ipa: '/ˈkɑːn.t̬ən.ənt/',
    definition: 'one of the seven large land masses on the earth',
    sentence: 'Antarctica is the coldest and windiest continent on planet Earth.',
    wordPromptScene: 'A colorful world map highlighting the seven continents with distinct colors.',
    sentPromptScene: 'A geography teacher points out the continent of Asia on a globe.',
  },
  {
    word: 'spoil',
    partOfSpeech: 'v.',
    meaningKo: '망치다, 상하다',
    ipa: '/spɔɪl/',
    definition: 'to destroy or reduce the pleasure or quality of something',
    sentence: 'Do not let a little rain spoil your cheerful mood.',
    wordPromptScene: 'A fresh ripe red apple kept cool and fresh inside a refrigerator.',
    sentPromptScene: 'Children play board games indoors so bad weather will not spoil fun.',
  },
  {
    word: 'tremendous',
    partOfSpeech: 'adj.',
    meaningKo: '엄청난, 대단한',
    ipa: '/trɪˈmen.dəs/',
    definition: 'extremely large, great, or impressive in amount or scale',
    sentence: 'The waterfall roared with tremendous power over the high cliff.',
    wordPromptScene: 'A massive magnificent waterfall roaring with white foam and rainbows.',
    sentPromptScene: 'The young orchestra receives tremendous applause from the proud school audience.',
  },
  {
    word: 'steep',
    partOfSpeech: 'adj.',
    meaningKo: '가파른, 비탈진',
    ipa: '/stiːp/',
    definition: 'rising or falling at a sharp, sudden upward angle',
    sentence: 'Hikers climbed the steep rocky trail with great careful balance.',
    wordPromptScene: 'A steep mountain trail with carved stone steps climbing up cliffside.',
    sentPromptScene: 'Climbers use walking poles to assist their ascent up a steep slope.',
  },
  {
    word: 'territory',
    partOfSpeech: 'n.',
    meaningKo: '영역, 영토',
    ipa: '/ˈter.ə.tɔːr.i/',
    definition: 'an area of land that is considered to belong to animal/state',
    sentence: 'The majestic lion guarded his vast grassland territory with pride.',
    wordPromptScene: 'A majestic lion standing proudly on a high savanna rock overlooking land.',
    sentPromptScene: 'A park ranger marks the boundary of the protected wildlife reserve territory.',
  },
  {
    word: 'split',
    partOfSpeech: 'v.',
    meaningKo: '쪼개다, 나누다',
    ipa: '/splɪt/',
    definition: 'to divide into two or more parts, or break along a line',
    sentence: 'They decided to split the fresh baked loaf of bread.',
    wordPromptScene: 'A fresh golden baguette loaf split neatly into two steaming halves.',
    sentPromptScene: 'Two friends agree to split a large watermelon evenly for lunch snack.',
  },
  {
    word: 'flash',
    partOfSpeech: 'n.',
    meaningKo: '섬광, 번쩍임',
    ipa: '/flæʃ/',
    definition: 'a sudden bright light that shines for a very short time',
    sentence: 'A bright flash of camera light captured their happy smiles.',
    wordPromptScene: 'A vintage camera lens emitting a brilliant golden starburst flash of light.',
    sentPromptScene: 'A photographer uses a gentle flash to take pictures of school graduates.',
  },
  {
    word: 'deposit',
    partOfSpeech: 'n.',
    meaningKo: '퇴적물, 예금, 보증금',
    ipa: '/dɪˈpɑː.zɪt/',
    definition: 'a layer of substance that has accumulated naturally on ground',
    sentence: 'The river left a rich mineral deposit along the farm fields.',
    wordPromptScene: 'A river bank showing rich dark silt deposits with green shoots sprouting.',
    sentPromptScene: 'A geologist examines a rich mineral deposit embedded in limestone layers.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 23, set: 1, wordsData: day23_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 23, set: 2, wordsData: day23_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 23, set: 3, wordsData: day23_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 23, set: 4, wordsData: day23_set4 });
  console.log('DAY 23 written successfully');
}

run();
