import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 12
// ==========================================
const day12_set1 = [
  {
    word: 'perform',
    partOfSpeech: 'v.',
    meaningKo: '공연하다, 수행하다',
    ipa: '/pɚˈfɔːrm/',
    definition: 'to entertain an audience by singing, dancing, or acting',
    sentence: 'The young musicians will perform three classical songs on stage.',
    wordPromptScene: 'A shiny wooden violin and sheet music on a well-lit stage.',
    sentPromptScene: 'Children perform a cheerful puppet play behind a colorful wooden booth.',
  },
  {
    word: 'feature',
    partOfSpeech: 'n.',
    meaningKo: '특징, 특색',
    ipa: '/ˈfiː.tʃɚ/',
    definition: 'a noticeable or important part or characteristic of something',
    sentence: 'A long trunk is the most noticeable physical feature of elephants.',
    wordPromptScene: 'A cute cartoon elephant happily spraying water from its long trunk.',
    sentPromptScene: 'A scientist points out a special design feature on the solar rover.',
  },
  {
    word: 'genre',
    partOfSpeech: 'n.',
    meaningKo: '장르, 유형',
    ipa: '/ˈʒɑːn.rə/',
    definition: 'a particular style or category of art, music, or literature',
    sentence: 'Fantasy is her favorite book genre with magical talking animals.',
    wordPromptScene: 'Four distinct book covers representing sci-fi, mystery, fantasy, and history.',
    sentPromptScene: 'A librarian introduces a new adventure story genre to young readers.',
  },
  {
    word: 'instrument',
    partOfSpeech: 'n.',
    meaningKo: '악기, 도구',
    ipa: '/ˈɪn.strə.mənt/',
    definition: 'an object used for producing musical sounds, or a tool',
    sentence: 'He chose the acoustic guitar as his main musical instrument.',
    wordPromptScene: 'A golden saxophone, acoustic guitar, and silver flute arranged together.',
    sentPromptScene: 'A student practices plucking strings on a musical instrument in music room.',
  },
  {
    word: 'broadcast',
    partOfSpeech: 'v.',
    meaningKo: '방송하다, 방영하다',
    ipa: '/ˈbrɑːd.kæst/',
    definition: 'to send out sound or pictures by radio or television',
    sentence: 'The school station will broadcast morning news announcements to classrooms.',
    wordPromptScene: 'A radio transmission tower emitting glowing curved signal broadcast waves.',
    sentPromptScene: 'Students speak into microphones to broadcast the school morning news.',
  },
  {
    word: 'artwork',
    partOfSpeech: 'n.',
    meaningKo: '미술품, 예술 작품',
    ipa: '/ˈɑːrt.wɝːk/',
    definition: 'paintings, sculptures, and drawings created by an artist',
    sentence: 'Students displayed their colorful ceramic artwork in the school hallway.',
    wordPromptScene: 'A vibrant clay vase with hand-painted swirl patterns on a pedestal.',
    sentPromptScene: 'Proud students stand beside their creative clay artwork in art class.',
  },
  {
    word: 'suit',
    partOfSpeech: 'v.',
    meaningKo: '어울리다, 적합하다',
    ipa: '/suːt/',
    definition: 'to look good on someone or be convenient for them',
    sentence: 'Bright yellow colors suit her cheerful and energetic personality well.',
    wordPromptScene: 'A mirror reflecting a bright yellow stylish cartoon hoodie.',
    sentPromptScene: 'A girl wears a sunny yellow hat that will suit her.',
  },
  {
    word: 'inspire',
    partOfSpeech: 'v.',
    meaningKo: '영감을 주다, 고무하다',
    ipa: '/ɪnˈspaɪr/',
    definition: 'to make someone feel that they want to do something creative',
    sentence: 'Beautiful nature scenes inspire the young painter to create art.',
    wordPromptScene: 'A glowing colorful lightbulb surrounded by flying paint splatters.',
    sentPromptScene: 'A stunning sunset landscape can inspire a painter sitting outdoors.',
  },
  {
    word: 'belief',
    partOfSpeech: 'n.',
    meaningKo: '신념, 믿음',
    ipa: '/bɪˈliːf/',
    definition: 'a feeling of certainty that something exists or is true',
    sentence: 'She had a strong belief in the power of kindness.',
    wordPromptScene: 'A glowing golden heart held securely within two gentle cartoon hands.',
    sentPromptScene: 'A team stands together sharing a common belief in fair play.',
  },
  {
    word: 'brief',
    partOfSpeech: 'adj.',
    meaningKo: '짧은, 간단한',
    ipa: '/briːf/',
    definition: 'lasting only a short time or using few words',
    sentence: 'The coach gave a brief talk before the soccer kickoff.',
    wordPromptScene: 'A small notepad with three short bullet points and a pencil.',
    sentPromptScene: 'A speaker gives a brief introduction before the science movie begins.',
  },
];

const day12_set2 = [
  {
    word: 'upset',
    partOfSpeech: 'adj.',
    meaningKo: '속상한, 화난',
    ipa: '/ʌpˈset/',
    definition: 'unhappy, disappointed, or worried because of something bad',
    sentence: 'The little girl was upset after losing her favorite hairclip.',
    wordPromptScene: 'A cartoon kitten with sad downturned ears and a caring hug.',
    sentPromptScene: 'A caring friend comforts a classmate who feels slightly upset today.',
  },
  {
    word: 'respond',
    partOfSpeech: 'v.',
    meaningKo: '응답하다, 반응하다',
    ipa: '/rɪˈspɑːnd/',
    definition: 'to say or do something as an answer or reaction',
    sentence: 'Please respond promptly to the birthday party invitation by Friday.',
    wordPromptScene: 'An open envelope with a smiling green RSVP reply checkmark.',
    sentPromptScene: 'A student raises her hand to respond to the teacher’s question.',
  },
  {
    word: 'steady',
    partOfSpeech: 'adj.',
    meaningKo: '안정된, 꾸준한',
    ipa: '/ˈsted.i/',
    definition: 'not shaking or moving, continuing in a reliable way',
    sentence: 'He held a steady hand while painting fine details on ceramic.',
    wordPromptScene: 'A balanced stack of smooth stones standing firmly by a stream.',
    sentPromptScene: 'A young archer maintains a steady grip before releasing the arrow.',
  },
  {
    word: 'dislike',
    partOfSpeech: 'v.',
    meaningKo: '싫어하다',
    ipa: '/dɪˈslaɪk/',
    definition: 'to not like someone or something',
    sentence: 'Some children dislike eating bitter green bell peppers with dinner.',
    wordPromptScene: 'A cartoon character gently nudging away a plate of bitter greens.',
    sentPromptScene: 'A child politely explains why some people dislike spicy mustard sauce.',
  },
  {
    word: 'define',
    partOfSpeech: 'v.',
    meaningKo: '정의하다, 명시하다',
    ipa: '/dɪˈfaɪn/',
    definition: 'to explain and describe the exact meaning of a word',
    sentence: 'Can you define the word habitat using your own simple words?',
    wordPromptScene: 'An open dictionary with a magnifying glass hovering over highlighted text.',
    sentPromptScene: 'A student uses clear examples to define a new scientific term.',
  },
  {
    word: 'celebrity',
    partOfSpeech: 'n.',
    meaningKo: '유명인사, 유명인',
    ipa: '/səˈleb.rə.t̬i/',
    definition: 'a person who is famous, especially in entertainment or sports',
    sentence: 'The Olympic runner became a popular sports celebrity across the nation.',
    wordPromptScene: 'A gold star embedded in a sparkling red carpet walkway.',
    sentPromptScene: 'Fans wave cheerfully as a friendly sports celebrity visits the school.',
  },
  {
    word: 'genius',
    partOfSpeech: 'n.',
    meaningKo: '천재, 비범한 재능',
    ipa: '/ˈdʒiː.ni.əs/',
    definition: 'someone with exceptionally high intelligence or extraordinary skill',
    sentence: 'Albert Einstein was recognized as a scientific genius worldwide.',
    wordPromptScene: 'A glowing cartoon lightbulb wearing spectacles and solving a Rubik’s cube.',
    sentPromptScene: 'A math genius solves a giant chalkboard calculation with a smile.',
  },
  {
    word: 'visual',
    partOfSpeech: 'adj.',
    meaningKo: '시각의, 눈에 보이는',
    ipa: '/ˈvɪʒ.u.əl/',
    definition: 'relating to seeing or to things that can be seen',
    sentence: 'Colorful visual charts help students understand solar system planets better.',
    wordPromptScene: 'A colorful poster showing eye-catching infographics, charts, and diagrams.',
    sentPromptScene: 'A teacher uses bright visual slides to illustrate ancient world history.',
  },
  {
    word: 'compose',
    partOfSpeech: 'v.',
    meaningKo: '작곡하다, 구성하다',
    ipa: '/kəmˈpoʊz/',
    definition: 'to write music, poetry, or a letter with care',
    sentence: 'The young musician learned to compose gentle piano melodies daily.',
    wordPromptScene: 'A fountain pen writing musical notes on a blank sheet scroll.',
    sentPromptScene: 'A girl sits at the piano to compose a melody for festival.',
  },
  {
    word: 'deal',
    partOfSpeech: 'n.',
    meaningKo: '거래, 합의',
    ipa: '/diːl/',
    definition: 'an agreement or arrangement, especially in business or sports',
    sentence: 'They made a fair deal to trade two collectible cards.',
    wordPromptScene: 'Two friendly hands shaking over a pair of shiny trading cards.',
    sentPromptScene: 'Friends make a friendly deal to take turns on the swing.',
  },
];

const day12_set3 = [
  {
    word: 'poll',
    partOfSpeech: 'n.',
    meaningKo: '여론조사, 투표',
    ipa: '/poʊl/',
    definition: 'a survey of people’s opinions on a particular subject',
    sentence: 'The classroom poll showed pizza as the favorite lunch choice.',
    wordPromptScene: 'A clear ballot box with colorful voting slips being inserted.',
    sentPromptScene: 'Students cast paper votes in a class poll for class mascot.',
  },
  {
    word: 'pitch',
    partOfSpeech: 'n.',
    meaningKo: '음의 높낮이, 투구',
    ipa: '/pɪtʃ/',
    definition: 'the highness or lowness of a musical sound tone',
    sentence: 'The soprano singer reached a very high pitch effortlessly today.',
    wordPromptScene: 'A musical tuning fork vibrating with shimmering sound wave lines.',
    sentPromptScene: 'A music teacher shows how violin strings change in sound pitch.',
  },
  {
    word: 'eager',
    partOfSpeech: 'adj.',
    meaningKo: '열망하는, 간절히 바라는',
    ipa: '/ˈiː.ɡɚ/',
    definition: 'wanting very much to do or have something good',
    sentence: 'The eager puppy waited by the front door for his walk.',
    wordPromptScene: 'A cute cartoon puppy wagging its tail eagerly beside a leash.',
    sentPromptScene: 'Eager students raise their hands to volunteer for the school play.',
  },
  {
    word: 'silly',
    partOfSpeech: 'adj.',
    meaningKo: '어리석은, 우스꽝스러운',
    ipa: '/ˈsɪl.i/',
    definition: 'showing a lack of thought or being playfully funny',
    sentence: 'He wore a silly giant foam hat to the carnival.',
    wordPromptScene: 'A colorful clown hat with jingle bells and polka dot patterns.',
    sentPromptScene: 'Children laugh together while making silly faces for a photo booth.',
  },
  {
    word: 'furious',
    partOfSpeech: 'adj.',
    meaningKo: '몹시 화난, 맹렬한',
    ipa: '/ˈfjʊr.i.əs/',
    definition: 'extremely angry, or showing great violent energy in weather',
    sentence: 'The furious winter gale shook the sturdy wooden cabin walls.',
    wordPromptScene: 'A cartoon storm cloud blowing swirling snowflakes with dramatic intensity.',
    sentPromptScene: 'Hikers stay safe inside a cabin during a furious winter blizzard.',
  },
  {
    word: 'barely',
    partOfSpeech: 'adv.',
    meaningKo: '간신히, 거의 ~않게',
    ipa: '/ˈber.li/',
    definition: 'by the smallest amount, almost not at all',
    sentence: 'We could barely hear the quiet whisper across the room.',
    wordPromptScene: 'A tiny sliver of a crescent moon peeking through dark clouds.',
    sentPromptScene: 'A hiker could barely see the trail through thick morning mountain fog.',
  },
  {
    word: 'thrill',
    partOfSpeech: 'n.',
    meaningKo: '스릴, 짜릿한 흥분',
    ipa: '/θrɪl/',
    definition: 'a sudden feeling of great excitement and pleasure',
    sentence: 'Riding the water slide gave the children a wonderful thrill.',
    wordPromptScene: 'A splash of water droplets over a winding bright water slide.',
    sentPromptScene: 'Riders shout in joy as they feel the thrill on a coaster.',
  },
  {
    word: 'particular',
    partOfSpeech: 'adj.',
    meaningKo: '특정한, 특별한',
    ipa: '/pɚˈtɪk.jə.lɚ/',
    definition: 'special, specific, or relating to one thing only',
    sentence: 'She was looking for one particular book about desert animals.',
    wordPromptScene: 'A magnifying glass highlighting a single red book among blue ones.',
    sentPromptScene: 'A student searches the shelf for a particular historical reference guide.',
  },
  {
    word: 'constant',
    partOfSpeech: 'adj.',
    meaningKo: '끊임없는, 일정한',
    ipa: '/ˈkɑːn.stənt/',
    definition: 'happening all the time or staying at the same rate',
    sentence: 'The mountain stream flowed with a steady constant rushing sound.',
    wordPromptScene: 'A continuous flowing circular blue arrow loop showing ongoing motion.',
    sentPromptScene: 'The ticking clock makes a constant gentle sound in the quiet study.',
  },
  {
    word: 'consistent',
    partOfSpeech: 'adj.',
    meaningKo: '한결같은, 일관된',
    ipa: '/kənˈsɪs.tənt/',
    definition: 'always behaving or happening in a similar, positive way',
    sentence: 'His consistent daily practice made him a champion tennis player.',
    wordPromptScene: 'A row of three identical bullseye hits on an archery target.',
    sentPromptScene: 'A dedicated student shows consistent effort by completing all homework daily.',
  },
];

const day12_set4 = [
  {
    word: 'employ',
    partOfSpeech: 'v.',
    meaningKo: '고용하다, 쓰다',
    ipa: '/ɪmˈplɔɪ/',
    definition: 'to pay someone to work for you or use a technique',
    sentence: 'The bakery decided to employ two assistants for morning bread.',
    wordPromptScene: 'A friendly business handshake with a Welcome to Team badge.',
    sentPromptScene: 'A shop owner smiles as she will employ new student helpers.',
  },
  {
    word: 'illusion',
    partOfSpeech: 'n.',
    meaningKo: '착각, 환상',
    ipa: '/ɪˈluː.ʒən/',
    definition: 'something that looks real but is not actually real',
    sentence: 'The clever street artist painted a 3D illusion on pavement.',
    wordPromptScene: 'An optical spiral illusion pattern that seems to move when viewed.',
    sentPromptScene: 'Passersby marvel at a 3D sidewalk chalk illusion of a waterfall.',
  },
  {
    word: 'funeral',
    partOfSpeech: 'n.',
    meaningKo: '장례식, 추모식',
    ipa: '/ˈfjuː.nɚ.əl/',
    definition: 'a ceremony held to remember and honor a deceased person',
    sentence: 'Townspeople gathered for a peaceful memorial funeral in the chapel.',
    wordPromptScene: 'A bouquet of white lilies resting peacefully beside a candle.',
    sentPromptScene: 'Quiet mourners hold white flowers at a peaceful memorial chapel service.',
  },
  {
    word: 'whisper',
    partOfSpeech: 'v.',
    meaningKo: '속삭이다, 귓속말하다',
    ipa: '/ˈwɪs.pɚ/',
    definition: 'to speak very softly using your breath, not voice',
    sentence: 'Please whisper quietly while we are inside the reading library.',
    wordPromptScene: 'Two cute cartoon mice sharing a secret with cupped paws.',
    sentPromptScene: 'Two students whisper quietly to each other during silent study time.',
  },
  {
    word: 'elaborate',
    partOfSpeech: 'adj.',
    meaningKo: '정교한, 공들인',
    ipa: '/iˈlæb.ɚ.ət/',
    definition: 'containing a lot of careful detail or complicated parts',
    sentence: 'The palace ceiling featured an elaborate design of golden leaves.',
    wordPromptScene: 'An intricately carved wooden jewelry box with fine decorative floral filigree.',
    sentPromptScene: 'An artist creates an elaborate paper sculpture with hundreds of folds.',
  },
  {
    word: 'bunch',
    partOfSpeech: 'n.',
    meaningKo: '다발, 송이',
    ipa: '/bʌntʃ/',
    definition: 'a number of things of the same type tied together',
    sentence: 'He bought a fresh bunch of ripe yellow bananas today.',
    wordPromptScene: 'A vibrant bunch of fresh yellow bananas and red grapes.',
    sentPromptScene: 'A boy carries a colorful bunch of balloons to the party.',
  },
  {
    word: 'atmosphere',
    partOfSpeech: 'n.',
    meaningKo: '분위기, 대기',
    ipa: '/ˈæt.məs.fɪr/',
    definition: 'the mood of a place or the air surrounding Earth',
    sentence: 'The cozy cafe had a warm and friendly holiday atmosphere.',
    wordPromptScene: 'Planet Earth surrounded by a glowing gentle blue halo atmosphere layer.',
    sentPromptScene: 'Fairy lights and soft music create a cozy atmosphere in cafe.',
  },
  {
    word: 'escape',
    partOfSpeech: 'v.',
    meaningKo: '탈출하다, 벗어나다',
    ipa: '/ɪˈskeɪp/',
    definition: 'to get free from a place or avoid something bad',
    sentence: 'The little mouse was able to escape into its burrow.',
    wordPromptScene: 'An open golden birdcage with a happy bird soaring into sky.',
    sentPromptScene: 'A cute bunny hops through a fence hole to escape quickly.',
  },
  {
    word: 'cultivate',
    partOfSpeech: 'v.',
    meaningKo: '경작하다, 기르다',
    ipa: '/ˈkʌl.tə.veɪt/',
    definition: 'to prepare land and grow crops, or develop skills',
    sentence: 'Farmers cultivate sweet strawberries in sunny greenhouse rows all spring.',
    wordPromptScene: 'Neat garden soil beds with young green strawberry plants sprouting.',
    sentPromptScene: 'A gardener uses a trowel to cultivate rich soil for flowers.',
  },
  {
    word: 'cast',
    partOfSpeech: 'v.',
    meaningKo: '던지다, 배역을 맡기다',
    ipa: '/kæst/',
    definition: 'to throw something, or choose actors for a play',
    sentence: 'The drama director will cast students for the spring play.',
    wordPromptScene: 'A fishing line cast smoothly over calm sparkling lake waters.',
    sentPromptScene: 'A drama teacher holds auditions to cast actors for the musical.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 12, set: 1, wordsData: day12_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 12, set: 2, wordsData: day12_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 12, set: 3, wordsData: day12_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 12, set: 4, wordsData: day12_set4 });
  console.log('DAY 12 written successfully');
}

run();
