import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 06
// ==========================================
const day06_set1 = [
  {
    word: 'relax',
    partOfSpeech: 'v.',
    meaningKo: '휴식을 취하다, 긴장을 풀다',
    ipa: '/rɪˈlæks/',
    definition: 'to rest and become calm and comfortable',
    sentence: 'After school, she likes to relax on the comfortable sofa.',
    wordPromptScene: 'A fluffy cat napping peacefully on a soft sunny cushion.',
    sentPromptScene: 'A relaxed girl sips warm chamomile tea on a comfy couch.',
  },
  {
    word: 'grateful',
    partOfSpeech: 'adj.',
    meaningKo: '감사하는, 고마워하는',
    ipa: '/ˈɡreɪt.fəl/',
    definition: 'feeling or showing thanks for something received',
    sentence: 'The hiker was grateful for the refreshing cup of water.',
    wordPromptScene: 'Two hands holding a glowing golden heart with sparkles.',
    sentPromptScene: 'A smiling boy gives a thank-you card and feels grateful.',
  },
  {
    word: 'complain',
    partOfSpeech: 'v.',
    meaningKo: '불평하다, 항의하다',
    ipa: '/kəmˈpleɪn/',
    definition: 'to say that you are unhappy about something',
    sentence: 'Good team players do not complain about bad weather today.',
    wordPromptScene: 'A small cartoon cloud raining a few drops over an umbrella.',
    sentPromptScene: 'A boy continues smiling on the soccer field without complain.',
  },
  {
    word: 'delighted',
    partOfSpeech: 'adj.',
    meaningKo: '아주 기뻐하는',
    ipa: '/dɪˈlaɪ.t̬ɪd/',
    definition: 'very pleased and happy about something',
    sentence: 'The young artist was delighted with her first prize ribbon.',
    wordPromptScene: 'A joyful cartoon sun shining with a big beaming smile.',
    sentPromptScene: 'A delighted girl jumps for joy holding a shiny blue ribbon.',
  },
  {
    word: 'express',
    partOfSpeech: 'v.',
    meaningKo: '표현하다, 나타내다',
    ipa: '/ɪkˈspres/',
    definition: 'to show what you feel or think using words or art',
    sentence: 'You can express your feelings through music and colorful paintings.',
    wordPromptScene: 'A painter’s palette with glowing rainbow paint splashes flowing out.',
    sentPromptScene: 'A student uses bright watercolors to express happy thoughts on canvas.',
  },
  {
    word: 'reward',
    partOfSpeech: 'n.',
    meaningKo: '보상, 포상',
    ipa: '/rɪˈwɔːrd/',
    definition: 'something given in return for good behavior or work',
    sentence: 'A delicious apple was a tasty reward for the hardworking puppy.',
    wordPromptScene: 'A golden trophy star resting on a plush velvet pedestal.',
    sentPromptScene: 'A happy puppy receives a crunchy biscuit as a training reward.',
  },
  {
    word: 'frustrated',
    partOfSpeech: 'adj.',
    meaningKo: '좌절감을 느끼는, 답답한',
    ipa: '/ˈfrʌs.treɪ.t̬ɪd/',
    definition: 'feeling annoyed because you cannot achieve what you want',
    sentence: 'He felt frustrated when the tricky wooden puzzle did not fit.',
    wordPromptScene: 'A cartoon character scratching head beside tangled colorful yarn.',
    sentPromptScene: 'A boy takes a calm breath when feeling frustrated with puzzle.',
  },
  {
    word: 'recognize',
    partOfSpeech: 'v.',
    meaningKo: '알아보다, 인정하다',
    ipa: '/ˈrek.əɡ.naɪz/',
    definition: 'to know someone or something because you have seen them before',
    sentence: 'I could easily recognize my classmate in the old group photo.',
    wordPromptScene: 'A magnifying glass highlighting a smiling familiar face in a crowd.',
    sentPromptScene: 'A girl points with joy as she can recognize her old friend.',
  },
  {
    word: 'temper',
    partOfSpeech: 'n.',
    meaningKo: '성미, 기분',
    ipa: '/ˈtem.pɚ/',
    definition: 'the state of your mind regarding being angry or calm',
    sentence: 'Take deep breaths to keep your temper calm during disagreements.',
    wordPromptScene: 'A thermometer balancing calmly in the middle of a cool blue zone.',
    sentPromptScene: 'A wise student counts to ten to control his temper peacefully.',
  },
  {
    word: 'temple',
    partOfSpeech: 'n.',
    meaningKo: '사원, 절',
    ipa: '/ˈtem.pəl/',
    definition: 'a building used for religious worship and prayer',
    sentence: 'Ancient stone statues guarded the entrance of the mountain temple.',
    wordPromptScene: 'A peaceful Asian wooden temple surrounded by blooming pink cherry blossoms.',
    sentPromptScene: 'Visitors walk respectfully up stone steps toward an ancient mountain temple.',
  },
];

const day06_set2 = [
  {
    word: 'object',
    partOfSpeech: 'v.',
    meaningKo: '반대하다',
    ipa: '/əbˈdʒekt/',
    definition: 'to express disagreement or disapproval about something',
    sentence: 'None of the students object to having a picnic outdoors.',
    wordPromptScene: 'A raised friendly hand making a calm gentle discussion gesture.',
    sentPromptScene: 'Club members vote and nobody wants to object to the field trip.',
  },
  {
    word: 'disappointed',
    partOfSpeech: 'adj.',
    meaningKo: '실망한, 낙담한',
    ipa: '/ˌdɪs.əˈpɔɪn.t̬ɪd/',
    definition: 'sad because something was not as good as expected',
    sentence: 'He was disappointed when the rainy storm canceled soccer practice.',
    wordPromptScene: 'A small wilting flower being gently watered to revive it.',
    sentPromptScene: 'A boy looks at raindrops on window feeling slightly disappointed.',
  },
  {
    word: 'anxious',
    partOfSpeech: 'adj.',
    meaningKo: '불안해하는, 걱정스러운',
    ipa: '/ˈæŋk.ʃəs/',
    definition: 'worried and nervous about something uncertain',
    sentence: 'The squirrel looked anxious while watching the rustling tall grass.',
    wordPromptScene: 'A cute squirrel holding an acorn with wide curious eyes.',
    sentPromptScene: 'A student feels anxious before stepping up for the spelling bee.',
  },
  {
    word: 'insist',
    partOfSpeech: 'v.',
    meaningKo: '주장하다, 고집하다',
    ipa: '/ɪnˈsɪst/',
    definition: 'to say firmly that something must happen',
    sentence: 'Parents insist on wearing safety helmets while riding fast bicycles.',
    wordPromptScene: 'A sturdy bicycle helmet with a bright green safety checkmark.',
    sentPromptScene: 'A caring parent helps fasten a helmet and will insist on safety.',
  },
  {
    word: 'sudden',
    partOfSpeech: 'adj.',
    meaningKo: '갑작스러운',
    ipa: '/ˈsʌd.ən/',
    definition: 'happening quickly and unexpectedly without warning',
    sentence: 'A sudden burst of bright sunshine lit up the garden.',
    wordPromptScene: 'A golden cartoon lightning flash surrounded by surprise sparkle stars.',
    sentPromptScene: 'Birds take flight during a sudden gentle gust of autumn wind.',
  },
  {
    word: 'immediate',
    partOfSpeech: 'adj.',
    meaningKo: '즉각적인, 당면한',
    ipa: '/ɪˈmiː.di.ət/',
    definition: 'happening or done without any delay',
    sentence: 'The rescue team provided immediate assistance to the lost puppy.',
    wordPromptScene: 'A stopwatch showing zero seconds with a lightning fast speed trail.',
    sentPromptScene: 'A veterinarian gives immediate gentle care to an injured little sparrow.',
  },
  {
    word: 'appreciate',
    partOfSpeech: 'v.',
    meaningKo: '고마워하다, 인정하다',
    ipa: '/əˈpriː.ʃi.eɪt/',
    definition: 'to recognize the good qualities of someone or be thankful',
    sentence: 'We truly appreciate your helpful advice on our science project.',
    wordPromptScene: 'A bouquet of colorful gratitude flowers wrapped in pastel paper.',
    sentPromptScene: 'Students present a handmade card to appreciate their favorite teacher.',
  },
  {
    word: 'pale',
    partOfSpeech: 'adj.',
    meaningKo: '창백한, 연한',
    ipa: '/peɪl/',
    definition: 'having less color than usual or light in shade',
    sentence: 'She painted the bedroom walls in a pale yellow color.',
    wordPromptScene: 'A soft pastel swatch card showing pale yellow and cream tones.',
    sentPromptScene: 'A painter applies a pale sky-blue tint to the canvas sky.',
  },
  {
    word: 'purpose',
    partOfSpeech: 'n.',
    meaningKo: '목적, 의도',
    ipa: '/ˈpɝː.pəs/',
    definition: 'the reason why something is done or exists',
    sentence: 'The purpose of our club is to help clean parks.',
    wordPromptScene: 'An archery target with a glowing arrow striking the bullseye center.',
    sentPromptScene: 'Students plant tree seedlings with the clear purpose of helping nature.',
  },
  {
    word: 'race',
    partOfSpeech: 'n.',
    meaningKo: '경주, 달리기',
    ipa: '/reɪs/',
    definition: 'a competition to see who is the fastest',
    sentence: 'The swift hare ran a friendly race with the tortoise.',
    wordPromptScene: 'A red running track lane with a checkered finish line ribbon.',
    sentPromptScene: 'Cheering classmates watch the exciting three-legged race at sports festival.',
  },
];

const day06_set3 = [
  {
    word: 'discouraged',
    partOfSpeech: 'adj.',
    meaningKo: '낙담한, 풀이 죽은',
    ipa: '/dɪˈskɝː.ɪdʒd/',
    definition: 'feeling less confident or less hopeful about something',
    sentence: 'Do not feel discouraged if you miss the soccer goal.',
    wordPromptScene: 'A tiny green seedling growing strongly between two gray rocks.',
    sentPromptScene: 'A friendly coach encourages a player not to feel discouraged.',
  },
  {
    word: 'stare',
    partOfSpeech: 'v.',
    meaningKo: '응시하다, 빤히 쳐다보다',
    ipa: '/ster/',
    definition: 'to look directly at someone or something for a long time',
    sentence: 'The curious owl continued to stare from the pine branch.',
    wordPromptScene: 'A wise cartoon owl with big round glowing eyes looking forward.',
    sentPromptScene: 'Children stare in wonder at a giant dinosaur skeleton in museum.',
  },
  {
    word: 'burst',
    partOfSpeech: 'v.',
    meaningKo: '터지다, 갑자기 나타나다',
    ipa: '/bɝːst/',
    definition: 'to break open suddenly or appear with great energy',
    sentence: 'Colorful soap bubbles burst into tiny drops in the air.',
    wordPromptScene: 'A shiny floating soap bubble popping with glittering sparkle droplets.',
    sentPromptScene: 'Joyful flowers burst into full bloom in the spring sunshine garden.',
  },
  {
    word: 'miserable',
    partOfSpeech: 'adj.',
    meaningKo: '비참한, 매우 불행한',
    ipa: '/ˈmɪz.ɚ.ə.bəl/',
    definition: 'very unhappy, uncomfortable, or in bad condition',
    sentence: 'The drenched little puppy looked miserable until wrapped in towels.',
    wordPromptScene: 'A tiny wet cartoon kitten warming up under a soft blanket.',
    sentPromptScene: 'A warm blanket comforts a wet puppy so it feels less miserable.',
  },
  {
    word: 'embarrassed',
    partOfSpeech: 'adj.',
    meaningKo: '당황스러운, 부끄러운',
    ipa: '/ɪmˈber.əst/',
    definition: 'feeling shy, awkward, or ashamed about something',
    sentence: 'He felt slightly embarrassed when his voice squeaked in class.',
    wordPromptScene: 'A cute cartoon character with blushing rosy cheeks smiling shyly.',
    sentPromptScene: 'A boy laughs along with friends when embarrassed by spilling chalk.',
  },
  {
    word: 'hardly',
    partOfSpeech: 'adv.',
    meaningKo: '거의 ~않다',
    ipa: '/ˈhɑːrd.li/',
    definition: 'scarcely or almost not at all',
    sentence: 'There was hardly any noise in the quiet study room.',
    wordPromptScene: 'A glass with barely a tiny drop of water at bottom.',
    sentPromptScene: 'The forest was so quiet that hikers could hardly hear footsteps.',
  },
  {
    word: 'panic',
    partOfSpeech: 'n.',
    meaningKo: '공황, 극심한 공포',
    ipa: '/ˈpæn.ɪk/',
    definition: 'a sudden strong feeling of fear that prevents calm thought',
    sentence: 'Stay calm and avoid panic during the school fire drill.',
    wordPromptScene: 'A glowing green emergency exit sign leading peacefully out doors.',
    sentPromptScene: 'Students walk in an orderly line without panic during safety drill.',
  },
  {
    word: 'correspond',
    partOfSpeech: 'v.',
    meaningKo: '일치하다, 편지를 주고받다',
    ipa: '/ˌkɔːr.əˈspɑːnd/',
    definition: 'to match something or communicate by writing letters',
    sentence: 'The numbers on the map correspond to our list of landmarks.',
    wordPromptScene: 'Two matching puzzle keys fitting into identical glowing lock slots.',
    sentPromptScene: 'Two pen pals correspond by sending handwritten illustrated letters monthly.',
  },
  {
    word: 'cruel',
    partOfSpeech: 'adj.',
    meaningKo: '잔인한, 잔혹한',
    ipa: '/ˈkruː.əl/',
    definition: 'causing pain or suffering to others without feeling bad',
    sentence: 'It is very cruel to leave pets outside in snow.',
    wordPromptScene: 'A warm protective shelter keeping a small cartoon dog safe.',
    sentPromptScene: 'Kind volunteers rescue animals and stop any cruel treatment forever.',
  },
  {
    word: 'crucial',
    partOfSpeech: 'adj.',
    meaningKo: '결정적인, 중대한',
    ipa: '/ˈkruː.ʃəl/',
    definition: 'extremely important or necessary for success',
    sentence: 'Good communication is a crucial part of any team project.',
    wordPromptScene: 'A golden central keystone fitting securely at the arch top.',
    sentPromptScene: 'Team members share a crucial clue to solve the escape puzzle.',
  },
];

const day06_set4 = [
  {
    word: 'isolated',
    partOfSpeech: 'adj.',
    meaningKo: '고립된, 외딴',
    ipa: '/ˈaɪ.sə.leɪ.t̬ɪd/',
    definition: 'far away from other places, buildings, or people',
    sentence: 'The lonely wooden cabin stood in an isolated mountain valley.',
    wordPromptScene: 'A cozy wooden cabin standing alone on a snowy mountain top.',
    sentPromptScene: 'A glowing lighthouse stands on an isolated island in calm sea.',
  },
  {
    word: 'awkward',
    partOfSpeech: 'adj.',
    meaningKo: '어색한, 서투른',
    ipa: '/ˈɑː.kwɚd/',
    definition: 'feeling embarrassed or not comfortable with others',
    sentence: 'There was an awkward silence before someone told a joke.',
    wordPromptScene: 'A cartoon penguin standing slightly tilted with an apologetic smile.',
    sentPromptScene: 'A funny joke breaks the awkward quiet in the classroom quickly.',
  },
  {
    word: 'sympathy',
    partOfSpeech: 'n.',
    meaningKo: '동정, 공감',
    ipa: '/ˈsɪm.pə.θi/',
    definition: 'the feeling of being sorry for someone’s bad luck',
    sentence: 'She expressed deep sympathy for her friend’s lost pet.',
    wordPromptScene: 'Two cartoon hands gently holding a glowing warm origami heart.',
    sentPromptScene: 'A caring friend offers a hug with heartfelt sympathy and warmth.',
  },
  {
    word: 'terrifying',
    partOfSpeech: 'adj.',
    meaningKo: '무서운, 겁나는',
    ipa: '/ˈter.ə.faɪ.ɪŋ/',
    definition: 'very frightening and causing great fear',
    sentence: 'The roller coaster had a terrifying but super exciting drop.',
    wordPromptScene: 'A thrilling cartoon amusement park roller coaster loop in sky.',
    sentPromptScene: 'Riders shout happily during a terrifying loop on a giant coaster.',
  },
  {
    word: 'optimistic',
    partOfSpeech: 'adj.',
    meaningKo: '낙천적인, 긍정적인',
    ipa: '/ˌɑːp.təˈmɪs.tɪk/',
    definition: 'hoping and believing that good things will happen',
    sentence: 'The cheerful team captain stayed optimistic about winning the match.',
    wordPromptScene: 'A smiling cartoon sun rising above rolling bright green hills.',
    sentPromptScene: 'An optimistic player cheers with a big smile on the bench.',
  },
  {
    word: 'sincere',
    partOfSpeech: 'adj.',
    meaningKo: '진실한, 진심 어린',
    ipa: '/sɪnˈsɪr/',
    definition: 'honest and saying what you really think or feel',
    sentence: 'He offered a sincere apology after breaking the garden pot.',
    wordPromptScene: 'A handwritten letter sealed with a shiny red wax heart stamp.',
    sentPromptScene: 'A boy bows politely and offers a sincere apology to neighbor.',
  },
  {
    word: 'likely',
    partOfSpeech: 'adj.',
    meaningKo: '~할 것 같은, 유망한',
    ipa: '/ˈlaɪ.kli/',
    definition: 'probable or expected to happen',
    sentence: 'Dark grey clouds mean it is likely to rain soon.',
    wordPromptScene: 'A fluffy grey cloud with gentle cartoon rain sparkles falling.',
    sentPromptScene: 'People open umbrellas as rain is likely to begin this evening.',
  },
  {
    word: 'endure',
    partOfSpeech: 'v.',
    meaningKo: '견디다, 참다',
    ipa: '/ɪnˈdʊr/',
    definition: 'to experience and deal with something difficult without giving up',
    sentence: 'The brave little flower could endure the cold winter frost.',
    wordPromptScene: 'A sturdy pine tree standing strong amidst swirling white snowflakes.',
    sentPromptScene: 'Campers endure a chilly night in tents and celebrate sunrise morning.',
  },
  {
    word: 'cognitive',
    partOfSpeech: 'adj.',
    meaningKo: '인지의, 인식의',
    ipa: '/ˈkɑːɡ.nə.t̬ɪv/',
    definition: 'connected with thinking or the conscious mental processes',
    sentence: 'Solving chess puzzles improves your cognitive abilities and memory power.',
    wordPromptScene: 'A glowing lightbulb brain surrounded by spinning colorful gears.',
    sentPromptScene: 'Children play memory card games to develop strong cognitive skills.',
  },
  {
    word: 'reflect',
    partOfSpeech: 'v.',
    meaningKo: '반사하다, 반영하다, 깊이 생각하다',
    ipa: '/rɪˈflekt/',
    definition: 'to show an image of something or think deeply',
    sentence: 'The calm lake surface can reflect the blue sky clearly.',
    wordPromptScene: 'A crystal clear water surface showing a reflection of snowy peaks.',
    sentPromptScene: 'A quiet pond can reflect the golden trees of autumn beautifully.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 6, set: 1, wordsData: day06_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 6, set: 2, wordsData: day06_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 6, set: 3, wordsData: day06_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 6, set: 4, wordsData: day06_set4 });
  console.log('DAY 06 written successfully');
}

run();
