import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 03
// ==========================================
const day03_set1 = [
  {
    word: 'journey',
    partOfSpeech: 'n.',
    meaningKo: '여행, 여정',
    ipa: '/ˈdʒɝː.ni/',
    definition: 'an act of traveling from one place to another',
    sentence: 'The young explorer packed a bag for a long journey.',
    wordPromptScene: 'A vintage suitcase with travel stickers next to a rolled map.',
    sentPromptScene: 'An adventurous traveler walks down a scenic mountain trail with backpack.',
  },
  {
    word: 'theater',
    partOfSpeech: 'n.',
    meaningKo: '극장, 공연장',
    ipa: '/ˈθiː.ə.t̬ɚ/',
    definition: 'a building or room for watching plays or movies',
    sentence: 'We bought tickets to watch a puppet show at the theater.',
    wordPromptScene: 'A classic theater stage with draped red velvet curtains.',
    sentPromptScene: 'Families enter a brightly lit theater holding colorful show tickets.',
  },
  {
    word: 'fee',
    partOfSpeech: 'n.',
    meaningKo: '요금, 수수료',
    ipa: '/fiː/',
    definition: 'an amount of money paid for a service or entry',
    sentence: 'Visitors pay a small admission fee at the park entrance.',
    wordPromptScene: 'A ticket booth window displaying a clear price list sign.',
    sentPromptScene: 'A tourist pays the admission fee at a zoo ticket counter.',
  },
  {
    word: 'prepare',
    partOfSpeech: 'v.',
    meaningKo: '준비하다',
    ipa: '/prɪˈper/',
    definition: 'to make someone or something ready for use',
    sentence: 'Let us prepare warm snacks before the guests arrive home.',
    wordPromptScene: 'A kitchen counter with baking ingredients laid out ready to mix.',
    sentPromptScene: 'A smiling chef cuts colorful vegetables to prepare a big meal.',
  },
  {
    word: 'surprised',
    partOfSpeech: 'adj.',
    meaningKo: '놀란',
    ipa: '/sɚˈpraɪzd/',
    definition: 'feeling wonder or shock because something unexpected happened',
    sentence: 'The little kitten looked surprised when the jack-in-the-box popped.',
    wordPromptScene: 'A friendly cartoon face with wide eyes and open mouth in wonder.',
    sentPromptScene: 'A child looks surprised when a colorful gift box pops open.',
  },
  {
    word: 'receive',
    partOfSpeech: 'v.',
    meaningKo: '받다',
    ipa: '/rɪˈsiːv/',
    definition: 'to get or accept something that is sent',
    sentence: 'He was excited to receive a postcard from his pen pal.',
    wordPromptScene: 'Two hands catching a glowing envelope wrapped with ribbon.',
    sentPromptScene: 'A happy boy opens the mailbox to receive a colorful postcard.',
  },
  {
    word: 'nervous',
    partOfSpeech: 'adj.',
    meaningKo: '긴장한, 불안한',
    ipa: '/ˈnɝː.vəs/',
    definition: 'worried or anxious about something that may happen',
    sentence: 'The actor felt nervous before stepping onto the bright stage.',
    wordPromptScene: 'A small cute cartoon rabbit holding its paws together shyly.',
    sentPromptScene: 'A young musician takes a deep breath while feeling nervous backstage.',
  },
  {
    word: 'stage',
    partOfSpeech: 'n.',
    meaningKo: '무대',
    ipa: '/steɪdʒ/',
    definition: 'a raised area where actors or musicians perform',
    sentence: 'Dancers leaped across the brightly lit stage during the performance.',
    wordPromptScene: 'A polished wooden stage with warm yellow spotlights shining down.',
    sentPromptScene: 'Costumed performers dance happily on the large wooden school stage.',
  },
  {
    word: 'vacation',
    partOfSpeech: 'n.',
    meaningKo: '방학, 휴가',
    ipa: '/veɪˈkeɪ.ʃən/',
    definition: 'a period of time away from school or work',
    sentence: 'Our family planned a sunny beach vacation for the summer.',
    wordPromptScene: 'A pair of sunglasses, sun hat, and a beach ball on sand.',
    sentPromptScene: 'A family builds a sandcastle on a sunny summer beach vacation.',
  },
  {
    word: 'vocation',
    partOfSpeech: 'n.',
    meaningKo: '천직, 소명, 직업',
    ipa: '/voʊˈkeɪ.ʃən/',
    definition: 'a type of work that you feel suited for',
    sentence: 'Helping sick animals became her true vocation in life.',
    wordPromptScene: 'A glowing lighthouse guiding ships, representing a calling and duty.',
    sentPromptScene: 'A kind veterinarian cares for injured animals as a true vocation.',
  },
];

const day03_set2 = [
  {
    word: 'pack',
    partOfSpeech: 'v.',
    meaningKo: '짐을 싸다',
    ipa: '/pæk/',
    definition: 'to put things into bags or boxes for travel',
    sentence: 'Remember to pack extra socks and a water bottle.',
    wordPromptScene: 'An open suitcase with neatly folded shirts and sneakers inside.',
    sentPromptScene: 'A girl folds colorful clothes to pack her backpack for camp.',
  },
  {
    word: 'host',
    partOfSpeech: 'n.',
    meaningKo: '주인, 진행자',
    ipa: '/hoʊst/',
    definition: 'a person who welcomes guests or runs an event',
    sentence: 'The friendly host welcomed all visitors with a warm beverage.',
    wordPromptScene: 'A smiling person opening a cozy front door with a welcome gesture.',
    sentPromptScene: 'A friendly host greets dinner guests with delicious warm drinks.',
  },
  {
    word: 'private',
    partOfSpeech: 'adj.',
    meaningKo: '개인의, 사적인',
    ipa: '/ˈpraɪ.vət/',
    definition: 'belonging to one particular person and not for everyone',
    sentence: 'He keeps a private diary in his study desk drawer.',
    wordPromptScene: 'A decorative small diary with a golden lock and key.',
    sentPromptScene: 'A student writes personal thoughts inside a private locked journal.',
  },
  {
    word: 'craft',
    partOfSpeech: 'n.',
    meaningKo: '공예, 기술',
    ipa: '/kræft/',
    definition: 'an activity involving skill in making things by hand',
    sentence: 'Students created a colorful paper craft during art class today.',
    wordPromptScene: 'Origami paper birds, safety scissors, and a bottle of glue.',
    sentPromptScene: 'Children make fun animal shapes during an afternoon craft workshop.',
  },
  {
    word: 'post',
    partOfSpeech: 'v.',
    meaningKo: '우편을 부치다, 게시하다',
    ipa: '/poʊst/',
    definition: 'to send a letter or display a notice publicly',
    sentence: 'She went to the corner mailbox to post the letter.',
    wordPromptScene: 'A bright red postal mailbox with a letter slot.',
    sentPromptScene: 'A girl drops a sealed birthday envelope into a street post box.',
  },
  {
    word: 'relieve',
    partOfSpeech: 'v.',
    meaningKo: '완화하다, 안도하게 하다',
    ipa: '/rɪˈliːv/',
    definition: 'to make pain or worry less severe',
    sentence: 'A cool glass of water helped relieve his dry thirst.',
    wordPromptScene: 'A gentle cool breeze blowing around a soothing green leaf.',
    sentPromptScene: 'A tired runner sits on a bench to relieve tired legs.',
  },
  {
    word: 'practice',
    partOfSpeech: 'v.',
    meaningKo: '연습하다',
    ipa: '/ˈpræk.tɪs/',
    definition: 'to do an activity regularly to become better',
    sentence: 'She likes to practice the violin for thirty minutes daily.',
    wordPromptScene: 'A wooden violin resting on a music stand with sheet notes.',
    sentPromptScene: 'A dedicated girl plays her violin to practice for a concert.',
  },
  {
    word: 'souvenir',
    partOfSpeech: 'n.',
    meaningKo: '기념품',
    ipa: '/ˌsuː.vəˈnɪr/',
    definition: 'something you buy to remember a place or event',
    sentence: 'He bought a small wooden windmill as a souvenir.',
    wordPromptScene: 'A miniature snow globe containing a famous landmark and glitter.',
    sentPromptScene: 'A traveler chooses a cute magnet souvenir from a gift shop.',
  },
  {
    word: 'decorate',
    partOfSpeech: 'v.',
    meaningKo: '장식하다, 꾸미다',
    ipa: '/ˈdek.ə.reɪt/',
    definition: 'to make something look more attractive by adding objects',
    sentence: 'They helped decorate the classroom with bright paper lanterns today.',
    wordPromptScene: 'Strings of colorful paper garland flags and twinkling fairy lights.',
    sentPromptScene: 'Students hang paper stars to decorate the school hallway for celebration.',
  },
  {
    word: 'book',
    partOfSpeech: 'v.',
    meaningKo: '예약하다',
    ipa: '/bʊk/',
    definition: 'to arrange to have a seat, room, or ticket',
    sentence: 'We should book train tickets early for our weekend trip.',
    wordPromptScene: 'A calendar appointment with a checkmark and two train tickets.',
    sentPromptScene: 'A family uses a tablet computer to book train tickets online.',
  },
];

const day03_set3 = [
  {
    word: 'reserve',
    partOfSpeech: 'v.',
    meaningKo: '예약하다, 남겨두다',
    ipa: '/rɪˈzɝːv/',
    definition: 'to keep something for a particular person or future use',
    sentence: 'They called the restaurant to reserve a table by the window.',
    wordPromptScene: 'A neat small card on a wooden table with Reserved written.',
    sentPromptScene: 'A waiter places a card to reserve a sunny table for guests.',
  },
  {
    word: 'wrap',
    partOfSpeech: 'v.',
    meaningKo: '싸다, 포장하다',
    ipa: '/ræp/',
    definition: 'to cover something completely in paper or cloth',
    sentence: 'She used shiny blue paper to wrap the birthday present.',
    wordPromptScene: 'A neatly wrapped gift box topped with a golden satin bow.',
    sentPromptScene: 'A boy ties a yellow ribbon to wrap a surprise gift.',
  },
  {
    word: 'occasion',
    partOfSpeech: 'n.',
    meaningKo: '행사, 특별한 때',
    ipa: '/əˈkeɪ.ʒən/',
    definition: 'a particular event, time, or celebration',
    sentence: 'The graduation ceremony was a truly joyful occasion for everyone.',
    wordPromptScene: 'A festive party banner with balloons and flying colorful confetti.',
    sentPromptScene: 'Friends gather around a table to celebrate a happy birthday occasion.',
  },
  {
    word: 'allow',
    partOfSpeech: 'v.',
    meaningKo: '허락하다, 허용하다',
    ipa: '/əˈlaʊ/',
    definition: 'to give permission for someone to do something',
    sentence: 'The park rules allow visitors to ride bicycles along trails.',
    wordPromptScene: 'A friendly green checkmark sign permitting bicycles on a path.',
    sentPromptScene: 'A park ranger smiles to allow children to enter the nature playground.',
  },
  {
    word: 'ensure',
    partOfSpeech: 'v.',
    meaningKo: '보장하다, 확실하게 하다',
    ipa: '/ɪnˈʃʊr/',
    definition: 'to make certain that something will happen safely',
    sentence: 'Fasten your seatbelt to ensure your safety during the ride.',
    wordPromptScene: 'A glowing shield icon with a sturdy lock mechanism.',
    sentPromptScene: 'A flight attendant checks overhead bins to ensure safety before takeoff.',
  },
  {
    word: 'agent',
    partOfSpeech: 'n.',
    meaningKo: '대리인, 중개인',
    ipa: '/ˈeɪ.dʒənt/',
    definition: 'a person who acts on behalf of another person',
    sentence: 'The travel agent found us a great hotel near beach.',
    wordPromptScene: 'A professional desk with travel brochures, a globe, and ticket folders.',
    sentPromptScene: 'A helpful travel agent shows a sunny vacation resort brochure to customers.',
  },
  {
    word: 'argue',
    partOfSpeech: 'v.',
    meaningKo: '말다툼하다, 주장하다',
    ipa: '/ˈɑːrɡ.juː/',
    definition: 'to speak angrily to someone because you disagree',
    sentence: 'Good friends do not argue over small rules in games.',
    wordPromptScene: 'Two cartoon birds chirping loudly facing opposite directions on branches.',
    sentPromptScene: 'Two playful kittens pause when they argue over a toy ball.',
  },
  {
    word: 'confirm',
    partOfSpeech: 'v.',
    meaningKo: '확인하다, 확정하다',
    ipa: '/kənˈfɝːm/',
    definition: 'to state or show that something is definitely true',
    sentence: 'Please call the hotel to confirm your room reservation today.',
    wordPromptScene: 'A digital screen displaying a green verified confirmation badge icon.',
    sentPromptScene: 'A traveler checks email to confirm hotel dates on smartphone.',
  },
  {
    word: 'wonder',
    partOfSpeech: 'v.',
    meaningKo: '궁금해하다',
    ipa: '/ˈwʌn.dər/',
    definition: 'to want to know something or feel curious',
    sentence: 'Children wonder how stars can shine so brightly at night.',
    wordPromptScene: 'A glowing yellow question mark surrounded by sparkling little stars.',
    sentPromptScene: 'A boy gazes up at the night sky to wonder about stars.',
  },
  {
    word: 'wander',
    partOfSpeech: 'v.',
    meaningKo: '거닐다, 헤매다',
    ipa: '/ˈwɑːn.dər/',
    definition: 'to walk slowly around with no clear destination',
    sentence: 'They like to wander along the quiet forest trail after lunch.',
    wordPromptScene: 'A winding dirt path curving gently through a sunny green meadow.',
    sentPromptScene: 'Two hikers wander peacefully through a sunlit pine forest path.',
  },
];

const day03_set4 = [
  {
    word: 'capital',
    partOfSpeech: 'n.',
    meaningKo: '수도, 자본',
    ipa: '/ˈkæp.ə.t̬əl/',
    definition: 'the city where the government of a country is located',
    sentence: 'Seoul is the bustling capital city of South Korea.',
    wordPromptScene: 'A grand government dome building with national flags waving proudly.',
    sentPromptScene: 'Tourists take pictures in front of historic buildings in a capital.',
  },
  {
    word: 'absolute',
    partOfSpeech: 'adj.',
    meaningKo: '완전한, 절대적인',
    ipa: '/ˈæb.sə.luːt/',
    definition: 'complete, total, and without any doubt',
    sentence: 'The quiet cave remained in absolute darkness without a flashlight.',
    wordPromptScene: 'A solid gold crown sitting proudly on a velvet cushion.',
    sentPromptScene: 'Explorers stand in absolute silence inside a magnificent crystal cave.',
  },
  {
    word: 'anticipate',
    partOfSpeech: 'v.',
    meaningKo: '기대하다, 예상하다',
    ipa: '/ænˈtɪs.ə.peɪt/',
    definition: 'to imagine or expect that something will happen',
    sentence: 'The excited fans anticipate a great victory for their team.',
    wordPromptScene: 'A smiling cartoon character eagerly peeking past a calendar page.',
    sentPromptScene: 'Excited students anticipate the arrival of the summer holiday break.',
  },
  {
    word: 'leisure',
    partOfSpeech: 'n.',
    meaningKo: '여가, 휴식',
    ipa: '/ˈliː.ʒɚ/',
    definition: 'time when you are free from work or duties',
    sentence: 'He enjoys spending his leisure time painting peaceful landscape pictures.',
    wordPromptScene: 'A hammock tied between two palm trees beside a sunny pool.',
    sentPromptScene: 'A boy reads an adventure novel during his weekend leisure hours.',
  },
  {
    word: 'undergo',
    partOfSpeech: 'v.',
    meaningKo: '겪다, 받다',
    ipa: '/ˌʌn.dɚˈɡoʊ/',
    definition: 'to experience or go through a process or change',
    sentence: 'The old steam locomotive will undergo major safety repairs soon.',
    wordPromptScene: 'A robot stepping into an upgrade scanning tunnel with glowing rings.',
    sentPromptScene: 'An antique wooden clock will undergo careful restoration by a craftsman.',
  },
  {
    word: 'spare',
    partOfSpeech: 'adj.',
    meaningKo: '여분의, 남는',
    ipa: '/sper/',
    definition: 'extra or available to use if needed',
    sentence: 'He keeps a spare bicycle tire in the garage shelf.',
    wordPromptScene: 'A spare round bicycle wheel mounted neatly on a garage wall.',
    sentPromptScene: 'A cyclist carries a spare inner tube on a long bike ride.',
  },
  {
    word: 'aquarium',
    partOfSpeech: 'n.',
    meaningKo: '수족관',
    ipa: '/əˈkwer.i.əm/',
    definition: 'a glass container or building for keeping fish and water animals',
    sentence: 'We saw colorful tropical fish swimming inside the giant aquarium.',
    wordPromptScene: 'A glowing blue glass tank filled with coral, clownfish, and bubbles.',
    sentPromptScene: 'Children press their hands against the glass at a large aquarium.',
  },
  {
    word: 'applaud',
    partOfSpeech: 'v.',
    meaningKo: '박수갈채를 보내다',
    ipa: '/əˈplɑːd/',
    definition: 'to clap your hands to show approval or praise',
    sentence: 'The audience stood up to applaud the young musicians loudly.',
    wordPromptScene: 'Two cartoon hands clapping together with musical praise sparkle stars.',
    sentPromptScene: 'Smiling theatergoers applaud with enthusiasm at the end of musical.',
  },
  {
    word: 'insurance',
    partOfSpeech: 'n.',
    meaningKo: '보험',
    ipa: '/ɪnˈʃʊr.əns/',
    definition: 'an agreement protecting you against money loss or damage',
    sentence: 'They bought travel insurance before boarding the cruise ship.',
    wordPromptScene: 'A green umbrella shielding a small house and car from rain.',
    sentPromptScene: 'A traveler signs a paper for travel insurance at the airport desk.',
  },
  {
    word: 'return',
    partOfSpeech: 'v.',
    meaningKo: '돌아오다, 반납하다',
    ipa: '/rɪˈtɝːn/',
    definition: 'to come back to a place or give something back',
    sentence: 'She will return the library books before the weekend starts.',
    wordPromptScene: 'A curved circular green arrow indicating a safe journey back home.',
    sentPromptScene: 'A student stops at the counter to return three borrowed books.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 3, set: 1, wordsData: day03_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 3, set: 2, wordsData: day03_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 3, set: 3, wordsData: day03_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 3, set: 4, wordsData: day03_set4 });
  console.log('DAY 03 written successfully');
}

run();
