import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 22
// ==========================================
const day22_set1 = [
  {
    word: 'ecosystem',
    partOfSpeech: 'n.',
    meaningKo: '생태계',
    ipa: '/ˈiː.koʊˌsɪs.təm/',
    definition: 'all living things in an area and their physical environment',
    sentence: 'Coral reefs form a vibrant and diverse underwater marine ecosystem.',
    wordPromptScene: 'A vibrant underwater coral reef teaming with tropical fish and sea turtles.',
    sentPromptScene: 'A science teacher uses a poster to explain a pond ecosystem.',
  },
  {
    word: 'desert',
    partOfSpeech: 'n.',
    meaningKo: '사막',
    ipa: '/ˈdez.ɚt/',
    definition: 'a large dry area of land with very little rain',
    sentence: 'Tall green cacti grow peacefully across the sunny sandy desert.',
    wordPromptScene: 'Golden desert sand dunes with flowering saguaro cacti under blue sky.',
    sentPromptScene: 'A camel caravan walks across rolling golden desert dunes at sunset.',
  },
  {
    word: 'creature',
    partOfSpeech: 'n.',
    meaningKo: '생물, 생명체',
    ipa: '/ˈkriː.tʃɚ/',
    definition: 'any living thing that can move independently, animal',
    sentence: 'The curious sea otter is a playful marine animal creature.',
    wordPromptScene: 'A cute sea otter floating happily on its back in calm waters.',
    sentPromptScene: 'Children observe a colorful chameleon, a fascinating forest creature in zoo.',
  },
  {
    word: 'mature',
    partOfSpeech: 'adj.',
    meaningKo: '성숙한, 다 자란',
    ipa: '/məˈtʃʊr/',
    definition: 'fully developed or grown up in physical body or mind',
    sentence: 'The mature oak tree provided generous cool shade across the lawn.',
    wordPromptScene: 'A majestic fully grown oak tree with a massive leafy green canopy.',
    sentPromptScene: 'A farmer inspects mature golden wheat stalks ready for autumn harvest.',
  },
  {
    word: 'habitat',
    partOfSpeech: 'n.',
    meaningKo: '서식지',
    ipa: '/ˈhæb.ə.tæt/',
    definition: 'the natural home or environment of an animal or plant',
    sentence: 'The bamboo forest is the natural wild habitat of giant pandas.',
    wordPromptScene: 'A peaceful green bamboo grove with misty morning sunlight filtering through.',
    sentPromptScene: 'Park rangers protect the wetland habitat where migratory birds nest safely.',
  },
  {
    word: 'maintain',
    partOfSpeech: 'v.',
    meaningKo: '유지하다, 관리하다',
    ipa: '/meɪnˈteɪn/',
    definition: 'to continue to have or keep something in good condition',
    sentence: 'Volunteers work hard to maintain clean hiking trails in national park.',
    wordPromptScene: 'A gardener trimming neat green hedge bushes along a park path.',
    sentPromptScene: 'Park rangers maintain wooden footbridges so visitors can hike safely.',
  },
  {
    word: 'tide',
    partOfSpeech: 'n.',
    meaningKo: '조수, 밀물과 썰물',
    ipa: '/taɪd/',
    definition: 'the regular rise and fall in the level of the sea',
    sentence: 'The receding low tide revealed small tide pools filled with starfish.',
    wordPromptScene: 'A rocky shoreline with a shallow tide pool revealing colorful sea stars.',
    sentPromptScene: 'Children explore coastal rock pools while the ocean tide is low.',
  },
  {
    word: 'balance',
    partOfSpeech: 'n.',
    meaningKo: '균형, 조화',
    ipa: '/ˈbæl.əns/',
    definition: 'a state where things are equal or in correct proportions',
    sentence: 'Predators and prey maintain a natural ecological balance in wild nature.',
    wordPromptScene: 'A stack of seven smooth river stones standing in perfect balance.',
    sentPromptScene: 'A gymnast maintains steady balance while walking across the balance beam.',
  },
  {
    word: 'grand',
    partOfSpeech: 'adj.',
    meaningKo: '웅장한, 대단한',
    ipa: '/ɡrænd/',
    definition: 'impressive and large in size, beauty, or importance',
    sentence: 'The grand waterfall cascaded down into the deep mountain canyon.',
    wordPromptScene: 'A majestic towering waterfall plunging into a turquoise canyon pool.',
    sentPromptScene: 'Hikers stand in awe before the grand panoramic mountain valley vista.',
  },
  {
    word: 'grant',
    partOfSpeech: 'v.',
    meaningKo: '승인하다, 주다',
    ipa: '/ɡrænt/',
    definition: 'to agree to give or allow someone something they asked',
    sentence: 'The teacher will grant extra reading time in the quiet library.',
    wordPromptScene: 'A golden scroll stamped with an official green Grant badge ribbon.',
    sentPromptScene: 'The principal smiles to grant permission for the class field trip.',
  },
];

const day22_set2 = [
  {
    word: 'huge',
    partOfSpeech: 'adj.',
    meaningKo: '거대한, 엄청난',
    ipa: '/hjuːdʒ/',
    definition: 'extremely large in size or amount, gigantic',
    sentence: 'A huge redwood tree stretched hundreds of feet into the sky.',
    wordPromptScene: 'A towering ancient giant redwood tree with tiny hikers standing below.',
    sentPromptScene: 'Children gather around the base of a huge ancient oak tree.',
  },
  {
    word: 'pile',
    partOfSpeech: 'n.',
    meaningKo: '더미, 쌓아 놓은 것',
    ipa: '/paɪl/',
    definition: 'a mass of things lying on top of each other',
    sentence: 'Children jumped into a crunchy pile of golden autumn leaves.',
    wordPromptScene: 'A large neat mound of golden and red raked autumn leaves on grass.',
    sentPromptScene: 'A laughing boy jumps into a big pile of dry autumn leaves.',
  },
  {
    word: 'react',
    partOfSpeech: 'v.',
    meaningKo: '반응하다',
    ipa: '/riˈækt/',
    definition: 'to act in response to something that happens',
    sentence: 'Sunflowers will react to sunlight by turning their blossoms eastward.',
    wordPromptScene: 'A bright yellow sunflower turning gracefully towards the rising morning sun.',
    sentPromptScene: 'Students observe how plant leaves react to warm lamp light in lab.',
  },
  {
    word: 'exist',
    partOfSpeech: 'v.',
    meaningKo: '존재하다',
    ipa: '/ɪɡˈzɪst/',
    definition: 'to be real or alive in the world',
    sentence: 'Fascinating creatures like giant squids exist in the deep ocean.',
    wordPromptScene: 'A glowing bioluminescent deep sea creature swimming peacefully in dark water.',
    sentPromptScene: 'A marine biologist explains how unique organisms exist in hydrothermal vents.',
  },
  {
    word: 'shade',
    partOfSpeech: 'n.',
    meaningKo: '그늘, 가리개',
    ipa: '/ʃeɪd/',
    definition: 'slight darkness caused by something blocking direct sunlight',
    sentence: 'We enjoyed a cool picnic under the leafy tree shade.',
    wordPromptScene: 'A bright red picnic blanket placed under a leafy green shade tree.',
    sentPromptScene: 'Hikers rest happily in the cool shade of an ancient pine.',
  },
  {
    word: 'element',
    partOfSpeech: 'n.',
    meaningKo: '요소, 원소',
    ipa: '/ˈel.ə.mənt/',
    definition: 'a basic part or quality of something whole',
    sentence: 'Water is a vital element for all living plants on Earth.',
    wordPromptScene: 'Four elemental icons representing fire, water, earth, and air glowing brightly.',
    sentPromptScene: 'A science teacher shows how carbon is a fundamental chemical element.',
  },
  {
    word: 'layer',
    partOfSpeech: 'n.',
    meaningKo: '층, 겹',
    ipa: '/ˈleɪ.ɚ/',
    definition: 'an amount of a substance covering a surface',
    sentence: 'A thick layer of white snow covered the garden overnight.',
    wordPromptScene: 'A cross-section illustration showing different colorful soil and rock layers.',
    sentPromptScene: 'A geologist points out each ancient rock layer in the canyon.',
  },
  {
    word: 'horizon',
    partOfSpeech: 'n.',
    meaningKo: '지평선, 수평선',
    ipa: '/həˈraɪ.zən/',
    definition: 'the line where the earth’s surface and sky appear meet',
    sentence: 'A golden sun sank slowly beneath the calm ocean horizon.',
    wordPromptScene: 'A breathtaking sunset with a golden sun touching the flat ocean horizon.',
    sentPromptScene: 'Sailors look towards the distant horizon from the deck of ship.',
  },
  {
    word: 'observe',
    partOfSpeech: 'v.',
    meaningKo: '관찰하다, 준수하다',
    ipa: '/əbˈzɝːv/',
    definition: 'to watch carefully the way something happens',
    sentence: 'Students use binoculars to observe wild birds in the forest canopy.',
    wordPromptScene: 'A pair of modern black binoculars resting on a nature field guide.',
    sentPromptScene: 'Children observe a family of ducks swimming across the nature pond.',
  },
  {
    word: 'block',
    partOfSpeech: 'v.',
    meaningKo: '막다, 차단하다',
    ipa: '/blɑːk/',
    definition: 'to stop something from passing or being seen',
    sentence: 'Thick sunglasses help block harmful ultraviolet sun rays during summer.',
    wordPromptScene: 'A pair of stylish sunglasses reflecting a bright sunny day safely.',
    sentPromptScene: 'A large umbrella opens up to block the midday hot sun rays.',
  },
];

const day22_set3 = [
  {
    word: 'reason',
    partOfSpeech: 'n.',
    meaningKo: '이유, 까닭, 이성',
    ipa: '/ˈriː.zən/',
    definition: 'the cause of an event or why something happened',
    sentence: 'Lack of rain was the main reason for dry soil conditions.',
    wordPromptScene: 'A glowing lightbulb thought bubble connecting puzzle pieces of cause and effect.',
    sentPromptScene: 'A student explains the scientific reason why leaves change color in autumn.',
  },
  {
    word: 'herd',
    partOfSpeech: 'n.',
    meaningKo: '무리, 떼',
    ipa: '/hɝːd/',
    definition: 'a large group of animals that live and feed together',
    sentence: 'A large herd of wild horses galloped across the green plain.',
    wordPromptScene: 'A herd of wild mustangs running gracefully across open grassy plains.',
    sentPromptScene: 'Tourists watch a peaceful herd of elephants walking near the waterhole.',
  },
  {
    word: 'filter',
    partOfSpeech: 'n.',
    meaningKo: '여과기, 필터',
    ipa: '/ˈfɪl.tɚ/',
    definition: 'a device with porous material through which liquid passes cleanly',
    sentence: 'The water filter removes tiny sand particles to make clean water.',
    wordPromptScene: 'A clean modern water filtration pitcher with clear water dripping through.',
    sentPromptScene: 'Students assemble a sand and charcoal water filter in science lab.',
  },
  {
    word: 'eco-friendly',
    partOfSpeech: 'adj.',
    meaningKo: '친환경적인',
    ipa: '/ˌiː.koʊˈfrend.li/',
    definition: 'not harmful to the environment or natural surroundings',
    sentence: 'Using reusable bamboo straws is an eco-friendly choice for everyone.',
    wordPromptScene: 'A set of reusable bamboo cutlery tied with a green leaf ribbon.',
    sentPromptScene: 'A student uses an eco-friendly canvas tote bag for grocery shopping.',
  },
  {
    word: 'portion',
    partOfSpeech: 'n.',
    meaningKo: '부분, 1인분',
    ipa: '/ˈpɔːr.ʃən/',
    definition: 'a part of a larger amount, or single food serving',
    sentence: 'She served a generous portion of fresh fruit salad for dessert.',
    wordPromptScene: 'A neat single slice portion of a delicious strawberry pie on plate.',
    sentPromptScene: 'A cafeteria cook serves a balanced portion of vegetables on a tray.',
  },
  {
    word: 'deadly',
    partOfSpeech: 'adj.',
    meaningKo: '치명적인, 극심한',
    ipa: '/ˈded.li/',
    definition: 'likely to cause extreme harm, ruin, or defeat in games',
    sentence: 'The hot midday desert heat was deadly to unprepared travelers.',
    wordPromptScene: 'A desert trail sign warning hikers to carry plenty of drinking water.',
    sentPromptScene: 'A board game player avoids a deadly trap square on the board.',
  },
  {
    word: 'tension',
    partOfSpeech: 'n.',
    meaningKo: '긴장, 장력',
    ipa: '/ˈten.ʃən/',
    definition: 'a feeling of nervousness, or the state of being stretched tight',
    sentence: 'Deep breathing exercises helped release physical tension in his neck.',
    wordPromptScene: 'A tight guitar string vibrating gently with glowing musical resonance waves.',
    sentPromptScene: 'Musicians tune pegs to achieve the correct string tension on cello.',
  },
  {
    word: 'migrate',
    partOfSpeech: 'v.',
    meaningKo: '이동하다, 이주하다',
    ipa: '/ˈmaɪ.ɡreɪt/',
    definition: 'to travel from one region to another with the seasons',
    sentence: 'Monarch butterflies migrate thousands of miles south before winter freezes.',
    wordPromptScene: 'A flock of wild geese flying in classic V formation across sunset.',
    sentPromptScene: 'Students track how monarch butterflies migrate across North America on map.',
  },
  {
    word: 'access',
    partOfSpeech: 'n.',
    meaningKo: '접근, 입장',
    ipa: '/ˈæk.ses/',
    definition: 'the right or opportunity to use or enter a place',
    sentence: 'All students have free access to the digital school library.',
    wordPromptScene: 'A modern keycard with a green glowing signal opening a digital gate.',
    sentPromptScene: 'A student uses her school ID card to gain access to computer room.',
  },
  {
    word: 'excess',
    partOfSpeech: 'n.',
    meaningKo: '과잉, 초과량',
    ipa: '/ˈek.ses/',
    definition: 'an amount of something that is more than necessary or allowed',
    sentence: 'Pour away any excess water from the plant saucer after watering.',
    wordPromptScene: 'A measuring cup overflowing slightly with clear sparkling water drops.',
    sentPromptScene: 'A gardener drains excess water from the flowerpot to protect roots.',
  },
];

const day22_set4 = [
  {
    word: 'expose',
    partOfSpeech: 'v.',
    meaningKo: '노출시키다, 드러내다',
    ipa: '/ɪkˈspoʊz/',
    definition: 'to uncover something so that it can be seen or affected',
    sentence: 'Do not expose tender plant seedlings to freezing cold winds.',
    wordPromptScene: 'A green seedling protected inside a transparent glass cloche dome.',
    sentPromptScene: 'A gardener covers tomato plants not to expose them to frost.',
  },
  {
    word: 'shelter',
    partOfSpeech: 'n.',
    meaningKo: '피난처, 쉼터, 보호소',
    ipa: '/ˈʃel.tɚ/',
    definition: 'a building or place providing protection from bad weather',
    sentence: 'Hikers found cozy wooden shelter from the heavy mountain rain.',
    wordPromptScene: 'A sturdy wooden trail shelter cabin nestled beneath protective pine trees.',
    sentPromptScene: 'Hikers stay warm inside a trail shelter as rain pours outside.',
  },
  {
    word: 'absorb',
    partOfSpeech: 'v.',
    meaningKo: '흡수하다, 빨아들이다',
    ipa: '/əbˈzɔːrb/',
    definition: 'to take in liquid, gas, or other substances from surroundings',
    sentence: 'Plant roots absorb fresh water and nutrients from the rich soil.',
    wordPromptScene: 'A clean yellow sponge soaking up clear water droplets from a surface.',
    sentPromptScene: 'A science teacher shows how dry sponges absorb water in beaker.',
  },
  {
    word: 'incredible',
    partOfSpeech: 'adj.',
    meaningKo: '믿기 힘든, 놀라운',
    ipa: '/ɪnˈkred.ə.bəl/',
    definition: 'impossible, or very difficult, to believe, extraordinary',
    sentence: 'The acrobat performed an incredible balance trick on the high wire.',
    wordPromptScene: 'A sparkling golden star trophy surrounded by brilliant rainbow celebration fireworks.',
    sentPromptScene: 'An audience cheers for an incredible juggling performance by young performers.',
  },
  {
    word: 'consist',
    partOfSpeech: 'v.',
    meaningKo: '구성되다, 이루어져 있다',
    ipa: '/kənˈsɪst/',
    definition: 'to be made of or formed from something',
    sentence: 'A healthy lunch should consist of vegetables, fruit, and grains.',
    wordPromptScene: 'A balanced food plate divided neatly into grain, vegetable, and protein sections.',
    sentPromptScene: 'A chef explains that salad will consist of fresh lettuce, tomatoes, and cucumbers.',
  },
  {
    word: 'peak',
    partOfSpeech: 'n.',
    meaningKo: '산봉우리, 정점',
    ipa: '/piːk/',
    definition: 'the highest, pointed top of a mountain, or maximum level',
    sentence: 'Hikers reached the snowy mountain peak just in time for sunrise.',
    wordPromptScene: 'A jagged snow-dusted alpine mountain peak glowing in morning golden light.',
    sentPromptScene: 'Cheering climbers take a photo at the highest mountain peak summit.',
  },
  {
    word: 'weed',
    partOfSpeech: 'n.',
    meaningKo: '잡초',
    ipa: '/wiːd/',
    definition: 'a wild plant growing where it is not wanted',
    sentence: 'Children helped pull out every pesky weed from the flower garden.',
    wordPromptScene: 'A garden trowel lifting a wild dandelion weed from rich soil.',
    sentPromptScene: 'A smiling young gardener removes weed plants from the vegetable patch.',
  },
  {
    word: 'scare',
    partOfSpeech: 'v.',
    meaningKo: '겁주다, 놀라게 하다',
    ipa: '/sker/',
    definition: 'to make a person or animal feel sudden fear',
    sentence: 'A sudden thunderclap can scare the timid little puppy indoors.',
    wordPromptScene: 'A friendly cartoon scarecrow with a straw hat standing in cornfield.',
    sentPromptScene: 'A friendly scarecrow stands in the field to scare crows away.',
  },
  {
    word: 'diminish',
    partOfSpeech: 'v.',
    meaningKo: '줄어들다, 감소하다',
    ipa: '/dɪˈmɪn.ɪʃ/',
    definition: 'to reduce or become smaller in size or importance',
    sentence: 'The stormy rain clouds will diminish as the warm sun rises.',
    wordPromptScene: 'A line of five stars decreasing in size from large to small.',
    sentPromptScene: 'A doctor explains that resting will diminish fever symptoms within hours.',
  },
  {
    word: 'yield',
    partOfSpeech: 'v.',
    meaningKo: '산출하다, 양보하다',
    ipa: '/jiːld/',
    definition: 'to produce a crop or result, or give way to vehicles',
    sentence: 'The sunny apple orchard will yield crates of crisp sweet fruit.',
    wordPromptScene: 'A ripe apple tree branch heavy with dozens of shiny red apples.',
    sentPromptScene: 'Farmers smile as their fertile fields yield an abundant harvest of corn.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 22, set: 1, wordsData: day22_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 22, set: 2, wordsData: day22_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 22, set: 3, wordsData: day22_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 22, set: 4, wordsData: day22_set4 });
  console.log('DAY 22 written successfully');
}

run();
