import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 16
// ==========================================
const day16_set1 = [
  {
    word: 'nature',
    partOfSpeech: 'n.',
    meaningKo: '자연, 본성',
    ipa: '/ˈneɪ.tʃɚ/',
    definition: 'all the animals, plants, rocks, and places in the world',
    sentence: 'We love spending peaceful weekends exploring the beauty of nature.',
    wordPromptScene: 'A lush green mountain valley with a sparkling river and wild flowers.',
    sentPromptScene: 'Children hike along a quiet forest trail admiring the natural scenery.',
  },
  {
    word: 'experiment',
    partOfSpeech: 'n.',
    meaningKo: '실험',
    ipa: '/ɪkˈsper.ə.mənt/',
    definition: 'a scientific test done to discover something or test ideas',
    sentence: 'Students conducted an exciting science experiment with baking soda today.',
    wordPromptScene: 'Glass lab beakers bubbling with colorful foaming liquids on table.',
    sentPromptScene: 'Young students observe a bubbling volcano experiment in science class.',
  },
  {
    word: 'condition',
    partOfSpeech: 'n.',
    meaningKo: '상태, 조건',
    ipa: '/kənˈdɪʃ.ən/',
    definition: 'the particular state that something or someone is in',
    sentence: 'The antique wooden telescope was kept in excellent working condition.',
    wordPromptScene: 'A polished brass vintage telescope resting in pristine gleaming state.',
    sentPromptScene: 'An astronomer inspects the fine condition of observatory lenses.',
  },
  {
    word: 'distance',
    partOfSpeech: 'n.',
    meaningKo: '거리, 먼 곳',
    ipa: '/ˈdɪs.təns/',
    definition: 'the amount of space between two places or things',
    sentence: 'The runner measured the exact distance of the race track.',
    wordPromptScene: 'A yellow measuring tape stretching across a straight track lane.',
    sentPromptScene: 'Hikers look at a wooden trail sign showing the distance to summit.',
  },
  {
    word: 'evidence',
    partOfSpeech: 'n.',
    meaningKo: '증거, 흔적',
    ipa: '/ˈev.ə.dəns/',
    definition: 'facts or signs that make you believe that something is true',
    sentence: 'Dinosaur footprints in stone provided clear evidence of ancient life.',
    wordPromptScene: 'A fossilized dinosaur footprint embedded in a museum rock slab.',
    sentPromptScene: 'Scientists examine rock layers to find evidence of ancient river beds.',
  },
  {
    word: 'chemical',
    partOfSpeech: 'adj.',
    meaningKo: '화학의, 화학 물질의',
    ipa: '/ˈkem.ɪ.kəl/',
    definition: 'relating to the science of chemistry or substances',
    sentence: 'Mixing vinegar and baking soda creates an exciting chemical reaction.',
    wordPromptScene: 'Two beakers pouring colorful liquids together with glowing reaction bubbles.',
    sentPromptScene: 'A teacher explains a safe chemical reaction using food coloring and water.',
  },
  {
    word: 'fluid',
    partOfSpeech: 'n.',
    meaningKo: '유체, 액체',
    ipa: '/ˈfluː.ɪd/',
    definition: 'any substance that can flow easily, like liquid or gas',
    sentence: 'Drinking plenty of healthy fluid is important during hot summer.',
    wordPromptScene: 'A clear glass bottle filled with cool sparkling berry juice.',
    sentPromptScene: 'A runner drinks fruit juice to restore healthy bodily fluid balance.',
  },
  {
    word: 'extensive',
    partOfSpeech: 'adj.',
    meaningKo: '광범위한, 폭넓은',
    ipa: '/ɪkˈsten.sɪv/',
    definition: 'covering a large area or having a wide range',
    sentence: 'The university library contains an extensive collection of science encyclopedias.',
    wordPromptScene: 'Endless rows of towering wooden bookshelves filled with leather books.',
    sentPromptScene: 'Students explore an extensive collection of world maps in the archive.',
  },
  {
    word: 'process',
    partOfSpeech: 'n.',
    meaningKo: '과정, 절차',
    ipa: '/ˈprɑː.ses/',
    definition: 'a series of actions that you take to achieve a result',
    sentence: 'Making homemade honey bread is a fun and rewarding process.',
    wordPromptScene: 'A circular three-step illustrated diagram showing mixing, baking, and slicing.',
    sentPromptScene: 'A baker explains the whole process of kneading bread dough.',
  },
  {
    word: 'progress',
    partOfSpeech: 'n.',
    meaningKo: '진전, 발전',
    ipa: '/ˈprɑː.ɡres/',
    definition: 'movement forward towards achieving a goal or becoming better',
    sentence: 'She made remarkable progress in her violin playing this semester.',
    wordPromptScene: 'A green plant sprout growing taller step by step towards sunlight.',
    sentPromptScene: 'A student smiles at her learning progress chart hanging on wall.',
  },
];

const day16_set2 = [
  {
    word: 'planet',
    partOfSpeech: 'n.',
    meaningKo: '행성',
    ipa: '/ˈplæn.ɪt/',
    definition: 'a large round object that moves around a sun in space',
    sentence: 'Earth is the third planet from the sun in our galaxy.',
    wordPromptScene: 'A vibrant blue and green planet Earth glowing peacefully in deep space.',
    sentPromptScene: 'Students look through a telescope to observe a distant ringed planet.',
  },
  {
    word: 'conduct',
    partOfSpeech: 'v.',
    meaningKo: '수행하다, 지휘하다',
    ipa: '/kənˈdʌkt/',
    definition: 'to organize and carry out a particular activity or experiment',
    sentence: 'Young scientists will conduct a simple magnet experiment in class.',
    wordPromptScene: 'A horseshoe magnet attracting shiny iron paperclips on a desk.',
    sentPromptScene: 'A teacher guides children as they conduct a gravity drop experiment.',
  },
  {
    word: 'solid',
    partOfSpeech: 'adj.',
    meaningKo: '고체의, 단단한',
    ipa: '/ˈsɑː.lɪd/',
    definition: 'hard and firm, not liquid or gas in physical state',
    sentence: 'Water turns into solid ice cubes when frozen inside freezer.',
    wordPromptScene: 'A crystal clear solid ice cube resting on a wooden surface.',
    sentPromptScene: 'A science teacher shows how liquid wax hardens into solid candles.',
  },
  {
    word: 'eternal',
    partOfSpeech: 'adj.',
    meaningKo: '영원한, 끝없는',
    ipa: '/ɪˈtɝː.nəl/',
    definition: 'lasting forever or seeming to be without any end',
    sentence: 'The high mountain peak was covered in eternal white snow.',
    wordPromptScene: 'A majestic snow-capped mountain summit glowing under twinkling night stars.',
    sentPromptScene: 'Hikers admire the eternal beauty of the snowy mountain range.',
  },
  {
    word: 'gravity',
    partOfSpeech: 'n.',
    meaningKo: '중력',
    ipa: '/ˈɡræv.ə.t̬i/',
    definition: 'the natural force that makes objects fall toward the ground',
    sentence: 'Earth’s strong gravity keeps the atmosphere securely around the planet.',
    wordPromptScene: 'A red apple falling gracefully from a tree toward green grass.',
    sentPromptScene: 'A science teacher drops two balls to demonstrate the force of gravity.',
  },
  {
    word: 'melt',
    partOfSpeech: 'v.',
    meaningKo: '녹다, 녹이다',
    ipa: '/melt/',
    definition: 'to change from a solid into a liquid because of heat',
    sentence: 'The warm spring sunshine will melt the snowmen in garden.',
    wordPromptScene: 'A sweet strawberry ice cream cone melting slowly in warm sunshine.',
    sentPromptScene: 'A smiling snowman begins to melt gently under the bright spring sun.',
  },
  {
    word: 'astronaut',
    partOfSpeech: 'n.',
    meaningKo: '우주비행사',
    ipa: '/ˈæs.trə.nɑːt/',
    definition: 'a person trained to travel in a spacecraft into space',
    sentence: 'The brave astronaut floated weightlessly outside the modern space station.',
    wordPromptScene: 'A friendly cartoon astronaut in a white spacesuit waving in starry space.',
    sentPromptScene: 'An astronaut conducts science experiments inside a glowing orbital space laboratory.',
  },
  {
    word: 'smooth',
    partOfSpeech: 'adj.',
    meaningKo: '매끄러운, 부드러운',
    ipa: '/smuːð/',
    definition: 'having an even surface with no rough points or bumps',
    sentence: 'River water polished the grey stone until it was completely smooth.',
    wordPromptScene: 'A collection of rounded smooth river pebbles resting on velvet cloth.',
    sentPromptScene: 'A child skips a smooth flat pebble across the calm lake surface.',
  },
  {
    word: 'oxygen',
    partOfSpeech: 'n.',
    meaningKo: '산소',
    ipa: '/ˈɑːk.sɪ.dʒən/',
    definition: 'a gas with no smell or color that humans must breathe',
    sentence: 'Green forest trees produce fresh oxygen for all living creatures.',
    wordPromptScene: 'A vibrant green leaf releasing sparkling glowing oxygen bubbles into air.',
    sentPromptScene: 'A science teacher explains how lush plants release vital oxygen for breathing.',
  },
  {
    word: 'support',
    partOfSpeech: 'v.',
    meaningKo: '지지하다, 뒷받침하다',
    ipa: '/səˈpɔːrt/',
    definition: 'to hold the weight of something or give encouragement',
    sentence: 'Strong wooden pillars support the heavy roof of the gazebo.',
    wordPromptScene: 'Two sturdy carved stone pillars holding up a garden pergola arch.',
    sentPromptScene: 'Teammates cheer loudly to support their runner in the relay race.',
  },
];

const day16_set3 = [
  {
    word: 'acid',
    partOfSpeech: 'n.',
    meaningKo: '산, 산성 물질',
    ipa: '/ˈæs.ɪd/',
    definition: 'a chemical substance with a sour taste like lemon juice',
    sentence: 'Citric acid gives fresh lemons their sharp and sour taste.',
    wordPromptScene: 'A sliced ripe yellow lemon with sparkling sour droplets spraying outward.',
    sentPromptScene: 'A student uses litmus paper to test the acid level of lemon.',
  },
  {
    word: 'orbit',
    partOfSpeech: 'n.',
    meaningKo: '궤도',
    ipa: '/ˈɔːr.bɪt/',
    definition: 'the curved path of a celestial object around a star',
    sentence: 'The moon travels in a steady circular orbit around Earth.',
    wordPromptScene: 'A glowing white moon following a dotted glowing orbit ring around Earth.',
    sentPromptScene: 'A science class examines a mechanical solar system model in orbital motion.',
  },
  {
    word: 'toxic',
    partOfSpeech: 'adj.',
    meaningKo: '유독한, 해로운',
    ipa: '/ˈtɑːk.sɪk/',
    definition: 'containing poisonous substances that are harmful to living things',
    sentence: 'Wild colorful mushrooms in the woods can sometimes be toxic.',
    wordPromptScene: 'A cartoon potion bottle with a clear danger warning label on shelf.',
    sentPromptScene: 'A park ranger points at a sign warning visitors about toxic plants.',
  },
  {
    word: 'atom',
    partOfSpeech: 'n.',
    meaningKo: '원자',
    ipa: '/ˈæt̬.əm/',
    definition: 'the smallest particle of a chemical element that can exist',
    sentence: 'Every drop of water is made of hydrogen and oxygen atom units.',
    wordPromptScene: 'A glowing 3D atom model with colorful orbiting electron rings.',
    sentPromptScene: 'Students assemble plastic atomic models showing oxygen and hydrogen bond links.',
  },
  {
    word: 'liquid',
    partOfSpeech: 'n.',
    meaningKo: '액체',
    ipa: '/ˈlɪk.wɪd/',
    definition: 'a substance that flows freely like water, not solid or gas',
    sentence: 'She poured the cool clear liquid into a tall glass.',
    wordPromptScene: 'A glass pitcher pouring fresh blue water into a transparent tumbler.',
    sentPromptScene: 'A student measures a blue liquid inside a graduated laboratory cylinder.',
  },
  {
    word: 'universe',
    partOfSpeech: 'n.',
    meaningKo: '우주, 만물',
    ipa: '/ˈjuː.nə.vɝːs/',
    definition: 'all of space and everything in it, including stars and planets',
    sentence: 'Astronomers study billions of distant galaxies across the vast universe.',
    wordPromptScene: 'A deep space nebula glowing with vibrant purple, magenta, and gold stars.',
    sentPromptScene: 'Children gaze up at the starry planetarium dome displaying the vast universe.',
  },
  {
    word: 'reverse',
    partOfSpeech: 'v.',
    meaningKo: '반대로 하다, 뒤집다',
    ipa: '/rɪˈvɝːs/',
    definition: 'to change the direction, order, or position to the opposite',
    sentence: 'You can reverse the toy train by flipping the switch.',
    wordPromptScene: 'Two curved circular arrows pointing in reverse directions in green light.',
    sentPromptScene: 'A boy flips a switch to reverse the toy train on tracks.',
  },
  {
    word: 'extend',
    partOfSpeech: 'v.',
    meaningKo: '연장하다, 뻗다',
    ipa: '/ɪkˈstend/',
    definition: 'to make something longer or stretch out your body parts',
    sentence: 'The gymnast will extend her arms gracefully during the beam routine.',
    wordPromptScene: 'A telescoping metal pointer extending smoothly out into full length.',
    sentPromptScene: 'A dancer steps onto the studio floor to extend arms in pose.',
  },
  {
    word: 'extent',
    partOfSpeech: 'n.',
    meaningKo: '정도, 범위',
    ipa: '/ɪkˈstent/',
    definition: 'the area, length, or degree to which something extends',
    sentence: 'We were amazed by the vast extent of the green forest.',
    wordPromptScene: 'A wide panoramic view of an endless green forest canopy from above.',
    sentPromptScene: 'Hikers stand on a summit viewing the immense extent of valley.',
  },
  {
    word: 'expand',
    partOfSpeech: 'v.',
    meaningKo: '확장하다, 팽창하다',
    ipa: '/ɪkˈspænd/',
    definition: 'to increase in size, number, or importance, or open out',
    sentence: 'Balloons expand as you blow warm air into them gently.',
    wordPromptScene: 'A bright red rubber balloon blowing up larger with gentle puffs.',
    sentPromptScene: 'A child watches bread dough expand in the warm kitchen bowl.',
  },
];

const day16_set4 = [
  {
    word: 'preserve',
    partOfSpeech: 'v.',
    meaningKo: '보존하다, 지키다',
    ipa: '/prɪˈzɝːv/',
    definition: 'to keep something in its original state or in good condition',
    sentence: 'National parks help preserve rare native flowers and wild animal habitats.',
    wordPromptScene: 'A glass jar filled with preserved sweet strawberry jam and ribbon.',
    sentPromptScene: 'Park rangers plant young saplings to preserve the natural mountain forest.',
  },
  {
    word: 'vapor',
    partOfSpeech: 'n.',
    meaningKo: '증기, 수증기',
    ipa: '/ˈveɪ.pɚ/',
    definition: 'a mass of very small drops of liquid in the air',
    sentence: 'Warm water vapor rose gently from the hot tea kettle.',
    wordPromptScene: 'Swirls of gentle white steam rising from a shiny tea kettle spout.',
    sentPromptScene: 'Clouds of white water vapor form above the bubbling thermal spring.',
  },
  {
    word: 'invisible',
    partOfSpeech: 'adj.',
    meaningKo: '눈에 보이지 않는',
    ipa: '/ɪnˈvɪz.ə.bəl/',
    definition: 'impossible to see with your eyes, not visible',
    sentence: 'The gentle wind is invisible, but we can feel its breeze.',
    wordPromptScene: 'An outline of a friendly cartoon ghost smiling gently among flowers.',
    sentPromptScene: 'Children fly colorful kites carried high by the invisible gusting wind.',
  },
  {
    word: 'substance',
    partOfSpeech: 'n.',
    meaningKo: '물질, 실체',
    ipa: '/ˈsʌb.stəns/',
    definition: 'material with particular physical characteristics, matter of any kind',
    sentence: 'Honey is a thick and sweet natural substance made by bees.',
    wordPromptScene: 'A wooden honey dipper dripping thick golden honey into a ceramic pot.',
    sentPromptScene: 'A science teacher displays three test tubes holding different powdery white substance.',
  },
  {
    word: 'particle',
    partOfSpeech: 'n.',
    meaningKo: '입자, 미립자',
    ipa: '/ˈpɑːr.t̬ə.kəl/',
    definition: 'a very small piece of something or tiny unit of matter',
    sentence: 'Tiny dust particle specks danced in the beam of morning sunshine.',
    wordPromptScene: 'Golden sunbeams illuminating floating microscopic sparkling dust particles in air.',
    sentPromptScene: 'A scientist views tiny pollen particle specimens through a high-powered microscope.',
  },
  {
    word: 'moisture',
    partOfSpeech: 'n.',
    meaningKo: '수분, 습기',
    ipa: '/ˈmɔɪs.tʃɚ/',
    definition: 'very small drops of water present in the air or surface',
    sentence: 'Morning dew adds fresh moisture to the green garden lawn grass.',
    wordPromptScene: 'A clear crystal dewdrop clinging to the tip of a green leaf.',
    sentPromptScene: 'A gardener feels the rich soil to check for healthy plant moisture.',
  },
  {
    word: 'abstract',
    partOfSpeech: 'adj.',
    meaningKo: '추상적인',
    ipa: '/ˈæb.strækt/',
    definition: 'existing in thought or as an idea, not physical reality',
    sentence: 'Love and courage are abstract concepts that we cannot physically touch.',
    wordPromptScene: 'An art canvas with colorful overlapping geometric pastel polygons and swirls.',
    sentPromptScene: 'An art teacher explains an abstract colorful painting to museum visitors.',
  },
  {
    word: 'valid',
    partOfSpeech: 'adj.',
    meaningKo: '유효한, 타당한',
    ipa: '/ˈvæl.ɪd/',
    definition: 'based on truth or reason, or legally acceptable for use',
    sentence: 'You must show a valid student pass to enter the library.',
    wordPromptScene: 'A stamped ID card with a glowing green verified checkmark badge.',
    sentPromptScene: 'A student presents a valid pass at the museum ticket turnstile.',
  },
  {
    word: 'invention',
    partOfSpeech: 'n.',
    meaningKo: '발명, 발명품',
    ipa: '/ɪnˈven.ʃən/',
    definition: 'something that has never been made before, a new creation',
    sentence: 'The electric lightbulb was a revolutionary invention that changed our lives.',
    wordPromptScene: 'A classic Edison lightbulb glowing brightly with intricate filament coils.',
    sentPromptScene: 'A young inventor displays his solar-powered fan invention at the fair.',
  },
  {
    word: 'stick',
    partOfSpeech: 'v.',
    meaningKo: '붙이다, 고수하다',
    ipa: '/stɪk/',
    definition: 'to join or become attached to something with glue or tape',
    sentence: 'Use clear tape to stick the colorful poster on the wall.',
    wordPromptScene: 'A roll of transparent tape and colorful stickers sticking to paper.',
    sentPromptScene: 'A student uses a glue stick to stick pictures on poster.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 16, set: 1, wordsData: day16_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 16, set: 2, wordsData: day16_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 16, set: 3, wordsData: day16_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 16, set: 4, wordsData: day16_set4 });
  console.log('DAY 16 written successfully');
}

run();
