import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// DAY 01
const day01_set1 = [
  {
    word: 'chore',
    partOfSpeech: 'n.',
    meaningKo: '집안일',
    ipa: '/tʃɔːr/',
    definition: 'a small job you must do at home',
    sentence: 'The little robot finished every morning chore with a smile.',
    wordPromptScene: 'A cheerful blue robot sweeps a bright living room floor.',
    sentPromptScene: 'A smiling robot happily washes dishes in a sunny kitchen.',
  },
  {
    word: 'laundry',
    partOfSpeech: 'n.',
    meaningKo: '세탁물, 빨래',
    ipa: '/ˈlɔːn.dri/',
    definition: 'clothes that need washing or are already washed',
    sentence: 'She carried a heavy basket of fresh laundry outside.',
    wordPromptScene: 'A wicker basket full of colorful folded shirts and towels.',
    sentPromptScene: 'A cheerful girl carries a laundry basket into a garden.',
  },
  {
    word: 'flavor',
    partOfSpeech: 'n.',
    meaningKo: '맛, 풍미',
    ipa: '/ˈfleɪ.vər/',
    definition: 'the particular taste of food or drink',
    sentence: 'The chef added sweet berry flavor to the cold juice.',
    wordPromptScene: 'Three scoops of colorful ice cream with fresh fruit toppings.',
    sentPromptScene: 'A baker tastes a spoonful of sweet cream with delight.',
  },
  {
    word: 'recipe',
    partOfSpeech: 'n.',
    meaningKo: '조리법, 레시피',
    ipa: '/ˈres.ə.pi/',
    definition: 'a set of instructions for cooking food',
    sentence: 'The baker read an old family recipe for warm bread.',
    wordPromptScene: 'An open cookbook with illustrated steps and fresh baking ingredients.',
    sentPromptScene: 'A happy baker points at a recipe card beside flour.',
  },
  {
    word: 'beverage',
    partOfSpeech: 'n.',
    meaningKo: '음료',
    ipa: '/ˈbev.ər.ɪdʒ/',
    definition: 'any liquid drink other than water',
    sentence: 'They enjoyed a cold fruity beverage on a hot afternoon.',
    wordPromptScene: 'A glass of sparkling lemonade with a straw and lemon.',
    sentPromptScene: 'Two friends drink a colorful iced beverage at an outdoor cafe.',
  },
  {
    word: 'operate',
    partOfSpeech: 'v.',
    meaningKo: '작동하다, 조작하다',
    ipa: '/ˈɑː.pə.reɪt/',
    definition: 'to use or control a machine or tool',
    sentence: 'The young mechanic learned how to operate the giant telescope.',
    wordPromptScene: 'A person presses glowing buttons on a friendly control panel.',
    sentPromptScene: 'An excited boy carefully learns to operate a big brass telescope.',
  },
  {
    word: 'edible',
    partOfSpeech: 'adj.',
    meaningKo: '먹을 수 있는, 식용의',
    ipa: '/ˈed.ə.bəl/',
    definition: 'safe or suitable to be eaten',
    sentence: 'These forest mushrooms are safe and edible for our dinner.',
    wordPromptScene: 'A basket of fresh edible mushrooms and crisp green apples.',
    sentPromptScene: 'A smiling explorer finds edible wild berries along a forest path.',
  },
  {
    word: 'shelf',
    partOfSpeech: 'n.',
    meaningKo: '선반',
    ipa: '/ʃelf/',
    definition: 'a flat board for holding objects',
    sentence: 'He placed a heavy dictionary on the highest wooden shelf.',
    wordPromptScene: 'A wooden wall shelf holding colorful books and a tiny plant.',
    sentPromptScene: 'A tall boy places a thick dictionary onto a high shelf.',
  },
  {
    word: 'quite',
    partOfSpeech: 'adv.',
    meaningKo: '꽤, 상당히',
    ipa: '/kwaɪt/',
    definition: 'to a large degree or very much',
    sentence: 'The giant library puzzle was quite difficult to solve quickly.',
    wordPromptScene: 'A tall thermometer showing high temperature with bright sunny rays.',
    sentPromptScene: 'A focused student solves a quite complicated jigsaw puzzle at desk.',
  },
  {
    word: 'quiet',
    partOfSpeech: 'adj.',
    meaningKo: '조용한',
    ipa: '/ˈkwaɪ.ət/',
    definition: 'making very little noise or sound',
    sentence: 'The cozy reading corner remained quiet throughout the snowy afternoon.',
    wordPromptScene: 'A peaceful sleeping cat resting on a soft pillow in silence.',
    sentPromptScene: 'Children read storybooks quietly in a quiet sunlit school library.',
  },
];

const day01_set2 = [
  {
    word: 'sweep',
    partOfSpeech: 'v.',
    meaningKo: '쓸다, 청소하다',
    ipa: '/swiːp/',
    definition: 'to clean a floor by using a brush',
    sentence: 'The friendly guard helped sweep dry leaves off the sidewalk.',
    wordPromptScene: 'A wooden broom sweeping golden dust across a wooden floor.',
    sentPromptScene: 'A friendly caretaker uses a broom to sweep fallen autumn leaves.',
  },
  {
    word: 'glance',
    partOfSpeech: 'v.',
    meaningKo: '힐끗 보다',
    ipa: '/ɡlæns/',
    definition: 'to look quickly at something',
    sentence: 'She gave a quick glance at the ticking wall clock.',
    wordPromptScene: 'A cartoon character with big eyes peeking sideways quickly.',
    sentPromptScene: 'A student takes a quick glance at a wristwatch before class.',
  },
  {
    word: 'match',
    partOfSpeech: 'v.',
    meaningKo: '일치하다, 어울리다',
    ipa: '/mætʃ/',
    definition: 'to be equal to or go well with something',
    sentence: 'These striped warm socks match the color of my shoes.',
    wordPromptScene: 'Two matching colorful puzzle pieces fitting together perfectly.',
    sentPromptScene: 'A girl wears yellow boots that match her bright raincoat.',
  },
  {
    word: 'furniture',
    partOfSpeech: 'n.',
    meaningKo: '가구',
    ipa: '/ˈfɜːr.nɪ.tʃər/',
    definition: 'movable objects like chairs, tables, and beds',
    sentence: 'They moved new wooden furniture into the sunny living room.',
    wordPromptScene: 'A cozy set of miniature wooden chair, table, and sofa.',
    sentPromptScene: 'Workers carry a handsome wooden table into an empty sunny room.',
  },
  {
    word: 'manual',
    partOfSpeech: 'n.',
    meaningKo: '설명서, 안내서',
    ipa: '/ˈmæn.ju.əl/',
    definition: 'a book that gives instructions for doing something',
    sentence: 'He opened the toy manual to assemble the model spaceship.',
    wordPromptScene: 'An open instruction booklet showing diagrams and tools.',
    sentPromptScene: 'A curious child follows a paper manual to build a robot.',
  },
  {
    word: 'value',
    partOfSpeech: 'n.',
    meaningKo: '가치, 중요성',
    ipa: '/ˈvæl.juː/',
    definition: 'the importance, worth, or usefulness of something',
    sentence: 'This shiny antique coin has great historical value to collectors.',
    wordPromptScene: 'A glowing gold medallion surrounded by sparkling gem stars.',
    sentPromptScene: 'A museum guide explains the value of a golden ancient artifact.',
  },
  {
    word: 'pot',
    partOfSpeech: 'n.',
    meaningKo: '냄비, 화분',
    ipa: '/pɑːt/',
    definition: 'a deep round container used for cooking or plants',
    sentence: 'A green herb grew happily in a clay flower pot.',
    wordPromptScene: 'A smooth terracotta ceramic pot with a small green plant.',
    sentPromptScene: 'A smiling gardener waters a green seedling inside a clay pot.',
  },
  {
    word: 'grocery',
    partOfSpeech: 'n.',
    meaningKo: '식료품, 식료품점',
    ipa: '/ˈɡroʊ.sər.i/',
    definition: 'food and other household goods sold in a store',
    sentence: 'The brown paper bag was packed with healthy grocery items.',
    wordPromptScene: 'A paper shopping bag brimming with fresh bread, milk, and carrots.',
    sentPromptScene: 'A customer loads fresh grocery bags into a red bicycle basket.',
  },
  {
    word: 'striped',
    partOfSpeech: 'adj.',
    meaningKo: '줄무늬의',
    ipa: '/straɪpt/',
    definition: 'having lines or bands of different colors',
    sentence: 'A cute puppy wore a warm striped sweater in winter.',
    wordPromptScene: 'A cozy fabric scarf with bold alternating blue and white stripes.',
    sentPromptScene: 'A playful puppy wearing a striped sweater runs across green grass.',
  },
  {
    word: 'mind',
    partOfSpeech: 'v.',
    meaningKo: '신경 쓰다, 꺼리다',
    ipa: '/maɪnd/',
    definition: 'to feel annoyed or worried about something',
    sentence: 'Do you mind if we open the window for fresh air?',
    wordPromptScene: 'A friendly person politely waving one hand with a warm smile.',
    sentPromptScene: 'A passenger kindly asks before opening a window on a train.',
  },
];

const day01_set3 = [
  {
    word: 'receipt',
    partOfSpeech: 'n.',
    meaningKo: '영수증',
    ipa: '/rɪˈsiːt/',
    definition: 'a paper showing that you have paid for goods',
    sentence: 'The cashier handed him a printed receipt after the purchase.',
    wordPromptScene: 'A printed paper store receipt showing prices and a barcode.',
    sentPromptScene: 'A friendly cashier gives a paper receipt to a polite customer.',
  },
  {
    word: 'bitter',
    partOfSpeech: 'adj.',
    meaningKo: '쓴, 쌉싸름한',
    ipa: '/ˈbɪt.ər/',
    definition: 'having a sharp, strong taste like black coffee',
    sentence: 'The dark chocolate had a slightly bitter but rich flavor.',
    wordPromptScene: 'A bar of dark chocolate broken next to a coffee bean.',
    sentPromptScene: 'A boy makes a funny face after tasting bitter black tea.',
  },
  {
    word: 'appearance',
    partOfSpeech: 'n.',
    meaningKo: '외모, 출현',
    ipa: '/əˈpɪr.əns/',
    definition: 'the way that someone or something looks',
    sentence: 'His neat appearance made a positive impression during the interview.',
    wordPromptScene: 'A tidy full-length mirror reflecting a neatly styled school uniform.',
    sentPromptScene: 'A student straightens a collar while checking appearance in a mirror.',
  },
  {
    word: 'iron',
    partOfSpeech: 'n.',
    meaningKo: '다리미, 철',
    ipa: '/ˈaɪ.ərn/',
    definition: 'a heated tool used to smooth clothes',
    sentence: 'She used a hot steam iron to smooth the shirt.',
    wordPromptScene: 'A modern blue steam iron resting upright on an ironing board.',
    sentPromptScene: 'A careful person presses wrinkles out of a shirt using iron.',
  },
  {
    word: 'palm',
    partOfSpeech: 'n.',
    meaningKo: '손바닥, 야자나무',
    ipa: '/pɑːm/',
    definition: 'the inside flat part of your hand',
    sentence: 'The little bird sat gently on the open palm today.',
    wordPromptScene: 'An open friendly cartoon hand showing clean lines on palm.',
    sentPromptScene: 'A tiny bluebird rests safely on an open human palm.',
  },
  {
    word: 'fancy',
    partOfSpeech: 'adj.',
    meaningKo: '화려한, 고급스러운',
    ipa: '/ˈfæn.si/',
    definition: 'expensive, decorative, or not plain',
    sentence: 'They wore fancy costumes for the royal festival in town.',
    wordPromptScene: 'A sparkling decorative masquerade mask with shiny gold trim.',
    sentPromptScene: 'Children wearing fancy royal capes dance at a school festival.',
  },
  {
    word: 'soak',
    partOfSpeech: 'v.',
    meaningKo: '담그다, 푹 젖게 하다',
    ipa: '/soʊk/',
    definition: 'to make something very wet in liquid',
    sentence: 'Please soak the dry seeds in warm water overnight first.',
    wordPromptScene: 'A glass bowl of clear water soaking colorful beans.',
    sentPromptScene: 'A gardener places dry sunflower seeds to soak in a bowl.',
  },
  {
    word: 'appeal',
    partOfSpeech: 'v.',
    meaningKo: '흥미를 끌다, 호소하다',
    ipa: '/əˈpiːl/',
    definition: 'to be attractive or interesting to someone',
    sentence: 'The bright colors of the book appeal to young readers.',
    wordPromptScene: 'A sparkling magnet drawing glowing stars towards its center.',
    sentPromptScene: 'A colorful pop-up picture book catches children with strong appeal.',
  },
  {
    word: 'compare',
    partOfSpeech: 'v.',
    meaningKo: '비교하다',
    ipa: '/kəmˈper/',
    definition: 'to examine things to see how they are different',
    sentence: 'We must compare the two maps before choosing our trail.',
    wordPromptScene: 'A classic balance scale weighing two different colorful apples.',
    sentPromptScene: 'Two hikers look closely to compare two different forest trail maps.',
  },
  {
    word: 'compel',
    partOfSpeech: 'v.',
    meaningKo: '강요하다, ~하게 만들다',
    ipa: '/kəmˈpel/',
    definition: 'to force someone to do something',
    sentence: 'Strong winds compel the sailors to stay in the harbor.',
    wordPromptScene: 'A glowing magical compass directing ships safely toward calm water.',
    sentPromptScene: 'Rough stormy ocean waves compel a wooden ship to harbor safely.',
  },
];

const day01_set4 = [
  {
    word: 'browse',
    partOfSpeech: 'v.',
    meaningKo: '둘러보다, 훑어보다',
    ipa: '/braʊz/',
    definition: 'to look at many things in a relaxed way',
    sentence: 'Visitors love to browse through old books in this shop.',
    wordPromptScene: 'A magnifying glass floating over open pages of ancient books.',
    sentPromptScene: 'A curious reader stops to browse colorful bookshelves in a store.',
  },
  {
    word: 'appetite',
    partOfSpeech: 'n.',
    meaningKo: '식욕, 입맛',
    ipa: '/ˈæp.ə.taɪt/',
    definition: 'the natural desire to eat food',
    sentence: 'Playing outdoor games gave the children a very hearty appetite.',
    wordPromptScene: 'A delicious steaming bowl of soup and freshly baked bread.',
    sentPromptScene: 'An active child shows a big appetite beside a lunch bowl.',
  },
  {
    word: 'attach',
    partOfSpeech: 'v.',
    meaningKo: '붙이다, 첨부하다',
    ipa: '/əˈtætʃ/',
    definition: 'to join or fix one thing to another',
    sentence: 'Remember to attach a name tag to your new backpack.',
    wordPromptScene: 'A colorful paperclip connecting two shiny papers securely.',
    sentPromptScene: 'A student uses a small clip to attach a name tag.',
  },
  {
    word: 'shut',
    partOfSpeech: 'v.',
    meaningKo: '닫다, 닫히다',
    ipa: '/ʃʌt/',
    definition: 'to close something firmly',
    sentence: 'Please shut the wooden gate before walking down the hill.',
    wordPromptScene: 'A sturdy wooden garden gate closed tightly with a latch.',
    sentPromptScene: 'A boy reaches out to shut a garden gate carefully.',
  },
  {
    word: 'tender',
    partOfSpeech: 'adj.',
    meaningKo: '부드러운, 연한',
    ipa: '/ˈten.dər/',
    definition: 'soft and easy to chew or cut',
    sentence: 'The cooked carrots were sweet and very tender to eat.',
    wordPromptScene: 'A tender green plant sprout growing softly out of rich soil.',
    sentPromptScene: 'A cook gently slices tender steamed vegetables on a wooden board.',
  },
  {
    word: 'pour',
    partOfSpeech: 'v.',
    meaningKo: '붓다, 따르다',
    ipa: '/pɔːr/',
    definition: 'to make a liquid flow from a container',
    sentence: 'He will pour fresh orange juice into four tall glasses.',
    wordPromptScene: 'A glass pitcher pouring clear water into a sparkling glass.',
    sentPromptScene: 'A young boy begins to pour cold milk into glass bottles.',
  },
  {
    word: 'lean',
    partOfSpeech: 'v.',
    meaningKo: '기울이다, 기대다',
    ipa: '/liːn/',
    definition: 'to slope or bend your body in a direction',
    sentence: 'The tired hiker decided to lean against a tall tree.',
    wordPromptScene: 'A wooden walking stick leaning gracefully against a stone wall.',
    sentPromptScene: 'A tired backpacker stops to lean against an old pine tree.',
  },
  {
    word: 'temporary',
    partOfSpeech: 'adj.',
    meaningKo: '임시의, 일시적인',
    ipa: '/ˈtem.pə.rer.i/',
    definition: 'lasting for only a short time',
    sentence: 'They built a temporary wooden bridge across the shallow river.',
    wordPromptScene: 'A pop-up yellow tent set up on a grassy field.',
    sentPromptScene: 'Hikers cross a temporary wooden plank bridge over a narrow stream.',
  },
  {
    word: 'cottage',
    partOfSpeech: 'n.',
    meaningKo: '작은 집, 오두막',
    ipa: '/ˈkɑː.tɪdʒ/',
    definition: 'a small simple house usually in the countryside',
    sentence: 'Grandmother lives in a lovely stone cottage near the forest.',
    wordPromptScene: 'A picturesque stone cottage with a blooming flower garden and chimney.',
    sentPromptScene: 'A cozy cottage stands peacefully by a quiet countryside meadow pathway.',
  },
  {
    word: 'minute',
    partOfSpeech: 'n.',
    meaningKo: '분, 잠깐',
    ipa: '/ˈmɪn.ɪt/',
    definition: 'a unit of time equal to sixty seconds',
    sentence: 'Wait just one minute while I pack my school bag.',
    wordPromptScene: 'A sand hourglass with glowing sand grains falling steadily downward.',
    sentPromptScene: 'A boy checks his wristwatch and waits a minute for friends.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 1, set: 1, wordsData: day01_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 1, set: 2, wordsData: day01_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 1, set: 3, wordsData: day01_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 1, set: 4, wordsData: day01_set4 });
  console.log('DAY 01 written successfully');
}

run();
