import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 28
// ==========================================
const day28_set1 = [
  {
    word: 'economic',
    partOfSpeech: 'adj.',
    meaningKo: '경제의, 경제학의',
    ipa: '/ˌiː.kəˈnɑː.mɪk/',
    definition: 'relating to trade, industry, and the management of money',
    sentence: 'Opening new local craft markets gave an economic boost to town.',
    wordPromptScene: 'A bustling colorful community farmers market with fruit stalls and smiling vendors.',
    sentPromptScene: 'Students study simple economic trade concepts using toy shop game.',
  },
  {
    word: 'budget',
    partOfSpeech: 'n.',
    meaningKo: '예산, 비용',
    ipa: '/ˈbʌdʒ.ɪt/',
    definition: 'a plan showing how much money will be earned and spent',
    sentence: 'The student club planned a careful budget for the spring picnic.',
    wordPromptScene: 'A neat budget ledger notebook with a pencil, calculator, and coins.',
    sentPromptScene: 'Children make a budget checklist before buying craft supplies for class.',
  },
  {
    word: 'possible',
    partOfSpeech: 'adj.',
    meaningKo: '가능한',
    ipa: '/ˈpɑː.sə.bəl/',
    definition: 'able to be done or achieved, not impossible',
    sentence: 'With team cooperation, it is possible to achieve any great goal.',
    wordPromptScene: 'A golden star glowing at the top of a climbable ladder.',
    sentPromptScene: 'A teacher encourages students that mastering fractions is completely possible with practice.',
  },
  {
    word: 'income',
    partOfSpeech: 'n.',
    meaningKo: '수입, 소득',
    ipa: '/ˈɪn.kʌm/',
    definition: 'money that is earned from work, investments, or business',
    sentence: 'Part of her weekly allowance income went into the savings jar.',
    wordPromptScene: 'A clear glass piggy bank jar with shiny golden coins inside.',
    sentPromptScene: 'A young artist uses her craft sale income to buy new paints.',
  },
  {
    word: 'crisis',
    partOfSpeech: 'n.',
    meaningKo: '위기, 중대한 국면',
    ipa: '/ˈkraɪ.sɪs/',
    definition: 'a time of great difficulty, danger, or difficulty in story',
    sentence: 'The brave firefighters resolved the water pipe crisis quickly and safely.',
    wordPromptScene: 'A friendly yellow emergency repair truck with flashing amber safety lights.',
    sentPromptScene: 'Characters in the adventure book work together to overcome a sudden crisis.',
  },
  {
    word: 'trade',
    partOfSpeech: 'n.',
    meaningKo: '무역, 거래, 교환',
    ipa: '/treɪd/',
    definition: 'the buying, selling, or exchanging of goods and services',
    sentence: 'Ancient merchant ships sailed across oceans for the spice trade route.',
    wordPromptScene: 'A vintage sailing ship carrying cargo crates across calm sunlit waters.',
    sentPromptScene: 'Children engage in a fair toy trade during the school swap meet.',
  },
  {
    word: 'offer',
    partOfSpeech: 'v.',
    meaningKo: '제공하다, 제안하다',
    ipa: '/ˈɑː.fɚ/',
    definition: 'to provide or supply something, or ask if someone wants',
    sentence: 'The friendly baker will offer a warm sample cookie to visitors.',
    wordPromptScene: 'A baker holding out a tray of warm fresh chocolate chip cookies.',
    sentPromptScene: 'A student is happy to offer assistance to a classmate carrying books.',
  },
  {
    word: 'specific',
    partOfSpeech: 'adj.',
    meaningKo: '구체적인, 특정한',
    ipa: '/spəˈsɪf.ɪk/',
    definition: 'clearly defined or identified, particular rather than general',
    sentence: 'Follow the specific recipe steps carefully when baking delicious vanilla cake.',
    wordPromptScene: 'An open recipe book with numbered step-by-step illustrations and checkmarks.',
    sentPromptScene: 'A science teacher gives specific instructions for measuring laboratory liquids safely.',
  },
  {
    word: 'several',
    partOfSpeech: 'det.',
    meaningKo: '몇몇의, 서너 개의',
    ipa: '/ˈsev.ɚ.əl/',
    definition: 'more than two but not many, a small number of',
    sentence: 'She picked several ripe red apples from the backyard orchard tree.',
    wordPromptScene: 'Four shiny red apples resting in a small wicker basket.',
    sentPromptScene: 'A student borrows several astronomy books from the school library for research.',
  },
  {
    word: 'severe',
    partOfSpeech: 'adj.',
    meaningKo: '극심한, 엄격한',
    ipa: '/səˈvɪr/',
    definition: 'very serious, harsh, or extreme in degree',
    sentence: 'The cabin was well built to withstand severe winter mountain blizzards.',
    wordPromptScene: 'A cozy log cabin with glowing windows during a snowy winter blizzard.',
    sentPromptScene: 'Hikers take shelter indoors to stay safe from severe stormy weather.',
  },
];

const day28_set2 = [
  {
    word: 'invest',
    partOfSpeech: 'v.',
    meaningKo: '투자하다, 쏟다',
    ipa: '/ɪnˈvest/',
    definition: 'to put time, effort, or money into something for growth',
    sentence: 'It is always wise to invest time in reading good books.',
    wordPromptScene: 'A small coin sprouting into a flourishing green money tree sapling.',
    sentPromptScene: 'Students invest effort into practicing violin every afternoon before the recital.',
  },
  {
    word: 'wealth',
    partOfSpeech: 'n.',
    meaningKo: '부, 재산, 풍부함',
    ipa: '/welθ/',
    definition: 'a large amount of money, valuable possessions, or rich resources',
    sentence: 'The public library holds a wealth of knowledge for young readers.',
    wordPromptScene: 'A grand bookshelf glowing with golden books and sparkling knowledge stars.',
    sentPromptScene: 'A nature guide explains the rich biodiversity wealth of the forest wetland.',
  },
  {
    word: 'provide',
    partOfSpeech: 'v.',
    meaningKo: '제공하다, 공급하다',
    ipa: '/prəˈvaɪd/',
    definition: 'to give something that is needed or wanted to someone',
    sentence: 'Big leafy oak trees provide cool comforting shade during hot summer.',
    wordPromptScene: 'A large leafy oak tree spreading broad branches over a wooden bench.',
    sentPromptScene: 'Volunteers provide warm meals and coats to community shelters during winter.',
  },
  {
    word: 'merchant',
    partOfSpeech: 'n.',
    meaningKo: '상인, 무역상',
    ipa: '/ˈmɝː.tʃənt/',
    definition: 'a person whose job is buying and selling goods in shop',
    sentence: 'The friendly silk merchant displayed rolls of colorful embroidered fabrics.',
    wordPromptScene: 'A cheerful market stall merchant surrounded by colorful spools of silk.',
    sentPromptScene: 'A merchant introduces exotic spices to curious shoppers at the bazaar.',
  },
  {
    word: 'finance',
    partOfSpeech: 'n.',
    meaningKo: '재정, 금융, 자금',
    ipa: '/ˈfaɪ.næns/',
    definition: 'the management of large amounts of money by businesses or states',
    sentence: 'She took a fun junior finance class to learn about savings.',
    wordPromptScene: 'A piggy bank, shiny calculator, and organized coin stacks on desk.',
    sentPromptScene: 'A student treasurer manages club finance and records bake sale receipts.',
  },
  {
    word: 'derive',
    partOfSpeech: 'v.',
    meaningKo: '끌어내다, 얻다',
    ipa: '/dɪˈraɪv/',
    definition: 'to get something from a specified source or origin',
    sentence: 'Many modern herbal medicines derive their healing properties from wild plants.',
    wordPromptScene: 'A droplet of herbal essential oil dripping from a green mint leaf.',
    sentPromptScene: 'Students derive satisfaction from solving challenging mathematics equations independently.',
  },
  {
    word: 'credit',
    partOfSpeech: 'n.',
    meaningKo: '신용, 칭찬, 학점',
    ipa: '/ˈkred.ɪt/',
    definition: 'praise or approval given to someone for an achievement',
    sentence: 'The teacher gave him credit for his creative science poster idea.',
    wordPromptScene: 'A gold star medal ribbon inscribed with the word Honor in gold.',
    sentPromptScene: 'Teammates share credit equally after winning the science Olympiad trophy.',
  },
  {
    word: 'substitute',
    partOfSpeech: 'n.',
    meaningKo: '대체물, 대리자',
    ipa: '/ˈsʌb.stə.tuːt/',
    definition: 'a person or thing that takes the place of another',
    sentence: 'Applesauce is a delicious healthy substitute for sugar in muffin baking.',
    wordPromptScene: 'A jar of sweet homemade applesauce beside freshly baked golden muffins.',
    sentPromptScene: 'A friendly substitute teacher guides the class through an interesting art activity.',
  },
  {
    word: 'debt',
    partOfSpeech: 'n.',
    meaningKo: '빚, 부채, 은혜',
    ipa: '/det/',
    definition: 'something, especially money, that is owed to someone else',
    sentence: 'He returned borrowed library books promptly to clear any small debt.',
    wordPromptScene: 'A shiny zero balance receipt stamped with a green Paid stamp.',
    sentPromptScene: 'A student returns borrowed colored pencils to clear her small craft debt.',
  },
  {
    word: 'bill',
    partOfSpeech: 'n.',
    meaningKo: '청구서, 지폐, 부리',
    ipa: '/bɪl/',
    definition: 'a request for payment, or the beak of a bird',
    sentence: 'The toucan used its colorful curved bill to pick berries.',
    wordPromptScene: 'A vibrant tropical toucan perched on branch showing its rainbow beak.',
    sentPromptScene: 'A waiter brings the restaurant bill neatly in a leather folder.',
  },
];

const day28_set3 = [
  {
    word: 'cancel',
    partOfSpeech: 'v.',
    meaningKo: '취소하다',
    ipa: '/ˈkæn.səl/',
    definition: 'to decide that an organized event will not happen',
    sentence: 'Rain forced organizers to cancel the afternoon outdoor soccer match.',
    wordPromptScene: 'A calendar page with a friendly blue Reschedule note over a date.',
    sentPromptScene: 'Teachers announce they will cancel the outdoor picnic and move indoors.',
  },
  {
    word: 'replace',
    partOfSpeech: 'v.',
    meaningKo: '대체하다, 교체하다',
    ipa: '/rɪˈpleɪs/',
    definition: 'to take the place of something, or put something new',
    sentence: 'It was time to replace the old battery with a new one.',
    wordPromptScene: 'A fresh new battery slotting cleanly into a green flashlight compartment.',
    sentPromptScene: 'A mechanic uses tools to replace a worn bicycle tire with new rubber.',
  },
  {
    word: 'property',
    partOfSpeech: 'n.',
    meaningKo: '재산, 소유물, 특성',
    ipa: '/ˈprɑː.pɚ.t̬i/',
    definition: 'a thing or things belonging to someone, or land owned',
    sentence: 'Please respect school property and keep all classroom desks clean.',
    wordPromptScene: 'A neat wooden name tag attached securely to a colorful backpack.',
    sentPromptScene: 'Students return art supplies and care for all school community property.',
  },
  {
    word: 'refund',
    partOfSpeech: 'n.',
    meaningKo: '환불, 반환금',
    ipa: '/ˈriː.fʌnd/',
    definition: 'an amount of money that is paid back to you',
    sentence: 'The friendly store clerk gave a full refund for the item.',
    wordPromptScene: 'A paper receipt with a green Refund Approved stamp and coins.',
    sentPromptScene: 'A customer receives a full cash refund for a returned toy train.',
  },
  {
    word: 'branch',
    partOfSpeech: 'n.',
    meaningKo: '나뭇가지, 지점, 분과',
    ipa: '/bræntʃ/',
    definition: 'a part of a tree that grows out from trunk',
    sentence: 'A little bluebird sang sweetly from a leafy tree branch.',
    wordPromptScene: 'A leafy oak tree branch with small green leaves and acorns.',
    sentPromptScene: 'A squirrel scampers along a sturdy pine tree branch in park.',
  },
  {
    word: 'recover',
    partOfSpeech: 'v.',
    meaningKo: '회복하다, 되찾다',
    ipa: '/rɪˈkʌv.ɚ/',
    definition: 'to get back to normal health or retrieve lost items',
    sentence: 'Plenty of rest and warm tea helped him recover from cold.',
    wordPromptScene: 'A cheerful blooming flower rising up freshly after a gentle rain.',
    sentPromptScene: 'A resting puppy begins to recover its energy and plays with ball.',
  },
  {
    word: 'hardship',
    partOfSpeech: 'n.',
    meaningKo: '고난, 어려움',
    ipa: '/ˈhɑːrd.ʃɪp/',
    definition: 'severe suffering, difficulty, or privation in story or life',
    sentence: 'Pioneer settlers faced cold winter hardship with courage and strong teamwork.',
    wordPromptScene: 'A cozy pioneer log cabin glowing warmly through a snowy forest clearing.',
    sentPromptScene: 'Characters in the historical novel help each other through winter hardship.',
  },
  {
    word: 'assemble',
    partOfSpeech: 'v.',
    meaningKo: '조립하다, 모이다',
    ipa: '/əˈsem.bəl/',
    definition: 'to put together the parts of something, or gather people',
    sentence: 'Children used colorful interlocking blocks to assemble a toy spaceship model.',
    wordPromptScene: 'Colorful toy building bricks clicking together to form a neat miniature rocket.',
    sentPromptScene: 'Students assemble in the school gymnasium for the morning awards ceremony.',
  },
  {
    word: 'proceed',
    partOfSpeech: 'v.',
    meaningKo: '진행하다, 나아가다',
    ipa: '/proʊˈsiːd/',
    definition: 'to continue as planned or move forward in a direction',
    sentence: 'After the green signal flashed, hikers could proceed along the trail.',
    wordPromptScene: 'A bright green glowing traffic light with a forward white arrow.',
    sentPromptScene: 'Students proceed quietly into the auditorium for the special musical performance.',
  },
  {
    word: 'precede',
    partOfSpeech: 'v.',
    meaningKo: '선행하다, 앞서다',
    ipa: '/prɪˈsiːd/',
    definition: 'to come before something in time, order, or position',
    sentence: 'A gentle drum roll will precede the start of the parade.',
    wordPromptScene: 'A marching band drum major leading musicians at the front of parade.',
    sentPromptScene: 'A short warm-up speech will precede the science fair keynote presentation.',
  },
];

const day28_set4 = [
  {
    word: 'stir',
    partOfSpeech: 'v.',
    meaningKo: '젓다, 뒤섞다, 자극하다',
    ipa: '/stɝː/',
    definition: 'to mix a liquid or food by moving a spoon around',
    sentence: 'Use a wooden spoon to stir the hot chocolate gently.',
    wordPromptScene: 'A wooden spoon stirring a mug of rich hot chocolate with marshmallows.',
    sentPromptScene: 'A young chef uses a whisk to stir pancake batter until smooth.',
  },
  {
    word: 'independent',
    partOfSpeech: 'adj.',
    meaningKo: '독립적인, 자립적인',
    ipa: '/ˌɪn.dɪˈpen.dənt/',
    definition: 'not depending on other people for authority or livelihood',
    sentence: 'Students learned to be independent by packing their own school bags.',
    wordPromptScene: 'A small bird spreading wings and taking its first proud independent flight.',
    sentPromptScene: 'An independent student completes her science homework without needing parental reminders.',
  },
  {
    word: 'overall',
    partOfSpeech: 'adj.',
    meaningKo: '전반적인, 종합적인',
    ipa: '/ˌoʊ.vɚˈɑːl/',
    definition: 'taking everything into account, general, total in view',
    sentence: 'The overall performance of our school choir was absolutely outstanding.',
    wordPromptScene: 'A panoramic view of a sunny green valley showing the overall landscape.',
    sentPromptScene: 'The principal praises the overall academic growth of the entire student body.',
  },
  {
    word: 'approach',
    partOfSpeech: 'v.',
    meaningKo: '접근하다, 다가가다',
    ipa: '/əˈproʊtʃ/',
    definition: 'to come near or nearer to someone or something',
    sentence: 'The friendly deer would approach the quiet meadow pool to drink.',
    wordPromptScene: 'A gentle spotted deer walking slowly towards a calm forest pond.',
    sentPromptScene: 'Hikers walk quietly as they approach the scenic mountain viewing platform.',
  },
  {
    word: 'challenge',
    partOfSpeech: 'n.',
    meaningKo: '도전, 난제',
    ipa: '/ˈtʃæl.ɪndʒ/',
    definition: 'a difficult task that tests someone’s ability and skill',
    sentence: 'Solving the advanced math puzzle was an exciting intellectual challenge.',
    wordPromptScene: 'A steep mountain path with stepping stones leading toward a gold summit flag.',
    sentPromptScene: 'Students enthusiastically tackle the challenge of building a spaghetti tower model.',
  },
  {
    word: 'impact',
    partOfSpeech: 'n.',
    meaningKo: '영향, 충격',
    ipa: '/ˈɪm.pækt/',
    definition: 'a powerful effect that something has on a situation or person',
    sentence: 'Reading every day has a lasting positive impact on vocabulary growth.',
    wordPromptScene: 'A water droplet hitting calm water creating wide glowing concentric ripple waves.',
    sentPromptScene: 'A teacher explains the positive environmental impact of planting neighborhood trees.',
  },
  {
    word: 'accelerate',
    partOfSpeech: 'v.',
    meaningKo: '가속하다, 빨라지다',
    ipa: '/əkˈsel.ɚ.eɪt/',
    definition: 'to increase speed or cause something to happen more quickly',
    sentence: 'The electric toy train will accelerate smoothly along the metal track.',
    wordPromptScene: 'A sleek miniature racing car with dynamic glowing speed motion lines.',
    sentPromptScene: 'A runner begins to accelerate as she approaches the final hundred meters.',
  },
  {
    word: 'collapse',
    partOfSpeech: 'v.',
    meaningKo: '무너지다, 붕괴하다',
    ipa: '/kəˈlæps/',
    definition: 'to fall down suddenly because of pressure or lack of strength',
    sentence: 'The tall tower of wooden toy blocks began to collapse gently.',
    wordPromptScene: 'A playful tower of colorful toy building blocks tumbling onto soft carpet.',
    sentPromptScene: 'Children laugh as their tall sandy castle starts to collapse under waves.',
  },
  {
    word: 'purchase',
    partOfSpeech: 'v.',
    meaningKo: '구매하다, 사다',
    ipa: '/ˈpɝː.tʃəs/',
    definition: 'to acquire something by paying money for it, buy',
    sentence: 'She used saved pocket money to purchase a new sketchbook.',
    wordPromptScene: 'A wrapped gift box being purchased with a green approved shopping cart.',
    sentPromptScene: 'A student visits the school book fair to purchase an adventure novel.',
  },
  {
    word: 'account',
    partOfSpeech: 'n.',
    meaningKo: '계좌, 이야기, 설명',
    ipa: '/əˈkaʊnt/',
    definition: 'an arrangement with a bank, or a report of an event',
    sentence: 'He opened a junior savings account to deposit birthday money.',
    wordPromptScene: 'A neat bank passbook showing savings deposits with a smiling star logo.',
    sentPromptScene: 'An explorer writes a fascinating account of his Arctic trek in journal.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 28, set: 1, wordsData: day28_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 28, set: 2, wordsData: day28_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 28, set: 3, wordsData: day28_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 28, set: 4, wordsData: day28_set4 });
  console.log('DAY 28 written successfully');
}

run();
