import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 09
// ==========================================
const day09_set1 = [
  {
    word: 'just',
    partOfSpeech: 'adj.',
    meaningKo: '공정한, 올바른',
    ipa: '/dʒʌst/',
    definition: 'fair and treating all people equally',
    sentence: 'A wise judge always makes a just and honest decision.',
    wordPromptScene: 'A balanced golden scale of justice shining on a polished wooden table.',
    sentPromptScene: 'A fair referee makes a just call during a close soccer match.',
  },
  {
    word: 'moral',
    partOfSpeech: 'adj.',
    meaningKo: '도덕적인, 도덕의',
    ipa: '/ˈmɔːr.əl/',
    definition: 'relating to the standards of good or right behavior',
    sentence: 'The fable teaches an important moral lesson about honesty today.',
    wordPromptScene: 'An open storybook showing an illustrated cartoon owl giving wise advice.',
    sentPromptScene: 'Students discuss the moral meaning behind an ancient Aesop fable.',
  },
  {
    word: 'peer',
    partOfSpeech: 'n.',
    meaningKo: '또래, 동료',
    ipa: '/pɪr/',
    definition: 'a person who is the same age or status as you',
    sentence: 'Working with a friendly peer makes science projects more fun.',
    wordPromptScene: 'Two cartoon classmates high-fiving over a shared robot model.',
    sentPromptScene: 'A student explains a math idea clearly to an attentive peer.',
  },
  {
    word: 'achieve',
    partOfSpeech: 'v.',
    meaningKo: '달성하다, 이루다',
    ipa: '/əˈtʃiːv/',
    definition: 'to succeed in doing something good after working hard',
    sentence: 'You can achieve your goals with steady daily practice exercises.',
    wordPromptScene: 'A golden star medal placed on top of a mountain summit rock.',
    sentPromptScene: 'A smiling runner crosses the finish line to achieve a personal best.',
  },
  {
    word: 'path',
    partOfSpeech: 'n.',
    meaningKo: '길, 오솔길',
    ipa: '/pæθ/',
    definition: 'a track made by footprints or laid down for walking',
    sentence: 'A scenic stone path leads straight to the peaceful garden.',
    wordPromptScene: 'A charming cobblestone path winding through blooming flower bushes.',
    sentPromptScene: 'Two hikers walk happily along a sunny forest path in morning.',
  },
  {
    word: 'necessary',
    partOfSpeech: 'adj.',
    meaningKo: '필요한, 필수의',
    ipa: '/ˈnes.ə.ser.i/',
    definition: 'needed in order to achieve a particular result',
    sentence: 'Water and sunlight are necessary for healthy plant growth everywhere.',
    wordPromptScene: 'A watering can, sunbeams, and a thriving green potted sprout.',
    sentPromptScene: 'A gardener brings all necessary tools to plant young tomato seedlings.',
  },
  {
    word: 'selfish',
    partOfSpeech: 'adj.',
    meaningKo: '이기적인',
    ipa: '/ˈsel.fɪʃ/',
    definition: 'caring only about yourself and not about other people',
    sentence: 'It is selfish to keep all the delicious snacks alone.',
    wordPromptScene: 'A cartoon squirrel hugging a giant pile of acorns protectively.',
    sentPromptScene: 'A generous boy shares cookies rather than being selfish with friends.',
  },
  {
    word: 'penalty',
    partOfSpeech: 'n.',
    meaningKo: '처벌, 페널티',
    ipa: '/ˈpen.əl.ti/',
    definition: 'a punishment for breaking a rule in sports or law',
    sentence: 'The referee awarded a penalty kick for the soccer foul.',
    wordPromptScene: 'A yellow referee card resting beside a soccer ball on grass.',
    sentPromptScene: 'A soccer player prepares to take a penalty kick at goal.',
  },
  {
    word: 'adopt',
    partOfSpeech: 'v.',
    meaningKo: '입양하다, 채택하다',
    ipa: '/əˈdɑːpt/',
    definition: 'to take a pet or child into your family legally',
    sentence: 'Our family decided to adopt a gentle rescue puppy yesterday.',
    wordPromptScene: 'A cozy pet bed with an Adopt Me ribbon on a happy puppy.',
    sentPromptScene: 'A happy family visits an animal shelter to adopt a kitten.',
  },
  {
    word: 'adapt',
    partOfSpeech: 'v.',
    meaningKo: '적응하다, 맞추다',
    ipa: '/əˈdæpt/',
    definition: 'to change your behavior in order to suit a new situation',
    sentence: 'Animals learn to adapt to cold weather by growing fur.',
    wordPromptScene: 'A cute chameleon changing its colorful spots to match a green leaf.',
    sentPromptScene: 'A polar bear has thick white fur to adapt to snowy conditions.',
  },
];

const day09_set2 = [
  {
    word: 'pause',
    partOfSpeech: 'v.',
    meaningKo: '잠시 멈추다',
    ipa: '/pɑːz/',
    definition: 'to stop what you are doing for a short time',
    sentence: 'Let us pause the music and listen to the announcement.',
    wordPromptScene: 'A glowing blue pause symbol button surrounded by audio waveform graphics.',
    sentPromptScene: 'A boy taps the screen to pause a video during study.',
  },
  {
    word: 'incentive',
    partOfSpeech: 'n.',
    meaningKo: '동기, 혜택, 장려책',
    ipa: '/ɪnˈsen.tɪv/',
    definition: 'something that encourages you to work harder or do something',
    sentence: 'A shiny gold star is a great incentive for students.',
    wordPromptScene: 'A glittering gold star sticker on a neat homework chart.',
    sentPromptScene: 'A teacher offers a prize incentive for reading five library books.',
  },
  {
    word: 'sacrifice',
    partOfSpeech: 'v.',
    meaningKo: '희생하다, 포기하다',
    ipa: '/ˈsæk.rə.faɪs/',
    definition: 'to give up something valuable to help someone else',
    sentence: 'The team captain chose to sacrifice free time for practice.',
    wordPromptScene: 'A superhero cape floating bravely beside a glowing heart crest.',
    sentPromptScene: 'Older siblings sacrifice playing games to help a younger brother study.',
  },
  {
    word: 'generous',
    partOfSpeech: 'adj.',
    meaningKo: '관대한, 아낌없는',
    ipa: '/ˈdʒen.ər.əs/',
    definition: 'willing to give money, help, or time freely to others',
    sentence: 'The generous baker gave extra warm muffins to the children.',
    wordPromptScene: 'A big overflowing basket of freshly baked bread and ripe fruits.',
    sentPromptScene: 'A generous girl donates colorful storybooks to the local children’s hospital.',
  },
  {
    word: 'appropriate',
    partOfSpeech: 'adj.',
    meaningKo: '적절한, 알맞은',
    ipa: '/əˈproʊ.pri.ət/',
    definition: 'suitable or right for a particular situation or person',
    sentence: 'Wear an appropriate warm coat for the snowy mountain hike.',
    wordPromptScene: 'A winter jacket, gloves, and boots matched neatly for cold weather.',
    sentPromptScene: 'Students wear appropriate safety goggles before starting a science chemistry lab.',
  },
  {
    word: 'chase',
    partOfSpeech: 'v.',
    meaningKo: '뒤쫓다, 추적하다',
    ipa: '/tʃeɪs/',
    definition: 'to run after someone or something in order to catch them',
    sentence: 'Playful kittens love to chase a colorful yarn ball indoors.',
    wordPromptScene: 'A rolling red ball of yarn with motion trail lines behind.',
    sentPromptScene: 'Two happy puppies chase each other across the sunny green grass.',
  },
  {
    word: 'deserve',
    partOfSpeech: 'v.',
    meaningKo: '~받을 만하다, 자격이 있다',
    ipa: '/dɪˈzɝːv/',
    definition: 'to have earned something because of your good qualities or actions',
    sentence: 'After hours of hard work, you deserve a healthy snack.',
    wordPromptScene: 'A bowl of fresh strawberries topped with a sparkling golden star.',
    sentPromptScene: 'Hardworking students celebrate because they deserve praise for great teamwork.',
  },
  {
    word: 'pretend',
    partOfSpeech: 'v.',
    meaningKo: '~인 척하다, 가장하다',
    ipa: '/prɪˈtend/',
    definition: 'to behave as if something is true when it is not',
    sentence: 'Children like to pretend to be space explorers in games.',
    wordPromptScene: 'A cardboard box rocket ship decorated with shiny foil and buttons.',
    sentPromptScene: 'Two children pretend to be brave knights using toy foam shields.',
  },
  {
    word: 'neglect',
    partOfSpeech: 'v.',
    meaningKo: '방치하다, 소홀히 하다',
    ipa: '/nɪˈɡlekt/',
    definition: 'to fail to look after or give enough care to something',
    sentence: 'Do not neglect to water your green houseplants every week.',
    wordPromptScene: 'A small potted plant looking perky beside a full watering can.',
    sentPromptScene: 'A responsible girl does not neglect her daily pet feeding duties.',
  },
  {
    word: 'lie',
    partOfSpeech: 'v.',
    meaningKo: '거짓말하다, 눕다',
    ipa: '/laɪ/',
    definition: 'to say something you know is not true',
    sentence: 'It is always best to be honest and never lie.',
    wordPromptScene: 'A wooden cartoon Pinocchio puppet with a cute small nose.',
    sentPromptScene: 'A brave child tells the truth rather than try to lie.',
  },
];

const day09_set3 = [
  {
    word: 'devote',
    partOfSpeech: 'v.',
    meaningKo: '바치다, 전념하다',
    ipa: '/dɪˈvoʊt/',
    definition: 'to give your time, energy, or attention to something',
    sentence: 'She decided to devote her summer vacation to volunteering locally.',
    wordPromptScene: 'A glowing heart surrounded by open books and paintbrushes.',
    sentPromptScene: 'A dedicated student will devote extra hours to mastering the cello.',
  },
  {
    word: 'admit',
    partOfSpeech: 'v.',
    meaningKo: '인정하다, 자백하다',
    ipa: '/ədˈmɪt/',
    definition: 'to agree that something is true, especially something bad',
    sentence: 'It takes courage to admit when you made a mistake.',
    wordPromptScene: 'A gentle handshake between two smiling friends reconciling differences.',
    sentPromptScene: 'A boy speaks honestly to admit he accidentally broke the ruler.',
  },
  {
    word: 'gender',
    partOfSpeech: 'n.',
    meaningKo: '성별',
    ipa: '/ˈdʒen.dɚ/',
    definition: 'the condition of being male, female, or another identity',
    sentence: 'Sports clubs welcome all players regardless of their gender identity.',
    wordPromptScene: 'A colorful circle of diverse smiling cartoon children holding hands.',
    sentPromptScene: 'Boys and girls play soccer together regardless of gender differences.',
  },
  {
    word: 'permit',
    partOfSpeech: 'v.',
    meaningKo: '허락하다, 허가하다',
    ipa: '/pɚˈmɪt/',
    definition: 'to allow something to happen or give permission officially',
    sentence: 'Park rules permit dogs on leashes on all walking trails.',
    wordPromptScene: 'An official stamped green pass card with a friendly checkmark.',
    sentPromptScene: 'A park ranger gives a pass to permit camping in woods.',
  },
  {
    word: 'spouse',
    partOfSpeech: 'n.',
    meaningKo: '배우자',
    ipa: '/spaʊs/',
    definition: 'a husband or wife considered in relation to their partner',
    sentence: 'My uncle and his spouse celebrated their tenth wedding anniversary.',
    wordPromptScene: 'Two interlocking golden wedding rings resting on a lace pillow.',
    sentPromptScene: 'A smiling couple holds hands and walks through a flower garden.',
  },
  {
    word: 'ultimate',
    partOfSpeech: 'adj.',
    meaningKo: '궁극적인, 최고의',
    ipa: '/ˈʌl.tə.mət/',
    definition: 'most important, highest, or coming at the end',
    sentence: 'Reaching the mountain peak was our ultimate goal this summer.',
    wordPromptScene: 'A glowing golden trophy sitting atop the highest mountain peak.',
    sentPromptScene: 'Hikers reach the summit rock to achieve their ultimate hiking dream.',
  },
  {
    word: 'cheat',
    partOfSpeech: 'v.',
    meaningKo: '속이다, 부정행위를 하다',
    ipa: '/tʃiːt/',
    definition: 'to act in a dishonest way to gain an advantage',
    sentence: 'True sports players never cheat to win any fun game.',
    wordPromptScene: 'A rulebook with a green fairness seal stamped on its cover.',
    sentPromptScene: 'Children play board games fairly and never cheat their good friends.',
  },
  {
    word: 'extraordinary',
    partOfSpeech: 'adj.',
    meaningKo: '비범한, 놀라운',
    ipa: '/ɪkˈstrɔːr.dən.er.i/',
    definition: 'very unusual, special, unexpected, or much better than normal',
    sentence: 'The young musician has an extraordinary talent for playing violin.',
    wordPromptScene: 'A glowing rainbow colored feather shimmering with magical sparkle light.',
    sentPromptScene: 'An audience applauds an extraordinary piano performance by a young prodigy.',
  },
  {
    word: 'ethnic',
    partOfSpeech: 'adj.',
    meaningKo: '민족의, 인종의',
    ipa: '/ˈeθ.nɪk/',
    definition: 'relating to a particular race or cultural group of people',
    sentence: 'The international food festival featured delicious dishes from ethnic cultures.',
    wordPromptScene: 'A vibrant platter with traditional dumplings, curries, and flatbreads.',
    sentPromptScene: 'People share delicious ethnic foods at an international cultural festival booth.',
  },
  {
    word: 'ethical',
    partOfSpeech: 'adj.',
    meaningKo: '윤리적인, 도덕적인',
    ipa: '/ˈeθ.ɪ.kəl/',
    definition: 'relating to beliefs about what is right and wrong behavior',
    sentence: 'Scientists must follow ethical rules when conducting any new experiment.',
    wordPromptScene: 'A glowing balance scale with a white dove resting on it.',
    sentPromptScene: 'Researchers discuss ethical guidelines before testing solar technology in nature.',
  },
];

const day09_set4 = [
  {
    word: 'fundamental',
    partOfSpeech: 'adj.',
    meaningKo: '기본적인, 근본적인',
    ipa: '/ˌfʌn.dəˈmen.t̬əl/',
    definition: 'forming the base from which everything else develops naturally',
    sentence: 'Learning addition and subtraction is a fundamental part of mathematics.',
    wordPromptScene: 'A solid stone foundation block supporting a colorful building pillar.',
    sentPromptScene: 'A teacher explains fundamental math rules using colorful counting blocks on desk.',
  },
  {
    word: 'modify',
    partOfSpeech: 'v.',
    meaningKo: '수정하다, 바꾸다',
    ipa: '/ˈmɑː.də.faɪ/',
    definition: 'to change something slightly to improve it or make suitable',
    sentence: 'We can modify the toy car to make it roll faster.',
    wordPromptScene: 'A tiny screwdriver adjusting the wheel gear on a toy car.',
    sentPromptScene: 'A young mechanic works to modify a model car for race.',
  },
  {
    word: 'instinct',
    partOfSpeech: 'n.',
    meaningKo: '본능, 직감',
    ipa: '/ˈɪn.stɪŋkt/',
    definition: 'a natural behavior or reaction that is not learned',
    sentence: 'Birds fly south in winter by a natural migration instinct.',
    wordPromptScene: 'A flock of geese flying in a classic V formation through clouds.',
    sentPromptScene: 'Migrating birds follow their natural instinct and fly across autumn sky.',
  },
  {
    word: 'volunteer',
    partOfSpeech: 'v.',
    meaningKo: '자원하다, 자원봉사하다',
    ipa: '/ˌvɑː.lənˈtɪr/',
    definition: 'to offer to do something without being forced or paid',
    sentence: 'Many students volunteer to plant trees in the local park.',
    wordPromptScene: 'A cheerful cartoon heart with a hand offering a seedling plant.',
    sentPromptScene: 'Friendly students volunteer to clean up litter along the river bank.',
  },
  {
    word: 'conscious',
    partOfSpeech: 'adj.',
    meaningKo: '의식하는, 자각하는',
    ipa: '/ˈkɑːn.ʃəs/',
    definition: 'aware of and responding to your surroundings and actions',
    sentence: 'Be conscious of recycling paper to help protect our planet.',
    wordPromptScene: 'A glowing green leaf surrounded by lightbulbs and recycling arrows.',
    sentPromptScene: 'A student makes a conscious effort to place plastic in recycling.',
  },
  {
    word: 'tempt',
    partOfSpeech: 'v.',
    meaningKo: '유혹하다, 부추기다',
    ipa: '/tempt/',
    definition: 'to make someone want to do or have something tempting',
    sentence: 'The smell of fresh cinnamon cookies can tempt any hungry child.',
    wordPromptScene: 'A warm freshly baked chocolate chip cookie releasing delicious swirling steam.',
    sentPromptScene: 'Warm apple pies on the windowsill tempt passersby with sweet aroma.',
  },
  {
    word: 'humble',
    partOfSpeech: 'adj.',
    meaningKo: '겸손한, 소박한',
    ipa: '/ˈhʌm.bəl/',
    definition: 'not proud or thinking that you are better than others',
    sentence: 'The champion remained humble and thanked all his training coaches.',
    wordPromptScene: 'A small simple wooden flowerpot with a sweet blooming wildflower.',
    sentPromptScene: 'A humble winner bows respectfully and shakes hands with his competitors.',
  },
  {
    word: 'ashamed',
    partOfSpeech: 'adj.',
    meaningKo: '부끄러운, 부끄러워하는',
    ipa: '/əˈʃeɪmd/',
    definition: 'feeling guilty or embarrassed about something you have done',
    sentence: 'He felt ashamed after forgetting to feed his pet goldfish.',
    wordPromptScene: 'A cute puppy sitting beside an empty food bowl looking apologetic.',
    sentPromptScene: 'A boy feels ashamed and immediately feeds his pet with care.',
  },
  {
    word: 'prejudice',
    partOfSpeech: 'n.',
    meaningKo: '편견, 선입견',
    ipa: '/ˈpredʒ.ə.dɪs/',
    definition: 'an unfair and unreasonable opinion formed without enough knowledge',
    sentence: 'Education helps us overcome unfair prejudice and understand different cultures.',
    wordPromptScene: 'An open window letting bright sunshine clear away dark foggy clouds.',
    sentPromptScene: 'Students learn about world cultures to stop prejudice and build harmony.',
  },
  {
    word: 'order',
    partOfSpeech: 'n.',
    meaningKo: '순서, 질서',
    ipa: '/ˈɔːr.dɚ/',
    definition: 'the arrangement of things according to a particular sequence',
    sentence: 'Please place the numbered library books in correct alphabetical order.',
    wordPromptScene: 'A row of colorful numbered building blocks lined up one to five.',
    sentPromptScene: 'A student arranges storybooks in neat alphabetical order on the shelf.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 9, set: 1, wordsData: day09_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 9, set: 2, wordsData: day09_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 9, set: 3, wordsData: day09_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 9, set: 4, wordsData: day09_set4 });
  console.log('DAY 09 written successfully');
}

run();
