import { writeCandidateSet } from './generate_helper.mjs';

const AUTHOR = 'gemini';

// ==========================================
// DAY 29
// ==========================================
const day29_set1 = [
  {
    word: 'industry',
    partOfSpeech: 'n.',
    meaningKo: '산업, 공업',
    ipa: '/ˈɪn.də.stri/',
    definition: 'economic activity concerned with the processing of raw materials',
    sentence: 'The clean solar power industry creates many green jobs today.',
    wordPromptScene: 'A modern eco-friendly technology factory campus with solar panels and trees.',
    sentPromptScene: 'Students tour a robotics factory to learn about modern manufacturing industry.',
  },
  {
    word: 'policy',
    partOfSpeech: 'n.',
    meaningKo: '정책, 방침',
    ipa: '/ˈpɑː.lə.si/',
    definition: 'a course or principle of action adopted by organization',
    sentence: 'The school has a strict anti-littering policy for all playgrounds.',
    wordPromptScene: 'A framed school charter scroll with a green environmental policy seal.',
    sentPromptScene: 'A teacher explains the library book renewal policy to new students.',
  },
  {
    word: 'commercial',
    partOfSpeech: 'adj.',
    meaningKo: '상업의, 상업적인',
    ipa: '/kəˈmɝː.ʃəl/',
    definition: 'concerned with or engaged in commerce or business profit',
    sentence: 'The busy harbor handles both fishing boats and commercial cargo ships.',
    wordPromptScene: 'A bustling deep-water harbor with large colorful commercial container freight ships.',
    sentPromptScene: 'Shop owners decorate their storefronts along the main commercial shopping street.',
  },
  {
    word: 'convey',
    partOfSpeech: 'v.',
    meaningKo: '전달하다, 운반하다',
    ipa: '/kənˈveɪ/',
    definition: 'to communicate a message or idea, or transport something',
    sentence: 'Illustrations help convey the warm emotional message of the storybook.',
    wordPromptScene: 'A carrier pigeon carrying a rolled parchment letter with golden ribbon.',
    sentPromptScene: 'An artist uses warm golden watercolor tones to convey a cozy mood.',
  },
  {
    word: 'international',
    partOfSpeech: 'adj.',
    meaningKo: '국제의, 세계적인',
    ipa: '/ˌɪn.t̬ɚˈnæʃ.ən.əl/',
    definition: 'existing, occurring, or carried on between two or more nations',
    sentence: 'Students shared traditional folk dances at the international culture festival.',
    wordPromptScene: 'A colorful globe surrounded by the diverse fluttering flags of many nations.',
    sentPromptScene: 'Children celebrate international friendship day by sharing foods from various cultures.',
  },
  {
    word: 'reveal',
    partOfSpeech: 'v.',
    meaningKo: '드러내다, 밝히다',
    ipa: '/rɪˈviːl/',
    definition: 'to make known to others, or uncover something hidden',
    sentence: 'Pulling back the stage velvet curtains will reveal the set.',
    wordPromptScene: 'Velvet red theater curtains opening to reveal a magical fairytale castle.',
    sentPromptScene: 'A magician pulls away a silk cloth to reveal a bouquet of flowers.',
  },
  {
    word: 'increase',
    partOfSpeech: 'v.',
    meaningKo: '증가하다, 늘리다',
    ipa: '/ɪnˈkriːs/',
    definition: 'to become or make greater in size, amount, or degree',
    sentence: 'Regular daily reading will increase your English vocabulary quickly.',
    wordPromptScene: 'A rising green staircase graph leading up toward five shining gold stars.',
    sentPromptScene: 'A gardener adds organic compost to increase the soil fertility naturally.',
  },
  {
    word: 'depend',
    partOfSpeech: 'v.',
    meaningKo: '의존하다, 달려 있다',
    ipa: '/dɪˈpend/',
    definition: 'to rely on someone or something for support or help',
    sentence: 'Baby bird chicks depend completely on their parents for food.',
    wordPromptScene: 'A mother robin feeding a juicy berry to her three nestlings.',
    sentPromptScene: 'Teammates depend on each other during the relay race to succeed.',
  },
  {
    word: 'transfer',
    partOfSpeech: 'v.',
    meaningKo: '이동하다, 옮기다, 환승하다',
    ipa: '/trænsˈfɝː/',
    definition: 'to move from one place, vehicle, or group to another',
    sentence: 'Passengers transfer to the green electric tram at central station.',
    wordPromptScene: 'A passenger stepping across a platform to transfer between two modern trains.',
    sentPromptScene: 'A gardener uses a trowel to transfer seedlings into larger garden pots.',
  },
  {
    word: 'transform',
    partOfSpeech: 'v.',
    meaningKo: '변형시키다, 탈바꿈하다',
    ipa: '/trænˈsfɔːrm/',
    definition: 'to make a thorough or dramatic change in form/appearance',
    sentence: 'A tiny green caterpillar will transform into a magnificent butterfly.',
    wordPromptScene: 'A chrysalis splitting open to reveal a glowing monarch butterfly spreading wings.',
    sentPromptScene: 'Artists use colorful paints to transform a plain wall into a mural.',
  },
];

const day29_set2 = [
  {
    word: 'launch',
    partOfSpeech: 'v.',
    meaningKo: '출시하다, 발사하다, 시작하다',
    ipa: '/lɑːntʃ/',
    definition: 'to set a boat or rocket in motion, start project',
    sentence: 'Scientists prepared to launch the new weather satellite into orbit.',
    wordPromptScene: 'A sleek white rocket lifting off cleanly from a launch pad with smoke.',
    sentPromptScene: 'Students launch their hand-crafted model gliders across the sunny school field.',
  },
  {
    word: 'deliver',
    partOfSpeech: 'v.',
    meaningKo: '배달하다, 전하다',
    ipa: '/dɪˈlɪv.ɚ/',
    definition: 'to take letters, packages, or goods to people’s houses',
    sentence: 'The friendly postal worker will deliver packages to our doorstep.',
    wordPromptScene: 'A friendly postal carrier putting a wrapped parcel on a sunny porch.',
    sentPromptScene: 'A courier rides a cargo bicycle to deliver books to local libraries.',
  },
  {
    word: 'measure',
    partOfSpeech: 'v.',
    meaningKo: '측정하다, 재다',
    ipa: '/ˈmeʒ.ɚ/',
    definition: 'to find the size, amount, or degree of something accurately',
    sentence: 'Use a wooden ruler to measure the length of paper.',
    wordPromptScene: 'A yellow wooden ruler measuring a crisp sheet of blue origami paper.',
    sentPromptScene: 'A student uses measuring tape to measure the height of a sunflower.',
  },
  {
    word: 'claim',
    partOfSpeech: 'v.',
    meaningKo: '주장하다, 요구하다',
    ipa: '/kleɪm/',
    definition: 'to state that something is the case, or assert ownership',
    sentence: 'Students can claim their lost jackets at the school office.',
    wordPromptScene: 'A Lost and Found wooden cubby with neatly hung coats and jackets.',
    sentPromptScene: 'A boy visits the lost property desk to claim his favorite water bottle.',
  },
  {
    word: 'satisfy',
    partOfSpeech: 'v.',
    meaningKo: '만족시키다, 충족하다',
    ipa: '/ˈsæt̬.ɪs.faɪ/',
    definition: 'to meet the expectations, needs, or desires of someone',
    sentence: 'A crisp sweet apple was enough to satisfy his hunger.',
    wordPromptScene: 'A shiny red apple sliced neatly on a clean porcelain plate.',
    sentPromptScene: 'A delicious bowl of warm soup is enough to satisfy everyone after hiking.',
  },
  {
    word: 'opposite',
    partOfSpeech: 'adj.',
    meaningKo: '반대의, 맞은편의',
    ipa: '/ˈɑː.pə.zɪt/',
    definition: 'completely different, or situated on the other side of space',
    sentence: 'The library is situated on the opposite side of street.',
    wordPromptScene: 'Two arrows pointing in completely opposite directions with contrasting colors.',
    sentPromptScene: 'A student points to the bookshop located on the opposite sidewalk corner.',
  },
  {
    word: 'strategy',
    partOfSpeech: 'n.',
    meaningKo: '전략, 계획',
    ipa: '/ˈstræt̬.ə.dʒi/',
    definition: 'a plan of action designed to achieve a long-term goal',
    sentence: 'Our soccer coach outlined a smart passing strategy for game.',
    wordPromptScene: 'A coach’s magnetic whiteboard with tactical soccer play diagrams and arrows.',
    sentPromptScene: 'Chess players carefully think ahead to develop a winning opening strategy.',
  },
  {
    word: 'import',
    partOfSpeech: 'v.',
    meaningKo: '수입하다, 들여오다',
    ipa: '/ɪmˈpɔːrt/',
    definition: 'to bring goods into a country from abroad for sale',
    sentence: 'Local grocery markets import fresh tropical pineapples and sweet bananas.',
    wordPromptScene: 'A cargo ship unloading wooden crates of tropical fruits at the dock.',
    sentPromptScene: 'A merchant explains how the market will import specialty spices from overseas.',
  },
  {
    word: 'trap',
    partOfSpeech: 'n.',
    meaningKo: '함정, 덫, 가두다',
    ipa: '/træp/',
    definition: 'a device or trick designed to catch animals or players',
    sentence: 'The clever maze runner avoided every trick trap in game.',
    wordPromptScene: 'A playful cardboard maze game with colorful marble obstacle checkpoints.',
    sentPromptScene: 'Players navigate a marble through a wooden maze avoiding the penalty trap.',
  },
  {
    word: 'present',
    partOfSpeech: 'n.',
    meaningKo: '선물, 현재',
    ipa: '/ˈprez.ənt/',
    definition: 'a thing given to someone as a gift, or current time',
    sentence: 'She wrapped a wonderful birthday present with a shiny ribbon.',
    wordPromptScene: 'A beautifully wrapped gift box tied with a satin golden ribbon bow.',
    sentPromptScene: 'Children gather around to present a handmade greeting card to their teacher.',
  },
];

const day29_set3 = [
  {
    word: 'consult',
    partOfSpeech: 'v.',
    meaningKo: '상담하다, 찾아보다',
    ipa: '/kənˈsʌlt/',
    definition: 'to seek information or advice from an expert or book',
    sentence: 'Always consult a reliable dictionary to verify new vocabulary spellings.',
    wordPromptScene: 'An open heavy leather dictionary with a bookmark ribbon and glasses.',
    sentPromptScene: 'Students consult an encyclopedia to find historical facts for their project.',
  },
  {
    word: 'organic',
    partOfSpeech: 'adj.',
    meaningKo: '유기농의, 생물의',
    ipa: '/ɔːrˈɡæn.ɪk/',
    definition: 'produced without the use of chemical fertilizers or pesticides',
    sentence: 'The local market sells delicious fresh organic carrots and strawberries.',
    wordPromptScene: 'A wooden crate of freshly picked organic carrots with green leafy tops.',
    sentPromptScene: 'A farmer displays organic apples at the Saturday morning community market.',
  },
  {
    word: 'manufacture',
    partOfSpeech: 'v.',
    meaningKo: '제조하다, 생산하다',
    ipa: '/ˌmæn.jəˈfæk.tʃɚ/',
    definition: 'to make something on a large scale using machinery',
    sentence: 'The eco-friendly factory will manufacture bicycles using recycled aluminum frames.',
    wordPromptScene: 'A robotic arm carefully assembling a shiny metallic bicycle wheel spoke.',
    sentPromptScene: 'Engineers oversee machinery designed to manufacture lightweight solar panels.',
  },
  {
    word: 'negative',
    partOfSpeech: 'adj.',
    meaningKo: '부정적인, 음수의',
    ipa: '/ˈneɡ.ə.t̬ɪv/',
    definition: 'expressing refusal or pessimism, or less than zero mathematically',
    sentence: 'Try to turn any negative thought into a positive opportunity.',
    wordPromptScene: 'A balance scale tilting smoothly from a minus sign to a plus.',
    sentPromptScene: 'A teacher shows students how negative numbers appear on a temperature thermometer.',
  },
  {
    word: 'peasant',
    partOfSpeech: 'n.',
    meaningKo: '소작농, 농부',
    ipa: '/ˈpez.ənt/',
    definition: 'a small farmer or farm worker of low social status historically',
    sentence: 'The fairy tale tells of a kind peasant who helped animals.',
    wordPromptScene: 'A friendly illustrated medieval villager holding a basket of fresh vegetables.',
    sentPromptScene: 'Students read a historical story about a generous peasant family in village.',
  },
  {
    word: 'agriculture',
    partOfSpeech: 'n.',
    meaningKo: '농업, 농경',
    ipa: '/ˈæɡ.rə.kʌl.tʃɚ/',
    definition: 'the science or practice of farming and cultivating soil/crops',
    sentence: 'Modern sustainable agriculture focuses on protecting soil and saving water.',
    wordPromptScene: 'A lush green terraced farm with irrigation canals under sunny skies.',
    sentPromptScene: 'Students visit a farm to learn how agriculture supplies food to cities.',
  },
  {
    word: 'alter',
    partOfSpeech: 'v.',
    meaningKo: '바꾸다, 고치다',
    ipa: '/ˈɑːl.tɚ/',
    definition: 'to change or cause to change in character or composition',
    sentence: 'The tailor will alter the jacket sleeves to fit perfectly.',
    wordPromptScene: 'A tailor’s chalk marking a clean adjustment hemline on blue fabric.',
    sentPromptScene: 'An artist uses a fine brush to alter minor details on canvas.',
  },
  {
    word: 'combine',
    partOfSpeech: 'v.',
    meaningKo: '결합하다, 조합하다',
    ipa: '/kəmˈbaɪn/',
    definition: 'to join or merge to form a single unit or whole',
    sentence: 'You can combine blue and yellow paint to create green.',
    wordPromptScene: 'Blue and yellow watercolor drops merging together to form bright vibrant green.',
    sentPromptScene: 'Chefs combine fresh flour, eggs, and milk in a ceramic mixing bowl.',
  },
  {
    word: 'compete',
    partOfSpeech: 'v.',
    meaningKo: '경쟁하다, 겨루다',
    ipa: '/kəmˈpiːt/',
    definition: 'to strive to gain or win something by defeating others',
    sentence: 'Athletes from many schools compete in the annual sprint race.',
    wordPromptScene: 'Three runners lined up eagerly at the starting blocks on track.',
    sentPromptScene: 'Young chess players compete with friendly sportsmanship during the school tournament.',
  },
  {
    word: 'complete',
    partOfSpeech: 'v.',
    meaningKo: '완료하다, 끝마치다',
    ipa: '/kəmˈpliːt/',
    definition: 'to finish making or doing something entirely, full',
    sentence: 'Take your time to complete every question on the worksheet.',
    wordPromptScene: 'A finished jigsaw puzzle with the final golden centerpiece slotted in.',
    sentPromptScene: 'A student smiles proudly as she finishes to complete her science project.',
  },
];

const day29_set4 = [
  {
    word: 'advance',
    partOfSpeech: 'v.',
    meaningKo: '나아가다, 진보하다',
    ipa: '/ədˈvæns/',
    definition: 'to move forward in a purposeful way, or make progress',
    sentence: 'The chess player decided to advance a pawn across board.',
    wordPromptScene: 'A white wooden chess pawn moving forward into a glowing victory square.',
    sentPromptScene: 'Hikers advance steadily along the mountain path toward the sunny summit.',
  },
  {
    word: 'imply',
    partOfSpeech: 'v.',
    meaningKo: '암시하다, 넌지시 비추다',
    ipa: '/ɪmˈplaɪ/',
    definition: 'to strongly suggest the truth or existence of something without saying',
    sentence: 'Dark gray storm clouds usually imply that heavy rain approaches.',
    wordPromptScene: 'Puffy dark rain clouds gathering over hills hinting at upcoming showers.',
    sentPromptScene: 'A detective analyzes story clues that imply where the treasure is hidden.',
  },
  {
    word: 'guarantee',
    partOfSpeech: 'n.',
    meaningKo: '보증, 보증서, 확약',
    ipa: '/ˌɡer.ənˈtiː/',
    definition: 'a formal promise or assurance that certain conditions will fulfill',
    sentence: 'The toy manufacturer offered a two-year repair guarantee on products.',
    wordPromptScene: 'A shiny gold certificate seal embossed with a 100% Quality Guarantee stamp.',
    sentPromptScene: 'A store clerk hands a written warranty guarantee to the customer with purchase.',
  },
  {
    word: 'chief',
    partOfSpeech: 'adj.',
    meaningKo: '주요한, 최고의, 우두머리',
    ipa: '/tʃiːf/',
    definition: 'most important, main, or holding the highest rank',
    sentence: 'Fresh river water was the chief source of local electricity.',
    wordPromptScene: 'A gleaming gold captain’s star insignia on a neat navy uniform shoulder.',
    sentPromptScene: 'The chief engineer explains the construction blueprints to visiting student reporters.',
  },
  {
    word: 'thrive',
    partOfSpeech: 'v.',
    meaningKo: '번창하다, 잘 자라다',
    ipa: '/θraɪv/',
    definition: 'to grow or develop well, flourish, or prosper successfully',
    sentence: 'Tomato plants thrive happily in warm soil and bright sunshine.',
    wordPromptScene: 'A lush tomato plant bursting with ripe red tomatoes and green leaves.',
    sentPromptScene: 'Wildflowers thrive in the sunny mountain meadow after gentle spring rains.',
  },
  {
    word: 'gain',
    partOfSpeech: 'v.',
    meaningKo: '얻다, 획득하다, 증가',
    ipa: '/ɡeɪn/',
    definition: 'to obtain or secure something wanted or desirable through effort',
    sentence: 'Students gain confidence and new vocabulary by reading books daily.',
    wordPromptScene: 'A cartoon character receiving a glowing gold knowledge star above head.',
    sentPromptScene: 'Athletes gain stamina and speed through consistent daily morning practice.',
  },
  {
    word: 'overlook',
    partOfSpeech: 'v.',
    meaningKo: '간과하다, 내려다보다',
    ipa: '/ˌoʊ.vɚˈlʊk/',
    definition: 'to fail to notice, or have a view from above',
    sentence: 'The mountain wooden cabin will overlook a calm blue lake.',
    wordPromptScene: 'A picturesque log cabin on a cliff overlooking a serene mountain lake.',
    sentPromptScene: 'Check your math calculations carefully so you do not overlook small errors.',
  },
  {
    word: 'disappear',
    partOfSpeech: 'v.',
    meaningKo: '사라지다, 없어지다',
    ipa: '/ˌdɪs.əˈpɪr/',
    definition: 'to cease to be visible, vanish from sight entirely',
    sentence: 'The morning valley mist began to disappear as sun rose.',
    wordPromptScene: 'Wisps of white morning mist fading away to reveal a sunny green meadow.',
    sentPromptScene: 'Children watch the magician make a silk handkerchief disappear with a wand.',
  },
  {
    word: 'initial',
    partOfSpeech: 'adj.',
    meaningKo: '처음의, 초기의',
    ipa: '/ɪˈnɪʃ.əl/',
    definition: 'existing or occurring at the beginning, first stage',
    sentence: 'Her initial reaction to the surprise puppy gift was joy.',
    wordPromptScene: 'A starting block line marked with the number One and a green flag.',
    sentPromptScene: 'Scientists record their initial observations before beginning the chemical trial.',
  },
  {
    word: 'domestic',
    partOfSpeech: 'adj.',
    meaningKo: '국내의, 가정의, 길든',
    ipa: '/dəˈmes.tɪk/',
    definition: 'relating to the running of a home or within country',
    sentence: 'The friendly domestic house cat curled up by the fireplace.',
    wordPromptScene: 'A fluffy domestic calico cat sleeping cozily on a patchwork quilt.',
    sentPromptScene: 'Passengers board a domestic flight connecting two cities within the country.',
  },
];

async function run() {
  await writeCandidateSet({ author: AUTHOR, day: 29, set: 1, wordsData: day29_set1 });
  await writeCandidateSet({ author: AUTHOR, day: 29, set: 2, wordsData: day29_set2 });
  await writeCandidateSet({ author: AUTHOR, day: 29, set: 3, wordsData: day29_set3 });
  await writeCandidateSet({ author: AUTHOR, day: 29, set: 4, wordsData: day29_set4 });
  console.log('DAY 29 written successfully');
}

run();
