export const FPS = 30;
export const WIDTH = 1920;
export const HEIGHT = 1080;

export const INTRO_SECONDS = 2.4;
export const WORD_SLOT_SECONDS = 1.5;
export const DEFINITION_SLOT_SECONDS = 8;
export const SENTENCE_SLOT_SECONDS = 8;
export const SENTENCE_VISUAL_LEAD_SECONDS = 1.5;
export const SENTENCE_AUDIO_START_SECONDS =
  WORD_SLOT_SECONDS * 2 + DEFINITION_SLOT_SECONDS;
export const WORD_BLOCK_SECONDS =
  SENTENCE_AUDIO_START_SECONDS + SENTENCE_SLOT_SECONDS;
export const STUDY_SECONDS =
  SENTENCE_AUDIO_START_SECONDS - SENTENCE_VISUAL_LEAD_SECONDS;
export const SENTENCE_SCREEN_SECONDS = WORD_BLOCK_SECONDS - STUDY_SECONDS;
export const NARRATION_START_SECONDS = INTRO_SECONDS;
export const NARRATION_SECONDS = WORD_BLOCK_SECONDS * 10;
export const TAIL_SECONDS = 0.4;
export const VIDEO_SECONDS = INTRO_SECONDS + NARRATION_SECONDS + TAIL_SECONDS;

export const INTRO_FRAMES = Math.round(INTRO_SECONDS * FPS);
export const STUDY_FRAMES = Math.round(STUDY_SECONDS * FPS);
export const SENTENCE_FRAMES = Math.round(SENTENCE_SCREEN_SECONDS * FPS);
export const WORD_BLOCK_FRAMES = Math.round(WORD_BLOCK_SECONDS * FPS);
export const NARRATION_START_FRAME = Math.round(NARRATION_START_SECONDS * FPS);
export const NARRATION_FRAMES = Math.round(NARRATION_SECONDS * FPS);
export const TAIL_FRAMES = Math.round(TAIL_SECONDS * FPS);
export const VIDEO_FRAMES = Math.round(VIDEO_SECONDS * FPS);
